import { compileActivities, type Subject, type ActivityDetail } from '../../authoredActivities';
const d = (isPremium: boolean, prompt: string, answer: string, revision: string): ActivityDetail => ({
  isPremium, difficulty: isPremium ? 'Advanced' : 'Core', estimatedMinutes: isPremium ? 28 : 20,
  priorKnowledgeCheck: [{ prompt, answer }],
  misconceptionCause: 'A familiar real-number or two-dimensional shortcut can conceal an extra condition; retain the defining algebra and check the result.',
  revision
});
export const furtherMathsYear12: Subject = ['further-maths', [
  ['Complex numbers and Cartesian arithmetic', [
    ['Calculate with the imaginary unit', 'Expand, simplify and divide complex numbers using i squared equals minus one.',
      'Define i by i² = −1. A complex number in Cartesian form is a + bi, with real part a and imaginary part b. The imaginary part is the real coefficient b, not bi. Add corresponding parts and multiply using ordinary distributivity before replacing i² by −1. To divide by c + di, multiply numerator and denominator by its conjugate c − di. Their product is c² + d², a real nonzero denominator unless the original divisor is zero. Complex arithmetic extends real arithmetic; it does not change the rules of expansion.',
      'Express (3 + 2i)/(1 − i) in Cartesian form.',
      ['Multiply top and bottom by 1 + i, the denominator’s conjugate.', 'Expand the numerator: (3 + 2i)(1 + i) = 3 + 5i + 2i² = 1 + 5i.', 'The denominator is (1 − i)(1 + i) = 1 − i² = 2.', 'The quotient is 1/2 + (5/2)i. Multiplication by 1 − i recovers 3 + 2i.'],
      'Expand first; substitute i² = −1 before collecting parts.', 'Leaving a negative squared imaginary unit as though i² were +1.', 'Apply i² = −1 explicitly, including the sign preceding it.',
      'What is the conjugate of −2 + 5i?', '−2 − 5i.',
      'Simplify (2 − i)(3 + 4i), giving its real and imaginary parts.',
      'Expansion gives 6 + 8i − 3i − 4i² = 10 + 5i. The real part is 10 and the imaginary part is 5. The term −4i² contributes +4, not −4.',
      d(false, 'Expand (a + b)(c + d).', 'ac + ad + bc + bd.', 'Tomorrow practise one quotient and verify it by multiplication. In a week explain why a complex number times its conjugate is real.')],
    ['Challenge: solve a real quadratic with nonreal roots', 'Use the discriminant and conjugate structure to solve and verify a quadratic.',
      'For a quadratic with real coefficients, a negative discriminant gives two nonreal conjugate roots. The quadratic formula remains valid in the complex numbers by interpreting the square root of a negative real number using i. Conjugate roots are a consequence of real coefficients, not a rule for every polynomial with complex coefficients. Verify a proposed pair using their sum and product or substitution. A negative discriminant means no real roots, not no roots in the enlarged number system.',
      'Solve x² − 4x + 13 = 0 over the complex numbers.',
      ['The discriminant is (−4)² − 4(1)(13) = −36.', 'Write a square root of −36 as 6i and retain the plus-or-minus in the formula.', 'The roots are (4 ± 6i)/2 = 2 ± 3i.', 'Their sum is 4 and product is 2² + 3² = 13, agreeing with the coefficients.'],
      'Negative discriminant: no real roots, but a conjugate pair over C.', 'Reporting “no solutions” without stating that the domain was restricted to real numbers.', 'State the number system before interpreting the discriminant.',
      'What is (a + bi)(a − bi) for real a and b?', 'a² + b².',
      'Find the monic real quadratic with roots −1 + 2i and −1 − 2i.',
      'The sum is −2 and product is 5. A monic quadratic with root sum S and product P is x² − Sx + P, so the polynomial is x² + 2x + 5. Equivalently, (x + 1 − 2i)(x + 1 + 2i) = (x + 1)² + 4.',
      d(true, 'What is the discriminant of ax² + bx + c?', 'b² − 4ac.', 'After two days solve a different negative-discriminant quadratic. A week later build a polynomial from a specified conjugate pair and check its coefficients.')]
  ]],
  ['Argand geometry and polar form', [
    ['Determine modulus and principal argument', 'Locate a complex number geometrically and use its quadrant to choose an argument.',
      'An Argand diagram plots a + bi at coordinates (a, b). Its modulus is the distance from the origin, |z| = √(a² + b²). An argument is the directed angle from the positive real axis; angles differing by 2π describe the same direction. Under the convention −π < Arg(z) ≤ π, the principal argument is unique for nonzero z. The zero complex number has modulus zero but no defined argument. Inverse tangent alone can give the wrong quadrant, so sketch or inspect the signs of both coordinates.',
      'Find the modulus and principal argument of −√3 + i.',
      ['The coordinates are (−√3, 1), placing the point in quadrant II.', 'The modulus is √(3 + 1) = 2.', 'The reference angle is π/6 since tan(π/6) = 1/√3.', 'The principal argument is π − π/6 = 5π/6, not −π/6.'],
      'Magnitude from Pythagoras; direction from the quadrant.', 'Using arctan(b/a) without correcting for the signs of a and b.', 'Locate the point before selecting an angle in the required interval.',
      'Is Arg(0) defined?', 'No; the origin has no direction from itself.',
      'Find |−1 − i| and its principal argument using −π < Arg(z) ≤ π.',
      'The modulus is √2. The point lies in quadrant III, so an argument is 5π/4; subtracting 2π gives the principal argument −3π/4. The angle π/4 has the correct tangent but the wrong direction.',
      d(false, 'What is the distance from (0, 0) to (a, b)?', '√(a² + b²).', 'Tomorrow sketch points in all four quadrants and label principal arguments. In a week include a point on the negative real axis and the origin.')],
    ['Challenge: interpret complex multiplication as rotation and scaling', 'Multiply polar forms and translate the result into an Argand transformation.',
      'Write a nonzero complex number as r(cos θ + i sin θ), abbreviated r cis θ. Multiplying two such numbers multiplies their moduli and adds their arguments; division divides moduli and subtracts arguments. This follows by expanding and using angle-addition identities. Multiplication by a fixed nonzero complex number is therefore a rotation about the origin together with a scale change. An argument obtained by addition may need reduction by 2π to meet a principal-argument convention.',
      'Let z = 2 cis(2π/3) and w = 3 cis(5π/6). Find zw in principal polar and Cartesian form.',
      ['Multiply the moduli to get 6.', 'Add arguments: 2π/3 + 5π/6 = 3π/2.', 'Reduce 3π/2 by 2π to the principal argument −π/2.', 'Thus zw = 6 cis(−π/2) = −6i.'],
      'Products multiply radii and add angles.', 'Adding moduli or treating the sum of angles as necessarily principal.', 'Separate the radius calculation from angle reduction.',
      'What geometric effect does multiplication by i have?', 'A rotation by π/2 anticlockwise about the origin, with no scale change.',
      'Describe multiplication by −2i, and apply it to 1 + i.',
      'The multiplier has modulus 2 and principal argument −π/2, so it doubles distances from the origin and rotates clockwise by π/2. Algebraically, (−2i)(1 + i) = 2 − 2i, consistent with that transformation.',
      d(true, 'State the cosine addition identity.', 'cos(α + β) = cos α cos β − sin α sin β.', 'After two days verify a polar product by Cartesian expansion. In a week explain why multiplication by a unit-modulus number preserves distance from the origin.')]
  ]],
  ['Matrices and linear transformations', [
    ['Compose two transformations in the correct order', 'Use column vectors and matrix multiplication to distinguish AB from BA.',
      'For column vectors, a matrix transforms v to Av. If transformation A occurs first and B second, the composite is BAv: the rightmost matrix acts first. Matrix multiplication is generally not commutative. Columns of a two-by-two transformation matrix are the images of the standard basis vectors (1, 0) and (0, 1). This provides a geometric check on calculations. A diagonal matrix can scale the coordinate directions differently, so it need not represent a uniform enlargement.',
      'Let A = [[2,0],[0,1]] stretch horizontally and B = [[0,−1],[1,0]] rotate anticlockwise by π/2. Find the image of (1,1) after A then B.',
      ['Apply A first: A(1,1) = (2,1).', 'Apply B next: B(2,1) = (−1,2).', 'The composite matrix is BA = [[0,−1],[2,0]], giving the same image.', 'Reversing the order gives AB(1,1) = (−2,1), so order matters.'],
      'With column vectors, the rightmost transformation happens first.', 'Writing AB because A was mentioned first in the sentence.', 'Apply the transformations to a test vector to verify the matrix order.',
      'What does the first column of a transformation matrix represent?', 'The image of the first standard basis vector.',
      'For A and B above, calculate AB and compare it with BA.',
      'AB = [[0,−2],[1,0]], whereas BA = [[0,−1],[2,0]]. Their different entries encode different results: rotation before horizontal stretch is not the same as horizontal stretch before rotation.',
      d(false, 'How is the first component of [[a,b],[c,d]] times (x,y) calculated?', 'ax + by.', 'Tomorrow compose a reflection and a nonuniform stretch in both orders. In a week check each composite on both standard basis vectors.')],
    ['Challenge: use the determinant to diagnose a linear system', 'Distinguish invertible, inconsistent and nonunique two-variable systems.',
      'For A = [[a,b],[c,d]], det A = ad − bc. If this is nonzero, A⁻¹ = (1/det A)[[d,−b],[−c,a]], and Av = b has a unique solution. A zero determinant means A has no inverse; it does not by itself tell whether a particular right-hand side gives no solutions or infinitely many. Geometrically, dependent equations can describe the same line or distinct parallel lines. Inspect the augmented equations before concluding.',
      'Compare x + 2y = 3, 2x + 4y = 6 with x + 2y = 3, 2x + 4y = 7.',
      ['Both coefficient matrices have determinant 4 − 4 = 0.', 'In the first system the entire second equation is twice the first, giving infinitely many points on one line.', 'In the second, doubling the first would give right-hand side 6, not 7.', 'The second system is inconsistent and has no solution; singularity alone did not distinguish these cases.'],
      'Zero determinant means no inverse, not automatically no solutions.', 'Dividing by a zero determinant or declaring every singular system inconsistent.', 'Check the right-hand side against the dependence between rows.',
      'When does a two-by-two matrix have an inverse?', 'Exactly when its determinant is nonzero.',
      'Solve 2x + y = 5 and x + y = 3 using the inverse matrix.',
      'The coefficient matrix has determinant 2(1) − 1(1) = 1 and inverse [[1,−1],[−1,2]]. Multiplying by (5,3) gives (2,1). Substitution gives 2(2) + 1 = 5 and 2 + 1 = 3, confirming the unique solution.',
      d(true, 'What does it mean for two equations to be consistent?', 'They have at least one common solution.', 'After two days construct singular systems with zero and infinitely many solutions. In a week explain why an invertible system cannot have two different solutions.')]
  ]],
  ['Proof by mathematical induction', [
    ['Prove a finite sum by induction', 'Connect a base case and a conditional inductive step into a proof for all positive integers.',
      'Induction proves a statement P(n) on a specified integer domain by establishing a starting case and showing that P(k) implies P(k+1) for an arbitrary allowed k. The hypothesis is a temporary conditional assumption, not an assertion that the whole theorem is already true. The base case starts the chain; the implication carries it forward. Testing many values without proving the implication is not induction. Always state the domain and conclude how the two steps establish the claim.',
      'Prove 1 + 2 + … + n = n(n+1)/2 for every positive integer n.',
      ['For n = 1, both sides equal 1.', 'Assume 1 + … + k = k(k+1)/2 for an arbitrary integer k ≥ 1.', 'Add k+1: k(k+1)/2 + (k+1) = (k+1)(k+2)/2.', 'This is the required formula at k+1; the base case and inductive implication prove the result for every n ≥ 1.'],
      'Start the chain, prove the link, state the domain.', 'Substituting k+1 into the desired formula and treating that target as already proved.', 'Begin the step from the sum at k+1 and use only the assumed case at k.',
      'Why is the base case needed?', 'The implication alone does not establish any starting true statement.',
      'A student checks the sum formula for n = 1, 2 and 3 and says it must hold for every n. Identify the missing argument.',
      'Finite checks do not cover all positive integers. The student must prove that whenever the formula holds at an arbitrary k ≥ 1, adding the next term produces the formula at k+1. A verified base case then allows the implication to propagate.',
      d(false, 'Factor k(k+1) + 2(k+1).', '(k+1)(k+2).', 'Tomorrow reconstruct the inductive step without looking at the formula. In a week explain why the proof is not circular despite assuming P(k).')],
    ['Challenge: prove a divisibility statement by induction', 'Express the next case as a multiple of the assumed case plus a visible divisible term.',
      'For divisibility induction, aim to rewrite the expression at k+1 using the expression at k plus a term whose divisibility is explicit. To say an integer is divisible by 7 means it equals 7m for some integer m. Preserve the integrality condition; approximate decimal calculations cannot prove divisibility. An algebraic identity valid for arbitrary k supplies the inductive implication. The proof’s domain must match its base case.',
      'Prove 8ⁿ − 1 is divisible by 7 for every positive integer n.',
      ['At n = 1, 8 − 1 = 7 is divisible by 7.', 'Assume 8ᵏ − 1 = 7m for some integer m.', 'Then 8ᵏ⁺¹ − 1 = 8(8ᵏ − 1) + 7 = 56m + 7.', 'This equals 7(8m + 1), an integer multiple of 7, completing the induction for n ≥ 1.'],
      'Expose the old expression inside the next one.', 'Writing 8ᵏ⁺¹ − 1 = 8(8ᵏ − 1) and losing the correcting constant.', 'Expand the proposed rearrangement and restore the missing +7.',
      'What must be true of m in the expression 7m to prove integer divisibility?', 'm must be an integer.',
      'Prove 5ⁿ − 1 is divisible by 4 for every positive integer n, showing the key rearrangement.',
      'The base value is 5 − 1 = 4. Assuming 5ᵏ − 1 = 4m, write 5ᵏ⁺¹ − 1 = 5(5ᵏ − 1) + 4 = 20m + 4 = 4(5m + 1). Because 5m + 1 is an integer, the next case is divisible by 4. The base case and implication establish the result for n ≥ 1.',
      d(true, 'How can an integer multiple of 4 be represented?', 'As 4m where m is an integer.', 'After two days recover the correcting constant in a different exponential expression. In a week compare an induction proof with a modular-arithmetic explanation, keeping their logical structures separate.')]
  ]],
  ['Polynomial roots and coefficient relationships', [
    ['Recover symmetric root expressions from a cubic', 'Use coefficient identities to evaluate root combinations without solving the cubic.',
      'For a monic cubic x³ − S₁x² + S₂x − S₃ with roots α, β and γ, expanding (x−α)(x−β)(x−γ) gives S₁ = α+β+γ, S₂ = αβ+αγ+βγ and S₃ = αβγ. Pay attention to alternating signs. Symmetric expressions can often be found without obtaining individual roots: α²+β²+γ² = S₁² − 2S₂. For a nonmonic polynomial, divide by the leading coefficient before applying these monic identities.',
      'For roots of x³ − 6x² + 11x − 6, calculate their sum, pair-product sum, product and squared-root sum.',
      ['Read S₁ = 6 from the negative coefficient of x².', 'Read S₂ = 11 and S₃ = 6 using the alternating signs.', 'Compute α² + β² + γ² = 6² − 2(11).', 'The squared-root sum is 14; no explicit root-solving was necessary.'],
      'Monic cubic signs alternate: minus sum, plus pairs, minus product.', 'Taking the constant term itself as the product of three roots.', 'Compare the fully expanded factorisation with the coefficient pattern.',
      'What is α² + β² + γ² in terms of S₁ and S₂?', 'S₁² − 2S₂.',
      'For 2x³ − 8x² + 10x − 12, find the sum of the squares of its roots.',
      'Divide by 2 to obtain x³ − 4x² + 5x − 6. Thus S₁ = 4 and S₂ = 5, so the squared-root sum is 16 − 10 = 6. Using coefficients before normalising would give an incorrect result.',
      d(false, 'Expand (α+β+γ)².', 'α² + β² + γ² + 2αβ + 2αγ + 2βγ.', 'Tomorrow extract root sums from a nonmonic cubic. In a week derive the sign pattern by expanding three linear factors.')],
    ['Challenge: transform roots by a change of variable', 'Construct a polynomial whose roots are shifted versions of an original root set.',
      'If α is a root of f(x), then u = α + c satisfies f(u − c) = 0. To obtain a polynomial with every root shifted by +c, substitute x = u − c into the original polynomial and expand. The sign reverses because the substitution must recover the old root from the new one. This method avoids solving for the roots. Check the new root sum: shifting each of three roots by c adds 3c to their sum.',
      'Find a monic polynomial whose roots are each one more than the roots of f(x) = x³ − 6x² + 11x − 6.',
      ['Set u = x + 1, hence x = u − 1.', 'Substitute to get (u−1)³ − 6(u−1)² + 11(u−1) − 6.', 'Expand and collect: u³ − 9u² + 26u − 24.', 'The new root sum is 9, which matches the old sum 6 plus three shifts of 1.'],
      'New root = old root + c means substitute old variable = new variable − c.', 'Substituting u + c when the roots should increase by c.', 'Write the relationship between old and new roots before replacing the variable.',
      'How does shifting all three cubic roots by c change their sum?', 'It increases the sum by 3c.',
      'Find a polynomial whose roots are twice the roots of x² − 3x + 2.',
      'Set u = 2x, so substitute x = u/2. The equation becomes u²/4 − 3u/2 + 2 = 0; multiplying by 4 gives u² − 6u + 8 = 0. The original roots 1 and 2 become 2 and 4, confirming the result.',
      d(true, 'If u = x + 3, express x in terms of u.', 'x = u − 3.', 'After two days construct a polynomial for a downward root shift. In a week compare shifts and scalings using both substitution and coefficient checks.')]
  ]],
  ['Three-dimensional vectors and lines', [
    ['Use the scalar product to find an angle', 'Calculate vector lengths and use the dot product to test perpendicularity or find a direction angle.',
      'For vectors a = (a₁,a₂,a₃) and b = (b₁,b₂,b₃), the scalar product is a·b = a₁b₁ + a₂b₂ + a₃b₃. For nonzero vectors it also equals |a||b| cos θ, where θ is the angle between them in [0,π]. A zero dot product indicates perpendicular nonzero vectors. The zero vector has no direction, so an angle involving it is undefined. Distinguish a dot product, which is a scalar, from a vector result.',
      'Find the angle between a = (1,2,2) and b = (2,0,1).',
      ['Calculate a·b = 1(2) + 2(0) + 2(1) = 4.', 'The lengths are |a| = 3 and |b| = √5.', 'Thus cos θ = 4/(3√5).', 'θ = arccos(4/(3√5)), approximately 53.4 degrees. State the unit and avoid rounding intermediate values.'],
      'Dot, lengths, divide, inverse cosine.', 'Using the dot product itself as the angle or forgetting one vector length.', 'Write a·b = |a||b| cos θ before rearranging.',
      'What does a zero dot product imply for two nonzero vectors?', 'They are perpendicular.',
      'Find k so that (k,1,2) is perpendicular to (2,−4,1).',
      'Set the dot product to zero: 2k − 4 + 2 = 0. Hence 2k − 2 = 0 and k = 1. Both vectors are nonzero, so the perpendicularity interpretation is valid.',
      d(false, 'Find the length of (1,2,2).', '√(1² + 2² + 2²) = 3.', 'Tomorrow test perpendicularity before using inverse trigonometry. In a week compare a negative dot product with the corresponding obtuse angle.')],
    ['Challenge: distinguish intersecting, parallel and skew lines', 'Solve line parameters independently and check every coordinate before claiming intersection.',
      'A line in three dimensions can be written r = a + λd with nonzero direction d. Two lines with proportional direction vectors are parallel or coincident. Nonparallel lines need not meet in three dimensions: they can be skew. To test intersection, use independent parameters for the two lines, equate all coordinates and check that one pair of parameters satisfies every equation. Solving only two coordinate equations is not enough; the third may contradict them.',
      'Compare L₁: r = (0,0,0) + λ(1,1,0) and L₂: r = (0,1,1) + μ(1,−1,0).',
      ['Their direction vectors (1,1,0) and (1,−1,0) are not proportional.', 'The x and y equations are λ = μ and λ = 1 − μ, giving λ = μ = 1/2.', 'The z equation would require 0 = 1, which is impossible.', 'The lines are nonparallel and nonintersecting, so they are skew.'],
      'Three coordinates require one consistent pair of parameters.', 'Calling nonparallel three-dimensional lines intersecting after checking only a projection.', 'Verify the parameter pair in all three coordinates.',
      'Can two nonparallel lines fail to intersect in three-dimensional space?', 'Yes; such lines are skew.',
      'Change L₂ to r = (0,1,0) + μ(1,−1,0). Find the intersection with L₁.',
      'The first two equations still give λ = μ = 1/2, but now both z coordinates equal zero. Thus all three equations are satisfied and the intersection is (1/2,1/2,0). The altered third coordinate changes the spatial relationship without changing the two-dimensional projection.',
      d(true, 'When are two nonzero direction vectors parallel?', 'When one is a nonzero scalar multiple of the other.', 'After two days solve an intersection problem using separate parameters. A week later alter one coordinate to produce skew lines and explain why the original projection was insufficient.')]
  ]]
]];
export const post16FurtherMathsYear12 = compileActivities('year-12', [furtherMathsYear12]).map(lesson => ({
  ...lesson, examples: lesson.examples.map(example => ({ ...example, title: 'Worked mathematical reasoning' })),
  memoryTips: lesson.memoryTips.map(tip => ({ ...tip, title: 'Method check' }))
}));
