import type { Subject } from '../authoredActivities';
export const year6World: Subject[] = [
['geography', [
 ['Climate change and evidence', [
  ['Distinguish weather variability from climate trends', 'Explain why a long-term pattern needs more than one day’s observation.',
   'Weather describes conditions at a particular time and place; climate describes longer-term patterns and averages. A cold week can occur during a period of rising global average temperature. Evaluate climate claims using suitable long-term data, geographic scope and consistent measurements. A global trend does not require every place to warm by the same amount every year.',
   'Assess “It snowed today, so the global climate cannot be warming”.', ['The snowfall is a local short-term observation.', 'Global climate concerns a much wider area and longer period.', 'One snowy day does not contradict a long-term rise in global average temperature.'], 'Match the timescale and the area.', 'Using one local event as a complete test of a global trend.', 'Compare evidence at the scale of the claim.',
   'Can a warming climate still include cold weather?', 'Yes.', 'Why use several decades rather than one summer to study a climate trend?', 'Longer records help distinguish sustained changes from short-term fluctuations and unusual seasons.'],
  ['Explain an enhanced greenhouse effect', 'Connect greenhouse gases with changes in Earth’s energy balance.',
   'Earth receives energy from the Sun and emits energy back towards space. Greenhouse gases absorb and re-emit some outgoing infrared radiation. Increasing their concentration changes the energy balance and contributes to warming. This is not the same as the ozone hole, and the atmosphere does not act exactly like a sealed glass greenhouse; the name is an analogy with limits.',
   'Explain why added carbon dioxide can affect temperature.', ['Earth emits infrared radiation after being warmed.', 'Carbon dioxide interacts with some of this outgoing radiation.', 'Increasing it changes how energy leaves the Earth system, contributing to warming.'], 'Follow incoming and outgoing energy.', 'Explaining warming simply as more sunlight entering through an ozone hole.', 'Separate greenhouse-gas processes from ozone depletion.',
   'Name one greenhouse gas.', 'Carbon dioxide, methane or water vapour.', 'Why is reducing fossil-fuel use relevant to this process?', 'Burning fossil fuels adds carbon dioxide to the atmosphere; reducing those emissions helps limit additional greenhouse forcing.']
 ]],
 ['Fieldwork and sustainable choices', [
  ['Design a defensible local survey', 'Choose a sample and recognise what it can and cannot represent.',
   'A fieldwork survey needs a clear question, safe collection method and a reasoned sample. Counting traffic only outside one school at dismissal may answer a question about that period but not the whole town’s daily traffic. Record time, place and categories consistently. Discuss who or what the sampling method leaves out before generalising.',
   'Investigate whether two nearby roads differ in traffic volume.', ['Observe safely with adult supervision for equal periods.', 'Use the same vehicle categories and comparable times.', 'Repeat where feasible and limit conclusions to the sampled conditions.'], 'A sample has a boundary.', 'Claiming a single ten-minute count represents every day.', 'State the sampling limits and gather additional observations for broader claims.',
   'Why record the time of observation?', 'Traffic can vary substantially through the day.', 'What would improve a claim about typical weekday traffic?', 'Comparable observations across several weekdays and times, using a consistent safe method, would provide a broader basis.'],
  ['Evaluate a transport proposal', 'Weigh environmental, social and practical effects using local evidence.',
   'A new cycle route may reduce some car journeys and improve access, but its value depends on connections, safety, users’ needs and displaced traffic. An evaluation should identify benefits, costs and who experiences them. “Sustainable” is a goal requiring evidence, not a label that settles every design question. Consider alternatives and possible unintended effects.',
   'Assess a proposed route ending before a busy junction.', ['Identify the improved section’s potential benefit.', 'Recognise that the remaining junction may limit safe access.', 'Recommend evidence-led changes or further investigation rather than declaring the whole proposal perfect or useless.'], 'Benefits, barriers, affected people.', 'Counting only the people who already cycle.', 'Consider potential users, accessibility and those affected by changed road use.',
   'Why compare a proposal with alternatives?', 'Different designs may achieve similar aims with different costs and effects.', 'What evidence could help assess whether a route connects useful destinations?', 'Maps of schools, workplaces and services, route observations and appropriately collected user information.']
 ]]
]],
['computer-science', [
 ['Algorithmic reasoning', [
  ['Trace a loop containing selection', 'Predict how a condition is checked during repeated execution.',
   'A loop can check a condition each time it repeats. In a simple game, each cycle might test whether a sprite touches a target and then update a score. If contact lasts through several cycles, the score may increase repeatedly. The algorithm must define whether continuous contact counts once or many times rather than leaving that behaviour accidental.',
   'A score rises five times while a sprite remains on one target.', ['The condition is true during five loop cycles.', 'Each true result triggers the update.', 'Add suitable logic, such as moving the target after a hit, if each target should count only once.'], 'A repeated check can repeat its action.', 'Assuming one physical contact automatically creates only one program event.', 'Trace the condition and action on every loop cycle.',
   'When is a condition inside a repeated loop normally checked?', 'Each time execution reaches that check.', 'Why might moving the target after a successful hit solve repeated scoring?', 'It makes the touching condition false until a new contact occurs, preventing continued scoring on the same unchanged contact.'],
  ['Define a reusable procedure', 'Use a named sequence to reduce duplication and clarify a program.',
   'A procedure groups instructions under a name so they can be called when needed. A reset procedure might place a character at its start, set score to zero and clear messages. Naming a repeated task makes the program easier to inspect and change. A procedure still follows exact instructions; its name does not supply missing behaviour automatically.',
   'Create a reset routine for a game.', ['List every state that must return to its initial value.', 'Group those instructions under resetGame.', 'Call the routine at the start and when restarting.'], 'Name the task; specify every step.', 'Resetting the position but forgetting the score or visible messages.', 'Use a checklist of state values changed during play.',
   'Does naming a procedure drawSquare make it draw a square without instructions?', 'No.', 'Why can one reset procedure be safer than several copied reset sequences?', 'A correction can be made in one place, reducing the risk that copies become inconsistent.']
 ]],
 ['Data representation and responsible computing', [
  ['Represent a small number in binary', 'Interpret four binary places using powers of two.',
   'Binary uses two digits, zero and one. In a four-bit unsigned representation, the places from left to right have values eight, four, two and one. A one includes that place’s value and a zero excludes it. Thus 1011 represents eight plus two plus one, or eleven. Leading zeros do not add value in this unsigned example.',
   'Represent thirteen with four bits.', ['Use eight, leaving five.', 'Use four, leaving one; do not use two.', 'Use one, giving 1101.'], 'Eight, four, two, one: include or exclude.', 'Reading 1011 as the decimal number one thousand and eleven.', 'Identify the number system and place values first.',
   'What is the value of the leftmost place in a four-bit unsigned number?', 'Eight.', 'Convert 0110 to decimal and explain the largest four-bit unsigned value.', '0110 is six. 1111 is fifteen because 8 + 4 + 2 + 1 = 15.'],
  ['Explain why personal data needs limits', 'Apply purpose and minimisation to a simple data-collection task.',
   'A digital project should collect only information needed for its stated purpose. A class preference survey may need a choice category but not a home address or full birth date. Personal data can expose people if shared or accessed inappropriately. Use approved tools and adult guidance, explain the purpose and avoid publishing identifiable responses without appropriate permission.',
   'Plan a survey about preferred library genres.', ['Define the purpose as comparing genre choices.', 'Collect categories without unnecessary identifiers.', 'Use school-approved storage and share only suitable summaries.'], 'Useful purpose, minimum data.', 'Collecting extra details merely because a form allows them.', 'Ask how each field is necessary to answer the question.',
   'Does removing a name always make a record impossible to identify?', 'No; combinations of other details may still identify someone.', 'Why might publishing a very small subgroup’s responses create a privacy issue?', 'People may infer the individuals from the group size and context even without names.']
 ]]
]],
['french', [
 ['Future plans and descriptions', [
  ['Build the near future', 'Use a present form of aller followed by an infinitive.',
   'The near future can express a plan using aller plus an infinitive: je vais lire means I am going to read. For we, use nous allons lire. The second verb remains an infinitive; it does not take the subject ending again. A time phrase such as demain, tomorrow, can make the intended time explicit.',
   'Say “Tomorrow we are going to sing”.', ['Choose Demain as the time phrase.', 'Use nous allons for we are going.', 'Add chanter: Demain, nous allons chanter.'], 'Conjugate aller; keep the next verb whole.', 'Writing nous allons chantons.', 'Only aller is conjugated in this two-verb construction; use chanter afterwards.',
   'What does demain mean?', 'Tomorrow.', 'Translate Je vais dessiner, then write “We are going to read”.', 'I am going to draw. Nous allons lire. The planned activity follows the correct form of aller.'],
  ['Compare present activity with future intention', 'Use verb structure and time language to distinguish now from a plan.',
   'Je joue describes I play or I am playing in an appropriate context. Je vais jouer describes I am going to play. The time phrase helps, but the verb construction carries important meaning too. A translation should preserve the intended time rather than matching individual words mechanically. Negation wraps the conjugated verb: je ne vais pas jouer.',
   'Change “I play” to “I am not going to play”.', ['Start from the future construction je vais jouer.', 'Put ne before vais and pas after it.', 'Write Je ne vais pas jouer.'], 'Negation wraps vais, not the infinitive.', 'Placing pas after jouer and leaving the verb structure unclear.', 'Use the standard written order je ne vais pas jouer.',
   'Which verb remains infinitive in je vais jouer?', 'Jouer.', 'Translate Nous jouons aujourd’hui, mais demain nous allons lire.', 'We are playing today, but tomorrow we are going to read. Aujourd’hui and demain reinforce the contrast between present activity and a future plan.']
 ]],
 ['Descriptions and connected writing', [
  ['Make taught adjectives agree', 'Apply gender and number agreement to familiar adjective patterns.',
   'In a simple description, an adjective often agrees with the noun’s grammatical gender and number. Un livre intéressant becomes des livres intéressants. Une histoire intéressante adds the feminine ending in this regular example. Not all adjectives follow exactly the same pattern or position, so learn irregular forms separately rather than forcing one rule onto every word.',
   'Describe some interesting stories.', ['Use des histoires for the plural feminine noun.', 'Add the feminine ending to intéressant.', 'Add the plural s: des histoires intéressantes.'], 'Check gender, then number.', 'Making the adjective match the person who owns the object.', 'Agreement follows the noun being described.',
   'What controls the adjective in une histoire intéressante?', 'The feminine singular noun histoire.', 'Translate un livre intéressant and des livres intéressants.', 'An interesting book; some interesting books. Both noun and adjective show regular written plural marking in the second phrase.'],
  ['Write a short coherent personal paragraph', 'Combine preferences, reasons and a future plan with consistent meaning.',
   'A short paragraph becomes coherent when its sentences connect rather than merely display unrelated vocabulary. Introduce a preference, give a reason and add a relevant plan. Use familiar constructions accurately: J’aime lire parce que c’est intéressant. Demain, je vais lire une histoire. Check articles, verb forms and connectors separately during revision.',
   'Write about enjoying singing and planning to sing tomorrow.', ['State J’aime chanter.', 'Add parce que c’est amusant.', 'Continue Demain, je vais chanter.'], 'Meaningful link before extra length.', 'Adding advanced-looking phrases whose meaning does not fit.', 'Keep the message within language you understand and can check.',
   'Which connector gives a reason?', 'Parce que.', 'Write two linked sentences saying you like drawing because it is fun and will draw tomorrow.', 'J’aime dessiner parce que c’est amusant. Demain, je vais dessiner. The reason explains the preference and the future sentence continues the same activity.']
 ]]
]],
['spanish', [
 ['Plans and time reference', [
  ['Use ir a with an infinitive', 'Build a near-future plan with the required connecting preposition.',
   'Spanish can express a plan with ir a plus an infinitive. Voy a leer means I am going to read; vamos a leer means we are going to read. The a is part of this construction and should not be omitted. The activity stays in the infinitive rather than receiving another subject ending.',
   'Say “Tomorrow we are going to sing”.', ['Use mañana for tomorrow.', 'Choose vamos a for we are going to.', 'Add cantar: Mañana vamos a cantar.'], 'Ir, a, infinitive.', 'Omitting a or changing cantar to cantamos after vamos a.', 'Keep the complete construction and leave the second verb in its infinitive form.',
   'What does voy a leer mean?', 'I am going to read.', 'Write “I am going to draw” using dibujar, then make it negative.', 'Voy a dibujar. No voy a dibujar. No goes before the conjugated verb voy.'],
  ['Distinguish a habit from a plan', 'Use present forms and future constructions to preserve time meaning.',
   'Canto can describe I sing or, in suitable context, I am singing. Voy a cantar describes I am going to sing. Time phrases such as hoy, today, and mañana, tomorrow, help connect events, but they do not replace correct verb structure. A future intention does not prove an action has already happened.',
   'Contrast reading today with singing tomorrow.', ['Use Hoy leo for I read today.', 'Use pero to introduce a contrast.', 'Continue mañana voy a cantar.'], 'Time word plus matching construction.', 'Translating a planned action as a completed event.', 'Identify whether the message concerns a habit, current activity or intended future action.',
   'What does hoy mean?', 'Today.', 'Translate Hoy hablamos, pero mañana vamos a escribir.', 'Today we speak, but tomorrow we are going to write. The first verb is present; the second activity follows vamos a.']
 ]],
 ['Agreement and extended messages', [
  ['Describe plural nouns accurately', 'Apply article, noun and adjective agreement in taught patterns.',
   'Los libros rojos means the red books. The article, noun and adjective all reflect masculine plural agreement in this example. Las reglas rojas uses feminine plural forms. Adjectives such as azul form the plural azules rather than simply adding s after a consonant. Agreement is grammatical, not a judgement about the people using the objects.',
   'Change la regla roja to a plural phrase.', ['Change la to las.', 'Change regla to reglas.', 'Change roja to rojas: las reglas rojas.'], 'Check the whole noun phrase.', 'Pluralising only the noun and leaving the article and adjective singular.', 'Review article, noun and adjective as a connected unit.',
   'What is the plural of azul?', 'Azules.', 'Translate “the blue books” and “the red rulers”.', 'Los libros azules; las reglas rojas. Articles and adjectives match the nouns’ number and appropriate gender patterns.'],
  ['Connect preference, reason and intention', 'Write a short message with accurate links between ideas.',
   'A coherent Spanish message can state a preference, explain it with porque and add a plan. Me gusta leer porque es interesante. Mañana voy a leer un libro. Notice that gusta introduces the infinitive activity, while voy a introduces the future plan. Longer writing is useful only when the meaning and grammar remain controlled.',
   'Write about liking singing and planning to sing tomorrow.', ['Start Me gusta cantar.', 'Explain porque es divertido.', 'Add Mañana voy a cantar.'], 'Preference, reason, plan.', 'Using me gustan before an infinitive activity.', 'Use gusta with the infinitive; gustan belongs with plural things liked.',
   'What does pero mean?', 'But.', 'Write a contrast: you like reading but are not going to read tomorrow.', 'Me gusta leer, pero mañana no voy a leer. The negative precedes voy and the contrast is linked by pero.']
 ]]
]],
['religious-studies', [
 ['Reasoned comparison of worldviews', [
  ['Compare explanations of responsibility', 'Represent two ethical approaches without oversimplifying either.',
   'An ethical discussion can ask whether an action is right because of a duty, its consequences, the character it expresses or several of these. Religious and non-religious people can use overlapping approaches. Compare stated reasons, not stereotypes based on labels. A strong comparison identifies a shared concern and a genuine difference in reasoning.',
   'Compare keeping a promise from duty with keeping it to protect trust.', ['Both approaches may recommend keeping the promise.', 'One emphasises the obligation itself.', 'The other emphasises effects on relationships and trust; a person may value both.'], 'Same conclusion can follow different reasons.', 'Assuming everyone with one worldview reasons in only one way.', 'Describe the particular argument and acknowledge possible overlap.',
   'Can two arguments reach the same conclusion by different routes?', 'Yes.', 'Why might an exception, such as a promise to hide danger, test these arguments?', 'It creates a conflict between keeping a promise and preventing harm, requiring reasons about priorities rather than a memorised slogan.'],
  ['Distinguish evidence questions from meaning questions', 'Recognise different kinds of enquiry without dismissing either.',
   'Some questions ask what can be established from observation or historical sources. Others ask what gives life meaning or how a practice expresses belonging. These can interact, but they are not answered in identical ways. Establish the kind of claim being made before choosing evidence, testimony, interpretation or philosophical reasoning to examine it.',
   'Compare “When was this building constructed?” with “Why is it sacred to worshippers?”', ['The first seeks historical dating evidence.', 'The second needs participants’ beliefs and the place’s religious context.', 'Both matter, but a construction date alone does not explain sacred meaning.'], 'Match the method to the question.', 'Expecting one type of evidence to answer every kind of enquiry.', 'Clarify whether the claim concerns dates, observable events, beliefs or meaning.',
   'Can a building have a known construction date and different meanings to different visitors?', 'Yes.', 'Why is interviewing a participant useful but not sufficient to date an ancient building?', 'It may illuminate current meaning, while dating needs relevant historical or archaeological evidence.']
 ]],
 ['Representation and dialogue', [
  ['Evaluate a general claim about a community', 'Check the scope of evidence before accepting a universal statement.',
   'A claim using all or never requires much broader support than a description of one group or setting. Survey results depend on who was asked and how. A tradition’s official teaching does not automatically establish every individual’s personal practice. Critically checking a generalisation supports accuracy and respect without preventing discussion of disagreement or harm.',
   'A small interview project concludes that all members observe one practice.', ['Identify the number and selection of interviewees.', 'Distinguish their accounts from the entire community.', 'Restate the conclusion at the scope the evidence supports.'], 'Small sample, limited claim.', 'Confusing an official statement with a measurement of every individual’s behaviour.', 'Separate normative teaching from observed practice.',
   'Does a universal claim need more support than a claim about one person?', 'Yes.', 'How could the conclusion be rewritten responsibly?', '“The participants in this project described observing this practice,” with details of the sample and its limits.'],
  ['Build respectful disagreement', 'Question an idea with reasons while respecting the person expressing it.',
   'Respectful dialogue does not require pretending to agree. State the other view accurately, identify the point of disagreement and offer reasons or questions rather than insults. People can decline to discuss private beliefs. A classroom should allow criticism of ideas while protecting participants from pressure, stereotyping or personal hostility.',
   'Respond to a classmate’s ethical conclusion you find unconvincing.', ['Restate their reason to check understanding.', 'Name the specific consequence or assumption you question.', 'Offer a reasoned alternative without attacking their identity.'], 'Challenge the reasoning, not the person.', 'Treating disagreement as permission to mock a group.', 'Keep discussion focused on the claim and its support.',
   'Must someone reveal private beliefs to participate in learning about religion?', 'No.', 'What is a constructive question when an argument overlooks an affected person?', '“How would this decision affect that person, and should their needs change the conclusion?”']
 ]]
]]
];
