import type { Subject } from '../authoredActivities';
export const year5Practical: Subject[] = [
['art', [
 ['Perspective and visual organisation', [
  ['Construct a simple one-point perspective', 'Use a vanishing point to organise receding parallel edges.',
   'In a simple one-point perspective drawing, selected parallel edges receding from the viewer appear to approach a vanishing point on the horizon line. Vertical edges usually remain vertical in this model. It is a drawing convention for a particular view, not a rule that every line in an image must meet the same point. Start with a box or corridor rather than a complicated street.',
   'Draw a box facing the viewer.', ['Draw its front rectangle and a horizon with one vanishing point.', 'Guide receding edges from the rectangle’s corners towards that point.', 'Choose the box’s depth, close the far edges and remove unneeded guides.'], 'Only the receding set converges.', 'Sending vertical and horizontal front edges to the vanishing point too.', 'Identify which edges recede in the chosen orientation before drawing guides.',
   'Where is the vanishing point in this model?', 'On the horizon line.', 'Why should two receding edges of the same box use one common vanishing point?', 'They represent a parallel set pointing in the same real-world direction, so consistent convergence helps the space appear coherent.'],
  ['Control emphasis through composition', 'Use contrast and placement to establish a deliberate focal point.',
   'Emphasis directs attention. A focal area may stand out through contrast in tone, colour, size or detail, but using every device everywhere can make the image compete with itself. Try alternative arrangements before committing. View the work at a distance or in a small thumbnail to check where the eye goes first.',
   'Make one doorway the main focus of a street drawing.', ['Keep surrounding details less contrasty or less dense.', 'Place a strong light-dark contrast near the doorway.', 'Check whether viewers notice that area before secondary details.'], 'If everything shouts, nothing leads.', 'Adding maximum detail to every area and expecting one focus.', 'Reduce competing contrasts rather than only strengthening the focal area.',
   'Must a focal point be exactly in the centre?', 'No.', 'How could a thumbnail sketch help planning?', 'Its small scale reveals the main masses, contrasts and placement without distracting fine detail.']
 ]],
 ['Material exploration and interpretation', [
  ['Plan relief texture with purpose', 'Choose raised surfaces that support an intended visual effect.',
   'Relief work projects from a backing rather than standing fully free. Layers of card, suitable modelling material or textiles can create raised areas. Consider depth, attachment and viewing angle as well as appearance. A texture can communicate an idea, such as roughness or movement, but should be chosen deliberately rather than added only to fill empty space.',
   'Build a relief suggesting flowing water.', ['Choose repeated curved raised forms.', 'Arrange them in a consistent directional pattern.', 'Secure the layers safely and examine shadows from the intended viewing angle.'], 'Raised form makes real shadows.', 'Ignoring attachment strength because the surface looks finished.', 'Test joins and backing before adding fragile details.',
   'How does relief differ from a completely flat drawing?', 'Some parts physically project from a backing.', 'Why might side lighting change the appearance of a relief?', 'Raised forms cast and receive different shadows, revealing or exaggerating its depth and texture.'],
  ['Interpret an artwork using evidence', 'Separate observation, interpretation and personal response.',
   'Observation states what can be seen: repeated dark figures, a narrow frame or rough marks. Interpretation proposes meaning using those features and contextual knowledge. Personal response describes your own reaction. Keeping these distinct helps avoid presenting a feeling as a proven artist intention. Research can strengthen an interpretation, but unsupported biography should not be invented.',
   'Respond to a picture of small figures under a large dark sky.', ['Observe the size contrast and dark upper area.', 'Suggest that the figures may seem vulnerable or overshadowed.', 'Explain your own response separately and acknowledge other supported readings.'], 'See, infer, respond.', 'Claiming the artist definitely felt sad solely because dark paint appears.', 'Support claims about intention with contextual evidence or phrase them as interpretations.',
   'Is “I find it unsettling” an observation or a personal response?', 'A personal response.', 'What makes “the figures seem isolated” an interpretation rather than a bare observation?', 'It assigns meaning to features such as spacing and scale; the claim needs those features as support.']
 ]]
]],
['design-tech', [
 ['Mechanical systems', [
  ['Explain a cam and follower', 'Describe how a rotating shaped part can produce another movement.',
   'A cam is a rotating shaped component that pushes a follower as its profile turns beneath it. The follower’s motion depends on the cam’s shape and arrangement. An off-centre circular cam can produce a smooth rise and fall in a simple model. Keep moving parts accessible for observation, and use adult-prepared components where cutting or drilling is required.',
   'Make a model figure rise and fall when a handle turns.', ['Attach an off-centre cam to a rotating shaft.', 'Position a guided follower on the cam.', 'Turn slowly and observe the follower’s changing height.'], 'Rotation in, rising motion out.', 'Assuming every cam produces exactly the same movement.', 'Compare the profile and follower position with the observed motion.',
   'What part directly follows the cam’s surface?', 'The follower.', 'Why guide the follower rather than leave it loose?', 'A guide helps it move in the intended direction instead of slipping sideways or losing contact.'],
  ['Match a mechanism to a design need', 'Choose a cam profile or arrangement by its output movement.',
   'A design may need a gradual lift, a quick drop or repeated bumps during one rotation. Sketch the desired movement before selecting a mechanism. Test a safe model slowly to compare intended and actual motion. A visually dramatic cam is not necessarily suitable if the follower jams or the output does not match the user’s purpose.',
   'A model should lift a sign once per handle rotation.', ['Define one rise and return as the required cycle.', 'Select and test a cam arrangement producing one cycle.', 'Adjust guidance or shape if the sign rises unpredictably or jams.'], 'Choose the output before the shape.', 'Designing the cam without stating what the moving part should do.', 'Record the required motion as a simple sequence or height sketch.',
   'Why turn a newly made mechanism slowly during testing?', 'It makes faults easier to observe and reduces the chance of damage.', 'What evidence would show the model meets its motion criterion?', 'Several controlled rotations consistently produce the intended one rise and return without jamming.']
 ]],
 ['Food systems and product evaluation', [
  ['Trace ingredients through a supply chain', 'Explain that food preparation depends on several linked stages.',
   'A bread product may involve growing grain, milling flour, transporting ingredients, baking and distribution. Each stage uses resources and requires appropriate handling. Local production is not automatically lower impact in every case; methods, energy use, storage and transport matter. Study a specific supply chain rather than making a claim based only on distance.',
   'Trace flour used in a school bread activity.', ['Identify grain growing and harvesting.', 'Identify milling and transport to the supplier.', 'Connect the flour with safe storage and the supervised preparation stage.'], 'Ingredient journeys have stages.', 'Treating the shop as the place where every ingredient originates.', 'Trace back through processing to the agricultural source.',
   'What process turns grain into flour?', 'Milling.', 'Why can packaging and storage matter as well as transport distance?', 'They use resources and affect spoilage and food safety, so total impacts depend on more than kilometres travelled.'],
  ['Use criteria to compare prototypes', 'Make a justified design decision using test evidence.',
   'A comparison table can record how two prototypes meet the same criteria. Separate measured results, such as a lid opening reliably, from opinions about appearance. Criteria may conflict: a stronger material might be heavier or harder to recycle. Explain the chosen priority for the intended user rather than assuming one prototype must be best in every respect.',
   'Compare two containers for carrying classroom equipment.', ['Test capacity and closure with the same contents.', 'Record mass, ease of carrying and any failures.', 'Choose using the user’s priorities and explain the trade-off.'], 'Same criteria, visible evidence.', 'Adding scores with no explanation of what they measure.', 'Define each criterion and support the result with observations.',
   'Why should prototypes be tested with the same load?', 'Different loads would make performance difficult to compare fairly.', 'Can a heavier prototype still be the better choice?', 'Yes, if a justified priority such as durability or stability outweighs mass for that user, provided safe handling is maintained.']
 ]]
]],
['music', [
 ['Metre and rhythmic layering', [
  ['Distinguish pulse from metre', 'Group a steady pulse into repeating patterns of emphasis.',
   'Pulse is the underlying regular beat. Metre organises beats into recurring groups, often with a stronger first beat. Three-beat grouping feels different from four-beat grouping even at the same tempo. Not every musical tradition uses the same metric conventions, so this exercise focuses on simple regular groupings rather than defining all music.',
   'Compare counting ONE-two-three with ONE-two-three-four.', ['Keep each beat equally spaced.', 'Emphasise the first beat of each group.', 'Notice the different interval between recurring strong beats.'], 'Pulse ticks; metre groups.', 'Making the first beat longer instead of emphasising it.', 'Keep durations steady while changing accent.',
   'Can two pieces share a tempo but use different metres?', 'Yes.', 'How many beats occur in four groups of three?', 'Twelve. The pulse count is twelve, organised into four recurring three-beat groups.'],
  ['Maintain contrasting rhythmic layers', 'Perform one repeated pattern without losing it to another part.',
   'When layers use different rhythms, a shared pulse allows them to fit together. Rehearse each part with the pulse before combining. Mark the cycle’s starting point and agreed length so patterns return together. Listening helps coordination, but copying the other part accidentally removes the intended contrast.',
   'Combine a four-beat pulse part with a clap-rest-clap-clap pattern.', ['Practise both parts separately over four beats.', 'Start together using a count-in.', 'Keep each part’s role through several cycles and finish on the agreed cue.'], 'Different pattern, shared clock.', 'Changing your pattern whenever another part has a rest.', 'Count the shared cycle internally while maintaining your own instructions.',
   'What helps different rhythms stay coordinated?', 'A shared pulse and agreed cycle structure.', 'How can a group simplify rehearsal without abandoning the layered design?', 'Slow the tempo, reduce the number of cycles or add one part at a time.']
 ]],
 ['Melody and evidence-based listening', [
  ['Develop a motif through sequence', 'Move a recognisable melodic idea to a different pitch level.',
   'A motif is a short recognisable musical idea. A melodic sequence repeats a pattern at a higher or lower pitch level, often preserving its general shape and rhythm. It differs from simply repeating the same notes. On a taught scale, try moving a short rising pattern one scale step higher and listen for both familiarity and change.',
   'Develop C-D-E as a rising three-note motif.', ['Play C-D-E with a clear rhythm.', 'Move the pattern one scale step higher to D-E-F.', 'Keep the rhythm so the relationship remains recognisable.'], 'Same shape, new starting height.', 'Changing rhythm and direction so much that the motif is no longer recognisable.', 'Preserve selected features when testing a sequential development.',
   'How does a sequence differ from an exact repeat?', 'It restates the idea at a different pitch level.', 'Why can repetition with variation help a longer piece?', 'It creates continuity while avoiding an entirely unchanged pattern throughout.'],
  ['Compare texture in two extracts', 'Describe musical layers using specific listening evidence.',
   'Texture concerns how musical parts combine. One melody alone differs from a melody with accompaniment or several simultaneous lines. A recording can sound fuller because more layers enter, not simply because it becomes louder. Identify audible roles before making a judgement about the effect, and recognise uncertainty when an instrument is difficult to identify.',
   'Compare a solo tune with the same tune plus bass and chord accompaniment.', ['Identify the tune as the continuing melodic part.', 'Notice the added lower and supporting layers.', 'Explain that texture becomes more layered even if overall loudness is controlled.'], 'Count roles, not just volume.', 'Calling every loud passage thick in texture.', 'Listen for how many distinct parts and roles are present.',
   'Can a solo instrument play loudly with a sparse texture?', 'Yes.', 'What evidence would support saying the texture becomes thinner?', 'One or more layers stop or simplify, leaving fewer simultaneous musical parts.']
 ]]
]],
['pe', [
 ['Tactical adaptation', [
  ['Choose a pass for the situation', 'Compare passing options using space, distance and readiness.',
   'A useful pass depends on the receiver’s position, nearby players and the game’s rules. The nearest teammate is not always the clearest option. Scan before receiving where possible, then select a safe achievable route. Adapt equipment, distances and rules to learners’ needs so decision-making is not confused with a single required movement technique.',
   'A nearby teammate is marked while a farther teammate has a clear lane.', ['Compare the safety and reachability of both routes.', 'Check whether the farther receiver is ready and within a suitable distance.', 'Choose the clearer achievable option rather than automatically the nearest.'], 'Available is more than nearby.', 'Passing to a favourite teammate regardless of the situation.', 'Use current space and readiness as the basis for the decision.',
   'Why scan before receiving?', 'It gives time to notice options before the next action.', 'When might the farther open player still be a poor choice?', 'If the pass exceeds a safe achievable distance or the receiver is not ready, another option may be better.'],
  ['Adapt a team plan during play', 'Use observed patterns to revise a simple tactic.',
   'A team plan is a starting idea, not a guarantee. If repeated attacks become crowded on one side, spreading play or changing support positions may create alternatives. Discuss one change during a suitable pause and agree how success will be recognised. Keep feedback about decisions and space rather than blaming a person.',
   'A team repeatedly loses possession in the same crowded zone.', ['Identify the repeated spatial pattern.', 'Agree to offer a wider support option.', 'Test whether the new position creates a clearer passing route.'], 'Notice the pattern, adjust one plan.', 'Changing every role at once without identifying the problem.', 'Choose a specific tactical adjustment that responds to evidence.',
   'Can a tactic need changing even if it worked previously?', 'Yes; opponents and conditions can change.', 'How could a team judge whether its wider support plan helps?', 'Observe whether the ball carrier gains more safe passing options and whether congestion decreases.']
 ]],
 ['Performance and training choices', [
  ['Set a process goal', 'Choose an improvement target based on a controllable action.',
   'An outcome goal names a result, such as reaching a target more often. A process goal names an action to practise, such as checking alignment before release. Process goals make feedback actionable and reduce reliance on winning or comparing bodies. Select a safe, realistic focus suited to the learner and review it over several attempts.',
   'Turn “win the throwing game” into a process goal.', ['Identify a controllable skill such as consistent alignment.', 'State “check my target and release direction before each attempt”.', 'Review whether the action was used, as well as where the object landed.'], 'Practise the action behind the result.', 'Choosing a goal entirely controlled by other players or chance.', 'Name something the learner can deliberately attempt.',
   'Is “keep a controlled finish” a process or outcome goal?', 'A process goal.', 'Why use several attempts to review a goal?', 'One attempt may be unrepresentative; a pattern better shows whether the chosen action is becoming consistent.'],
  ['Explain recovery as part of activity', 'Recognise that rest and appropriate support belong in a safe activity plan.',
   'Activity places demands on the body, and recovery allows breathing, temperature and effort to settle. Safe plans consider rest, hydration, conditions and individual needs. More intense practice is not always better. Pain, dizziness or feeling unwell are reasons to stop safely and tell a supervising adult, not signals to prove determination.',
   'A learner feels dizzy during repeated practice.', ['Stop the activity safely.', 'Inform the supervising adult immediately.', 'Follow appropriate support and do not resume merely because teammates continue.'], 'Recovery supports participation.', 'Treating discomfort or dizziness as something to hide.', 'Communicate symptoms and let the responsible adult guide the response.',
   'Does every learner need identical rest intervals?', 'No.', 'Why can a short planned rest improve a skill session?', 'It can reduce fatigue and support attention and control, though the plan should match the learner and task.']
 ]]
]],
['pshe', [
 ['Change and respectful support', [
  ['Understand variation during puberty', 'Recognise puberty as a developmental process with varied timing.',
   'Puberty involves physical and emotional changes as bodies develop towards adulthood. Timing and sequence vary, and comparing classmates is not a reliable measure of health or maturity. Changes can include growth, skin changes and altered feelings. Questions deserve accurate, private and respectful answers from trusted adults or appropriate health professionals; teasing is not acceptable.',
   'A learner worries because a friend is growing faster.', ['Recognise that development does not follow one identical timetable.', 'Avoid making judgements from a comparison with one friend.', 'Encourage a private conversation with a trusted adult if worried.'], 'Different timing does not mean lesser worth.', 'Using classmates’ development as a competition.', 'Respect privacy and seek reliable guidance rather than comparing bodies.',
   'Do all people begin puberty at the same age?', 'No.', 'What makes a supportive response to a question about bodily change?', 'Respectful language, privacy, accurate age-appropriate information and help from a trusted adult when needed.'],
  ['Identify reliable help for health questions', 'Choose a support source suited to the concern.',
   'Friends may provide reassurance but can pass on inaccurate health claims. A trusted adult, school nurse or appropriate clinician can help find reliable guidance. Online information should be checked for source, relevance and date, and should not replace urgent help when someone is unwell. Asking a question is not something to be ashamed of.',
   'A social-media post makes a worrying claim about normal development.', ['Avoid treating popularity as medical evidence.', 'Discuss the concern privately with a trusted adult.', 'Use an appropriate health source or professional for reliable clarification.'], 'Popularity is not health expertise.', 'Following a viral recommendation before checking whether it is safe.', 'Seek qualified guidance rather than experimenting with health advice.',
   'Can a friend’s experience represent everyone’s health needs?', 'No.', 'Why might a school nurse be more useful than an anonymous comment?', 'They have a relevant professional role and can consider the concern responsibly or direct the learner to suitable help.']
 ]],
 ['Media influence and money', [
  ['Recognise hidden persuasion', 'Identify when entertainment or a recommendation may also be advertising.',
   'A creator may be paid or receive products for promoting something. Advertising can appear inside entertainment rather than in a separate obvious advert. Look for sponsorship disclosures and consider the creator’s incentive. A genuine personal opinion can coexist with payment, but the audience should know the relationship and evaluate the evidence rather than relying only on trust in the personality.',
   'A gaming video repeatedly praises a product and includes a purchase link.', ['Check for sponsorship or affiliate disclosure.', 'Consider how the creator may benefit from purchases.', 'Evaluate claims separately from enjoyment of the video.'], 'Ask who benefits from the click.', 'Assuming a friendly presenter cannot be advertising.', 'Check commercial relationships and supporting evidence.',
   'Does a sponsorship automatically prove every product claim is false?', 'No.', 'Why does disclosure matter even when a product is good?', 'It helps viewers understand incentives and make an informed judgement about the recommendation.'],
  ['Compare unit prices', 'Use equal quantities to compare costs in a fictional purchasing decision.',
   'A larger pack may cost more overall but less for each item. Divide price by quantity to compare unit costs, while also considering budget, need and waste. A lower unit price is not automatically the best purchase if most of the pack will not be used. Always compare equivalent items and include relevant costs.',
   'Compare six pencils for £1.80 with ten similar pencils for £2.50.', ['Six-pack unit cost: 180p ÷ 6 = 30p.', 'Ten-pack unit cost: 250p ÷ 10 = 25p.', 'The ten-pack is cheaper per pencil but requires a larger total spend.'], 'Equal unit, fairer price comparison.', 'Choosing only the lowest total price without checking quantity.', 'Calculate unit cost, then consider actual need and affordability.',
   'Does cheaper per item always mean affordable?', 'No.', 'Compare four notebooks for £3.20 with three for £2.70.', '80p versus 90p per notebook. The four-pack is cheaper per notebook, but the total budget and number needed still matter.']
 ]]
]]
];
