import type { Subject, ActivityDetail } from '../authoredActivities';
const core: ActivityDetail = { isPremium: false, difficulty: 'Core', estimatedMinutes: 16, revision: 'Tomorrow, reconstruct the causal chain without notes. In a week, distinguish what changed from what continued and support each claim with a precise example.' };
const challenge: ActivityDetail = { ...core, isPremium: true, difficulty: 'Higher', estimatedMinutes: 22 };
export const year8History: Subject = ['history', [
 ['Reformation: authority and religious change', [
  ['Separate royal supremacy from Protestant doctrine', 'Distinguish changes in church authority from changes in belief and worship.',
   'The 1534 Act of Supremacy recognised Henry VIII as supreme head of the Church of England. Breaking papal authority did not immediately make every belief or practice Protestant. Henry retained important traditional doctrines, while later monarchs changed religious policy in different directions. Explain the distinction between who governs a church and what it teaches; neither chronology nor religious identity should be reduced to one event.',
   'Assess “England became completely Protestant in 1534”.', ['Identify the act as a major change in authority.', 'Distinguish authority from doctrine and worship.', 'Reject completely because traditional beliefs persisted and later policy changed.'], 'Authority is not identical to doctrine.', 'Treating a legal break with Rome as an instant uniform change of belief.', 'Specify which dimension changed and whose experience is being described.', 'Which authority did royal supremacy reject?', 'The pope’s governing authority over the English Church.',
   'Explain one reason the Reformation should be studied as a process rather than a single date.', 'Legal authority, official doctrine, worship and local beliefs changed on different timescales. The 1534 settlement marks an important shift but cannot describe all later religious policy or everyone’s convictions.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What is a monarchy?', answer: 'A system with a king or queen as head of state.' }], memoryExplanation: 'Separating government from teaching prevents one date from carrying several unsupported claims.', misconceptionCause: 'A memorable act of Parliament can obscure slower and contested changes.' }],
  ['Challenge: weigh motives for dissolving monasteries', 'Construct a multi-causal explanation without treating all motives as equally evidenced.',
   'The dissolution of monasteries in the 1530s transferred substantial property and reshaped religious and local life. Explanations include royal finance, political control and criticism of religious houses. Reports alleging misconduct must be examined in light of the investigators’ remit and the Crown’s interests, not simply accepted or dismissed. A persuasive explanation links motives to decisions and consequences while acknowledging uncertainty about individual intentions.',
   'Evaluate a royal investigation reporting failures in a monastery.', ['Identify who commissioned the investigation and its purpose.', 'Ask what specific evidence the report gives and whether independent evidence supports it.', 'Use it as evidence of accusations and policy justification without assuming every allegation is established.'], 'Purpose affects interpretation, not automatic usefulness.', 'Calling a source biased and therefore worthless.', 'Identify the questions it can answer and the claims requiring corroboration.', 'Does evidence of financial benefit prove finance was the only motive?', 'No.',
   'Explain how a report could be useful even if some allegations were exaggerated.', 'It can reveal how dissolution was justified and what behaviour officials condemned. Its claims about actual conduct need comparison with other evidence, so usefulness depends on the historical question.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What is corroboration?', answer: 'Checking a claim against other relevant evidence.' }], memoryExplanation: 'A source may reliably reveal a justification while unreliably describing the conduct it condemns.', misconceptionCause: 'Source evaluation is often reduced to a trustworthy-or-useless label.' }]
 ]],
 ['Civil war: interacting causes and contested authority', [
  ['Connect finance with political conflict under Charles I', 'Explain how disputes about revenue became disputes about government.',
   'Charles I ruled without Parliament from 1629 to 1640. Measures to raise revenue, including extending ship money beyond coastal areas, generated disputes about consent and the limits of royal authority. Religious conflict and wars in Scotland increased pressure on royal finances. The causal link matters: the need for money helped force the recall of Parliament, where existing grievances could be raised rather than automatically resolved.',
   'Build a chain linking military costs to renewed parliamentary conflict.', ['War increased the Crown’s financial needs.', 'Obtaining sufficient revenue made parliamentary cooperation more important.', 'Meeting Parliament gave critics an opportunity to demand changes and air grievances.'], 'Money needs opened an arena for political demands.', 'Listing money and religion as isolated causes without showing connections.', 'Use causal verbs to explain how one pressure changed another.', 'In which year did Charles recall Parliament after the Personal Rule?', '1640.',
   'Why is “Charles needed money, so war immediately began” an incomplete explanation?', 'It skips the intervening disputes, negotiations and breakdown of trust. Financial pressure explains a change in political circumstances, not by itself the decision to fight in 1642.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What is taxation?', answer: 'Compulsory payments collected by government to fund public purposes.' }], memoryExplanation: 'A causal chain explains the mechanism between background pressure and later confrontation.', misconceptionCause: 'A timeline can be mistaken for a complete explanation of why events occurred.' }],
  ['Challenge: distinguish a trigger from long-term causes', 'Evaluate the attempted arrest of five MPs within a wider explanation of war.',
   'In January 1642 Charles entered the Commons seeking to arrest five MPs, who had already left. The episode intensified distrust, but it followed years of conflict and did not alone explain why armed sides formed. Distinguish a trigger that escalates a crisis from longer-term grievances and the later struggle over control of armed forces. Counterfactual questions can test importance, but cannot supply certain answers about an alternative past.',
   'Assess “Without the attempted arrests, civil war could never have happened”.', ['The incident damaged trust and is relevant to escalation.', 'Other unresolved conflicts and military-control disputes remained.', 'Never is too certain because an alternative sequence cannot be directly observed.'], 'A trigger acts on an existing situation.', 'Assuming the nearest dramatic event is a sufficient explanation.', 'Relate escalation to underlying disputes and subsequent choices.', 'Can a trigger also be important?', 'Yes; distinguishing its role does not make it insignificant.',
   'Write a qualified judgement about the incident’s significance.', '“The attempted arrests sharply worsened distrust and narrowed opportunities for cooperation. However, financial, religious and constitutional conflicts, together with disputes over armed force, are needed to explain why the crisis developed into war.”',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What does long-term mean in a causal explanation?', answer: 'A pressure or condition developing before the immediate crisis.' }], memoryExplanation: 'Separate roles in a causal explanation instead of ranking causes by dramatic appearance.', misconceptionCause: 'Narratives can make one vivid moment appear inevitable and all-explanatory.' }]
 ]],
 ['Atlantic slavery, resistance and abolition', [
  ['Explain a coercive economic system', 'Link plantation production to forced labour, commerce and resistance.',
   'Atlantic slavery involved the forced transportation and exploitation of millions of African people. Plantation commodities connected coerced labour to merchants, consumers, finance and states across the Atlantic. The familiar triangular diagram simplifies a much more complex network of routes. Enslaved people resisted through escape, rebellion, preserving relationships and other actions under severe constraints; they were historical agents, not merely passive figures in an economic diagram.',
   'Explain why a commodity-route map alone is insufficient.', ['It can show connections between production and markets.', 'It may hide the violence and coercion that made production possible.', 'It may also omit resistance and the experiences of enslaved people.'], 'Routes connect markets; people and power explain the system.', 'Describing forced transportation as ordinary voluntary migration.', 'State clearly the absence of consent and the coercive legal and labour relations.', 'Did the triangular diagram describe every Atlantic voyage?', 'No.',
   'Give two different kinds of evidence needed to study this system beyond routes.', 'Shipping and plantation records can illuminate trade and production, while testimony and records of resistance help recover experiences and agency. Each source still requires attention to authorship, survival and limitations.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What distinguishes forced labour from freely agreed work?', answer: 'People cannot freely refuse or leave and are compelled through coercion.' }], memoryExplanation: 'A network becomes historically meaningful when the unequal relationships within it are explained.', misconceptionCause: 'Trade diagrams can erase coercion by using the same arrows for commodities and people.' }],
  ['Challenge: distinguish abolition of trade from emancipation', 'Explain the limits of different abolition measures and avoid a single-hero account.',
   'Britain’s 1807 act prohibited its transatlantic slave trade; it did not end slavery in British colonies. The 1833 Slavery Abolition Act led to emancipation across most of the British Empire from 1834, but imposed apprenticeship on many formerly enslaved people until 1838. Compensation went to enslavers, not the people they had enslaved. Campaigning, resistance by enslaved people and changing political circumstances all belong in explanations of abolition.',
   'Correct “The 1807 law immediately freed everyone and compensated them”.', ['Separate prohibiting British slave trading from abolishing slavery.', 'Identify the later 1833 act and the constraints of apprenticeship.', 'State that compensation was paid to enslavers rather than formerly enslaved people.'], 'Trade prohibition, emancipation and equal freedom are different questions.', 'Collapsing several laws and their implementation into a single complete victory.', 'Track legal scope, timing, enforcement and the experiences of affected people.', 'Did the 1807 act itself end plantation slavery in British colonies?', 'No.',
   'Why is an account crediting only one parliamentary campaigner inadequate?', 'It leaves out collective campaigning, resistance by enslaved people and wider political pressures. It also risks treating a law’s passage as the end of the story rather than examining restrictions, compensation and implementation.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What is the difference between a law and its implementation?', answer: 'A law states legal rules; implementation concerns how those rules take effect in practice.' }], memoryExplanation: 'Separate dates and legal scopes reveal both genuine change and continuing injustice.', misconceptionCause: 'Commemorative narratives often compress complex collective struggles into a single person and date.' }]
 ]]
]];
