import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 24 : 17, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, reconstruct the interpretation with a precise short quotation. In a week, test it against a different scene or poem and address evidence that complicates the claim.' });
export const year10EnglishLiterature: Subject = ['english-lit', [
 ['Macbeth: guilt and insecure power', [
  ['Analyse blood as physical evidence and imagined moral stain', 'Connect Macbeth’s language after Duncan’s murder with the distinction between action and consequence.',
   'After Duncan’s murder, Macbeth asks whether “great Neptune’s ocean” can wash the blood from his hand. The enormous imagined scale contrasts with the small physical stain and suggests guilt exceeding ordinary cleaning. Lady Macbeth’s “A little water clears us of this deed” initially treats the problem as manageable evidence. Analyse the contrast between perspectives without assuming one line permanently defines either character’s response throughout the play.',
   'Compare ocean with a little water in the two speeches.', ['Macbeth imagines an almost unlimited cleansing resource as inadequate.', 'Lady Macbeth minimises the required action and presents control.', 'The contrast separates perceived moral consequence from practical removal of evidence.'], 'Physical stain and moral consequence are not the same problem.', 'Explaining blood only as a literal stage property.', 'Connect imagery to the character’s response while retaining the immediate dramatic situation.', 'Which mythological figure is associated with Macbeth’s ocean image?', 'Neptune.',
   'Why does Lady Macbeth’s later sleepwalking complicate her earlier claim?', 'Her later disturbed attempts to remove an imagined stain undermine the confidence that a little water can settle the deed’s consequences. This is a developing dramatic contrast, not a retrospective claim that her earlier practical response was insincere.',
   d(false, 'What has happened immediately before these responses?', 'Duncan has been murdered.', 'A repeated image may be analysed at only one moment rather than across a changing dramatic sequence.')],
  ['Challenge: explain how the pursuit of security deepens tyranny', 'Build a causal thematic argument from Macbeth’s kingship to further violence.',
   'Macbeth’s statement “To be thus is nothing, / But to be safely thus” distinguishes possessing kingship from feeling secure in it. His fear of Banquo and the succession encourages further violence, which creates new threats and isolation. A thematic argument should connect choices and consequences rather than list ambition, guilt and power as separate labels. The play complicates the assumption that achieving a desired position ends the desire or fear.',
   'Explain how safely changes the meaning of Macbeth’s achieved kingship.', ['Thus refers to his position as king in the dramatic context.', 'Safely makes security an additional condition of satisfaction.', 'The new condition helps explain why success leads to further coercion rather than contentment.'], 'Achievement can create a new insecurity rather than closure.', 'Assuming Macbeth’s ambition ends once he becomes king.', 'Trace how the objective changes and generates new decisions.', 'Does the speech present kingship alone as sufficient?', 'No.',
   'Write a qualified whole-play claim about violence and security.', '“Macbeth pursues violence as a means of securing power, yet its consequences repeatedly produce fear and opposition. The play therefore presents a tension between his intended protection and the instability his choices create.”',
   d(true, 'What is tyranny?', 'Oppressive exercise of power without adequate restraint.', 'A theme may be treated as a static character label rather than a pattern of developing actions.')]
 ]],
 ['A Christmas Carol: isolation and social responsibility', [
  ['Interpret Scrooge’s oyster comparison without forcing a symbol', 'Use alternative associations and later development to test a reading.',
   'Dickens describes Scrooge as “solitary as an oyster”. The simile suggests enclosure, hardness and separation from others. A reader may also consider the possibility of something valuable hidden within, but that association should be framed as an interpretation supported by later change, not as a literal guarantee that every oyster contains a pearl. Close reading requires both imaginative association and limits imposed by the text.',
   'Develop a defensible interpretation of solitary and oyster together.', ['Solitary explicitly establishes separation.', 'The oyster’s enclosed shell can reinforce guarded isolation.', 'Later transformation may invite a reading of concealed potential, but that additional association needs qualification.'], 'Start with stated meaning, then test symbolic possibilities.', 'Presenting an optional association as the only possible meaning.', 'Use the wider novella to support rather than merely announce the extension.', 'What comparison device is used in “solitary as an oyster”?', 'Simile.',
   'Why might the opening description make later generosity more significant?', 'A strongly established pattern of isolation provides a contrast against which changed relationships and actions become visible. The transformation matters because it revises an earlier social position, not simply a mood.',
   d(false, 'What is a simile?', 'An explicit comparison commonly using like or as.', 'A memorised symbolic reading can become detached from the wording and its later development.')],
  ['Challenge: connect Ignorance and Want with the novella’s argument', 'Explain personification and social context without replacing analysis with history.',
   'The children named Ignorance and Want embody conditions of deprivation beneath the Ghost of Christmas Present’s robe. Their vulnerable human form turns abstract social problems into an urgent encounter. Dickens published the novella in 1843, amid debates about poverty and responsibility, but a historical date alone does not explain the scene. Analyse naming, presentation and the demand to acknowledge suffering alongside any carefully selected context.',
   'Explain the effect of giving abstract conditions the form of children.', ['The names retain the general social problems.', 'Their embodiment makes vulnerability visible and difficult to dismiss.', 'The scene connects collective conditions with people affected rather than leaving them as detached statistics.'], 'Abstract problem, embodied vulnerability, demanded response.', 'Writing a general paragraph about Victorian poverty without connecting it to the children.', 'Link one relevant contextual idea to a specific textual choice.', 'Are Ignorance and Want simply ordinary names with no thematic role?', 'No.',
   'How could this scene challenge Scrooge’s earlier dismissal of responsibility?', 'It confronts him with vulnerable figures whose suffering cannot be reduced comfortably to institutional provision or distant categories. The encounter pressures the social assumptions expressed earlier in the novella.',
   d(true, 'What does personification do?', 'Presents an abstract or non-human thing through human qualities or form.', 'Context may be inserted as a detachable fact rather than used to illuminate a method.')]
 ]],
 ['Jekyll and Hyde: knowledge and self-explanation', [
  ['Explain the effect of following Utterson’s limited enquiry', 'Connect restricted knowledge with mystery and social assumptions.',
   'Much of Stevenson’s narrative follows Utterson’s attempts to understand troubling evidence about Jekyll and Hyde. His partial knowledge delays the explanation and channels interpretation through a respectable professional’s assumptions. The eventual documents change how earlier details are understood. Limited perspective is not the same as deliberate lying: a character can report sincerely while lacking decisive information.',
   'Explain why a suspicious document does not immediately reveal the whole truth to Utterson.', ['He interprets it using the information and social possibilities available to him.', 'The reader often shares that restricted position.', 'Later testimony can reframe the earlier clue rather than simply add an unrelated surprise.'], 'Restricted knowledge shapes both suspicion and disclosure.', 'Calling every limited viewpoint an intentionally deceptive narrator.', 'Distinguish incomplete understanding from dishonest reporting.', 'What profession is Utterson associated with?', 'Law.',
   'Why would placing the final explanation at the opening change the reading experience?', 'The reader would follow how known facts become uncovered rather than share the mystery of their relationship. Suspense could remain, but its central question and the function of clues would change.',
   d(false, 'What is a narrative perspective?', 'The position through which events and knowledge are presented.', 'A reader’s later knowledge may be projected backwards onto a character who did not yet possess it.')],
  ['Challenge: evaluate Jekyll’s account as an interested explanation', 'Distinguish confession, justification and the author’s overall argument.',
   'Jekyll’s account of divided identity provides essential information but also comes from a participant trying to explain his own actions. His claim that “man is not truly one, but truly two” should be analysed as a character’s proposition within the narrative, not automatically Stevenson’s final scientific statement. Ask whether the language distributes responsibility, acknowledges agency or attempts to separate a respectable self from harmful choices.',
   'Assess a reading that Jekyll’s explanation removes all responsibility for Hyde.', ['The explanation proposes divided aspects of identity.', 'Jekyll nevertheless makes choices enabling and continuing the experiment.', 'A reasoned argument must address those choices rather than use division as automatic exoneration.'], 'An explanation can reveal facts and defend its speaker.', 'Treating a final confession as neutral omniscient commentary.', 'Analyse the speaker’s position, wording and acknowledged actions.', 'Does explaining a harmful action necessarily excuse it?', 'No.',
   'Write a qualified interpretive claim about the final account.', '“Jekyll’s account clarifies the mystery while remaining shaped by his need to explain himself. Its language of division therefore invites scrutiny of responsibility rather than settling every moral question in his favour.”',
   d(true, 'What is a dramatic or narrative voice?', 'A constructed speaker or perspective within a work, distinct from the author as a person.', 'Explanatory authority at a narrative ending may be mistaken for complete reliability or authorial endorsement.')]
 ]],
 ['Poetry comparison: power and representation', [
  ['Analyse the Duke’s control in My Last Duchess', 'Connect possessive language, display and conversational management.',
   'Browning’s speaker introduces “my last Duchess” as a painted image controlled within his own display. The possessive can establish a relationship while also contributing to a reading of ownership, especially alongside his management of who sees the portrait and how her behaviour is described. A dramatic monologue reveals the speaker through what he says and fails to recognise about himself; his judgement is not automatically the poem’s endorsement.',
   'Explain why control of the portrait’s viewing matters.', ['The Duchess is presented through an object the Duke can display selectively.', 'He controls the accompanying account of her character.', 'The arrangement can expose his desire to manage representation and response.'], 'Ask who controls both the image and its explanation.', 'Assuming the speaker’s criticism of the Duchess is an objective verdict.', 'Read his self-revelation and control alongside his stated complaints.', 'What is a dramatic monologue?', 'A poem spoken by a constructed character whose speech reveals their situation and character.',
   'Why should an analysis connect my with further evidence rather than call every possessive oppressive?', 'Possessives have ordinary relational uses. The controlling interpretation becomes stronger through the portrait’s presentation and the speaker’s wider behaviour, not the word alone.',
   d(false, 'What does a possessive determiner indicate?', 'A relationship of possession or association in a noun phrase.', 'One grammatical feature can be assigned a moral meaning without contextual support.')],
  ['Challenge: compare art and failed authority across two poems', 'Integrate My Last Duchess and Ozymandias without flattening their differences.',
   'Both poems connect powerful figures with representations of people, but the effects differ. The Duke appears to control a portrait and its story while revealing troubling traits; Ozymandias’ command survives within a ruined setting that defeats its intended boast. Compare the relationship between authority and art, supporting both sides. A shared theme does not mean identical narrative form, historical situation or ending.',
   'Build a comparison around the viewer’s response.', ['The Duke attempts to direct an immediate listener’s interpretation.', 'Ozymandias’ inscription attempts to command later viewers but is undermined by ruins.', 'Both expose limits or problems in controlling how power is represented, through different structures.'], 'Shared question, distinct mechanisms.', 'Writing that both rulers are powerful without examining how the poems represent that power.', 'Compare voice, framing and material image together.', 'Which poem places the boast within a traveller’s reported account?', 'Ozymandias.',
   'Write one comparative judgement that preserves a difference.', '“Where the Duke’s apparently controlled display exposes him through his own speech, Ozymandias’ ruined monument exposes the failure of a command to survive with its intended meaning. Art outlasts or complicates the authority each ruler tries to assert.”',
   d(true, 'What makes a comparison analytical rather than a pair of summaries?', 'A shared interpretive question supported by evidence and explanation from both works.', 'A shared theme can encourage treating different methods as interchangeable.')]
 ]],
 ['Unseen poetry and form', [
  ['Read a line break as a choice rather than a fixed effect', 'Connect enjambment with syntax and a particular moment of expectation.',
   'Consider this original two-line model: “I kept the key because I could not leave / the room entirely to the dust.” The line break after leave briefly permits one expectation before the next line specifies what is being left. Enjambment carries syntax across a line boundary; it does not always speed reading. Analyse the actual suspended phrase, punctuation and possible reinterpretation rather than attach a universal effect.',
   'Explain the significance of the break after leave.', ['At the line end, leave can momentarily suggest departure.', 'The continuation makes the room the object of leaving to dust.', 'The break can enact hesitation or divided attachment without requiring a single compulsory reading.'], 'Read the sentence across the line, then revisit the break.', 'Saying every enjambment always creates speed and excitement.', 'Identify the particular expectation produced at the boundary.', 'What is enjambment?', 'Continuation of a grammatical unit beyond a line ending.',
   'How would a full stop after “I kept the key” alter the opening?', 'It would make that statement more self-contained and interrupt the immediate causal explanation. The change may create emphasis or delay, but its value depends on the intended voice.',
   d(false, 'What is syntax?', 'The arrangement and grammatical relationship of words and clauses.', 'A formal label can be memorised with one effect instead of tested against the sentence.')],
  ['Challenge: revise an unseen interpretation after a tonal shift', 'Use the ending to qualify rather than erase the earlier reading.',
   'An unseen poem may begin with a celebratory image and end by exposing its cost. In an original model, “We lit the windows gold” is later followed by “but counted every empty chair.” The contrast can turn apparent celebration towards absence without making the opening meaningless. Track the shift and ask whether joy and loss coexist, rather than force the poem into only happy or only sad.',
   'Explain the role of but in the model contrast.', ['The opening establishes warmth and visible celebration.', 'But introduces a counterweight through the empty chairs.', 'The poem can hold communal effort and remembered absence together.'], 'A shift can complicate an emotion rather than replace it.', 'Ignoring the opening once the ending introduces sadness.', 'Explain the relationship between both phases of the poem.', 'What does a tonal shift change?', 'The apparent attitude or emotional register of the speaking voice.',
   'Write a qualified claim about the original model.', '“The illuminated windows suggest a deliberate act of celebration, yet counting the empty chairs makes absence part of that gathering. The contrast presents joy as conscious of loss rather than simply false.”',
   d(true, 'What is tone?', 'The attitude or emotional quality conveyed by a voice’s language and presentation.', 'Binary emotion labels can conceal a poem’s simultaneous or changing attitudes.')]
 ]],
 ['Whole-text arguments and contextual precision', [
  ['Link an extract to a developing pattern elsewhere', 'Move between local detail and the whole work without retelling the plot.',
   'An extract-based argument should explain the local words and then test their significance through another relevant moment. Macbeth’s immediate response to blood can be connected with later altered responses to violence, but a long plot summary does not establish that relationship. Choose a focused comparison in time, identify continuity or change and explain what it contributes to the question being answered.',
   'Plan a paragraph connecting early guilt with later decisions in Macbeth.', ['Analyse one precise early response rather than name guilt alone.', 'Select a later decision or speech relevant to moral response.', 'Explain development or tension and return to the paragraph’s claim.'], 'Local detail, selected later moment, explained relationship.', 'Retelling every event between two quotations.', 'Use only the narrative information needed to support the comparison.', 'Must whole-text knowledge mean mentioning every scene?', 'No.',
   'Why might a contradictory later moment improve the paragraph?', 'It can reveal change, instability or a limit to the initial claim. Addressing it creates a more accurate argument than selecting only moments that repeat the same impression.',
   d(false, 'What is a thesis in an essay?', 'The central argument or interpretive claim developed through the response.', 'Knowledge of many events can be mistaken for an argument about their relationship.')],
  ['Challenge: use context without claiming a uniform historical audience', 'Qualify claims about reception and connect history to textual choices.',
   'Historical audiences were not a single mind. Statements that all Jacobeans feared the same thing or all Victorians held one view need stronger evidence than a broad period label. Context can explain why kingship, poverty, science or reputation mattered, but the link must be specific and relevant. Distinguish a plausible contextual reading from a documented account of every audience member’s response.',
   'Revise “All Victorians agreed with the Duke because men had power”.', ['Reject the unsupported universal claim about agreement.', 'Recognise that gender and social power are relevant contexts.', 'Analyse how the poem’s dramatic self-revelation may invite criticism rather than endorsement of the speaker.'], 'Context opens a reading; it does not dictate every response.', 'Using a period label to erase disagreement or the work’s critical possibilities.', 'Qualify reception claims and return to language and form.', 'Does depicting a powerful speaker prove the work endorses them?', 'No.',
   'Write a more defensible contextual sentence.', '“The Duke’s treatment of the Duchess can be read against unequal gender and social power, while the dramatic monologue exposes the controlling assumptions in his account.” This links context to a method without inventing unanimous approval.',
   d(true, 'What is reception?', 'How audiences or readers encounter and interpret a work.', 'Broad historical knowledge can be inflated into certainty about every individual response.')]
 ]]
]];
