import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 24 : 17, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, reconstruct the particle explanation or calculation without notes. In a week, apply it to a different substance, checking charges, atom conservation, units and assumptions.' });
export const year10Chemistry: Subject = ['chemistry', [
 ['Atomic models and periodic patterns', [
  ['Connect scattering evidence with a nuclear atom', 'Explain why rare large deflections mattered more than a simple average trajectory.',
   'In alpha-particle scattering experiments, most particles passed through thin metal foil with little deflection, while a small fraction deflected strongly. This supported an atom with a small, concentrated positive nucleus and much of its volume not occupied by dense positive material. It challenged a model spreading positive charge throughout the atom. Evidence supported a revised model; the experiment did not directly reveal every detail of modern electron structure.',
   'Explain why the small number of backward deflections was significant.', ['A diffuse positive charge would not readily explain such strong deflection in one encounter.', 'A concentrated region could produce a much stronger interaction.', 'The rarity suggested that region occupied a small fraction of the atom’s cross-sectional area.'], 'Rare observations can discriminate between models.', 'Ignoring unusual trajectories because most particles travelled straight.', 'Ask which observations a proposed model cannot explain.', 'What did most alpha particles do?', 'Passed through with little deflection.',
   'Why does this evidence not prove electrons travel in the exact paths shown in a textbook diagram?', 'The scattering primarily constrained the distribution of mass and positive charge. Electron arrangements required additional evidence and models; a diagram can contain information from several developments.',
   d(false, 'What charge does an alpha particle carry?', 'Positive.', 'A model diagram can be mistaken for a single direct observation of every atomic feature.')],
  ['Challenge: explain opposite reactivity trends in Groups 1 and 7', 'Use electron transfer and shielding without applying one trend to both groups.',
   'Group 1 atoms typically react by losing an outer electron; increased distance and shielding down the group make that electron easier to remove. Group 7 halogens typically gain an electron; increased distance and shielding down the group weaken attraction for an incoming electron. The resulting reactivity trends run in opposite directions. Greater nuclear charge alone is therefore not an adequate explanation without considering shells and shielding.',
   'Compare potassium with sodium and bromine with chlorine.', ['Potassium’s outer electron is farther from the nucleus with more shielding than sodium’s.', 'Potassium therefore loses it more readily in the introductory model.', 'Bromine attracts an incoming electron less strongly than chlorine under comparable conditions, so is the less reactive halogen.'], 'Ask whether the atom loses or gains before predicting the trend.', 'Saying every group becomes more reactive down the periodic table.', 'Link the direction of electron transfer to distance and shielding.', 'Which group tends to gain one electron?', 'Group 7 halogens.',
   'Why can chlorine displace bromide ions but bromine not ordinarily displace chloride ions?', 'Chlorine is the more reactive halogen and more readily gains electrons from bromide ions. Reversing the pair does not have the same favourable electron-transfer tendency under ordinary aqueous conditions.',
   d(true, 'What is electron shielding?', 'Reduction of nuclear attraction experienced by outer electrons due to inner electron shells.', 'A periodic-table direction may be memorised without identifying the process that controls reactivity.')]
 ]],
 ['Structure determines material behaviour', [
  ['Explain metallic bonding and electrical conduction', 'Connect delocalised electrons with properties without describing a metal as molecular.',
   'A simple metallic model contains positive ion cores attracted to delocalised electrons. The mobile electrons can carry charge through a solid metal. Layers can move while attraction is maintained, helping explain malleability in many metals. A metal is not a collection of small molecules held by weak intermolecular forces. Alloys contain different atoms that can hinder layer movement, but their exact properties depend on composition and structure.',
   'Explain why a metal can conduct while solid ionic sodium chloride cannot.', ['Metal electrons can move through the solid structure.', 'Solid salt’s ions occupy lattice positions and cannot move freely through it.', 'Both contain charged particles, but their available mobile carriers differ.'], 'Identify the mobile charge carrier.', 'Saying conductivity proves the whole solid flows internally.', 'Distinguish electron movement from movement of the structural particles.', 'What carries current through a typical metal?', 'Delocalised electrons.',
   'Why can adding differently sized atoms make an alloy harder than a pure metal?', 'Distortion and obstacles in the structure can make layers or defects less able to move. The explanation concerns resistance to deformation, not a claim that every alloy is stronger in every sense.',
   d(false, 'What does malleable mean?', 'Able to deform under compression without readily breaking.', 'Bulk shape change, particle arrangement and electron movement can be conflated.')],
  ['Challenge: compare diamond and graphite using bonding topology', 'Explain different properties of two forms of the same element.',
   'Diamond and graphite both consist of carbon but have different bonding arrangements. Diamond’s carbon atoms each bond to four others in an extended network. In graphite each bonds to three within layers, leaving electrons delocalised within the structure; weaker attractions between layers allow sliding. The difference is not that graphite has weak covalent bonds everywhere. A structure-property argument must identify which interaction governs the property considered.',
   'Explain graphite’s combination of a high melting or sublimation temperature and slippery behaviour.', ['Strong covalent bonds within layers resist disruption.', 'Weaker attractions between layers permit relative sliding.', 'Different interactions control structural breakdown and layer movement.'], 'Same element, different network, different property mechanism.', 'Calling graphite entirely weakly bonded because layers slide.', 'Separate within-layer bonding from between-layer attraction.', 'How many neighbouring carbon atoms does each carbon bond to in graphite’s basic layer model?', 'Three.',
   'Why does diamond not conduct like graphite in the simple model?', 'Its valence electrons are involved in localised covalent bonds, with no comparable mobile delocalised-electron system. Carbon identity alone does not determine conductivity.',
   d(true, 'What is an allotrope?', 'A different structural form of the same element.', 'Identical chemical composition may be assumed to imply identical structure and properties.')]
 ]],
 ['Amounts and reaction quantities', [
  ['Use moles to connect mass with particle amounts', 'Apply n = m/M with consistent molar-mass units.',
   'A mole contains a fixed number of entities, approximately 6.02 × 10^23. Amount n in moles equals mass m in grams divided by molar mass M in grams per mole. Relative formula mass is a dimensionless sum of relative atomic masses; the corresponding molar mass has units. One mole of different substances contains the same number of specified entities but not generally the same mass.',
   'Find the amount in 18 g of water using H = 1 and O = 16.', ['The formula mass is 2 × 1 + 16 = 18.', 'The molar mass is 18 g/mol.', 'n = 18/18 = 1 mol of H2O molecules.'], 'Moles count entities; grams measure mass.', 'Assuming one mole of every substance weighs one gram.', 'Use the substance’s formula to obtain its molar mass.', 'How many moles are in 36 g of water with M = 18 g/mol?', '2 mol.',
   'Calculate the amount in 11 g of CO2 using C = 12 and O = 16.', 'M = 12 + 2 × 16 = 44 g/mol, so n = 11/44 = 0.25 mol. The entity counted is a carbon dioxide molecule.',
   d(false, 'What does the subscript 2 in CO2 indicate?', 'Two oxygen atoms per carbon dioxide molecule.', 'A counting unit can be mistaken for a fixed mass independent of substance.')],
  ['Calculate concentration with a converted solution volume', 'Distinguish grams per cubic decimetre from moles per cubic decimetre.',
   'Mass concentration is solute mass divided by solution volume; amount concentration uses moles divided by volume. A cubic decimetre equals 1,000 cubic centimetres. Use the final solution volume, not automatically the initial water volume, because dissolving can change volume. A number without its concentration units is ambiguous: 2 g/dm³ and 2 mol/dm³ describe very different solutions.',
   'A solution contains 5 g solute in a final volume of 250 cm³.', ['Convert 250 cm³ to 0.250 dm³.', 'Calculate 5/0.250.', 'Mass concentration is 20 g/dm³.'], 'Convert the volume before dividing.', 'Dividing by 250 and labelling the result grams per dm³.', 'Match the volume unit to the concentration unit.', 'How many dm³ is 500 cm³?', '0.500 dm³.',
   'Find molar concentration when 0.10 mol is present in 200 cm³ of solution.', 'The volume is 0.200 dm³, so concentration = 0.10/0.200 = 0.50 mol/dm³. This is an amount concentration, not a mass concentration.',
   d(false, 'What does solute mean?', 'The dissolved substance in a solution.', 'Numerically correct division can produce a thousand-fold error when volume units are not converted.')],
  ['Challenge: identify a limiting reactant from mole ratios', 'Compare available amounts with balanced-equation requirements.',
   'Balanced coefficients give ratios of amounts in moles, not necessarily ratios of masses. For 2H2 + O2 → 2H2O, two moles of hydrogen require one mole of oxygen. A limiting reactant is consumed first according to that ratio and sets the maximum product amount. Having fewer grams does not automatically make a substance limiting; convert and compare chemically relevant amounts.',
   'There are 3 mol H2 and 2 mol O2 in the stated reaction.', ['Three moles of H2 require 1.5 mol O2.', 'Oxygen is available in excess, so hydrogen is limiting.', 'At complete conversion, 3 mol H2O form and 0.5 mol O2 remains.'], 'Compare available amount divided by required coefficient.', 'Selecting the smaller starting number without accounting for the equation.', 'Use the balanced mole ratio before deciding which runs out.', 'Do equation coefficients normally represent gram ratios?', 'No.',
   'For the same reaction, find maximum water from 4 mol H2 and 1 mol O2.', 'Oxygen is limiting: 1 mol O2 reacts with 2 mol H2 to form 2 mol H2O. Two moles of H2 remain if the reaction completes under the stated model.',
   d(true, 'Why must a chemical equation be balanced?', 'To conserve the number of atoms of each element.', 'Mass, amount and coefficient values can be compared directly despite representing different quantities.')]
 ]],
 ['Acids, salts and ionic explanations', [
  ['Explain neutralisation in terms of ions', 'Connect acid-alkali reactions with water formation and spectator ions.',
   'In a simple aqueous acid-alkali reaction, hydrogen ions from the acid react with hydroxide ions from the alkali to form water: H+ + OH− → H2O. Other ions remain in solution and determine the salt obtainable after suitable separation. Neutral does not mean every ion disappears, and an excess of acid or alkali can leave the final solution non-neutral. Practical work requires supervised school procedures.',
   'Explain hydrochloric acid reacting with sodium hydroxide.', ['Identify H+ from the acid and OH− from the alkali.', 'They form water in the net ionic reaction.', 'Na+ and Cl− remain as spectator ions, corresponding to sodium chloride in solution.'], 'Neutralisation removes the reacting acid-base ions, not all ions.', 'Claiming neutralised solution contains only water.', 'Account for spectator ions and any excess reactant.', 'What is the formula of the hydroxide ion?', 'OH−.',
   'Why does mixing any volumes of an acid and alkali not guarantee pH 7?', 'Their concentrations and reacting amounts may not match, leaving one in excess. Also, acid-base systems differ; the simple neutral endpoint assumption applies to suitable strong acid-strong alkali examples.',
   d(false, 'What is an alkali?', 'A soluble base that produces hydroxide ions in water in this introductory model.', 'The word neutralisation can be interpreted as an automatic final pH rather than a reacting process.')],
  ['Challenge: choose a salt-preparation method by solubility', 'Explain why excess-solid separation works for one reactant but not another.',
   'To make a soluble salt from an acid and a suitable insoluble base, excess solid can ensure acid consumption and then be removed by filtration under a supervised method. An excess soluble alkali cannot be filtered out in the same way; controlled amount measurement, often using titration, is needed. Method choice follows physical properties and reaction chemistry, not simply a memorised sequence for every salt.',
   'Compare an insoluble metal oxide with sodium hydroxide as a reactant for a soluble salt.', ['Unreacted insoluble oxide remains a separable solid.', 'Dissolved sodium hydroxide passes through ordinary filter paper with the solution.', 'The second preparation therefore needs control of reacting amounts rather than filtration of excess alkali.'], 'Filtration separates particles, not dissolved ions.', 'Claiming a filter removes all excess reactants regardless of solubility.', 'State whether the excess species is dissolved or solid.', 'Can ordinary filtration remove dissolved sodium ions from water?', 'No.',
   'Why should crystals be dried before using their mass to estimate yield?', 'Attached solution or water not part of the intended product can inflate the measured mass. The appropriate drying conditions depend on the salt and whether its crystal water must be retained.',
   d(true, 'What does soluble mean?', 'Able to dissolve in a stated solvent under the conditions.', 'A familiar laboratory operation can be chosen without checking what form the impurity takes.')]
 ]],
 ['Electrolysis and selective discharge', [
  ['Track ions and electrons in molten electrolysis', 'Explain reduction and oxidation at electrodes without sending ions through the wire.',
   'Electrolysis uses electrical energy to drive chemical change in an ionic conductor. In a molten ionic compound, positive ions move towards the negative cathode and gain electrons; negative ions move towards the positive anode and lose electrons. Electrons travel in the external circuit, while ions carry charge through the melt. The products depend on the ions present and electrode material.',
   'Describe molten lead bromide using inert electrodes as a theoretical example.', ['Pb2+ ions reach the cathode and gain two electrons to form lead.', 'Bromide ions reach the anode and lose electrons.', 'Two bromide ions form one Br2 molecule; this is a theoretical model, not an unsupervised practical instruction.'], 'Cathode gains electrons; anode loses electrons.', 'Saying positive metal ions travel through the external wire.', 'Distinguish charge carriers in metal wires and ionic material.', 'Is electron gain reduction or oxidation?', 'Reduction.',
   'Balance the cathode half-equation for Mg2+ becoming magnesium.', 'Mg2+ + 2e− → Mg. The two electrons balance the ion’s positive charge, and the magnesium atom count remains one.',
   d(false, 'What makes a cation positively charged?', 'It has fewer electrons than protons.', 'A single phrase electric current can conceal different charge carriers in different parts of a circuit.')],
  ['Challenge: explain why an aqueous electrolyte has extra possible products', 'Account for water-derived species and state the limits of simplified selection rules.',
   'An aqueous electrolyte contains water as well as dissolved ions, so its products can differ from those of the molten compound. In introductory cases, a metal less reactive than hydrogen may be deposited at the cathode; otherwise hydrogen can form. At an inert anode, halide-containing solutions may produce a halogen, while other cases may produce oxygen. Concentration, electrode material and conditions matter; these are models for stated cases, not universal recipes.',
   'Compare aqueous copper sulfate with molten copper chloride conceptually.', ['The aqueous solution includes water-derived competing species.', 'Copper can be deposited from Cu2+ at the cathode under the usual school model.', 'An inert anode in aqueous sulfate typically yields oxygen, showing why the dissolved anion alone does not identify every product.'], 'Water adds competitors; conditions select products.', 'Predicting aqueous products solely by reading the solute’s formula.', 'List the relevant species and state the assumed electrode and conditions.', 'Why can molten and aqueous forms give different products?', 'The aqueous system includes water and its associated species.',
   'Why would replacing an inert copper-sulfate anode with copper alter the interpretation?', 'The copper electrode can itself oxidise and supply Cu2+ ions. Electrode material is then part of the chemistry, so the inert-anode prediction no longer applies unchanged.',
   d(true, 'What does aqueous mean?', 'Dissolved in water.', 'The solvent and electrode may be treated as passive even when they can participate in reactions.')]
 ]],
 ['Energy changes and equilibrium', [
  ['Estimate a reaction energy change from bond energies', 'Subtract bond-making release from bond-breaking input.',
   'Breaking bonds requires energy; forming bonds releases energy. A bond-energy estimate of reaction energy change is energy to break reactant bonds minus energy released forming product bonds. Average bond energies are approximations and usually describe gas-phase bonds, so a calculation may not equal a measured value under different conditions. Exothermic reactions have a negative result under this convention.',
   'For H2 + Cl2 → 2HCl, use H–H 436, Cl–Cl 243 and H–Cl 431 kJ/mol.', ['Breaking requires 436 + 243 = 679 kJ per mole of reaction as written.', 'Forming two H–Cl bonds releases 2 × 431 = 862 kJ.', 'Estimated change is 679 − 862 = −183 kJ/mol of reaction, so it is exothermic.'], 'Break costs; make releases; subtract in that order.', 'Claiming bond breaking releases stored energy by itself.', 'Evaluate the whole balance of broken and formed bonds.', 'What sign indicates an exothermic change under this convention?', 'Negative.',
   'If breaking requires 500 kJ and forming releases 420 kJ for a stated reaction amount, classify the change.', '500 − 420 = +80 kJ, so that amount of reaction absorbs energy overall and is endothermic.',
   d(false, 'What does exothermic mean?', 'Energy is transferred from the reacting system to the surroundings.', 'The phrase energy stored in bonds can lead to the mistaken idea that breaking a bond alone releases energy.')],
  ['Challenge: distinguish equilibrium position from reaction speed', 'Predict the effect of temperature and catalysts on a reversible exothermic reaction.',
   'At dynamic equilibrium in a closed system, forward and reverse reactions continue at equal rates, so macroscopic amounts remain constant. Increasing temperature favours the endothermic direction, while a catalyst speeds both directions without changing the equilibrium composition at that temperature. Reaching equilibrium sooner is different from obtaining a higher equilibrium yield. A closed system prevents relevant matter escaping; it need not be thermally isolated.',
   'The forward reaction is exothermic and the system is at equilibrium.', ['A temperature rise favours the endothermic reverse direction.', 'The equilibrium amount of forward product therefore decreases in the simple model.', 'Adding a catalyst instead changes the time to reach equilibrium, not its final position at fixed conditions.'], 'Position determines composition; speed determines how quickly it is reached.', 'Saying a catalyst always increases equilibrium product yield.', 'Separate kinetic and equilibrium effects.', 'Are forward and reverse reactions stopped at equilibrium?', 'No; their rates are equal.',
   'Why can equal forward and reverse rates coexist with unequal reactant and product concentrations?', 'The two rates depend on their own reaction pathways and concentrations. Equal rates mean no net change, not equal amounts of every substance.',
   d(true, 'What does reversible mean for a reaction?', 'The products can react to reform reactants under suitable conditions.', 'Everyday meanings of balance can be confused with equal quantities rather than equal opposing rates.')]
 ]],
 ['Organic molecules and useful mixtures', [
  ['Balance complete alkane combustion', 'Apply the general alkane formula and conserve carbon, hydrogen and oxygen atoms.',
   'Acyclic alkanes have the general formula CnH2n+2 and contain only single carbon-carbon bonds. Complete combustion in sufficient oxygen produces carbon dioxide and water. Balance carbon first, hydrogen next and oxygen last; coefficients change amounts without changing each molecule’s formula. Insufficient oxygen can lead to carbon monoxide or carbon, so combustion safety is not established by writing a complete-combustion equation.',
   'Balance complete combustion of propane, C3H8.', ['Three carbon atoms require 3CO2.', 'Eight hydrogen atoms require 4H2O.', 'Products contain ten oxygen atoms, so use 5O2: C3H8 + 5O2 → 3CO2 + 4H2O.'], 'Carbon, hydrogen, then oxygen count.', 'Changing H2O to another formula to balance the equation.', 'Adjust coefficients rather than the identity of products.', 'What is the alkane formula for four carbon atoms?', 'C4H10.',
   'Balance complete methane combustion.', 'CH4 + 2O2 → CO2 + 2H2O. Both sides contain one carbon, four hydrogen and four oxygen atoms.',
   d(false, 'What does a coefficient before a chemical formula count?', 'The relative number of molecules or moles of that species.', 'Formula subscripts and reaction coefficients can be treated as interchangeable balancing tools.')],
  ['Challenge: distinguish cracking from fractional distillation', 'Explain a physical separation versus a chemical conversion.',
   'Fractional distillation separates a mixture into boiling ranges without intentionally changing the molecules’ covalent structures. Cracking breaks larger hydrocarbons into smaller molecules, often producing a mixture containing alkanes and alkenes. The two processes meet different needs: separating existing substances is not the same as making different ones. Product equations must conserve atoms, and industrial process conditions should not be treated as home experiments.',
   'Check C10H22 → C8H18 + C2H4 as a possible simplified cracking equation.', ['Carbon counts are 10 on each side.', 'Hydrogen counts are 22 on each side.', 'An alkane and an alkene result, so molecular identities changed rather than merely being separated.'], 'Distillation sorts molecules; cracking changes them.', 'Calling a smaller fraction a cracked product merely because it boils earlier.', 'Ask whether bonds and molecular formulas have changed.', 'Does an alkene contain a carbon-carbon double bond?', 'Yes.',
   'Why can a distillation fraction still be a mixture?', 'Several compounds have similar boiling ranges and can be collected together. A fraction is not automatically one pure chemical substance.',
   d(true, 'What is a physical separation?', 'Separation that does not intentionally create new substances by chemical reaction.', 'Industrial stages can be conflated because both produce useful hydrocarbon streams.')]
 ]],
 ['Analysis and water quality', [
  ['Calculate and interpret a chromatography Rf value', 'Use comparable conditions and the solvent-front distance.',
   'In paper chromatography, substances partition differently between the stationary phase and moving solvent. Rf is distance travelled by a spot from the baseline divided by distance travelled by the solvent front from the same baseline. Compare values only under suitable matched conditions. A single matching Rf supports but does not uniquely prove identity because different substances can behave similarly.',
   'A spot moves 36 mm while the solvent front moves 60 mm.', ['Measure both distances from the baseline.', 'Calculate Rf = 36/60.', 'Rf = 0.60, a unitless ratio.'], 'Same origin, spot over front.', 'Measuring from the paper edge instead of the baseline.', 'Identify the origin and solvent front on the actual chromatogram.', 'Does Rf have millimetre units?', 'No.',
   'Why might the same substance have a different Rf in another solvent?', 'The balance of attraction to stationary and mobile phases changes with solvent composition. An Rf value is conditional on the method, not a universal permanent identifier.',
   d(false, 'What does a ratio compare?', 'Two quantities by division.', 'A numerical identifier may be treated as unique and independent of experimental conditions.')],
  ['Challenge: distinguish potable water from chemically pure water', 'Match treatment processes to the contaminants they can address.',
   'Potable water is suitable for drinking according to relevant safety standards; it need not contain only H2O molecules. Dissolved minerals may remain. Filtration removes appropriate suspended particles, while disinfection targets microorganisms; neither automatically removes every dissolved chemical. Desalination removes salts but requires energy and suitable controls. Clear appearance alone is not evidence of safe drinking water, and classroom filtration must not be used to declare water drinkable.',
   'Evaluate “The filtered sample is clear, therefore it is safe”.', ['Clarity suggests reduced visible suspended material.', 'Dissolved contaminants and microorganisms may remain.', 'Safety needs validated treatment and testing, not a visual judgement.'], 'Clear is an appearance; potable is a safety judgement.', 'Treating every contaminant as a particle removable by filter paper.', 'Identify the contaminant and appropriate validated treatment.', 'Must potable water be chemically pure?', 'No.',
   'Why might disinfection and filtration both be used in a treatment train?', 'They address different problems: particle removal and microbial risk reduction. Combining steps can be necessary, but each still has conditions and limitations requiring monitoring.',
   d(true, 'What is a dissolved substance?', 'A solute dispersed at molecular or ionic scale in a solvent.', 'A successful visible change can hide hazards that cannot be seen.')]
 ]]
]];
