import type { Subject, ActivityDetail } from '../authoredActivities';
const free: ActivityDetail = { isPremium: false, difficulty: 'Core', estimatedMinutes: 15, revision: 'Tomorrow, draw the process from memory. Next week, answer the application again and explain each causal link.' };
const extension: ActivityDetail = { ...free, isPremium: true, difficulty: 'Higher', estimatedMinutes: 20 };
export const year8Biology: Subject = ['biology', [
 ['Digestion and absorption', [
  ['Explain enzyme action in digestion', 'Connect the breakdown of large food molecules with absorption.',
   'Digestion breaks large insoluble molecules into smaller soluble ones that can be absorbed. Enzymes are biological catalysts: they speed specific reactions without being used up in the overall process. Amylase acts on starch; proteases act on proteins. Chewing increases surface area but does not itself perform the same chemical breakdown as an enzyme.',
   'Explain why chewing can help starch digestion.', ['Chewing divides food into smaller pieces.', 'More surface is exposed to saliva containing amylase.', 'The enzyme can act on exposed starch, producing smaller carbohydrate molecules.'], 'Mechanical exposes; chemical changes molecules.', 'Calling enzymes living organisms that eat food.', 'Enzymes are molecules catalysing reactions.', 'Why must many food molecules be digested before absorption?', 'They are too large or insoluble to be absorbed readily in their original form.',
   'Distinguish biting a potato from amylase acting on its starch.', 'Biting changes the size of food pieces; amylase catalyses chemical breakdown of starch molecules. Both can contribute to digestion but perform different roles.',
   { ...free, memoryExplanation: 'The distinction separates changes in food-piece size from molecular changes.', misconceptionCause: 'Both processes are called breaking down in ordinary language.' }],
  ['Challenge: explain villus adaptations causally', 'Link small-intestine structure with efficient uptake and transport.',
   'Villi increase the small intestine’s surface area. Their thin surface reduces diffusion distance, and blood flow carries absorbed substances away, helping maintain concentration differences. These adaptations cooperate: simply saying a villus is efficient earns little explanation. Different digested products follow different transport routes; not all absorbed fat enters blood capillaries directly.',
   'Predict an effect of damage that flattens villi.', ['Flattening reduces available absorption area.', 'Less surface can exchange substances over the same time.', 'Nutrient uptake may be reduced even when digestion still produces small molecules.'], 'Area, distance, transport away.', 'Explaining absorption only by saying villi are small.', 'Specify which dimension or process changes transfer.', 'What does a thin absorption surface reduce?', 'The distance substances must cross.',
   'Why would slower removal of absorbed glucose tend to reduce net diffusion, all else equal?', 'Glucose can accumulate on the receiving side, reducing the concentration difference that drives net diffusion. Transport away helps preserve that difference.',
   { ...extension, memoryExplanation: 'Each word names a separate part of the transfer problem.', misconceptionCause: 'Listing adaptations without their mechanisms turns explanation into labels.' }]
 ]],
 ['Respiration and activity', [
  ['Distinguish respiration from ventilation', 'Explain energy release in cells rather than confusing it with breathing.',
   'Aerobic respiration transfers energy from glucose through reactions using oxygen, producing carbon dioxide and water. It occurs in cells, not just the lungs. Ventilation moves air into and out of the lungs, supporting gas exchange that supplies oxygen and removes carbon dioxide. Plants respire too, including when they cannot photosynthesise.',
   'Explain how breathing supports a working leg muscle.', ['Ventilation brings fresh air to the lungs.', 'Oxygen passes into blood and is transported to muscle cells.', 'Cells use oxygen in aerobic respiration to transfer energy for activity.'], 'Breathing supplies; cells release energy.', 'Saying plants only photosynthesise and never respire.', 'Living plant cells need respiration day and night.', 'Name the products of aerobic respiration.', 'Carbon dioxide and water.',
   'A plant is kept in darkness briefly. Does respiration stop immediately?', 'No. It can continue respiring using stored organic molecules; photosynthesis requires light, but respiration does not directly require illumination.',
   { ...free, memoryExplanation: 'Following oxygen from air to a cell separates related processes.', misconceptionCause: 'Everyday speech uses breathing and respiration as if they were identical.' }],
  ['Challenge: interpret oxygen demand during exercise', 'Explain why anaerobic pathways may contribute during intense activity.',
   'During intense activity, aerobic energy transfer may not meet demand even as breathing and heart rate rise. Muscles can also respire anaerobically, transferring less energy per glucose and producing lactate. Recovery involves several processes, so do not claim that lactate alone explains every type of fatigue or later soreness. Interpret measured changes rather than diagnosing from a single pulse reading.',
   'Explain increased breathing after a sprint has ended.', ['The body has not instantly returned to its resting state.', 'Recovery processes and restored oxygen supply continue to require circulation and ventilation.', 'Breathing can remain elevated even though rapid movement has stopped.'], 'Activity ends before recovery ends.', 'Treating all post-exercise soreness as trapped lactate.', 'Distinguish short-term metabolic recovery from delayed muscle soreness.', 'Which pathway yields less energy per glucose: aerobic or anaerobic respiration?', 'Anaerobic respiration.',
   'Why does faster breathing during a sprint not prove all muscle respiration is aerobic?', 'Delivery and use of oxygen may still not meet the high demand; aerobic and anaerobic pathways can contribute at the same time.',
   { ...extension, memoryExplanation: 'The timing reminder prevents equating visible movement with all cellular demand.', misconceptionCause: 'One observable response can be mistaken for proof of the whole internal process.' }]
 ]],
 ['Ecological interactions', [
  ['Interpret a food web', 'Predict direct and indirect consequences while recognising alternative food sources.',
   'A food web joins feeding relationships rather than showing a single chain. Arrows point from food to consumer, representing transfer of material and energy. If a prey species decreases, a predator may switch to another source or decline; the result depends on the web and other conditions. One arrow does not prove an animal eats nothing else.',
   'Rabbits and mice are eaten by foxes; rabbits also feed another predator. Predict a rabbit decline.', ['Both predators lose one food source.', 'Foxes may increase reliance on mice if available.', 'Population effects remain conditional on alternatives and other limiting factors.'], 'Follow every connected route.', 'Predicting that a predator must immediately disappear when one prey falls.', 'Check other foods and the scale of the change.', 'Which direction do food-web arrows point?', 'From the food organism towards its consumer.',
   'Explain why removing a predator could affect plants indirectly.', 'Herbivores may increase when predation falls and consume more plants, although competition, disease and food limits can alter the outcome.',
   { ...free, memoryExplanation: 'A web contains alternative pathways missing from a simple chain.', misconceptionCause: 'A familiar three-organism chain can encourage one-route predictions.' }],
  ['Challenge: evaluate competition evidence', 'Distinguish a plausible ecological mechanism from proof by correlation.',
   'Organisms compete when a shared resource is limited. Plants may compete for light, water, mineral ions or space. Poor growth near a large tree could reflect competition, but shade, soil differences and other factors need investigation. A comparison must identify the resource and control alternatives before assigning the whole effect to one cause.',
   'Seedlings near a tree are smaller than those farther away.', ['State the observed association without assuming a cause.', 'Propose mechanisms such as lower light or water availability.', 'Measure relevant conditions and design safe controlled comparisons where feasible.'], 'Shared resource must be limiting.', 'Calling any proximity between organisms competition.', 'Identify a resource both need and evidence that supply limits performance.', 'Can two species compete for the same resource?', 'Yes, when they both use it and it is limiting.',
   'Why would adding more water alone not fully test a claim about light competition?', 'It changes water availability, not the proposed limiting light. A useful test must measure or manipulate light while controlling relevant alternatives.',
   { ...extension, memoryExplanation: 'Competition requires both overlap in need and constrained availability.', misconceptionCause: 'Visible co-occurrence is easier to notice than the actual limiting resource.' }]
 ]]
]];
