import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 24 : 17, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, reconstruct the calculation or decision chain. In a week, change one business assumption and explain how the recommendation changes rather than repeating a general advantage.' });
export const year10Business: Subject = ['business', [
 ['Ownership, objectives and stakeholders', [
  ['Compare limited liability with ownership and control', 'Distinguish a company’s separate identity from an owner’s personal position.',
   'A limited company has a separate legal identity from its owners. Shareholders’ liability is generally limited to their investment or unpaid share commitments, while a sole trader ordinarily has personal liability for business debts. Limited liability does not mean a business cannot fail, directors can ignore duties or lenders never seek personal guarantees. Ownership structure also affects control, administration and access to finance.',
   'Compare a fictional sole-trader repair shop with a private limited company.', ['The sole trader keeps direct control but generally faces personal responsibility for debts.', 'The company separates business identity from shareholders under the relevant rules.', 'The choice also involves reporting, finance and management considerations rather than liability alone.'], 'Limited liability limits a defined exposure, not every risk.', 'Assuming incorporation guarantees the owner cannot lose money.', 'Distinguish business failure, investment loss and additional personal obligations.', 'Does a shareholder automatically manage every daily decision?', 'No.',
   'Why might a small owner accept sole-trader risks initially?', 'They may value simple administration and direct control, with modest financing needs. That explanation depends on their actual risks and circumstances and is not a recommendation to choose a legal structure without advice.',
   d(false, 'What is a stakeholder?', 'A person or group affected by or interested in a business’s activities.', 'One legal advantage can be interpreted as a complete removal of commercial risk.')],
  ['Challenge: resolve a stakeholder conflict with explicit criteria', 'Evaluate a relocation beyond a single profit figure.',
   'A relocation can lower rent while increasing employee travel, losing local customers or improving delivery access. Stakeholders may value different outcomes, and short-term savings can conflict with long-term capability. Evaluate options against stated objectives and evidence. A balanced answer need not give every stakeholder equal influence, but it should explain whose interests are affected and why a recommendation remains defensible.',
   'A fictional bakery could save £12,000 annual rent by moving away from its main customer area.', ['Identify the saving and estimate possible lost contribution from customers.', 'Consider staff retention, delivery and transition costs.', 'Recommend only after comparing the net effect and uncertainties with the bakery’s objectives.'], 'A saving is one consequence, not a complete decision.', 'Choosing the lowest rent while ignoring revenue and staff effects.', 'Use an option-wide comparison with explicit assumptions.', 'Can an action help one stakeholder while harming another?', 'Yes.',
   'What evidence would make the relocation judgement stronger?', 'Customer location and purchasing data, staff consultation, realistic moving costs and demand testing at the new site would reduce uncertainty. The rent figure alone cannot establish higher long-term profit.',
   d(true, 'What is an objective?', 'An outcome the organisation aims to achieve.', 'A readily quantified benefit can crowd out less visible but important costs.')]
 ]],
 ['Revenue, contribution and break-even', [
  ['Calculate profit without confusing revenue with cash', 'Separate sales income, variable cost and fixed cost in a stated period.',
   'Revenue equals selling price multiplied by quantity sold. In a simple model, total cost combines fixed costs and variable cost per unit multiplied by output. Profit is revenue minus total cost; it is not the same as the balance in a bank account because payment timing and non-profit transactions matter. State the period and whether produced items are also sold before using the model.',
   'A fictional stall sells 200 items at £6, with variable cost £2 each and fixed costs £500 for the period.', ['Revenue is 200 × £6 = £1,200.', 'Total cost is £400 variable plus £500 fixed = £900.', 'Profit is £300 under the stated model.'], 'Revenue less all relevant costs gives profit.', 'Calling the full sales income profit.', 'Separate the price received from the cost of supplying the sale.', 'What is contribution per unit in this example?', '£6 − £2 = £4.',
   'Find break-even quantity for the same price and costs.', 'Break-even is fixed cost divided by unit contribution: £500/£4 = 125 items. At that sales level total contribution covers fixed cost, assuming the linear model holds.',
   d(false, 'What is a fixed cost in a short-run model?', 'A cost that does not change with output within the relevant period and range.', 'Money arriving from sales can be mistaken for the amount left after producing those sales.')],
  ['Challenge: test a price cut against required sales growth', 'Use contribution rather than revenue alone to judge the proposal.',
   'A lower price may increase sales but reduces contribution per unit if variable cost stays fixed. To preserve total contribution, the firm may need a larger proportional quantity increase than the percentage price reduction suggests. Demand response, capacity and added costs are uncertain. A numerical threshold identifies what must happen; it does not prove customers will respond accordingly.',
   'Price falls from £10 to £8 with variable cost £4. Current sales are 100 units.', ['Original contribution is £6 per unit, or £600 total.', 'New contribution is £4 per unit.', 'Maintaining £600 requires 150 units, a 50 percent quantity rise, with fixed costs unchanged.'], 'Price changes the margin on every unit.', 'Judging success only from higher sales volume or revenue.', 'Compare total contribution and costs under both scenarios.', 'Does a 20 percent price cut require only 20 percent more sales in this example?', 'No.',
   'Why might selling 150 units still fail to preserve profit?', 'Extra capacity, overtime, delivery or marketing may add costs. The threshold assumes the original cost model remains valid, so those changes must be included.',
   d(true, 'What is contribution?', 'Revenue remaining after variable costs, available to cover fixed costs and profit.', 'The quantity response may be considered without the reduced margin on existing as well as additional sales.')]
 ]],
 ['Cash flow and sources of finance', [
  ['Construct a simple cash-flow forecast', 'Distinguish opening balance, net flow and closing balance.',
   'A cash-flow forecast records expected cash receipts and payments by period. Net flow is receipts minus payments; closing balance is opening balance plus net flow. A profitable business can still face a cash shortage if customers pay late or stock is bought before sales receipts arrive. A forecast is a planning estimate, not evidence that the cash has already arrived.',
   'Opening cash is £700, expected receipts £1,200 and payments £1,500.', ['Net flow is £1,200 − £1,500 = −£300.', 'Closing cash is £700 − £300 = £400.', 'A negative net flow does not necessarily mean a negative closing balance.'], 'Opening plus movement equals closing.', 'Calling a negative monthly net flow the same as insolvency or a loss.', 'Separate cash movement, cash balance and accounting profit.', 'What becomes next period’s opening cash in a continuous forecast?', 'The previous period’s closing balance.',
   'If £500 of expected receipts is delayed beyond the period, find the revised closing balance.', 'Receipts become £700, net flow becomes −£800 and closing cash becomes −£100. The forecast exposes a financing or payment-timing problem requiring action.',
   d(false, 'What is a cash receipt?', 'Money actually entering the business during the period.', 'A sale may be counted as received money even when the customer has not paid.')],
  ['Challenge: match finance to purpose and repayment capacity', 'Evaluate a funding source using timing, cost, control and risk.',
   'Short-lived cash gaps and long-lived assets create different funding needs. An overdraft may offer flexibility for temporary timing differences, while a longer-term loan spreads repayment for an asset but creates scheduled commitments. Selling equity can raise funds without the same repayment schedule while diluting ownership and future returns. No source is best for every business; test affordability and the use of funds.',
   'A fictional firm needs machinery expected to be used for several years.', ['Identify the asset’s long-lived purpose and expected contribution.', 'Compare loan repayments with forecast cash available over time.', 'Consider alternatives and risks rather than rely permanently on an uncertain short-term facility.'], 'Match the funding clock to the business need.', 'Choosing finance only because it is immediately available.', 'Compare total cost, repayment timing, flexibility and control.', 'Does issuing shares usually preserve all existing owners’ percentage control?', 'Not necessarily.',
   'Why should an optimistic sales forecast be stress-tested before borrowing?', 'If receipts are lower or later, fixed repayments may strain cash. Alternative scenarios reveal whether the proposal depends on an unrealistically favourable outcome.',
   d(true, 'What is a forecast?', 'An estimate of future outcomes based on stated assumptions.', 'The funding decision can be separated from the cash flows needed to service it.')]
 ]],
 ['Market research and positioning', [
  ['Choose research to answer a defined business question', 'Distinguish customer preferences from willingness to buy at a specific price.',
   'Market research should begin with a decision question. Asking whether people like a product concept differs from testing whether the target market will buy it at a stated price and under realistic conditions. Primary research collects new evidence; secondary research uses existing sources. Both require attention to relevance, sample selection and bias. A large number of enthusiastic responses from friends may not represent likely customers.',
   'A fictional café considers a £5 lunch product.', ['Define the target customers and purchase occasion.', 'Ask about the actual product and price rather than a vague idea of liking lunch.', 'Compare responses with a small realistic trial and relevant existing market information.'], 'Research the decision, not only the enthusiasm.', 'Treating positive opinions as guaranteed paid demand.', 'Include price, context and representative recruitment.', 'What is primary research?', 'New data collected for the investigation.',
   'Why might a free tasting overestimate paid demand?', 'Removing price changes the decision and can attract people who would not purchase. The trial can inform product quality but does not by itself establish sales at the intended price.',
   d(false, 'What is a target market?', 'The customer group a business intends to serve.', 'Approval of an idea can be mistaken for behaviour under real purchase constraints.')],
  ['Challenge: align the marketing mix with a positioning claim', 'Evaluate product, price, promotion and place as a connected decision.',
   'A positioning claim identifies how a product should be understood relative to alternatives. A premium-service claim can be undermined by unreliable delivery or unclear support, even if advertising is polished. Price, product, promotion and distribution should support a coherent proposition while fitting costs and target customers. Consistency is not proof of demand; it makes the strategy testable.',
   'A fictional shop promotes durable repairs but offers no explanation of aftercare.', ['Identify the promised value of durability.', 'Check product service and aftercare against that promise.', 'Revise operations and communication together rather than merely increase advertising.'], 'The promise must survive the delivery.', 'Treating marketing as advertising alone.', 'Examine all relevant parts of the offer and customer experience.', 'What does place concern in the marketing mix?', 'How and where the product or service reaches customers.',
   'Why might a lower price damage rather than improve this positioning?', 'It could weaken perceived quality or make the promised service financially unsustainable, depending on customers and costs. A lower price is not automatically wrong, but it must fit the proposition and evidence.',
   d(true, 'What is positioning?', 'The intended place of an offer in customers’ understanding relative to alternatives.', 'Visible promotional activity can overshadow whether the underlying offer fulfils its claims.')]
 ]],
 ['Operations, quality and productivity', [
  ['Calculate labour productivity and interpret its limits', 'Distinguish output per worker from profit and product quality.',
   'Labour productivity can be measured as output per worker or per worker-hour over a defined period. Higher output per hour may reflect better equipment, organisation or skills, but counting defective units as successful output can mislead. Productivity is not profit: prices and costs still matter. State whether the measure uses all output or acceptable finished output before comparing teams.',
   'A team makes 240 acceptable units in 60 worker-hours.', ['Use output divided by total worker-hours.', 'Calculate 240/60 = 4.', 'Productivity is 4 acceptable units per worker-hour.'], 'Define the output before dividing by the input.', 'Confusing total output with output per unit of labour.', 'Include the labour input and a consistent quality definition.', 'Would output doubling with worker-hours doubling raise this measure?', 'No.',
   'Another team makes 300 units in 60 hours, but 60 are defective. Compare acceptable-output productivity.', 'Acceptable output is 240, so productivity is also 4 acceptable units per worker-hour. The headline total of 300 conceals the quality loss.',
   d(false, 'What does productivity compare?', 'Output with an input used to produce it.', 'A larger production count can be treated as efficiency without checking resources or usable quality.')],
  ['Challenge: evaluate inventory reduction under supply uncertainty', 'Balance holding costs against the consequences of a stockout.',
   'Holding less inventory can reduce storage, spoilage and cash tied up, but increases exposure to supply disruption or unexpected demand. Reliable suppliers, short replenishment times and flexible operations make low-stock approaches more feasible. A low inventory figure is not itself evidence of good management. Evaluate the cost of shortages, customer impact and resilience as well as warehouse savings.',
   'A fictional manufacturer relies on one component with unpredictable delivery.', ['Low stock reduces holding costs.', 'A delayed delivery may stop the entire production line.', 'Compare a buffer stock or supplier diversification with the expected disruption cost.'], 'Inventory can be both a cost and a buffer.', 'Assuming the smallest possible stock is always optimal.', 'Assess uncertainty and the consequences of running out.', 'What is a stockout?', 'A shortage when required inventory is unavailable.',
   'Why might a perishable café ingredient justify a different stock policy from a durable critical component?', 'Spoilage costs, replenishment options and the effect of a shortage differ. The best balance depends on the item and operation rather than one universal inventory rule.',
   d(true, 'What is lead time?', 'The time between ordering or initiating a process and receiving the required result.', 'A cost-saving method can be detached from the reliability conditions that make it effective.')]
 ]],
 ['People, motivation and organisational change', [
  ['Connect training with capability and business outcomes', 'Distinguish attending a course from demonstrating changed performance.',
   'Training aims to develop relevant knowledge or skills, but attendance alone does not establish learning or improved business performance. On-the-job training uses the work setting and can be directly relevant, while off-the-job training may offer focused expertise away from immediate tasks. Both require support, suitable practice and evaluation. Errors, service quality and retention may be relevant outcomes alongside production speed.',
   'A fictional retailer trains staff on a new returns system.', ['Define the required skill and service standard.', 'Provide practice and feedback on realistic cases.', 'Evaluate accurate independent use and customer outcomes rather than only count attendance.'], 'Participation is an input; changed capability is an outcome.', 'Assuming a training session automatically solves a performance problem.', 'Check whether the problem involves skill, tools, workload or unclear processes.', 'What is on-the-job training?', 'Learning delivered through or alongside actual workplace tasks.',
   'Why might repeated training fail when the software interface is confusing?', 'The underlying barrier may be a poor process or tool rather than missing knowledge alone. Evaluating the cause can lead to redesign as well as training.',
   d(false, 'What is feedback?', 'Information used to understand and improve performance.', 'Visible activity can be mistaken for the desired change it is meant to produce.')],
  ['Challenge: evaluate a motivation proposal in its context', 'Compare financial incentives with job design and fairness.',
   'Performance pay may encourage a measured output but can create shortcuts or conflict if the measure ignores quality or teamwork. Recognition, autonomy, progression and fair working conditions can also influence motivation. Avoid claiming every worker responds identically to one reward. A proposal should explain the mechanism, likely unintended effects and evidence that would indicate improvement.',
   'A call centre proposes bonuses based only on calls completed per hour.', ['The measure may encourage faster handling.', 'It may also reward rushed or unresolved calls.', 'Combine relevant quality and resolution evidence with a fair evaluation of workload before judging success.'], 'People respond to what is measured, not only what is intended.', 'Assuming one financial reward improves every aspect of performance.', 'Inspect the incentive’s definition and the behaviours it may encourage.', 'Can a productivity target conflict with service quality?', 'Yes.',
   'What would make a trial of the bonus scheme more informative?', 'Compare call resolution, customer outcomes, staff feedback and workload as well as volume, using a suitable baseline and transparent criteria. A rise in the rewarded metric alone is insufficient.',
   d(true, 'What is an incentive?', 'A reward or consequence intended to influence behaviour.', 'An intended outcome can be assumed without considering how people can satisfy the metric differently.')]
 ]]
]];
