import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 22 : 16, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, explain the mechanism or decision without notes. In a week, apply it to a different fictional case, identifying the information and qualified support needed before acting.' });
export const year9Health: Subject[] = [
['pe', [
 ['Muscles, joints and controlled movement', [
  ['Explain an antagonistic pair at the elbow', 'Relate muscle contraction to joint movement without claiming muscles push bones.',
   'Skeletal muscles generate tension and pull through tendons. At the elbow, the biceps contributes to flexion while the triceps contributes to extension; their roles depend on the movement and load. In a simplified antagonist model, one muscle’s action opposes the other’s. Real movement can involve co-contraction and stabilising muscles, so do not assume the opposing muscle is always completely inactive.',
   'Describe bending an unloaded elbow in the simplified model.', ['Identify flexion as reducing the joint angle.', 'The biceps contributes a pulling force through its tendon.', 'The triceps opposes extension-related action, with actual activation depending on control and load.'], 'Muscles pull; coordinated pairs control opposite actions.', 'Saying the biceps pushes the forearm back down.', 'Identify which muscle can pull in the required direction.', 'Which action increases the elbow angle?', 'Extension.',
   'Why does the simplified pair not describe every muscle involved in a real throw?', 'A throw uses several joints, stabilisation and coordinated muscle groups. The elbow pair explains one relationship but not the whole movement’s timing or force production.',
   d(false, 'What does a tendon connect?', 'Muscle to bone.', 'A visible limb movement can lead to an incorrect push-pull description of muscle force.')],
  ['Challenge: distinguish shortening from controlled lengthening', 'Explain why an active muscle can lengthen while controlling a load.',
   'A concentric contraction involves active shortening; an eccentric contraction involves active lengthening under tension. When a light supported load is lowered slowly by extending the elbow, the elbow flexors can remain active while lengthening to control descent. Movement direction alone therefore does not identify which muscle is working. Practical demonstrations should follow teacher guidance and use appropriate loads, not maximal efforts.',
   'Explain a slow lowering phase after an elbow curl.', ['The elbow angle increases as the load descends.', 'The flexors can resist the load while lengthening.', 'Their eccentric action controls speed; it is not simply complete relaxation.'], 'Active does not always mean shortening.', 'Assuming a lengthening muscle must be switched off.', 'Distinguish muscle activation, length change and external load.', 'What is an isometric contraction?', 'Tension production without a substantial change in muscle length in the model.',
   'Why is dropping a load not equivalent to lowering it under muscular control?', 'A drop removes much of the controlled resisting action and can create risk. Controlled lowering uses tension to regulate motion; this explanation is not an instruction to test unsafe loads.',
   d(true, 'What does flexion at the elbow do?', 'Reduces the angle between upper arm and forearm.', 'The direction of joint movement can be mistaken for proof of which muscle is shortening.')]
 ]],
 ['Energy supply during activity', [
  ['Compare aerobic and anaerobic contributions', 'Explain why activities do not switch between completely isolated energy systems.',
   'Muscles need a continuing usable energy supply. Aerobic processes use oxygen, while anaerobic processes can contribute rapidly without directly using oxygen in those pathways. Their relative contributions change with intensity and duration; they are not separate switches with only one active at a time. An endurance activity still includes changes of pace, and a sprint still has some aerobic contribution.',
   'Compare the start of a fast run with a sustained moderate phase.', ['The rapid initial demand increases reliance on fast anaerobic contributions.', 'Aerobic supply becomes especially important during sustained activity.', 'Both contribute rather than one being absent whenever the other is emphasised.'], 'Relative contributions, not exclusive switches.', 'Calling every movement either entirely aerobic or entirely anaerobic.', 'Discuss intensity, duration and overlapping contributions.', 'Does aerobic energy release involve oxygen?', 'Yes.',
   'Why might a field-game player need both sustained endurance and repeated high-intensity capacity?', 'The player alternates lower-intensity movement with brief demanding actions. The pattern places different demands on energy supply and recovery within the same match.',
   d(false, 'What happens to breathing during many demanding activities?', 'It generally increases to support the body’s changing demands.', 'Convenient sport labels can obscure changing intensity within one activity.')],
  ['Challenge: interpret recovery without using one measure as a diagnosis', 'Explain why elevated breathing can continue after activity stops.',
   'Recovery involves restoring physiological conditions after exercise, including replenishing energy stores and managing heat and other changes. Oxygen consumption and breathing may remain elevated; this should not be explained only as “removing all lactic acid”. Fatigue has multiple causes. A classroom recovery observation is not a medical diagnosis, and unusual pain, faintness or breathing difficulty requires stopping and appropriate adult or medical help.',
   'A fictional learner’s breathing remains raised after a supervised activity.', ['Recognise continued recovery demands after movement stops.', 'Consider intensity, heat, individual response and timing.', 'Avoid diagnosing fitness or illness from one observation without context.'], 'The activity stops before every recovery process finishes.', 'Treating one slow recovery reading as proof of poor effort or disease.', 'Use appropriate context and qualified support rather than a label.', 'Is fatigue explained by one substance in every situation?', 'No.',
   'Why standardise the time after exercise when comparing repeated recovery observations?', 'The measured value changes during recovery. Different sampling times can create an apparent difference unrelated to the activity or adaptation being investigated.',
   d(true, 'What is a controlled measurement condition?', 'A relevant aspect kept comparable so differences are easier to interpret.', 'A single observable measure can be overinterpreted as a complete account of physiology.')]
 ]],
 ['Skill demands and decision-making', [
  ['Place skills on an open-closed continuum', 'Relate environmental predictability to perception and adaptation.',
   'A relatively closed skill occurs in a stable, predictable environment, while an open skill responds to changing conditions such as opponents or a moving ball. These are ends of a continuum, not permanent labels for entire sports. A basketball free throw differs from passing during active play even though both belong to basketball. Classify the particular task and conditions.',
   'Compare a stationary target throw with a pass to a moving teammate under pressure.', ['The stationary target offers more predictable conditions.', 'The live pass requires reading movement and opponents.', 'The second task is relatively more open, even if the basic throwing action is similar.'], 'Classify the situation, not just the sport.', 'Calling all skills in one sport equally open or closed.', 'Identify what can change while the action is selected and performed.', 'What makes an environment more open?', 'Unpredictable changes requiring adaptation.',
   'How could a teacher gradually make a passing drill more open?', 'Introduce a moving receiver, then controlled choices or opposition, while maintaining safe and appropriate difficulty. The change adds perception and decision demands rather than merely increasing distance.',
   d(false, 'What is a skill in PE?', 'A learned ability to perform a task effectively under relevant conditions.', 'A sport’s general reputation can replace analysis of the actual task.')],
  ['Challenge: evaluate speed and accuracy together', 'Choose a performance measure aligned with the task rather than rewarding rushed errors.',
   'A faster attempt may contain more errors, so time alone may misrepresent improvement. Define what successful performance requires before selecting a measure. A safe target task might record completion time alongside correct hits; a game decision might also need appropriateness and timing. Combining scores requires transparent weighting, since an arbitrary penalty can decide the winner without reflecting the real performance goal.',
   'A learner completes ten passes in less time but misses four targets rather than one.', ['Record both time and accuracy changes.', 'Compare them with the task’s intended performance requirement.', 'Do not call the faster trial better without deciding how errors affect successful play.'], 'Faster is useful only in relation to the task’s success criteria.', 'Celebrating speed while discarding the errors it creates.', 'Use a balanced, pre-stated measure and inspect its components.', 'Can a combined score hide different strengths?', 'Yes.',
   'Why should a scoring rule be set before trials are compared?', 'Changing it afterwards can favour a preferred result. A pre-stated rule makes the judgement more transparent, although its relevance still needs justification.',
   d(true, 'What is accuracy?', 'How closely an action achieves its intended target or result.', 'One convenient metric can be substituted for the full quality of performance.')]
 ]]
]],
['pshe', [
 ['Sexual health, consent and reliable support', [
  ['Distinguish pregnancy prevention from infection protection', 'Understand why health choices require accurate information and voluntary agreement.',
   'Contraceptive methods reduce the chance of pregnancy in different ways; not all protect against sexually transmitted infections. Condoms can reduce the risk of many STIs as well as pregnancy when used correctly, but no method removes every risk. Nobody owes sexual activity to another person, and agreement must be freely given and can change. Qualified sexual-health services can explain options, confidentiality and safeguarding without requiring classroom disclosure of personal experiences.',
   'Evaluate “If pregnancy is prevented, every sexual-health risk is removed”.', ['Pregnancy and infection are different possible outcomes.', 'A method aimed at one may not prevent the other.', 'Accurate advice, freely given consent and appropriate protection remain separate considerations.'], 'Preventing pregnancy is not identical to preventing infection.', 'Assuming every contraceptive method offers the same protection.', 'Check the purpose and limits of a method with qualified services.', 'Can someone change their mind after initially agreeing?', 'Yes.',
   'Where should a young person seek reliable advice rather than rely on a group chat?', 'A qualified healthcare professional or sexual-health service can provide appropriate information and explain confidentiality limits. A trusted adult can help access support; urgent danger should be taken to emergency services.',
   d(false, 'What does freely given agreement exclude?', 'Pressure, threats, manipulation or an inability to choose.', 'One form of protection may be mistaken for complete safety across unrelated risks.')],
  ['Challenge: evaluate a misleading health claim without personal disclosure', 'Use evidence, scope and safe referral in a fictional conversation.',
   'A claim that an infection always has obvious symptoms is unsafe: some STIs can be present without noticeable symptoms. Appearance is not a diagnostic test. A responsible response avoids shaming or demanding personal details and directs the person towards qualified testing and advice. Confidentiality should not be promised absolutely by a peer, especially where someone is unsafe or being pressured.',
   'A fictional peer says “We both look healthy, so testing can never matter”.', ['Identify the unsupported assumption that all infections are visible.', 'Explain that symptoms or their absence do not establish infection status.', 'Suggest confidential professional advice while respecting privacy and avoiding accusations.'], 'Appearance cannot establish infection status.', 'Treating a lack of symptoms as proof that no infection exists.', 'Use appropriate testing and professional advice rather than visual judgement.', 'Can an infection be asymptomatic?', 'Yes.',
   'Write a respectful response without asking for private details.', '“Some infections have no obvious symptoms, so appearance cannot settle this. A sexual-health service can explain whether testing is appropriate and how confidentiality works.”',
   d(true, 'What does asymptomatic mean?', 'Having no noticeable symptoms.', 'Visible wellness can be incorrectly treated as a complete health assessment.')]
 ]],
 ['Interest, borrowing and financial claims', [
  ['Compare simple and compound interest in a stated model', 'Track whether interest is calculated on the original amount or a changing balance.',
   'Simple interest is calculated on the original principal; compound interest includes accumulated interest in later calculations. In a fictional savings model, £100 at 10 percent annually becomes £110 after one year and £121 after two with annual compounding. Simple interest would give £120 after two years. Real products include conditions, fees or tax considerations, so a classroom rate is not a recommendation.',
   'Calculate two years of annual compound growth on £200 at 5 percent.', ['After year one, £200 × 1.05 = £210.', 'After year two, £210 × 1.05 = £220.50.', 'The second interest amount is £10.50 because the balance has changed.'], 'Update the balance before calculating the next period.', 'Adding the first year’s interest forever while calling the model compound.', 'Apply the percentage to the stated current balance.', 'What is the principal?', 'The initial amount saved or borrowed in the model.',
   'Compare two-year simple interest on £200 at 5 percent with the compound result.', 'Simple interest adds £10 each year, giving £220. Annual compounding gives £220.50; the extra 50p arises from interest on the first year’s interest.',
   d(false, 'What is five percent of £200?', '£10.', 'A familiar repeated-addition approach can hide a changing percentage base.')],
  ['Challenge: compare borrowing offers using consistent assumptions', 'Include stated fees, time and repayment structure rather than a headline rate alone.',
   'Borrowing costs depend on principal, duration, interest calculation, fees and repayments. A monthly rate cannot be compared directly with an annual rate as if they cover the same period. In a simplified one-year model with no interim repayments, an upfront fee can outweigh a lower stated interest rate. Real credit requires understanding full terms and appropriate adult guidance; this calculation is not advice to borrow.',
   'A fictional £100 one-year loan charges £10 simple interest with no fee; another charges £5 interest plus a £12 fee.', ['The first total repayment is £110.', 'The second total cost is £5 + £12 = £17, giving £117.', 'The lower interest amount does not make the second offer cheaper under these assumptions.'], 'Compare total cost over the same period.', 'Choosing the smallest interest figure while ignoring fees.', 'Include all stated costs and equivalent timing.', 'Are monthly and annual rates directly interchangeable?', 'No.',
   'Why must the example state that there are no interim repayments?', 'Repayments change the outstanding balance and can change interest calculations. Without the assumption, the simplified totals may not represent the contract’s actual cost.',
   d(true, 'What is a fee?', 'A separately charged cost for a service or arrangement.', 'Prominent rate figures may divert attention from charges and timing that change the total.')]
 ]],
 ['Careers, evidence and decisions', [
  ['Turn a skill claim into an evidenced example', 'Describe a specific contribution without exaggerating responsibility.',
   'A claim such as “I am a good organiser” becomes more useful when supported by a situation, task, action and result. Explain what you personally did while acknowledging teamwork and limits. School, caring, volunteering or creative activities can supply evidence; paid experience is not the only source. Do not invent achievements or disclose sensitive information about other people to make an example impressive.',
   'Describe organising materials for a group presentation.', ['State the task and relevant deadline.', 'Identify personal actions such as a shared checklist and reminders.', 'Describe the observed result and acknowledge others’ contributions without claiming sole credit.'], 'Claim, action, evidence, honest limits.', 'Listing an impressive skill with no example of using it.', 'Connect the skill to observable behaviour and a relevant outcome.', 'Must useful skill evidence come from paid employment?', 'No.',
   'Improve “I did everything and made the team successful”.', '“I maintained the checklist and checked missing materials before rehearsal; the group finished on time, with each member completing their section.” This specifies a contribution without erasing the team.',
   d(false, 'What is a transferable skill?', 'An ability useful across more than one task or setting.', 'Confidence and exaggeration can be mistaken for persuasive evidence.')],
  ['Challenge: evaluate career information and uncertainty', 'Distinguish current evidence, individual fit and predictions about future demand.',
   'Career decisions draw on interests, values, requirements, access routes and labour-market information. A salary headline may be a mean, median, senior-level figure or an advertisement rather than a typical starting salary. Future demand is uncertain and varies by location. Compare several credible, dated sources and investigate alternatives; one forecast should not be treated as a guarantee or as a reason to dismiss a person’s aspirations.',
   'An undated post claims everyone entering a field will earn a very high salary.', ['Check who produced it and what population the figure describes.', 'Look for date, region, career stage and whether it is typical or exceptional.', 'Compare entry requirements and several credible sources before using it in a decision.'], 'A headline needs a population, date and context.', 'Treating a top salary as a guaranteed starting outcome.', 'Separate typical distributions from selected success stories.', 'Does a forecast guarantee an individual job outcome?', 'No.',
   'Suggest a next step that reduces uncertainty without requiring an immediate commitment.', 'Compare current official or reputable careers information and discuss routes with a qualified adviser, then try an appropriate taster or informational conversation. Record what is learned and what remains uncertain.',
   d(true, 'What is a median?', 'The middle value when data are ordered.', 'Exceptional stories and undated figures can be mistaken for representative evidence.')]
 ]]
]]
];
