import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 22 : 16, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, draw the graph or force model and repeat the calculation with units. In a week, explain a changed situation before selecting an equation.' });
export const year9Physics: Subject = ['physics', [
 ['Motion represented mathematically', [
  ['Calculate acceleration as a rate of velocity change', 'Use signed velocities and a consistent time interval.',
   'Acceleration is change in velocity divided by elapsed time. Its unit m/s² means a change of metres per second each second, not a speed measured in square metres. Choose a positive direction before using signed values. Negative acceleration is not always slowing down: if velocity is also negative, the speed may be increasing in that direction. State the direction and interpret the signs.',
   'An object moving in the positive direction slows from 12 m/s to 4 m/s in 2 s.', ['Calculate velocity change as 4 − 12 = −8 m/s.', 'Divide by 2 s to obtain −4 m/s².', 'The acceleration points opposite the positive velocity, so speed decreases over this interval.'], 'Final minus initial, divided by time.', 'Using initial minus final and then assigning a sign by guesswork.', 'Choose a direction and retain the signed subtraction.', 'What does a = 3 m/s² mean for constant acceleration?', 'Velocity changes by 3 m/s in the positive direction each second.',
   'Find acceleration when velocity changes from −2 m/s to −8 m/s in 3 s and interpret it.', 'a = (−8 − (−2))/3 = −2 m/s². The object becomes faster in the negative direction, so a negative acceleration here accompanies increasing speed.',
   d(false, 'How does velocity differ from speed?', 'Velocity includes direction.', 'Everyday use of acceleration as speeding up can obscure its vector meaning.')],
  ['Challenge: combine gradient and area on a velocity-time graph', 'Extract acceleration and displacement without confusing their graphical measures.',
   'On a velocity-time graph, gradient represents acceleration and signed area represents displacement. A section below the time axis contributes negative displacement, not negative distance travelled. For piecewise linear motion, rectangles and triangles can calculate areas. Total distance uses the magnitudes of positive and negative contributions when direction changes; the net displacement may be much smaller.',
   'Velocity rises linearly from 0 to 6 m/s in 3 s, then stays at 6 m/s for 2 s.', ['The initial gradient is 6/3 = 2 m/s².', 'The triangular area is one half × 3 × 6 = 9 m.', 'The rectangle adds 2 × 6 = 12 m, giving displacement 21 m.'], 'Slope changes velocity; area accumulates displacement.', 'Multiplying the final speed by the entire time despite acceleration.', 'Divide the graph into intervals and calculate each area.', 'What does a horizontal velocity-time segment show?', 'Constant velocity and zero acceleration.',
   'A body moves at +3 m/s for 2 s then −2 m/s for 3 s. Find displacement and distance.', 'Signed areas are +6 m and −6 m, so displacement is 0 m. Distance is 6 + 6 = 12 m because both travelled lengths count positively.',
   d(true, 'How is the area of a triangle calculated?', 'One half × base × perpendicular height.', 'Gradient, height and area can be used interchangeably without identifying the physical quantity represented.')]
 ]],
 ['Resultant force and inertia', [
  ['Apply Newton’s second law to the resultant', 'Distinguish a single applied force from the net force on an object.',
   'For constant mass in this introductory model, resultant force equals mass multiplied by acceleration: F = ma. The resultant is the vector combination of all external forces, not necessarily the force of an engine or push. If horizontal forces balance, horizontal acceleration is zero; the object can remain at rest or continue at constant velocity. Motion itself does not require an unbalanced forward force.',
   'A 5 kg trolley has a 20 N forward push and 5 N backward resistance.', ['Take forward as positive and calculate resultant 20 − 5 = 15 N.', 'Use a = F/m = 15/5.', 'Acceleration is 3 m/s² forward.'], 'Combine forces before dividing by mass.', 'Putting the 20 N push into F = ma while ignoring resistance.', 'Draw and combine the forces acting on the same object.', 'What acceleration follows from zero resultant force?', 'Zero acceleration.',
   'A 4 kg object travels at constant velocity while pulled with 12 N horizontally. Find the opposing horizontal force in a two-force model.', 'It is 12 N in the opposite direction. Constant velocity means zero acceleration and therefore zero resultant; it does not mean there are no individual forces.',
   d(false, 'What is mass measured in?', 'Kilograms.', 'A visible applied force can dominate attention while opposing forces are omitted.')],
  ['Challenge: distinguish force pairs from balanced forces', 'Identify whether forces act on the same object or on different interacting objects.',
   'Newton’s third-law pair consists of equal and opposite forces of the same interaction acting on different objects. A book pushes down on a table and the table pushes up on the book. Those two forces do not cancel in a force diagram for the book because one acts on the table. The book’s weight and table’s support may balance, but are not a third-law pair: they involve different interactions.',
   'Identify the partner of Earth’s gravitational pull on a book.', ['Earth pulls the book downward through gravity.', 'The paired force is the book’s gravitational pull on Earth.', 'The table’s upward contact force is a separate interaction, even if it balances the book’s weight.'], 'Pair: two objects, one interaction. Balance: one object, several forces.', 'Calling every equal and opposite pair a third-law pair.', 'Name the object receiving each force and the interaction producing it.', 'Do third-law partners act on the same object?', 'No.',
   'Why can two interacting objects accelerate differently despite equal force magnitudes?', 'Acceleration also depends on mass through F = ma, and each object may experience additional forces. Equal interaction forces do not imply equal resultant accelerations.',
   d(true, 'What does a force diagram describe?', 'Forces acting on a specified object or system.', 'Equal magnitudes and opposite arrows look alike whether they represent balance or an interaction pair.')]
 ]],
 ['Wave relationships and signals', [
  ['Relate wave speed, frequency and wavelength', 'Use v = fλ while distinguishing oscillation from propagation.',
   'Frequency counts oscillations per second, wavelength is the distance between equivalent points on adjacent cycles, and wave speed describes propagation. Their relationship is v = fλ. In a fixed medium under unchanged conditions, increasing frequency usually reduces wavelength rather than automatically increasing wave speed. A medium’s particles may oscillate locally while the disturbance transfers energy along it.',
   'A wave has frequency 5 Hz and wavelength 0.8 m.', ['Use v = fλ.', 'Multiply 5 × 0.8 to obtain 4.', 'The wave speed is 4 m/s, not 4 Hz.'], 'Cycles per second × metres per cycle gives metres per second.', 'Assuming faster oscillation always means faster wave propagation.', 'Check whether the medium and its conditions determine a fixed speed.', 'What is the unit of frequency?', 'Hertz, or cycles per second.',
   'At a fixed speed of 12 m/s, find the wavelength for 3 Hz and 6 Hz.', 'Using λ = v/f gives 4 m and 2 m respectively. Doubling frequency halves wavelength when speed stays fixed.',
   d(false, 'What does a periodic oscillation do?', 'Repeats a pattern of motion or change over time.', 'The rate of local vibration can be confused with how fast a disturbance travels.')],
  ['Challenge: distinguish refraction from a source-frequency change', 'Explain what changes when a wave enters a medium with a different speed.',
   'When a wave crosses a stationary boundary into another medium, its frequency normally stays fixed by the source while speed and wavelength can change. If it enters obliquely, the speed change can alter its direction: refraction. A ray entering along the normal can change speed without bending. Do not use every case of slowing to infer a frequency reduction.',
   'Light enters a transparent medium at a lower speed, with the source unchanged.', ['The frequency remains the source frequency.', 'Since λ = v/f, the wavelength decreases with speed.', 'Bending depends on incidence relative to the normal, so normal incidence gives no directional change.'], 'Source fixes frequency; medium affects speed and wavelength.', 'Reducing frequency just because wave speed falls.', 'Use the unchanged source frequency in the wave equation.', 'Can refraction involve a speed change without a direction change?', 'Yes, at normal incidence.',
   'A hypothetical wave’s speed changes from 8 to 6 m/s at a boundary while frequency stays 2 Hz. Compare wavelengths.', 'The wavelengths are 8/2 = 4 m and 6/2 = 3 m. The lower speed corresponds to a shorter wavelength, not fewer oscillations per second at the source.',
   d(true, 'What is the normal at a boundary?', 'An imaginary line perpendicular to the boundary at the point of incidence.', 'Wave speed, frequency and ray direction may be assumed to change together in every boundary crossing.')]
 ]]
]];
