import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 22 : 16, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, redraw the study or model and justify its decisions. In a week, compare an alternative against the same brief, recording evidence rather than preference alone.' });
export const year9Design: Subject[] = [
['art', [
 ['Two-point construction and observation', [
  ['Construct a box using two vanishing points', 'Distinguish two families of receding horizontal edges.',
   'For a box viewed towards a vertical corner, two-point perspective uses two vanishing points on the same eye-level horizon. Each family of receding horizontal edges converges towards its own point; vertical edges remain vertical in this simplified upright view. Placing points too close together can produce exaggerated distortion. The construction is a model for spatial relationships, not a substitute for observing a particular object.',
   'Plan a box seen from one upright corner.', ['Draw the nearest vertical edge and two horizon points.', 'Send each side’s receding edges towards its corresponding point.', 'Close the sides with verticals and check that each edge family uses one consistent point.'], 'Two edge families, one horizon.', 'Giving the two vanishing points unrelated eye levels.', 'Place both on a shared horizon for this construction.', 'What remains vertical in the simplified model?', 'The box’s upright edges.',
   'Why might a very wide-angle-looking box result from nearby vanishing points?', 'The receding edges converge rapidly, exaggerating the apparent perspective. Wider spacing can better suit a less distorted view, depending on the intended viewpoint.',
   d(false, 'What does a horizon line represent in perspective?', 'The viewer’s eye level.', 'Separate sides can be drawn as unrelated one-point constructions without a common viewpoint.')],
  ['Challenge: use negative space to test a constructed drawing', 'Compare observed gaps with a perspective plan to diagnose proportion errors.',
   'Negative space is the shape around or between objects. Observing a triangular gap between a chair’s legs can expose a proportion error that remains hidden when drawing each leg as a familiar symbol. A perspective construction may be internally consistent yet unlike the actual object. Compare angles, gap shapes and relative lengths, deciding whether accuracy or deliberate distortion serves the work’s intention.',
   'A chair looks too wide although its perspective lines converge consistently.', ['Compare the shapes of the gaps between its legs with observation.', 'Check relative widths against a stable reference measurement.', 'Revise the proportion rather than assume converging lines guarantee likeness.'], 'Check what is between as well as what is there.', 'Trusting technical construction more than the observed relationships it should represent.', 'Use negative spaces and comparative measurements as independent checks.', 'Can a geometrically consistent drawing still have wrong proportions?', 'Yes.',
   'How could a thumbnail of only negative spaces help?', 'It removes familiar object labels and encourages comparison of actual shapes. A mismatch can then be traced back to adjacent contours or proportions in the full drawing.',
   d(true, 'What is proportion?', 'The relative size of parts compared with each other or the whole.', 'Recognising an object can encourage drawing its remembered symbol rather than its observed relationships.')]
 ]],
 ['Material layers and surface', [
  ['Plan transparent and opaque paint passages', 'Predict how underlying colour contributes to a layered image.',
   'A transparent layer allows an underlying colour or tonal structure to influence the visible result; an opaque layer covers it more strongly. The effect depends on pigment, medium, thickness and surface, not merely whether paint is labelled water-based. Make small safe material tests with school-approved supplies before applying a layer to a final piece. Record drying and surface conditions so results can be interpreted.',
   'Compare a thin transparent blue layer over white and over yellow.', ['Keep the paint and application comparable.', 'Observe how the ground contributes differently to each result.', 'Record the visual mixture rather than assume the upper layer has exactly the same appearance on every base.'], 'The ground remains active through transparency.', 'Assuming the visible colour is determined only by the last applied paint.', 'Consider the optical contribution of every visible layer.', 'What does opacity describe?', 'How strongly a layer prevents the underlying surface from showing through.',
   'Why test on the intended support rather than unrelated paper only?', 'Absorbency, texture and ground colour affect spreading and appearance. A test on a different surface may not predict the final result reliably.',
   d(false, 'What is a painting ground?', 'The prepared surface or underlying layer on which paint is applied.', 'Layered colour can be mistaken for a simple replacement of one colour by another.')],
  ['Challenge: revise edge quality to communicate material', 'Use selective hard and soft edges instead of outlining every object uniformly.',
   'Edge quality helps suggest focus, light and material relationships. A sharp silhouette may contrast with a soft shadow transition; a reflective object may contain abrupt internal changes unlike a matte surface under diffuse light. These are contextual observations, not absolute material codes. Compare a small edge study against the intended lighting before adding detail to the whole image.',
   'A rounded matte object looks cut out because every boundary is equally dark and sharp.', ['Identify which edges are visible through contrast and which merge with the surroundings.', 'Soften selected transitions consistent with the lighting.', 'Retain sharp accents where observation supports them rather than blur everything.'], 'Edges describe relationships, not only outlines.', 'Applying a uniform dark contour to every boundary.', 'Observe where contrast rises, falls or disappears.', 'Does a soft edge necessarily mean the object is physically fuzzy?', 'No.',
   'Explain why sharpening every reflected highlight could still misrepresent a metal surface.', 'The reflection pattern depends on what surrounds the object and the light source. Material knowledge cannot replace observation of the specific reflection shapes and transitions.',
   d(true, 'What is tonal contrast?', 'A difference in lightness and darkness between areas.', 'A memorised material effect may be applied without considering actual light and surroundings.')]
 ]],
 ['Context, appropriation and developed outcomes', [
  ['Distinguish contextual research from biographical listing', 'Connect an artwork’s circumstances with a visible or material decision.',
   'Artist research becomes useful when it informs a question about the work. A date or birthplace alone does not explain a composition. Materials available, intended audience, commissioning purpose or social circumstances may illuminate a choice, but the link needs evidence. Keep direct observation, sourced contextual information and your interpretation distinct rather than presenting every imagined intention as fact.',
   'Research a public monument’s scale and original site.', ['Observe its size relationship to a viewer and surrounding space.', 'Find reliable information about its commission and placement.', 'Explain how those circumstances may shape its public address, qualifying unsupported intentions.'], 'Context must connect to a decision in the work.', 'Filling a page with biography unrelated to visual analysis.', 'Select context that helps explain a specific observed feature.', 'Is an inferred intention the same as a documented statement?', 'No.',
   'What should accompany a contextual claim in a sketchbook?', 'Record the source and connect the claim to a relevant feature or test. Separate a documented fact from an interpretation that remains open to other explanations.',
   d(false, 'What is visual analysis?', 'Examining how an artwork’s visible features contribute to meaning or effect.', 'Collected facts can look like research depth without explaining anything about the work.')],
  ['Challenge: transform a researched method without copying an outcome', 'Develop a personal response while acknowledging sources and cultural context.',
   'Borrowing a method differs from tracing an artist’s finished composition and calling it original. Identify a principle, such as fragmented viewpoints or restricted colour, then investigate it through your own subject and decisions. Acknowledge the source and consider cultural significance, especially where motifs have sacred or community-specific meanings. Transformation should be visible in choices and reasoning, not just in a changed title.',
   'Develop a response to a researched use of fragmented viewpoints.', ['Identify how fragmentation functions in the source work.', 'Create original observational studies from several positions.', 'Compose and evaluate a new arrangement, recording the influence without reproducing the source composition.'], 'Borrow a question or method; develop your own answer.', 'Treating a minor colour change as sufficient original development.', 'Document new observations, experiments and justified decisions.', 'Should the influence be acknowledged?', 'Yes.',
   'Why consult reliable cultural context before using a ceremonial motif decoratively?', 'The motif may carry meanings or restrictions that a surface-level reference misses. Context supports a more respectful, informed decision and may suggest choosing another method rather than extracting the symbol.',
   d(true, 'What is attribution?', 'Acknowledging the source of an idea, image or method.', 'Visual availability can be mistaken for permission or adequate understanding of cultural meaning.')]
 ]]
]],
['design-tech', [
 ['Structures and load paths', [
  ['Distinguish tension, compression and bending', 'Trace how a simple structure carries an applied load.',
   'Tension pulls a member apart; compression pushes it together. Bending creates different stresses across a section, commonly tension on one side and compression on the other. A load path traces force through members and joints to supports. The weakest joint or an unstable geometry can govern failure even when the material itself seems strong. Investigations must use safe low-load classroom models under supervision.',
   'Explain a simply supported model beam loaded downward at its centre.', ['Trace the load through the beam towards both supports.', 'Recognise bending rather than describe the whole beam as only compressed.', 'Check the joints, section and support arrangement as parts of the load path.'], 'Follow the load, then name the stress.', 'Assuming a strong material guarantees a strong structure regardless of geometry.', 'Evaluate members, joints and support together.', 'What does tension do?', 'Pulls or stretches a member.',
   'Why can a paper structure change capacity when folded without adding material?', 'Folding changes its cross-sectional geometry and resistance to bending or buckling. The material is similar, but the structural arrangement changes how it carries load.',
   d(false, 'What is a force?', 'An interaction that can change motion or deform an object.', 'Material labels can overshadow shape and connection quality.')],
  ['Challenge: explain triangulation and its limitations', 'Compare a hinged quadrilateral with a braced frame.',
   'A four-sided frame with freely turning joints can change shape without changing member lengths. Adding a diagonal forms triangles and constrains that motion. Real stability still depends on joint quality and whether the brace can resist the forces it experiences. A thin cable carries tension well but may go slack under reversed loading, so not every diagonal works equally in both directions.',
   'Compare a square frame with one string diagonal under opposite sideways pushes.', ['The unbraced square can distort through joint rotation.', 'One loading direction may tension the string and restrain motion.', 'The reverse can slacken it, revealing why brace type and load direction matter.'], 'Geometry helps only when members and joints can carry the required force.', 'Assuming any drawn diagonal guarantees equal stability for every load direction.', 'Check tension, compression and connection behaviour.', 'Can a loose string effectively resist compression?', 'No.',
   'Why might two crossed tension braces be used in a model?', 'Different diagonals can become tensioned under opposite lateral directions. This can improve resistance to reversal, but connection strength and pretension still affect performance.',
   d(true, 'What is a joint in a structure?', 'A connection between structural members.', 'An ideal rigid-line diagram can conceal the actual mechanical behaviour of a chosen brace.')]
 ]],
 ['Electronic control and system boundaries', [
  ['Describe input, processing and output with feedback', 'Explain a thermostat as a controlled system rather than a timer.',
   'A simple temperature-control system measures temperature through a sensor, compares it with a target and changes an output such as a heater. Feedback means the output’s effect is measured again to inform later decisions. A timer alone does not know whether the target temperature has been reached. Classroom exploration should use simulation or approved low-voltage models, not modification of domestic heating equipment.',
   'Model a controller that turns heat on below a set threshold.', ['Read the temperature sensor as input.', 'Compare the value with the target using a control rule.', 'Change the heater output and repeat the measurement to close the loop.'], 'Measure, compare, act, measure again.', 'Calling any repeating timer a feedback controller.', 'Check whether the controlled outcome is actually measured.', 'What provides feedback in the thermostat example?', 'The measured temperature after the system acts.',
   'Why might heating for exactly ten seconds produce different final temperatures on different days?', 'Starting temperature, heat losses and other conditions can differ. Without measuring the result, a fixed timing rule cannot compensate for those changes.',
   d(false, 'What does an input sensor do?', 'Measures a condition and provides information to a system.', 'A repeated action can be mistaken for a closed feedback loop.')],
  ['Challenge: reduce rapid switching with a control band', 'Explain hysteresis using different on and off thresholds.',
   'If a heater switches on and off at exactly the same temperature, noise and small fluctuations near that threshold can cause rapid switching. A simple hysteresis band turns it on below one temperature and off above a higher one, retaining its current state between them. The band trades tighter control for reduced switching; it does not correct a broken or badly calibrated sensor.',
   'Use on below 18 °C and off above 20 °C in a simulated controller.', ['Below 18 °C, command on.', 'Above 20 °C, command off.', 'Between the thresholds, retain the previous state rather than issue alternating commands.'], 'Two thresholds plus memory of the current state.', 'Switching off immediately above the on threshold despite a stated band.', 'Use both thresholds and define behaviour within the interval.', 'Does hysteresis eliminate every source of measurement error?', 'No.',
   'At 19 °C, can the output be determined without knowing its previous state?', 'Not from these rules alone. Within the band the output retains its previous state, which is part of the controller’s information.',
   d(true, 'What is a threshold?', 'A value at which a decision rule changes behaviour.', 'A controller may be treated as a stateless comparison when its design requires memory.')]
 ]],
 ['Manufacturing decisions and evaluation', [
  ['Compare one-off and batch production', 'Connect production scale with tooling, consistency and flexibility.',
   'One-off production can support a unique requirement but may involve high labour per item. Batch production makes a defined group of items using repeated processes, often sharing setup costs. The choice depends on demand, variation, quality and resources; higher volume is not automatically cheaper once tooling, waste and unsold stock are considered. Compare total and per-unit costs explicitly.',
   'A fictional batch has a £120 setup cost plus £8 per item for 30 items.', ['Variable cost is 30 × £8 = £240.', 'Total cost is £120 + £240 = £360.', 'Average cost is £360/30 = £12 per item, assuming all 30 are useful.'], 'Share setup cost, but count every produced item’s cost.', 'Dividing only variable cost and ignoring setup.', 'Include fixed and variable costs before averaging.', 'What is a setup cost?', 'A cost incurred to prepare production rather than repeated identically for each item.',
   'Find average cost if the same setup produces only 10 items.', 'Total cost is £120 + £80 = £200, so average cost is £20. Fewer items share the same setup expense.',
   d(false, 'How is an average cost calculated?', 'Total cost divided by the number of items.', 'Visible material costs may be treated as the whole cost of production.')],
  ['Challenge: design an acceptance test that detects failure', 'Translate a specification into a repeatable and relevant test.',
   'A product test needs a defined condition, measurement and acceptance criterion. “It seems strong” is not a repeatable test. A school storage tray might need to hold a stated safe load without a specified level of deflection, but duration, support and measuring position also matter. Passing one test does not certify every safety or durability property; destructive or hazardous tests require appropriate professional supervision.',
   'Plan a safe low-load comparison of two model tray designs.', ['Specify equal support positions and teacher-approved loads.', 'Measure deflection at the same point after the same time.', 'Compare results with a pre-stated criterion and record damage or recovery rather than only the best reading.'], 'Condition, measure, criterion, limitation.', 'Choosing the pass threshold after seeing which prototype looks better.', 'Set the requirement before testing and keep conditions comparable.', 'Why record the test’s duration?', 'Materials and joints may deform differently over time.',
   'Why would a successful short load test not prove years of durability?', 'Repeated use, creep, impacts, moisture and ageing are not fully represented. Further relevant tests and realistic limits are needed before making a long-service claim.',
   d(true, 'What is a prototype?', 'A model or early version used to explore and test a design.', 'A favourable demonstration may be treated as comprehensive evidence of reliability.')]
 ]]
]]
];
