import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 24 : 17, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, trace the worked model without notes. In a week, test a boundary case and explain the invariant, limitation or security assumption rather than only giving an output.' });
export const year10Computing: Subject = ['computer-science', [
 ['Sorting, tracing and algorithm efficiency', [
  ['Trace a bubble-sort pass and its invariant', 'Distinguish one pass from a fully sorted array.',
   'Bubble sort compares adjacent items and swaps those in the wrong order. A left-to-right ascending pass moves a largest remaining value to the right-hand end of the active region. It does not necessarily sort every earlier position. Later passes can exclude the settled suffix. Trace changes immediately after each comparison rather than compare every pair against an unchanged original array.',
   'Trace one ascending pass through [4, 1, 3, 2].', ['Compare 4 and 1, giving [1, 4, 3, 2].', 'Compare 4 and 3, giving [1, 3, 4, 2].', 'Compare 4 and 2, giving [1, 3, 2, 4]; the last 4 is settled but the prefix is not sorted.'], 'One pass settles an extreme, not necessarily the whole list.', 'Reporting a fully sorted result after one pass without tracing swaps.', 'Update the array after each comparison and identify the settled region.', 'Are 3 and 2 ordered in the one-pass result?', 'No.',
   'Trace one pass through [2, 3, 1].', 'Compare 2 and 3 with no swap; then swap 3 and 1, giving [2, 1, 3]. The largest value reaches the end, while another pass is needed for the prefix.',
   d(false, 'What does ascending order mean?', 'From smaller to larger values under the chosen comparison.', 'A sorting algorithm’s goal can be confused with the guarantee made by one iteration.')],
  ['Challenge: justify early termination and its limitations', 'Use a no-swap pass as evidence while distinguishing best and worst cases.',
   'An optimised bubble sort can stop after a complete active pass makes no swaps. Every adjacent pair in that region was then already ordered, and the previously settled suffix remains correct. An already sorted input can therefore finish after one pass. Reverse order still requires many comparisons and swaps, so a best-case improvement does not turn the algorithm into an efficient choice for every large input.',
   'Explain why stopping after one individual no-swap comparison is wrong.', ['That comparison checks only one adjacent pair.', 'A later pair may still be inverted.', 'Only a complete relevant pass with no swaps establishes the required ordering condition.'], 'A local success is not a global stopping condition.', 'Resetting or testing the swapped flag inside the loop as if one pair proves completion.', 'Reset before the pass, update on swaps and test after the pass.', 'Can an optimised bubble sort finish quickly on an already sorted list?', 'Yes.',
   'For [1, 3, 2], why would stopping after comparing 1 and 3 fail?', 'The first pair is ordered, but 3 and 2 are not. The remaining comparison must still occur; a whole-pass condition prevents that premature exit.',
   d(true, 'What is a loop invariant?', 'A property maintained across iterations that helps explain correctness.', 'A correct observation about one location may be extended to an unchecked collection.')]
 ]],
 ['Programming control and data handling', [
  ['Validate a sentinel-controlled input loop', 'Check the termination value before adding it to the data total.',
   'A sentinel marks the end of input and is not normally part of the data. For scores terminated by −1, read a value, test whether it is −1, then validate and process it if not. Counting the sentinel biases both total and mean. An immediate sentinel produces no data, so the program must handle an empty collection explicitly rather than divide by zero.',
   'Trace inputs 8, 6, −1 for a mean-of-scores routine.', ['Accept 8: total 8, count 1.', 'Accept 6: total 14, count 2.', 'Recognise −1 as termination, leaving mean 14/2 = 7.'], 'Read, test sentinel, validate, process.', 'Adding the sentinel before checking whether input should stop.', 'Separate control values from data values.', 'What count follows an immediate sentinel?', 'Zero.',
   'What should happen for inputs −1 only?', 'The program should report that no valid scores were supplied, or return a documented empty result. It must not calculate total/count with count zero or falsely claim the mean is zero.',
   d(false, 'What does a sentinel do?', 'Signals termination or another control condition.', 'A value arriving through the same input channel may be assumed to belong to the data set.')],
  ['Challenge: test mutation and aliasing in a list routine', 'Explain why two names can observe a change to the same mutable object.',
   'In languages with reference-based mutable lists, assigning b = a can make both names refer to the same list rather than copy its contents. Changing b[0] can therefore change what a[0] returns. A shallow copy creates a new outer list but may still share nested mutable items. State the language model; this behaviour is not a universal rule for every type or programming language.',
   'Under a Python-style list model, a = [1, 2]; b = a; b[0] = 9.', ['The assignment b = a copies the reference.', 'The update changes the shared list object.', 'Reading a gives [9, 2], not [1, 2].'], 'Two names can point to one mutable object.', 'Assuming every assignment creates an independent deep copy.', 'Distinguish copying a reference, a container and nested contents.', 'Would rebinding b to a completely new list necessarily mutate a?', 'No.',
   'Why might copying only the outer list fail to isolate a two-dimensional table?', 'Its inner lists may still be shared. Updating an element inside a shared row can affect both structures, so the required copy depth depends on the data and contract.',
   d(true, 'What is mutation?', 'Changing an existing object’s stored contents.', 'Assignment syntax can hide whether values or references are being shared.')]
 ]],
 ['Binary integers and finite representations', [
  ['Interpret a fixed-width two’s-complement number', 'Use the negative most-significant-bit weight and remaining positive weights.',
   'An n-bit two’s-complement integer ranges from −2^(n−1) to 2^(n−1) − 1. For eight bits, the leading weight is −128 and the others are 64, 32, 16, 8, 4, 2 and 1. Thus 11111101 represents −3 under this signed interpretation, but 253 if interpreted as unsigned. The bits alone do not specify which interpretation a system uses.',
   'Interpret 11111010 as an eight-bit two’s-complement integer.', ['The leading bit contributes −128.', 'The set positive weights sum to 64 + 32 + 16 + 8 + 2 = 122.', 'The value is −128 + 122 = −6.'], 'Representation needs both bits and an interpretation.', 'Reading every binary pattern as an unsigned positive value.', 'State width and signed format before converting.', 'What is the eight-bit two’s-complement range?', '−128 to 127.',
   'Write −5 in eight-bit two’s complement.', '11111011. Its weighted value is −128 + 64 + 32 + 16 + 8 + 2 + 1 = −5, providing a direct check.',
   d(false, 'What does a place value assign to a bit?', 'A numerical weight contributing when that bit is set.', 'A familiar unsigned conversion can be used without noticing a signed format.')],
  ['Challenge: detect signed overflow rather than trust the stored result', 'Explain why a fixed-width sum can fall outside its representable range.',
   'Eight-bit signed integers cannot represent 140. Adding 100 and 40 may produce the eight-bit pattern 10001100 if arithmetic wraps, which represents −116 in two’s complement. This does not make the mathematical sum negative: it reveals a range limitation. Languages differ in whether overflow wraps, raises an error or uses another integer model, so specify behaviour before predicting program output.',
   'Add 01100100 and 00101000 as eight-bit patterns.', ['The operands represent 100 and 40.', 'The retained eight-bit sum is 10001100.', 'A positive-plus-positive result with a negative sign indicates signed overflow in this fixed-width model.'], 'Check the mathematical range before accepting the bit pattern.', 'Treating a stored negative result as a correct mathematical sum.', 'Distinguish finite representation from integer arithmetic.', 'Is every binary carry-out identical to signed overflow?', 'No.',
   'Does adding −100 and −40 fit the eight-bit signed range?', 'No: the mathematical result is −140, below −128. Under wrapping arithmetic a misleading positive pattern may result; the overflow must be recognised rather than interpreted as a valid sum.',
   d(true, 'What is the largest eight-bit signed positive value?', '127.', 'A successful bit-level operation can be mistaken for a representable mathematical result.')]
 ]],
 ['Processor operation and performance', [
  ['Trace the fetch-decode-execute cycle', 'Distinguish an instruction address from the instruction stored at that address.',
   'In a simplified stored-program processor, the program counter holds the address of the next instruction. Fetching uses that address to read an instruction from memory into an instruction register; the control unit decodes it and coordinates execution. The program counter normally advances but can change through a branch. Registers have different roles, so an address is not interchangeable with the data stored there.',
   'The program counter contains 120 in a byte-addressed teaching model.', ['Use address 120 to locate the next instruction.', 'Fetch the instruction stored there and decode its operation.', 'Update the next-instruction address according to instruction length and any branch, not by assuming every architecture increments by exactly one.'], 'Address tells where; instruction tells what.', 'Claiming the program counter contains the instruction itself.', 'Name each register’s role and the model’s assumptions.', 'What does decoding determine?', 'The operation and relevant operands or control actions required by an instruction.',
   'Why can a branch break a simple sequential reading of the program?', 'It changes the next-instruction address according to its condition or target. The processor still follows the cycle, but the sequence of fetched addresses changes.',
   d(false, 'What is main memory used for in a stored-program computer?', 'Holding instructions and data needed by running programs.', 'Related register values can be described vaguely as the next instruction even when one is its address.')],
  ['Challenge: evaluate a multi-factor performance comparison', 'Explain why clock frequency alone does not rank every processor or task.',
   'Clock frequency describes cycles per second, not directly useful tasks completed per second. Work per cycle, cache behaviour, memory delays, core count and software parallelism also matter. More cores help only when work can use them effectively, and coordination has costs. Compare a relevant benchmark under stated conditions rather than declare one computer faster for every task from a single specification.',
   'A four-core processor has lower clock frequency than a two-core processor.', ['The specification alone does not determine performance for a particular program.', 'A highly parallel workload may benefit from more cores.', 'A mostly serial or memory-bound workload may depend more on other factors and requires measurement.'], 'Cycles are not completed tasks.', 'Multiplying cores by GHz and treating it as a universal speed score.', 'Match the architecture and benchmark to the workload.', 'Can unused cores make a strictly serial task four times faster automatically?', 'No.',
   'Why might a larger cache improve one workload but not another?', 'A workload reusing data that fits the cache can avoid slower memory accesses. A different access pattern may gain less, so capacity alone does not guarantee equal benefit.',
   d(true, 'What does a cache do?', 'Stores selected data or instructions closer to the processor for faster reuse.', 'Visible specification numbers can overshadow the workload’s actual bottleneck.')]
 ]],
 ['Networks, names and secure transport', [
  ['Separate DNS resolution from HTTP communication', 'Trace a simplified browser request without treating every protocol as a website server.',
   'DNS helps translate a domain name into address information. The browser then communicates with the destination using application protocols such as HTTP, usually protected by TLS for HTTPS. DNS does not normally return the webpage itself. Caches can avoid repeating every lookup, and modern delivery systems add layers, but naming, transport protection and application content remain distinct roles.',
   'A learner enters a website domain into a browser.', ['Resolve the name using available cached or DNS information.', 'Establish the necessary connection and, for HTTPS, TLS protection.', 'Send the HTTP request and receive application content from the addressed service.'], 'Name lookup finds where; HTTP asks for content.', 'Saying DNS downloads and renders the entire page.', 'Assign each protocol its specific role.', 'What does HTTPS add to HTTP in ordinary use?', 'TLS-based protection for the connection, including confidentiality and integrity under its security assumptions.',
   'Why can a site fail to load even if DNS resolution succeeds?', 'The destination may be unreachable, its server may fail, or TLS or application requests may have problems. Successful name resolution proves only one step worked.',
   d(false, 'What is a domain name?', 'A human-readable name used in internet naming systems.', 'A multi-stage request can be collapsed into one service called the internet.')],
  ['Challenge: distinguish encryption from trustworthy content', 'Explain what a secure connection does and does not establish.',
   'HTTPS protects data in transit between the browser and the authenticated endpoint under the certificate system. It does not guarantee that the site’s claims are honest, that its product is safe or that a user intended that domain. A fraudulent site can also use HTTPS. Evaluate the domain, context and requested action separately from transport protection, and never enter credentials to test a suspicious page.',
   'A message links to a convincing login page with HTTPS but an unexpected domain.', ['HTTPS can protect the connection to that domain.', 'It does not prove the domain belongs to the service the message impersonates.', 'Use a known trusted route to the service rather than supply credentials through the message.'], 'Protected transport is not proof of honest purpose.', 'Treating a padlock as an endorsement of every statement or request on the page.', 'Separate endpoint identity, intended destination and content credibility.', 'Can a phishing site use HTTPS?', 'Yes.',
   'Why is checking only the logo inadequate?', 'A logo can be copied easily and does not authenticate the domain or request. Independent navigation and careful origin checking address a different question from visual resemblance.',
   d(true, 'What is phishing?', 'A deceptive attempt to obtain information or actions by impersonating a trusted source.', 'A valid technical security property may be extended into an unsupported judgement about intent.')]
 ]],
 ['Databases and reliable queries', [
  ['Use keys to relate two tables', 'Explain why identifiers are safer relationships than repeated names.',
   'A primary key uniquely identifies a row. A foreign key references a relevant key in another table, allowing relationships without copying every detail. Student names are poor identifiers when names can repeat or change. Separating Students from Enrolments can store one student’s details once while recording several subject relationships. Database constraints help maintain integrity but do not automatically make every recorded fact true.',
   'Link an Enrolments row to a Students row.', ['Give Students a unique student_id.', 'Store that student_id in the Enrolments relationship.', 'Use the key rather than the display name to distinguish two students with the same name.'], 'Names describe; keys identify.', 'Using a person’s name as if it were guaranteed unique.', 'Choose stable identifiers and enforce appropriate constraints.', 'Can one student have several enrolment rows?', 'Yes, when the relationship allows multiple subjects.',
   'Why does changing a student’s display name not need to break their enrolments?', 'The relationships use the stable student_id rather than the changing name. Correct design separates identification from presentation.',
   d(false, 'What is a database row?', 'One record containing values for defined fields.', 'A familiar descriptive field can be mistaken for a unique and stable identity.')],
  ['Challenge: keep user data scoped when joining tables', 'Distinguish a valid relationship query from an authorised query.',
   'A join can correctly combine related rows yet expose another user’s records if ownership is not checked. A progress query must restrict results to the authenticated user using server-verified identity, not a freely editable user_id parameter alone. Parameterised values prevent SQL injection, but do not themselves enforce authorisation. Query safety therefore includes both how values enter SQL and which records the caller is allowed to access.',
   'A route joins progress with lesson titles using a supplied user_id.', ['The join may be structurally correct.', 'A caller could alter the supplied identifier unless ownership is enforced.', 'Derive or validate the user scope against the authenticated session before returning records.'], 'Correct join plus safe syntax still needs authorisation.', 'Calling a parameterised query secure against every data leak.', 'Check identity and ownership in addition to SQL construction.', 'Does preventing SQL injection automatically prevent cross-user access?', 'No.',
   'What test would reveal a missing ownership check?', 'Create two test users with different progress and request the first user’s records while authenticated as the second. The route must refuse or return only the authenticated user’s permitted data; it must not expose the other user’s history.',
   d(true, 'What does authorisation decide?', 'Whether an authenticated or otherwise identified caller may perform a particular action or access particular data.', 'Different security properties can be conflated into a single label of safe query.')]
 ]]
]];
