import type { Subject, ActivityDetail } from '../authoredActivities';
const free: ActivityDetail = { isPremium: false, difficulty: 'Core', estimatedMinutes: 15, revision: 'Trace a fresh example by hand tomorrow. In a week, explain one boundary case and one way the solution can fail.' };
const extension: ActivityDetail = { ...free, isPremium: true, difficulty: 'Higher', estimatedMinutes: 20 };
export const year8Computing: Subject = ['computer-science', [
 ['Lists and algorithmic state', [
  ['Trace an accumulator loop', 'Distinguish a running total from the current list item.',
   'An accumulator stores a result built over repeated steps. Initialise total to zero, then for each number assign total = total + number. The right side uses the previous total before the new value is stored. A list item and the accumulating variable serve different roles. Resetting total inside the loop would discard earlier contributions.',
   'Sum the list [4, 7, 2].', ['Initialise total = 0.', 'After the first two items the total is 4, then 11.', 'After adding 2, total = 13.'], 'Initialise once; update each cycle.', 'Setting total to zero on every iteration.', 'Place initialisation before the loop.', 'What is the initial value for a sum accumulator?', 'Zero.',
   'Trace total = 0 followed by total = total + item for [5, −2, 8].', 'The successive totals are 5, 3 and 11. The negative item reduces the running total rather than being ignored.',
   { ...free, memoryExplanation: 'A running total must remember earlier iterations.', misconceptionCause: 'Confusing setup with repeated work erases the stored state.' }],
  ['Challenge: compute an average with an empty-list guard', 'Combine iteration, counting and a precondition for division.',
   'An average requires both total and count. A non-empty numeric list can be summed, then divided by its length. An empty list has count zero, so an ordinary mean is undefined and the program should handle that case deliberately. Do not invent zero as the mean unless the application explicitly chooses and labels that convention.',
   'Design an average function for a possibly empty list.', ['If the length is zero, return a clear no-data result.', 'Otherwise accumulate the total.', 'Divide total by count and return the value.'], 'No observations is not an observed zero.', 'Allowing division by zero or silently presenting zero as a measured average.', 'Handle the empty case before division.', 'What distinguishes [0] from []?', '[0] contains one observed value with mean zero; [] contains no observations.',
   'Find the mean of [3, 6, 12] and state an appropriate result for an empty list.', 'The mean is 21/3 = 7. For [], return a documented no-data value or message rather than perform division by zero.',
   { ...extension, memoryExplanation: 'A meaningful statistic needs evidence as well as a formula.', misconceptionCause: 'Default numeric values can be mistaken for real measurements.' }]
 ]],
 ['Searching and testing', [
  ['Explain binary search on a sorted list', 'Use ordered information to eliminate half the remaining search interval.',
   'Binary search compares the target with a middle item. In an ascending sorted list, a smaller target must lie to its left and a larger one to its right. Repeatedly narrow the remaining interval until a match is found or the interval is empty. The sorting precondition is essential; applying the method to an arbitrary unsorted list can discard the target.',
   'Search [2, 5, 8, 11, 14, 17, 20] for 17.', ['Compare with middle item 11; the target is larger.', 'Keep the right interval [14, 17, 20].', 'Its middle is 17, so the search succeeds.'], 'Order licenses elimination.', 'Using binary search on unsorted data because it sounds faster.', 'Verify or establish sorted order first.', 'What makes it safe to discard one side?', 'The list’s order and the comparison with its middle value.',
   'Why can binary search use fewer comparisons than linear search on a large sorted list?', 'Each comparison can discard roughly half the remaining candidates instead of removing only one, though sorting and data-access costs also matter.',
   { ...free, memoryExplanation: 'The efficiency comes from information supplied by sorted order.', misconceptionCause: 'Remembering the halving action without its precondition produces an invalid algorithm.' }],
  ['Challenge: test off-by-one errors', 'Choose cases that expose mistakes in index bounds and termination.',
   'An off-by-one error includes one too many or one too few positions. In a zero-indexed list of length n, valid indices run from zero to n − 1. Test first and last elements, a one-element list and an absent target. An empty list also tests whether the algorithm accesses a position before checking that one exists.',
   'A loop tests indices while i < n − 1.', ['Valid final index is n − 1.', 'The strict condition stops before testing that index.', 'Use a correct bound such as i < n, with appropriate initialisation and increment.'], 'Last index is length minus one; exclusive bound is length.', 'Treating length as a valid index in a zero-indexed list.', 'Write a concrete small list and label its positions.', 'What indices are valid for a zero-indexed list of length three?', '0, 1 and 2.',
   'Give two tests that could expose a search skipping its final element.', 'Search for the last item in a multi-item list and for the sole item in a one-item list. Both require testing a boundary the faulty loop may omit.',
   { ...extension, memoryExplanation: 'Small boundary cases make abstract inequalities visible.', misconceptionCause: 'Length counts items, while an index labels a position starting at zero.' }]
 ]],
 ['Networks and security', [
  ['Trace a web request through network roles', 'Distinguish a browser, server and address lookup.',
   'A browser acts as a client requesting resources from a server. A domain-name lookup helps translate a readable name into addressing information, after which network communication can reach the service. The internet is the network infrastructure; the Web is a service using it. Cached data and different protocols can change the detailed sequence, so this is a simplified model.',
   'Explain opening a school website by its domain name.', ['The client needs suitable addressing information for that name.', 'It sends a request to the web service over the network.', 'The server returns resources that the browser interprets for display.'], 'Name lookup, request, response, render.', 'Saying the browser is the remote server storing every website.', 'Separate the user’s client software from the service responding remotely.', 'Is the Web identical to the whole internet?', 'No; it is one service using internet infrastructure.',
   'Why could a website fail to load even while another internet service works?', 'The failure may concern that server, its name lookup or the particular service rather than the entire network connection.',
   { ...free, memoryExplanation: 'Different roles create different possible failure points.', misconceptionCause: 'A single browser window hides several cooperating systems.' }],
  ['Challenge: distinguish authentication from authorisation', 'Explain why identity verification does not grant every permission.',
   'Authentication establishes who a requester is; authorisation decides what that identity may do. A signed-in learner should not automatically edit another user’s records. A hidden button is not a security boundary because requests can be sent independently of the interface. A server must check identity, resource ownership and relevant permission for each protected operation.',
   'A learner changes a URL to request another learner’s progress.', ['The session may validly identify the requester.', 'That does not establish ownership of the requested record.', 'The server must reject unauthorised access rather than trusting the requested identifier.'], 'Who are you? What may you do?', 'Treating successful login as permission for every resource.', 'Check access to the specific action and object on the server.', 'Does hiding an admin link enforce server permissions?', 'No.',
   'Why must a premium-content API check entitlement even if the page already hid its button?', 'The API can be requested directly or from a modified client. Only a server-side permission check reliably protects the content.',
   { ...extension, memoryExplanation: 'Separating identity and permission prevents overbroad trust.', misconceptionCause: 'A trusted login can be wrongly extended to untrusted request parameters.' }]
 ]]
]];
