import type { Subject, ActivityDetail } from '../authoredActivities';
const core: ActivityDetail = { isPremium: false, difficulty: 'Core', estimatedMinutes: 16, revision: 'Tomorrow, explain the distinction without notes. Next week, apply it to a different example while identifying whose belief or argument is being represented.' };
const challenge: ActivityDetail = { ...core, isPremium: true, difficulty: 'Higher', estimatedMinutes: 20 };
export const year8Religion: Subject = ['religious-studies', [
 ['Religious texts and interpretation', [
  ['Distinguish genre from a text’s religious importance', 'Explain why readers consider genre and context when interpreting scripture.',
   'Religious collections contain different literary forms, including poetry, narrative, legal teaching and letters. Identifying a text as poetic or metaphorical does not by itself deny its religious importance. Christians differ over how particular biblical passages should be interpreted, including how creation texts relate to scientific explanations. Explain a specific interpretive approach rather than assigning one identical reading to every believer or assuming that literal means serious and non-literal means unimportant.',
   'Consider a reader who treats a creation passage as theological teaching rather than a scientific timetable.', ['Identify the question the reader thinks the passage answers: meaning and relationship to God.', 'Distinguish that from a scientific account of physical mechanisms.', 'Explain that this approach can regard the text as authoritative without using it as a chronology of natural processes.'], 'Genre shapes how meaning is sought.', 'Assuming a non-literal interpretation rejects all authority or truth in the text.', 'Ask what kind of claim the reader thinks the passage makes.', 'Can a metaphor communicate something a reader regards as true?', 'Yes.',
   'Why is “all Christians reject evolution” an inaccurate generalisation?', 'Christian interpretations and views about evolution vary. Some see scientific accounts as compatible with theological creation beliefs, while others reject aspects of those accounts; a claim must identify the approach being described.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What is a metaphor?', answer: 'A way of describing something in terms of something else rather than making only a literal comparison.' }], memoryExplanation: 'A question about literary form is different from a question about religious authority.', misconceptionCause: 'Everyday uses of literal and true can falsely make them seem interchangeable.' }],
  ['Challenge: compare sources of guidance in Islam', 'Distinguish the Qur’an, hadith and interpretation without presenting Muslims as uniform.',
   'Muslims regard the Qur’an as revelation from God to Muhammad. Hadith reports concern the Prophet’s words, actions and approvals and are important sources for understanding the Sunnah. Assessing reports and applying guidance involves traditions of scholarship; different Muslim communities do not accept every report or interpretation identically. Distinguish a source, a judgement about its reliability and an interpretation of its application to a situation.',
   'Evaluate “One quoted report proves every Muslim must make the same decision”.', ['Identify whether the quotation is from the Qur’an or a hadith report.', 'For a report, consider its acceptance and relevant scholarly assessment.', 'Consider context and interpretation before making a universal claim about contemporary decisions.'], 'Source, reliability, interpretation, application.', 'Treating every online quotation as equally authoritative for every Muslim.', 'Identify provenance and the community or scholarly approach being described.', 'Are the Qur’an and hadith the same collection?', 'No.',
   'Why can two Muslims share respect for the same source but differ about applying it?', 'They may understand context, relevant principles or the circumstances differently, or follow different scholarly traditions. Shared authority does not automatically remove all interpretive disagreement.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'Who is Muhammad in Islamic belief?', answer: 'The final prophet, to whom Muslims believe the Qur’an was revealed.' }], memoryExplanation: 'Several reasoning steps stand between a quotation and a practical judgement.', misconceptionCause: 'Quotations without provenance can create a misleading picture of uniform interpretation.' }]
 ]],
 ['Suffering and philosophical argument', [
  ['Set out the problem of evil accurately', 'Explain the tension rather than treating a philosophical question as a personal accusation.',
   'The problem of evil asks how suffering relates to belief in a God understood as all-powerful, all-knowing and perfectly good. Moral evil refers to harm associated with agents’ choices; natural suffering includes events such as disease or earthquakes. Philosophers distinguish claims of logical incompatibility from arguments that suffering makes such a God’s existence less likely. Represent the argument respectfully: suffering is also a lived experience, not merely an abstract classroom puzzle.',
   'Explain the tension raised by preventable harm.', ['A perfectly good God is understood to oppose evil.', 'An all-powerful, all-knowing God is understood to have knowledge and power relevant to preventing harm.', 'The existence of suffering prompts questions about how these beliefs fit together and whether further reasons are possible.'], 'State the beliefs, then explain the tension.', 'Claiming that asking the question means someone is hostile to religious people.', 'Separate examination of an argument from judgement of the people considering it.', 'How does natural suffering differ from moral evil in this distinction?', 'It is not classified primarily as harm resulting from a moral agent’s choice.',
   'Is “suffering makes belief less likely” the same claim as “belief is logically impossible”? Explain.', 'No. A probability-based argument weighs evidence, whereas a logical incompatibility claim says the propositions cannot all be true. The latter requires a stronger kind of demonstration.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What is an argument in philosophy?', answer: 'Reasons offered to support a conclusion, not necessarily a quarrel.' }], memoryExplanation: 'Clarifying the strength of a claim helps identify what a response must establish.', misconceptionCause: 'Different philosophical versions of the question are often collapsed into one slogan.' }],
  ['Challenge: evaluate a free-will response and its limits', 'Explain what a response addresses and what remains unresolved.',
   'A free-will response argues that meaningful moral freedom allows people to choose harmful actions and that a world with such freedom may have value. This directly addresses some moral evil more readily than natural suffering. Critics also ask why particularly severe harms are not prevented without removing every choice. Evaluation should explain the response’s reasoning and a specific limitation rather than announce that it solves everything or answers nothing.',
   'Assess the claim that free will fully explains earthquakes.', ['Human choice can explain some deliberate harms.', 'The tectonic event itself is not ordinarily explained as a human moral decision.', 'Human choices may affect vulnerability and response, but that does not fully explain the existence of the natural hazard.'], 'A response has a scope; test its boundary.', 'Using a response to one category of suffering as a complete account of every category.', 'Distinguish the physical event from choices that affect its consequences.', 'Can a response have value without settling every aspect of a debate?', 'Yes.',
   'Write a balanced evaluation of the free-will response in two sentences.', '“The response explains why eliminating all harmful choices might threaten morally significant freedom. However, it needs further argument to address natural suffering and why the gravest consequences of choices are not sometimes prevented.”',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What is moral evil in this discussion?', answer: 'Harm associated with the choices of moral agents.' }], memoryExplanation: 'Testing the boundary is more precise than treating a response as wholly successful or wholly useless.', misconceptionCause: 'Debates can reward absolute verdicts instead of examining exactly what has been explained.' }]
 ]],
 ['Ethical reasoning: consequences, duties and dignity', [
  ['Compare consequences with duties', 'Explain how different ethical approaches can reach or justify decisions differently.',
   'Consequentialist approaches assess actions by their outcomes; utilitarian approaches seek overall welfare or happiness, though versions differ. Duty-based approaches emphasise obligations or constraints, such as a requirement not to deceive. These are families of reasoning, not simple labels for selfishness and kindness. The same decision can be supported by different reasons, and an apparent benefit may conflict with an obligation or a person’s rights.',
   'Consider whether to keep a promise to help someone study.', ['An outcome-focused reason is that reliable help improves learning and trust.', 'A duty-focused reason is that a freely made promise creates an obligation.', 'Both can support keeping the promise, but their justification and response to exceptions may differ.'], 'Ask not only what is chosen, but why.', 'Assuming different ethical approaches must always recommend different actions.', 'Compare the reasons as well as the final decision.', 'Does consequentialism assess only the decision-maker’s personal benefit?', 'Not necessarily; utilitarianism concerns overall welfare.',
   'Give one question each approach might ask when an emergency conflicts with a promise.', 'An outcome-focused approach may ask which action prevents greater harm. A duty-focused approach may ask which obligations apply and whether a duty to protect life overrides the promise in these circumstances.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What is a reason for an action?', answer: 'A consideration offered to explain or justify choosing it.' }], memoryExplanation: 'Identical behaviour can conceal different principles that become visible in a difficult case.', misconceptionCause: 'Ethical theories are sometimes taught as fixed answer lists rather than ways of reasoning.' }],
  ['Challenge: test fairness in an aggregate-benefit argument', 'Consider rights, distribution and uncertainty alongside claimed overall gains.',
   'A proposal can produce a large total benefit while imposing serious harm on a small group. Ethical evaluation asks whose interests count, how effects are estimated and whether some treatments are unacceptable even for a net gain. Religious and non-religious thinkers offer different accounts of dignity and rights; do not assume only one worldview can care about them. A fair argument considers alternatives that reduce harm rather than treating a dilemma’s first two options as exhaustive.',
   'A hypothetical school policy saves most pupils time but excludes a few disabled pupils from an activity.', ['Identify the benefit and the unequal burden.', 'Consider equality, access and the affected pupils’ rights rather than only total minutes saved.', 'Seek an accessible alternative and consult those affected before assuming exclusion is necessary.'], 'Count effects without making people merely numbers.', 'Assuming majority convenience automatically justifies serious exclusion.', 'Consider the kind, distribution and avoidability of harm alongside aggregate benefits.', 'Why should affected people be consulted?', 'They can explain impacts and needs that planners may otherwise overlook.',
   'Write a reasoned objection that does not deny the value of saving time.', '“Saving time is worthwhile, but convenience alone does not justify denying a group access. The school should investigate accessible scheduling or support so that efficiency is pursued without avoidable exclusion.”',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What is an aggregate?', answer: 'A combined total across several people or items.' }], memoryExplanation: 'A total hides distribution, while rights and dignity ask how particular people are treated.', misconceptionCause: 'Majority benefit can be mistaken for a complete account of justice.' }]
 ]]
]];
