import type { Subject, ActivityDetail } from '../authoredActivities';
const free: ActivityDetail = { isPremium: false, difficulty: 'Core', estimatedMinutes: 15, revision: 'Tomorrow, explain the particle or reaction model without notes. In a week, use it on a different set of reactants.' };
const extension: ActivityDetail = { ...free, isPremium: true, difficulty: 'Higher', estimatedMinutes: 20 };
export const year8Chemistry: Subject = ['chemistry', [
 ['Atoms and chemical reactions', [
  ['Explain conservation of atoms', 'Represent a chemical reaction as rearrangement rather than creation of matter.',
   'In an ordinary chemical reaction, atoms are rearranged into new combinations. They are not created or destroyed. A closed-system mass measurement can therefore remain constant even when appearance changes. If a gas escapes from an open container, the measured container contents may lose mass; this does not mean matter was destroyed.',
   'An acid-carbonate reaction loses measured mass in an open flask.', ['The reaction produces a gas.', 'Gas can leave the measured flask.', 'Including the escaped material would account for the apparent loss.'], 'Count the whole system.', 'Using an open-container mass loss as proof atoms vanished.', 'Define the measurement boundary and track matter crossing it.', 'What happens to atoms in a chemical reaction?', 'They rearrange into new substances.',
   'Why can burning a metal increase its measured mass?', 'Oxygen from the surroundings combines with the metal. The product includes atoms not initially included in the metal-only measurement.',
   { ...free, memoryExplanation: 'A boundary tells you which incoming or outgoing matter the balance misses.', misconceptionCause: 'The measured object can be confused with the complete reacting system.' }],
  ['Challenge: balance a simple symbol equation', 'Use coefficients to preserve the number of each atom type.',
   'An equation must show equal atom counts of each element on both sides. Change coefficients in front of formulas, not the small numbers defining a compound. For hydrogen reacting with oxygen, 2H₂ + O₂ → 2H₂O balances four hydrogen and two oxygen atoms. H₂O₂ would be a different substance, not a convenient correction to water.',
   'Balance Mg + O₂ → MgO.', ['There are two oxygen atoms on the left but one in MgO.', 'Write 2MgO, requiring two magnesium atoms.', 'Use 2Mg + O₂ → 2MgO and recount both elements.'], 'Change the number of packages, not their contents.', 'Changing MgO to MgO₂ to balance oxygen.', 'A subscript defines the substance; use whole-formula coefficients instead.', 'What does the coefficient 2 in 2H₂O count?', 'Two water molecules or two corresponding amounts of water formula units.',
   'Balance N₂ + H₂ → NH₃ and show the atom check.', 'N₂ + 3H₂ → 2NH₃. Both sides contain two nitrogen atoms and six hydrogen atoms.',
   { ...extension, memoryExplanation: 'Formulas are fixed packages of atoms; coefficients choose how many packages participate.', misconceptionCause: 'Both coefficients and subscripts change a count, but only one preserves chemical identity.' }]
 ]],
 ['Acids, alkalis and salts', [
  ['Interpret pH without confusing it with amount', 'Use pH as a scale of acidity or alkalinity in a solution.',
   'At ordinary classroom conditions, pH below seven is acidic, seven neutral and above seven alkaline. Universal indicator estimates a range through colour rather than supplying an exact universal digit. Acidity is not the same as total volume: a large dilute sample need not have a lower pH than a small concentrated one. Handle all laboratory solutions according to supervision and labels.',
   'An indicator comparison suggests pH 3 for A and pH 6 for B.', ['Both values are below seven.', 'A is more acidic on this scale.', 'The readings alone do not tell the total amount of acid in either container.'], 'pH describes solution conditions, not container size.', 'Calling pH 6 alkaline because it is close to seven.', 'Use the boundary correctly: below seven remains acidic.', 'What does pH 7 indicate in this introductory model?', 'A neutral solution under the stated conditions.',
   'Can a pH reading alone establish which sample has greater volume?', 'No. pH does not measure volume, and samples of different volumes can have the same pH.',
   { ...free, memoryExplanation: 'Keeping quantity and intensity separate prevents false comparisons.', misconceptionCause: 'The everyday word stronger can blur acidity, concentration and total quantity.' }],
  ['Challenge: predict products and qualify neutralisation', 'Use reaction patterns and distinguish neutralisation from automatically reaching pH seven.',
   'An acid reacting with an alkali forms salt and water. Hydrochloric acid with sodium hydroxide forms sodium chloride and water. The word neutralisation describes the reaction, but excess acid or alkali can remain; mixing any arbitrary volumes does not guarantee a neutral final solution. Salt names reflect the acid and the positive part supplied by the other reactant.',
   'Predict the products of hydrochloric acid and potassium hydroxide.', ['Hydrochloric acid supplies the chloride name.', 'Potassium hydroxide supplies potassium.', 'The products are potassium chloride and water; final pH depends on relative amounts.'], 'Reaction type does not guarantee the final balance.', 'Assuming equal volumes always contain matching reacting amounts.', 'Concentrations and the reaction ratio matter as well as volume.', 'Which salt family is associated with hydrochloric acid?', 'Chlorides.',
   'Why can a mixture remain acidic after some neutralisation has occurred?', 'The alkali may be used up while acid remains in excess. A reaction occurred, but not all acid was neutralised.',
   { ...extension, memoryExplanation: 'Balance refers to reacting amounts, not merely equal-looking portions.', misconceptionCause: 'The name neutralisation sounds like a promise that any mixture ends neutral.' }]
 ]],
 ['Reactivity and displacement', [
  ['Infer relative reactivity from displacement', 'Use a reaction to compare two metals in a stated context.',
   'A more reactive metal can displace a less reactive metal from a suitable compound in solution. Iron placed in copper sulfate can form iron sulfate and copper. A visible coating may therefore be a new metal deposit rather than dirt. Observations and chemical tests must be interpreted with the actual reactants, not by colour alone.',
   'Iron reacts in copper sulfate solution and copper appears.', ['Copper was initially part of the dissolved compound.', 'Iron takes its place in the compound.', 'Under these conditions the result supports iron being more reactive than copper.'], 'The more reactive metal takes the place.', 'Concluding copper is more reactive because it appears as the visible solid.', 'Track which metal leaves its original state to replace the other.', 'What happens in a displacement reaction?', 'One element replaces another in a compound.',
   'If metal A displaces B from its compound, what relative order is supported?', 'A is more reactive than B for the reaction under the tested conditions. It does not rank unrelated metals without further evidence.',
   { ...free, memoryExplanation: 'Following the replacement is more reliable than focusing on the most visible product.', misconceptionCause: 'A dramatic deposit can be mistaken for the metal driving the reaction.' }],
  ['Challenge: construct a reactivity order from incomplete data', 'Combine comparisons and identify what cannot yet be concluded.',
   'Displacement evidence gives pairwise relationships. If A displaces B and B displaces C, a consistent order is A above B above C. A failed reaction needs care: a protective surface or unsuitable conditions may interfere. State assumptions and do not assign an untested metal a precise position without relevant comparisons.',
   'A displaces B; C displaces A. Rank A, B and C.', ['A is above B.', 'C is above A.', 'The combined order is C, A, B from more to less reactive.'], 'Build a chain from justified comparisons.', 'Placing an untested metal using appearance or density.', 'Reactivity requires reaction evidence, not an unrelated physical property.', 'Do two comparisons always rank every metal in a four-metal set?', 'No.',
   'A is above B and C is above D. Can you decide whether A is above C? Suggest a useful test.', 'No; the two pairs are unconnected. A suitable displacement comparison between A and a compound of C could connect them, subject to controlled conditions and safety.',
   { ...extension, memoryExplanation: 'A partial order contains gaps; recognising them guides the next investigation.', misconceptionCause: 'A completed-looking list can conceal missing comparisons.' }]
 ]]
]];
