import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 22 : 16, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, reconstruct the model and explain its grammatical choices. In a week, change the subject and time frame, then translate both ways and check that the meaning remains consistent.' });
export const year9Languages: Subject[] = [
['french', [
 ['Background and completed events', [
  ['Form the imperfect from a present-tense stem', 'Use the nous stem with imperfect endings for taught verbs.',
   'The imperfect often describes past habits or ongoing background. For many verbs, remove -ons from the present nous form and add -ais, -ais, -ait, -ions, -iez or -aient. Nous finissons gives je finissais. Être is exceptional with the stem ét-, as in j’étais. A time word alone cannot determine whether the imperfect or passé composé best conveys the intended perspective.',
   'Form “we used to finish” from finir.', ['Start with nous finissons.', 'Remove -ons to obtain finiss-.', 'Add -ions: nous finissions.'], 'Present nous stem, then imperfect person ending.', 'Using the infinitive stem for every imperfect verb.', 'Derive the taught stem from the present nous form and learn exceptions.', 'What is the imperfect stem of être?', 'Ét-.',
   'Write “I used to play” and “I was” using jouer and être.', 'Je jouais; j’étais. Jouais uses the regular nous jouons stem, while étais uses the exceptional être stem.',
   d(false, 'What is the nous present form of jouer?', 'Nous jouons.', 'A stem rule from one tense can be carried into another without checking its formation.')],
  ['Challenge: combine an ongoing background with an interruption', 'Choose imperfect and passé composé according to the role of each event.',
   'Je lisais quand le téléphone a sonné presents reading as ongoing background and the ring as a completed interrupting event. The choice is about how events are viewed, not simply which lasted longer. A long event can be presented as completed, and a short repeated action as habitual. Translate the relationship between actions rather than applying a short-versus-long slogan.',
   'Explain Je regardais un film quand mon ami est arrivé.', ['Regardais sets an ongoing activity.', 'Est arrivé introduces the arrival as a completed event.', 'Quand connects the background with what happened during it.'], 'Background unfolds; the narrated event advances.', 'Putting every long action in the imperfect regardless of perspective.', 'Identify ongoing background, habit or a bounded event in the intended meaning.', 'Which form supplies the ongoing background in je lisais quand il a appelé?', 'Je lisais.',
   'Translate “I was playing when the telephone rang”.', 'Je jouais quand le téléphone a sonné. The imperfect frames the playing as ongoing; the passé composé presents the ringing as the event occurring against it.',
   d(true, 'What two parts form a regular passé composé with avoir?', 'A conjugated avoir auxiliary and a past participle.', 'Duration can be confused with the viewpoint that tense selection expresses.')]
 ]],
 ['Object pronouns and sentence cohesion', [
  ['Replace a known direct object with le, la or les', 'Place a taught object pronoun before the conjugated verb.',
   'In Je regarde le film, le film is a direct object. Once the referent is clear, Je le regarde avoids repetition. La replaces a feminine singular object and les a plural object; le and la become l’ before a vowel sound. The pronoun normally precedes the finite verb in these simple affirmative statements, unlike the English object after watch.',
   'Replace les livres in Je cherche les livres.', ['Identify a plural direct object.', 'Select les.', 'Place it before cherche: Je les cherche.'], 'Identify the object, choose its form, move it before the verb.', 'Writing je cherche les with the pronoun after the verb.', 'Use the taught French pronoun position rather than English order.', 'What replaces a feminine singular direct object before a consonant?', 'La.',
   'Replace la chanson in J’aime la chanson.', 'Je l’aime. La becomes l’ before aime; je is no longer directly before a vowel because the pronoun intervenes.',
   d(false, 'What is a direct object?', 'The person or thing directly receiving the action without a preposition in the construction.', 'An article and object pronoun may look alike while occupying different grammatical roles.')],
  ['Challenge: place an object pronoun with a following infinitive', 'Connect the pronoun to the verb whose object it replaces.',
   'In Je vais regarder le film, the film is the object of regarder. Replacing it gives Je vais le regarder: the pronoun comes before the infinitive, not before vais. Negating the plan gives Je ne vais pas le regarder. Keep the finite-verb negative pattern separate from the infinitive’s object position; multiple grammatical relationships operate in the same sentence.',
   'Replace les billets in Nous allons acheter les billets.', ['The object belongs to acheter.', 'Choose plural les.', 'Write Nous allons les acheter.'], 'Put the pronoun with its action, not automatically with the first verb.', 'Writing nous les allons acheter.', 'Identify which verb takes the object before locating the pronoun.', 'Which verb takes the object in je veux le lire?', 'Lire.',
   'Translate “I am not going to watch it”, referring to a known film.', 'Je ne vais pas le regarder. Ne ... pas surrounds vais, while le stands before regarder as its direct-object pronoun.',
   d(true, 'What does je vais regarder mean?', 'I am going to watch.', 'A correct one-verb pronoun rule can be overextended to a construction with a separate infinitive.')]
 ]],
 ['Future reference and hypothetical wishes', [
  ['Build the simple future of regular verbs', 'Use a future stem plus endings instead of an extra aller auxiliary.',
   'For regular -er and -ir verbs, the simple future uses the infinitive plus -ai, -as, -a, -ons, -ez or -ont. Je visiterai means I will visit. Regular -re verbs lose the final e before those endings: je prendrai is formed from prendre’s future stem prendr-. Some common verbs have irregular stems, such as ser- for être and aur- for avoir.',
   'Write “we will finish” using finir.', ['Use the infinitive stem finir-.', 'Choose -ons for nous.', 'Write nous finirons.'], 'Future stem plus person ending.', 'Adding present-tense endings or an unnecessary extra conjugated verb.', 'Choose the future construction consistently.', 'What is the future stem of être?', 'Ser-.',
   'Translate “I will visit the museum” and “we will be here”.', 'Je visiterai le musée; nous serons ici. The first uses a regular infinitive stem and the second the irregular ser- stem.',
   d(false, 'What is the infinitive?', 'The dictionary form of a verb.', 'The near-future pattern with aller can be mixed unintentionally with simple-future endings.')],
  ['Challenge: contrast a future prediction with a conditional wish', 'Use context and endings to distinguish will from would.',
   'The present conditional uses the future stem with imperfect endings: je visiterais means I would visit. Compare je visiterai and je visiterais in writing; their similar pronunciation in some varieties makes context and spelling important. In a taught hypothetical pattern, si j’avais le temps, je visiterais le musée uses imperfect after si and conditional in the outcome clause, not conditional in both.',
   'Explain Si j’avais le temps, je voyagerais.', ['J’avais presents the hypothetical condition.', 'Voyagerais uses the future stem with -ais.', 'The result means If I had time, I would travel.'], 'Hypothetical si condition: imperfect; imagined result: conditional.', 'Writing si j’aurais in this taught hypothetical construction.', 'Separate the condition’s grammar from the result’s grammar.', 'Does je voyagerais mean the same as je voyagerai?', 'No: would travel versus will travel.',
   'Write “If I had time, I would finish the book”.', 'Si j’avais le temps, je finirais le livre. Avais is imperfect and finirais conditional; the sentence describes a hypothetical possibility rather than a definite future promise.',
   d(true, 'Which endings form the first-person singular imperfect?', '-ais, with the appropriate stem.', 'The meaning would may be translated into both clauses even though French assigns different forms.')]
 ]]
]],
['spanish', [
 ['Imperfect and preterite contrast', [
  ['Use imperfect forms for habitual background', 'Form taught regular imperfect verbs and recognise iba and era.',
   'Regular -ar imperfect endings are -aba, -abas, -aba, -ábamos, -abais and -aban. For -er and -ir verbs they are -ía, -ías, -ía, -íamos, -íais and -ían. Cantaba can mean I used to sing or was singing, depending on context. Common irregular forms include iba from ir and era from ser. Context or a pronoun identifies the subject where forms coincide.',
   'Translate “We used to live here” with vivir.', ['Remove -ir to obtain viv-.', 'Add -íamos for nosotros or nosotras.', 'Write Vivíamos aquí, preserving the accent.'], 'Habitual or ongoing past needs its own endings.', 'Using the preterite for every English past-tense sentence.', 'Consider whether the action is framed as habit, background or a completed event.', 'What is the imperfect of ir for yo?', 'Iba.',
   'Translate “I used to sing and we used to eat here”.', 'Cantaba y comíamos aquí. Context identifies cantaba as I; yo can be added for clarity. Comíamos uses the -er imperfect ending with its accent.',
   d(false, 'What does a habitual action mean?', 'Something occurring repeatedly rather than just one bounded event.', 'English past wording does not always make the viewpoint distinction explicit.')],
  ['Challenge: pair background and a completed occurrence', 'Select tense by narrative function rather than action length.',
   'Leía cuando sonó el teléfono frames reading as ongoing and the ringing as a completed occurrence. The imperfect and preterite organise a narrative rather than simply label long and short events. A bounded period such as “I studied for two hours” may use preterite even though it is lengthy. Identify how the speaker packages the action and explain the contrast.',
   'Analyse Jugábamos cuando llegó Ana.', ['Jugábamos supplies an ongoing background.', 'Llegó presents Ana’s arrival as an event.', 'Cuando links the two without requiring them to use the same tense.'], 'Background and event can share a sentence but not a tense.', 'Assuming every past verb in one sentence must match.', 'Choose each verb according to its role.', 'Which infinitive produces llegó?', 'Llegar.',
   'Translate “I was eating when Ana arrived”.', 'Comía cuando llegó Ana. Comía gives the background action; llegó marks the arrival as a completed event. A subject pronoun can clarify who was eating if context requires it.',
   d(true, 'What does the preterite usually present in these examples?', 'A bounded or completed event.', 'Tense consistency can be confused with using one tense regardless of narrative function.')]
 ]],
 ['Direct objects and reference', [
  ['Choose lo, la, los or las for a known object', 'Match gender and number while placing the pronoun before a simple finite verb.',
   'In the taught direct-object pattern, lo replaces a masculine singular noun, la a feminine singular noun, and los or las plural nouns. Leo el libro becomes Lo leo. The object’s grammatical properties determine the choice, not the speaker’s gender. Regional patterns vary, especially with human objects; these exercises use ordinary inanimate referents to establish the basic construction.',
   'Replace las revistas in Leo las revistas.', ['Revistas is feminine plural.', 'Select las.', 'Place it before the verb: Las leo.'], 'The replaced noun controls the pronoun.', 'Choosing a pronoun according to who is reading.', 'Identify the object rather than the subject.', 'What replaces el libro in this pattern?', 'Lo.',
   'Replace la película in Veo la película.', 'La veo. La refers back to the feminine singular película and precedes the conjugated verb veo.',
   d(false, 'What do singular and plural distinguish?', 'One item from more than one.', 'The speaker’s identity may be confused with the grammatical features of the object being replaced.')],
  ['Challenge: use two valid pronoun positions with an infinitive', 'Preserve meaning when moving a direct-object pronoun in a modal construction.',
   'Quiero comprar el libro can become Lo quiero comprar or Quiero comprarlo. In this construction the object pronoun may precede the finite verb or attach to the infinitive. It cannot simply stand as a separate word after comprar. When negating, No lo quiero comprar and No quiero comprarlo keep no before the finite verb. Do not combine both positions and duplicate the object pronoun.',
   'Replace las entradas in Voy a comprar las entradas.', ['Choose las for the feminine plural object.', 'One form is Las voy a comprar.', 'The alternative is Voy a comprarlas, attaching the pronoun to the infinitive.'], 'Before the finite verb or attached to the infinitive.', 'Writing voy a comprar las as if the detached pronoun were an English object.', 'Use one of the valid positions and preserve the infinitive.', 'Must comprarlo be written as one word?', 'Yes.',
   'Give two ways to say “I do not want to read it”, referring to el libro.', 'No lo quiero leer; no quiero leerlo. Both place the negative before quiero and identify the book through lo; neither duplicates the pronoun.',
   d(true, 'What is the infinitive in quiero leer?', 'Leer.', 'A placement pattern from a single finite verb can conceal alternatives involving an infinitive.')]
 ]],
 ['Future and hypothetical expression', [
  ['Form a simple future prediction', 'Add future endings to a regular infinitive and preserve accents.',
   'Regular simple-future forms use the infinitive plus -é, -ás, -á, -emos, -éis or -án. Visitaré means I will visit; viviremos means we will live. The same endings serve -ar, -er and -ir verbs, although some verbs have irregular stems, such as tendr- from tener. A future form expresses a prediction or commitment in these examples, not merely a sentence containing a future time word.',
   'Write “We will eat tomorrow”.', ['Use the infinitive comer.', 'Add -emos for we.', 'Write Comeremos mañana.'], 'Infinitive stem, future ending.', 'Removing the infinitive ending as in many present forms.', 'Keep the full regular infinitive before adding the future ending.', 'What is the yo future of visitar?', 'Visitaré.',
   'Translate “They will live here” and “I will have time”.', 'Vivirán aquí; tendré tiempo. Vivirán uses the regular infinitive stem, while tendré uses the irregular tendr- stem and the same yo ending.',
   d(false, 'What does mañana mean in a time expression?', 'Tomorrow.', 'Present-tense stem formation may be incorrectly transferred to the future.')],
  ['Challenge: express a conditional preference with reasons', 'Distinguish a hypothetical would statement from a definite future plan.',
   'The conditional uses the future stem with -ía, -ías, -ía, -íamos, -íais or -ían. Viajaría means I would travel. A response such as Me gustaría visitar Madrid porque me interesa el arte expresses a desired possibility rather than a booked trip. Explain the reason and any limitation without changing into a definite future claim unintentionally. Accents remain part of correct written forms.',
   'Compare Visitaré Madrid and Me gustaría visitar Madrid.', ['Visitaré states a future visit in this context.', 'Me gustaría presents a wish or hypothetical preference.', 'Visitar remains infinitive after gustaría in the preference construction.'], 'Would expresses a different commitment from will.', 'Treating a conditional wish as evidence that travel is already arranged.', 'Preserve the speaker’s degree of commitment and intended meaning.', 'Which stem is used for the conditional of tener?', 'Tendr-.',
   'Write “I would like to read the book because history interests me”.', 'Me gustaría leer el libro porque me interesa la historia. Gustaría frames a preference, leer remains infinitive and the reason explains the interest rather than guaranteeing a future action.',
   d(true, 'What does porque introduce?', 'A reason.', 'Future-oriented wishes and definite plans can look similar while making different commitments.')]
 ]]
]],
['german', [
 ['Past narration with different verb forms', [
  ['Use war and hatte in a short past description', 'Combine common simple-past forms with accurate time and subject information.',
   'War is the ich and er/sie/es simple-past form of sein; hatte serves those persons for haben. Wir waren and wir hatten are plural forms. These are common in both descriptions and narration, including alongside perfect-tense actions: Ich war müde, aber ich habe gelesen. German tense choices do not map exactly onto an English past/simple-versus-continuous distinction.',
   'Translate “Yesterday we were tired and had no time”.', ['Begin Gestern and keep waren second.', 'Use wir müde, then the coordinated verb hatten.', 'Write Gestern waren wir müde und hatten keine Zeit.'], 'Common past states: war and hatte.', 'Using a present form because the time phrase already says yesterday.', 'Make the verb form carry the intended past meaning as well.', 'What is the wir past form of sein?', 'Waren.',
   'Translate “I was here, but I had no book”.', 'Ich war hier, aber ich hatte kein Buch. War and hatte express past states, and kein Buch is neuter accusative after hatte.',
   d(false, 'What do sein and haben mean?', 'To be and to have.', 'Time adverbs can be treated as a substitute for choosing the intended verb tense.')],
  ['Challenge: explain the position of a separable prefix', 'Compare aufstehen in a main clause and in the perfect tense.',
   'Aufstehen means to get up. In a simple present main clause, the prefix separates: Ich stehe um sieben Uhr auf. In the perfect, the participle is aufgestanden and the auxiliary is sein: Ich bin um sieben Uhr aufgestanden. The prefix does not detach again from the participle. Learn the verb’s forms and auxiliary as a set rather than move every prefix identically in every tense.',
   'Front heute in the present sentence.', ['Heute occupies the first constituent.', 'The finite verb stehe remains second, followed by ich.', 'Write Heute stehe ich um sieben Uhr auf.'], 'Present splits the prefix; the participle holds it together.', 'Writing ich bin gestanden auf for the taught perfect of aufstehen.', 'Use the complete participle aufgestanden with sein.', 'What is the perfect auxiliary of aufstehen?', 'Sein.',
   'Translate “Yesterday I got up at eight”.', 'Gestern bin ich um acht Uhr aufgestanden. Bin is the finite auxiliary in second position and aufgestanden is the complete final participle.',
   d(true, 'Where does a participle go in a simple German perfect main clause?', 'Normally at the end.', 'A correct separable-prefix pattern can be overextended to a participle with a different structure.')]
 ]],
 ['Subordination and relative reference', [
  ['Use dass to report a thought', 'Place the finite verb at the end of a standard subordinate clause.',
   'Dass introduces a subordinate content clause, as in Ich denke, dass der Film interessant ist. The main clause retains its second-position finite verb, while ist ends the dass clause. The comma marks the clause boundary in writing. Dass with double s is a conjunction here, distinct from das as an article or pronoun; their similar sound does not make their functions identical.',
   'Build “I think that the book is good”.', ['Write the main clause Ich denke.', 'Add comma and dass.', 'Finish with das Buch gut ist, placing ist last.'], 'Dass introduces content; its finite verb goes last.', 'Writing dass das Buch ist gut in the standard written pattern.', 'Find the subordinate finite verb and move it to the clause end.', 'Which word is finite in dass er hier wohnt?', 'Wohnt.',
   'Translate “We think that she has time”.', 'Wir denken, dass sie Zeit hat. Denken remains second in the main clause; hat ends the subordinate clause.',
   d(false, 'What does a conjunction do?', 'Links words, phrases or clauses according to its grammatical role.', 'Main-clause word order may persist after a subordinating conjunction.')],
  ['Challenge: introduce a nominative relative clause', 'Choose a relative pronoun and distinguish its clause role from the main clause.',
   'A relative clause adds information about a noun. In Das ist der Mann, der hier wohnt, der refers to the masculine singular Mann and acts as the subject of wohnt. The finite verb ends the relative clause. In these nominative examples, die refers to a feminine noun and das to a neuter noun. Other cases change forms, so this is not a rule that every relative pronoun simply copies the noun’s main-clause article.',
   'Add “who lives here” to Das ist die Frau.', ['The referent Frau is feminine singular.', 'The relative pronoun is the subject of wohnt, so use nominative die.', 'Write Das ist die Frau, die hier wohnt.'], 'Referent gives gender; clause role gives case.', 'Assuming the article in the main clause determines every later pronoun form.', 'Identify the relative pronoun’s role inside its own clause.', 'Where is wohnt in the relative clause?', 'At the end.',
   'Complete Das ist das Kind, ... hier wohnt and explain the form.', 'Das ist das Kind, das hier wohnt. Kind is neuter and the relative pronoun is nominative as the subject of wohnt, so das is used.',
   d(true, 'What is the subject of a clause?', 'The grammatical participant with which the finite verb agrees in these examples.', 'Two linked clauses can be analysed as if every word retains the same case role throughout.')]
 ]],
 ['Adjective endings and future plans', [
  ['Add an adjective after a definite article in the nominative', 'Use the taught singular weak endings without generalising them to every case.',
   'In nominative singular noun phrases after a definite article, a descriptive adjective normally takes -e: der kleine Hund, die kleine Katze, das kleine Haus. The article carries much of the gender and case information. This lesson’s pattern is restricted to nominative singular: plural forms, other cases and other determiners need their own endings. Noun gender does not change because an adjective is added.',
   'Describe das Haus as klein in a nominative phrase.', ['Keep the neuter definite article das.', 'Add -e to klein in this taught pattern.', 'Write das kleine Haus.'], 'Definite article plus nominative singular: adjective -e.', 'Using the bare adjective before every noun.', 'Check determiner, number and case before selecting an ending.', 'What is the adjective form in die ... Katze using klein?', 'Kleine.',
   'Build “the old man” as a nominative phrase using der Mann and alt.', 'Der alte Mann. Alte takes -e after der in this nominative singular phrase; the noun remains capitalised.',
   d(false, 'Which word is the noun in das kleine Haus?', 'Haus.', 'English adjectives usually do not change ending, encouraging omission of German agreement.')],
  ['Challenge: distinguish werden future from a present-tense arrangement', 'Explain two ways of referring to future time while preserving word order.',
   'German can use a present tense with a future time expression: Morgen besuche ich meine Tante. A future construction uses werden plus a final infinitive: Morgen werde ich meine Tante besuchen. The choice depends on context and emphasis; English will should not be copied as German will, which means wants. Keep the finite verb second and the infinitive final in the werden construction.',
   'Compare Ich will reisen and Ich werde reisen.', ['Will is a form of wollen and expresses wanting to travel.', 'Werde is a form of werden and forms a future statement with reisen.', 'The similar English spelling does not make German will a future auxiliary.'], 'German will means wants; werden builds this future.', 'Translating English I will travel as ich will reisen without noticing the meaning change.', 'Choose the intended modal meaning before translating.', 'What is the wir form of werden?', 'Werden.',
   'Translate “Tomorrow we will visit the museum” using werden and besuchen.', 'Morgen werden wir das Museum besuchen. Morgen fills the first constituent, werden is second and besuchen ends the clause. A contextual present-tense arrangement could instead use Morgen besuchen wir das Museum.',
   d(true, 'Where does a finite verb go after a fronted time phrase in a main clause?', 'In second constituent position.', 'A familiar English word can create a false-friend translation with a different German function.')]
 ]]
]]
];
