import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 24 : 17, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, sketch the process and reconstruct the causal links. In a week, compare a different place or dataset, identifying which conclusions depend on the original conditions.' });
export const year10Geography: Subject = ['geography', [
 ['Tectonic boundaries and place-specific risk', [
  ['Explain continental collision without assuming volcanic arcs', 'Connect compression, crustal thickening and earthquakes in the Himalayan setting.',
   'The Indian and Eurasian continental collision compresses and thickens crust, contributing to the Himalayas. Movement on faults can release accumulated strain as earthquakes. This setting should not be explained by copying an oceanic-subduction volcanic-arc diagram: buoyant continental crust behaves differently, and a chain of typical subduction volcanoes is not the defining outcome here. Plate-boundary labels summarise processes but do not capture every local fault.',
   'Explain why Himalayan mountain building can coexist with major earthquakes.', ['Convergent motion compresses and deforms continental crust.', 'Faults can lock while strain accumulates.', 'Sudden slip releases energy, so mountain building and seismic activity reflect related tectonic processes.'], 'Collision thickens crust; locked faults can release strain.', 'Predicting a volcanic arc at every convergent boundary.', 'Identify the plate types and mechanism rather than only the direction of movement.', 'Which plates are involved in the Himalayan collision?', 'The Indian and Eurasian plates.',
   'Why does a regional plate map not locate every future earthquake precisely?', 'It shows broad movement and boundaries, while local fault geometry, stress and rupture timing are more complex. Tectonic setting explains risk patterns, not an exact short-term prediction.',
   d(false, 'What is a convergent boundary?', 'A setting where plates move towards one another.', 'One familiar boundary diagram can be overgeneralised to geologically different combinations of plates.')],
  ['Challenge: connect Nepal’s 2015 earthquake impacts with access and vulnerability', 'Use a named event to build linked rather than isolated consequences.',
   'The April 2015 Nepal earthquake occurred in the Himalayan collision region. Building vulnerability, settlements on difficult terrain and damage to transport links shaped impacts and response. Landslides could both harm communities and obstruct access, linking a secondary physical hazard with delayed assistance. A place-based explanation should connect these mechanisms without treating national income alone as a complete cause or assuming every settlement experienced the same damage.',
   'Explain a chain from earthquake shaking to delayed medical assistance.', ['Shaking can trigger slope failure or damage roads.', 'Blocked routes can isolate communities and restrict transport of people and supplies.', 'Access problems can prolong disruption even after the initial shaking stops.'], 'Link the physical impact to the human response pathway.', 'Listing landslides and aid delays as unrelated facts.', 'Use a causal connection grounded in terrain and infrastructure.', 'Is a landslide triggered by shaking a primary tectonic rupture?', 'No; it is a secondary hazard resulting from the shaking.',
   'Why compare building condition and local shaking before attributing all damage differences to wealth?', 'Exposure and physical intensity vary within a country, as do construction and access. A broad income label can hide those factors and cannot alone explain a particular building’s outcome.',
   d(true, 'What does vulnerability mean in hazard studies?', 'Susceptibility to harm under particular physical and social conditions.', 'A named case study can become a list of effects without explaining why they differed between places.')]
 ]],
 ['Tropical storms and cascading impacts', [
  ['Explain the energy and circulation of a tropical storm', 'Connect warm water, rising moist air and latent heat release.',
   'Tropical storms draw energy from warm ocean conditions that support evaporation and moist rising air. Condensation releases latent heat, helping sustain uplift and low pressure. Air converges and rotates under Earth’s rotation away from the equator; sufficiently low vertical wind shear helps the system remain organised. Warm water alone does not guarantee a storm, and a storm can weaken over land when its energy supply and circulation are disrupted.',
   'Explain why condensation can strengthen an already developing storm.', ['Warm moist air rises and cools.', 'Condensation releases energy into the surrounding air.', 'That heating supports further uplift and circulation under suitable conditions.'], 'Evaporation supplies moisture; condensation releases stored energy.', 'Describing condensation as a process that only removes energy from the storm air.', 'Track where energy is absorbed and where it is released.', 'Why are tropical storms uncommon right on the equator?', 'The rotational deflection needed for organised circulation is very weak there.',
   'Why does a forecast need more than sea-surface temperature?', 'Wind shear, moisture, atmospheric stability, existing disturbances and other conditions affect formation and development. One necessary or favourable condition is not sufficient by itself.',
   d(false, 'What is latent heat?', 'Energy associated with a state change rather than a temperature change of the substance.', 'A single memorable temperature condition may replace the interacting atmospheric processes.')],
  ['Challenge: explain storm surge using Typhoon Haiyan', 'Distinguish coastal water rise from wind damage and rainfall flooding.',
   'Typhoon Haiyan struck the Philippines in November 2013, with severe impacts including coastal flooding around Tacloban. Storm surge is an abnormal rise in sea level driven strongly by storm winds, with pressure, coastline shape and shallow-water conditions also contributing. It differs from river flooding caused by rainfall, although hazards can combine. Effective warnings need locally understandable information and realistic evacuation options, not only an accurate storm category.',
   'Explain why a coastal household can face danger without its roof first being damaged by wind.', ['Storm-driven water can inundate low coastal ground.', 'Flood depth and moving water can threaten people and buildings independently of direct wind failure.', 'Risk communication must therefore include surge, not just expected wind strength.'], 'One storm creates several distinct pathways of harm.', 'Treating storm surge as simply another name for heavy rain.', 'Identify the water source and physical mechanism.', 'Where did Haiyan make its devastating 2013 impacts discussed here?', 'The Philippines, including the Tacloban area.',
   'Why might an accurate warning still fail to protect everyone?', 'People may not understand the hazard, have transport, trust the message or have an accessible safe destination. Warning quality and the practical capacity to act must be evaluated together.',
   d(true, 'What is exposure?', 'People or assets being located where a hazard can affect them.', 'Forecast accuracy can be mistaken for guaranteed protective action without social and logistical capacity.')]
 ]],
 ['Tropical ecosystems and land-use decisions', [
  ['Explain rapid nutrient cycling in a tropical rainforest', 'Distinguish large biomass stores from assumptions about deep fertile soil.',
   'Warm, wet conditions can support rapid decomposition and uptake in tropical rainforests, with much nutrient capital held in living biomass and a relatively thin litter layer. Heavy rainfall can promote leaching from exposed soil. Removing vegetation therefore changes stores and transfers, not just shade. A productive forest does not prove that cleared soil will sustain repeated cropping without declining fertility or additional inputs.',
   'Explain why initial crop growth after clearance may not predict long-term fertility.', ['Burned or decomposed biomass can release nutrients temporarily.', 'Loss of continuing litter inputs and vegetation uptake changes the cycle.', 'Leaching and erosion can remove nutrients, reducing later productivity under unsuitable management.'], 'A large living store is not the same as a durable soil reserve.', 'Calling every rainforest soil permanently fertile because the vegetation is dense.', 'Trace the nutrient stores and transfer rates before and after clearance.', 'What is leaching?', 'Movement of dissolved substances down through soil with percolating water.',
   'Why does keeping some ground cover help more than simply shading crops?', 'Cover can reduce raindrop impact and runoff, retain organic inputs and protect soil structure. Its effects include physical and nutrient processes as well as temperature or shade.',
   d(false, 'What is decomposition?', 'Breakdown of dead organic material by organisms and associated processes.', 'Visible biomass can be taken as a direct indication of nutrient reserves in the underlying soil.')],
  ['Challenge: evaluate forest conservation across scales', 'Compare local livelihoods, supply chains and environmental effects.',
   'Forest clearance can be linked to farming, logging, infrastructure and wider demand for commodities. Conservation proposals must consider local livelihoods, land rights, enforcement and the possibility that damaging activity moves elsewhere. Protected areas can help but are not self-enforcing lines on a map. Evaluate who bears costs and benefits across local, national and global scales rather than portray all residents as having identical priorities.',
   'A fictional conservation plan prohibits clearance but provides no alternative income or enforcement budget.', ['Identify the environmental aim and the activities it would restrict.', 'Consider how households and commercial actors may respond under economic pressure.', 'Assess support, rights and monitoring needed to turn the rule into a lasting outcome.'], 'A protected boundary needs institutions and viable choices.', 'Assuming announcing protection automatically stops all deforestation.', 'Evaluate implementation and displacement as well as designated area.', 'What does displacement of environmental harm mean here?', 'Moving damaging activity elsewhere rather than eliminating it.',
   'Why examine consumers and firms outside the forest region?', 'External demand and finance can shape local incentives and supply chains. Focusing only on nearby households can miss major drivers and unfairly allocate responsibility.',
   d(true, 'What is a scale in geographical analysis?', 'A level such as local, national or global at which processes and decisions are examined.', 'A local visible action can conceal distant economic drivers.')]
 ]],
 ['Changing landscapes and coastal management', [
  ['Explain meander migration and oxbow formation', 'Link unequal erosion and deposition with a changing channel shape.',
   'In a simplified meander model, faster flow near the outside bend promotes erosion while slower flow towards the inside encourages deposition. Continued erosion can narrow a meander neck. During suitable high-flow conditions, water may take a shorter route across it; later deposition can isolate an oxbow lake. The sequence is a model, not a fixed timetable for every bend, and local geology and engineering affect behaviour.',
   'Explain why erosion and deposition can occur within the same river bend.', ['Flow speed and stress vary across the channel.', 'The outer bend can experience stronger erosive action.', 'Reduced energy near the inner bend encourages deposition of transported sediment.'], 'Different positions in one channel can have different energy conditions.', 'Saying a river must be either eroding or depositing everywhere at once.', 'Locate the process within the channel and state its mechanism.', 'What feature can remain after a cut-off meander is isolated?', 'An oxbow lake.',
   'Why does a straightened channel not prove a natural oxbow sequence occurred?', 'People may deliberately realign channels. Historical maps, landforms and records are needed to distinguish human engineering from the natural process model.',
   d(false, 'What is deposition?', 'The laying down of transported material when conditions favour its settlement.', 'A regional process label can be applied uniformly to every location or used to infer history without evidence.')],
  ['Challenge: evaluate managed realignment at Medmerry', 'Explain deliberately changing a defence line rather than simply abandoning protection.',
   'At Medmerry in West Sussex, a managed realignment scheme opened in 2013 used a new inland defence alignment while allowing tidal water into an area seaward of it. The approach combined flood-risk management with habitat creation rather than continually relying on the former coastal barrier alone. It involved land-use trade-offs, engineering and ongoing management. Evaluation should compare protected assets, costs, habitat and affected land users rather than label all retreat as doing nothing.',
   'Explain why managed realignment is different from uncontrolled defence failure.', ['A new defence line and controlled spatial plan are established.', 'Specified land is allowed to flood while other assets receive protection.', 'The deliberate redistribution of exposure requires design and management rather than simple neglect.'], 'Move the protection strategy, not merely remove all protection.', 'Describing every retreat policy as abandoning everyone to the sea.', 'Identify which land is flooded, which assets are protected and how.', 'In which English county is Medmerry?', 'West Sussex.',
   'What information is needed to judge whether a similar scheme suits another coast?', 'Topography, assets, land ownership, ecological opportunities, future sea-level assumptions and comparative costs are needed. A successful named example is not a universal solution independent of place.',
   d(true, 'What is coastal management?', 'Actions intended to influence coastal risk, use or environmental change.', 'A policy label can obscure deliberate engineering and the distribution of benefits and losses.')]
 ]],
 ['Urban opportunities, inequality and upgrading', [
  ['Explain urban growth through migration and natural increase', 'Connect employment opportunities with uneven access to services.',
   'Urban populations can grow through migration, natural increase and reclassification. Employment, education and family networks may attract migrants, while rural pressures also matter. Growth can support services and markets but outpace formal housing and infrastructure provision. Informal settlements are diverse communities, not evidence that residents lack skills or agency. Explain the mismatch between demand, affordability and provision rather than treat all growth as automatically harmful.',
   'A fictional city gains jobs faster than affordable formal housing is built.', ['Employment attracts or retains residents.', 'Housing demand increases while affordable supply lags.', 'Some households use informal or overcrowded options, linking economic opportunity with infrastructure pressure.'], 'Opportunity and constraint can arise from the same growth process.', 'Explaining informal housing only as an individual preference or failure.', 'Consider affordability, land access and the speed of provision.', 'What is natural increase?', 'Births exceeding deaths in a population over a period.',
   'Why might migration continue despite housing difficulties?', 'People compare several opportunities and constraints, including work, family and safety, rather than housing alone. Difficult conditions do not prove the decision has no rationale.',
   d(false, 'What is rural-to-urban migration?', 'Movement from countryside settlements to towns or cities.', 'A city’s visible difficulties can hide the alternatives and networks shaping migration decisions.')],
  ['Challenge: assess upgrading using Rio de Janeiro', 'Compare physical improvements with security, affordability and participation.',
   'Rio de Janeiro includes major economic opportunities alongside substantial spatial inequality. Upgrading initiatives such as Favela-Bairro sought to improve infrastructure and integration in selected settlements. Physical works can improve access but do not automatically settle land tenure, employment or long-term affordability. Evaluate what changed for residents, whose views shaped decisions and whether improvements were maintained, rather than treat a programme name as proof of complete success.',
   'A settlement receives improved paths and drainage under an upgrading approach.', ['Identify direct benefits for access and water management.', 'Ask whether housing security, maintenance and service affordability also improved.', 'Compare resident experiences and possible displacement pressures before judging the overall outcome.'], 'An upgraded surface is one part of a lived neighbourhood.', 'Equating infrastructure completion with the end of urban inequality.', 'Use social and maintenance evidence alongside construction outputs.', 'What does land tenure concern?', 'Rights and arrangements for occupying or using land.',
   'Why is resident participation relevant to evaluating the project?', 'Residents can identify routes, risks and needs planners may miss, and their involvement affects legitimacy and use. Participation should be examined in practice, not assumed from consultation publicity.',
   d(true, 'What is social inequality?', 'Unequal access to resources, opportunities or outcomes between groups.', 'Visible construction is easier to count than security, access or long-term social effects.')]
 ]],
 ['Fieldwork, data and geographical judgement', [
  ['Choose a sampling strategy suited to a spatial question', 'Compare systematic and stratified approaches with their limitations.',
   'Systematic sampling selects observations at regular intervals, useful for examining a spatial gradient. Stratified sampling represents defined subgroups, such as land-use zones, in a planned way. Neither automatically removes bias: interval choice can align with a repeating pattern, while incorrect strata can miss important variation. State the geographical question, access limits and the population or area represented before choosing a method.',
   'Plan pedestrian counts along a route from a transport hub to a residential area using supplied safe locations.', ['Use regular route intervals to examine a distance pattern.', 'Keep count duration and observation rules comparable.', 'Repeat at relevant times and state that the route does not represent every neighbourhood.'], 'Method follows the spatial question and its limits.', 'Claiming a regular interval makes a sample random.', 'Distinguish systematic selection from random selection and explain the trade-off.', 'What does stratified sampling deliberately represent?', 'Defined groups or sections of the population or study area.',
   'Why record weather and time during pedestrian counts?', 'They can affect movement and help explain differences between observations. Without that context, a spatial conclusion may actually reflect changing conditions during the route.',
   d(false, 'What is an independent variable in an investigation?', 'The factor deliberately varied or used as the explanatory comparison.', 'A named sampling technique can be treated as inherently unbiased without checking the study pattern.')],
  ['Challenge: qualify a conclusion using reliability and alternative explanations', 'Separate a supported association from a universal or causal claim.',
   'A fieldwork conclusion should answer the question within the evidence’s scale and uncertainty. Repeated counts can reveal variability, while maps may show clustering or exceptions. A correlation between distance and a measured feature does not by itself prove distance causes the difference; land use, transport and timing may also vary. Strong evaluation identifies a specific limitation and explains how it affects the claim.',
   'A single afternoon’s counts decline with distance from a station.', ['The observations support a pattern for that route and period.', 'Nearby shops or school closing times may also influence counts.', 'Repeat across times and comparable routes before generalising to all urban areas.'], 'State the result at the scale the evidence can support.', 'Calling a small local association a universal law.', 'Name the alternative explanation and the evidence needed to distinguish it.', 'Does repeating an unchanged biased route guarantee city-wide representativeness?', 'No.',
   'Improve “Our method was inaccurate because human error”.', '“Counts at later sites coincided with school dismissal, so time and distance changed together. Repeating sites simultaneously or on a rotated schedule would help separate the spatial pattern from timing.” This identifies a mechanism and a relevant improvement.',
   d(true, 'What is reliability in repeated measurement?', 'Consistency or repeatability under comparable conditions.', 'Generic evaluation phrases can name no actual source of uncertainty or effect on the conclusion.')]
 ]]
]];
