import type { Subject, ActivityDetail } from '../authoredActivities';
const core: ActivityDetail = { isPremium: false, difficulty: 'Core', estimatedMinutes: 15, revision: 'Tomorrow, redraw the process or indicator relationship from memory. In a week, apply it to a new named or explicitly hypothetical place and state the limits of the comparison.' };
const challenge: ActivityDetail = { ...core, isPremium: true, difficulty: 'Higher', estimatedMinutes: 20 };
export const year8Geography: Subject = ['geography', [
 ['Tectonic processes and disaster risk', [
  ['Explain subduction without melting every plate edge', 'Connect plate motion, earthquakes and volcanic activity at a subduction zone.',
   'Where a denser oceanic plate descends beneath another plate, friction can lock sections of the boundary while motion continues elsewhere. Stored strain may be released in an earthquake. Water released from the descending slab helps lower the melting temperature in the overlying mantle, generating magma that may rise. Avoid the misleading shortcut that all volcanoes form simply because two plates rub together and melt.',
   'Trace two different consequences of an oceanic plate descending beneath a continental plate.', ['Locking and sudden slip can produce earthquakes.', 'Released water promotes partial melting in the mantle above the slab.', 'Rising magma may feed a volcanic arc on the overriding plate.'], 'Slip releases strain; melting supplies magma.', 'Using frictional melting as the complete explanation of a volcanic arc.', 'Distinguish the earthquake mechanism from magma generation.', 'What is subduction?', 'One tectonic plate descending beneath another.',
   'Would every earthquake at a subduction boundary require a volcanic eruption? Explain.', 'No. Earthquakes can result from fault movement and strain release without magma reaching the surface. The processes are related to the same plate setting but are not identical events.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What are tectonic plates?', answer: 'Large moving sections of Earth’s lithosphere.' }], memoryExplanation: 'Two linked but distinct mechanisms prevent a single inaccurate explanation being used for all tectonic hazards.', misconceptionCause: 'Simple diagrams can collapse several physical processes into one collision arrow.' }],
  ['Challenge: compare hazard magnitude with disaster impact', 'Use exposure and vulnerability to explain unequal earthquake losses.',
   'Earthquake magnitude measures the event’s size, not the final disaster losses. Exposure concerns people and assets in affected areas; vulnerability concerns susceptibility to harm, influenced by building quality, access, preparedness and other conditions. Depth, distance and local ground conditions also affect shaking. A valid comparison must consider these interacting factors rather than infer that a wealthier place is always safe or a larger magnitude always kills more people.',
   'In a hypothetical comparison, a smaller shallow earthquake near fragile housing causes greater losses than a larger distant event.', ['The magnitude alone does not describe local shaking.', 'More people and fragile buildings may be exposed near the smaller event.', 'Building vulnerability and response access can increase losses.'], 'Event size is not the same as experienced harm.', 'Ranking disaster severity using magnitude alone.', 'Compare hazard characteristics, exposure, vulnerability and response capacity.', 'What does exposure mean in disaster risk?', 'People or assets being located where a hazard can affect them.',
   'Name two further measurements needed before attributing the difference only to building quality.', 'Local shaking intensity and the number of people exposed would help separate physical hazard and exposure from vulnerability. Building quality may matter, but cannot be isolated from these data by assumption.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'Can the same physical event affect different locations differently?', answer: 'Yes; distance, ground conditions and human circumstances vary.' }], memoryExplanation: 'Breaking risk into components identifies alternative explanations for an apparent pattern.', misconceptionCause: 'A single widely reported number can dominate comparisons while other variables remain hidden.' }]
 ]],
 ['Development measures and inequality', [
  ['Interpret income per person without assuming equal incomes', 'Explain the strengths and limits of a national average.',
   'GDP per person divides the value of production by population. It is an average indicator of economic output, not the amount each person receives or a direct measure of happiness. Comparisons across countries also need attention to prices and the year of measurement. A high average can coexist with unequal distribution, while unpaid work and environmental damage may be poorly represented in the figure.',
   'A hypothetical economy produces £120 million for 10,000 residents.', ['Divide £120,000,000 by 10,000.', 'The result is £12,000 of GDP per person.', 'This does not show that every resident earns or receives £12,000.'], 'An average output is not a payslip.', 'Treating GDP per person as each person’s salary.', 'Distinguish output, income distribution and individual earnings.', 'What two quantities are used to calculate GDP per person?', 'Total GDP and population.',
   'Two places have the same GDP per person. Must their living conditions be the same?', 'No. Distribution, prices, public services, health, environmental quality and many other conditions can differ despite an equal output average.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'How is an arithmetic mean calculated?', answer: 'Add the values and divide by how many values there are.' }], memoryExplanation: 'Remembering the calculation keeps the indicator’s meaning separate from claims it cannot support.', misconceptionCause: 'The phrase per person can sound like an actual payment to each individual.' }],
  ['Challenge: combine indicators without hiding trade-offs', 'Evaluate why a composite development measure needs supporting evidence.',
   'The Human Development Index combines dimensions of health, education and income using life expectancy, schooling measures and gross national income per person. It broadens comparison beyond output alone, but a national composite still masks internal differences and excludes many valued conditions. Similar overall scores can arise from different combinations. Use component indicators and distributional evidence before proposing which policy should take priority.',
   'Two hypothetical countries have similar HDI but different education and health results.', ['The composite can conceal offsetting strengths and weaknesses.', 'Inspect component indicators rather than assume identical needs.', 'Look within each country for regional and group inequalities before recommending interventions.'], 'Unpack the score before prescribing a solution.', 'Assuming an equal composite index means equal conditions in every dimension.', 'Inspect components, distribution and what the index omits.', 'Does HDI directly include every aspect of environmental quality?', 'No.',
   'Why would HDI alone be insufficient to choose where to build a clinic within a country?', 'It is a national summary, not a local needs map. Local health outcomes, travel times, population needs and existing services are required to select a site responsibly.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What is an indicator?', answer: 'A measure used to give information about a condition or process.' }], memoryExplanation: 'A composite compresses several dimensions, so decisions require reversing that compression.', misconceptionCause: 'A single ranked score creates an impression of complete and precise knowledge.' }]
 ]],
 ['Urban change and inclusive planning', [
  ['Separate urban growth from urbanisation', 'Distinguish an increasing urban population from an increasing urban share.',
   'Urban growth is an increase in the number of people living in urban places; urbanisation is an increase in the proportion of a population living there. Rural-to-urban migration, natural increase and reclassification can contribute to change. A country’s urban population may rise while its urban share falls if the total population grows faster. State the denominator whenever making a percentage comparison.',
   'A hypothetical country changes from 4 million urban residents out of 10 million to 5 million out of 15 million.', ['The urban population rises by 1 million, so there is urban growth.', 'The urban share changes from 40 percent to about 33.3 percent.', 'The share falls, so this example does not show urbanisation over the period.'], 'Growth counts people; urbanisation compares shares.', 'Assuming more urban residents always means a greater urban percentage.', 'Calculate the urban proportion using the total population in each year.', 'What is the denominator in the urban share?', 'The country’s total population.',
   'If urban residents rise from 6 million to 8 million while total population stays at 12 million, describe both changes.', 'Urban growth is 2 million people. The share rises from 50 percent to about 66.7 percent, so urbanisation also occurs.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'How do you calculate a percentage share?', answer: 'Divide the part by the whole and multiply by 100.' }], memoryExplanation: 'A count and a proportion answer different questions about settlement change.', misconceptionCause: 'Everyday language often uses urban growth and urbanisation interchangeably.' }],
  ['Challenge: evaluate an urban redevelopment proposal', 'Compare benefits, displacement risks and evidence from different affected groups.',
   'Redevelopment may improve housing, transport or flood protection while raising costs or displacing residents and businesses. Benefits are not necessarily shared equally. Evaluate who gains, who bears costs, what alternatives exist and how affected people participate. A consultation is not representative simply because many responses arrive; timing, language, access and housing tenure can influence who is heard.',
   'A hypothetical riverfront plan adds flood defences and new homes but removes low-cost rental housing.', ['Identify the safety and housing benefits claimed.', 'Ask whether existing residents can afford or access the replacement homes.', 'Compare an alternative that retains affordable homes and examine evidence from those at risk of displacement.'], 'Whose benefit, whose cost, whose voice?', 'Treating a higher total housing count as proof that every resident benefits.', 'Examine affordability, access, tenure and displacement alongside totals.', 'What is displacement in this planning context?', 'People or activities being forced or priced out of their existing location.',
   'Suggest two improvements to a consultation that only accepts online comments during working hours.', 'Offer accessible offline and out-of-hours ways to respond, and actively reach groups likely to be missed, including renters and people needing translation. Record whose views are represented rather than equating response volume with representativeness.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What is a stakeholder?', answer: 'A person or group affected by, or with an interest in, a decision.' }], memoryExplanation: 'Distribution and participation determine whether an aggregate improvement is inclusive.', misconceptionCause: 'Headline investment or housing numbers can conceal unequal effects.' }]
 ]]
]];
