import type { Subject, ActivityDetail } from '../authoredActivities';
const detail = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({
 isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 20 : 15,
 priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause,
 revision: 'Tomorrow, explain the performance decision without notes. In a week, apply it to a short new passage and evaluate a recording or written plan against the intended audience effect.'
});
export const year8Performance: Subject[] = [
['music', [
 ['Triads and harmonic direction', [
  ['Build primary triads in C major', 'Construct I, IV and V from alternate scale notes.',
   'A triad contains three notes built from a root, third and fifth. In C major, the tonic triad I is C–E–G, the subdominant IV is F–A–C and the dominant V is G–B–D. Roman numerals identify the root’s scale degree, not the number of notes in the chord. These three chords can support many simple harmonic patterns, but they are not the only possible chords in a key.',
   'Build the dominant triad in C major.', ['Locate the fifth scale degree, G.', 'Take alternate scale notes G, B and D.', 'Identify the resulting chord as V in C major.'], 'Choose a scale-degree root, then stack alternate notes.', 'Thinking V means a chord with five notes.', 'Read the numeral as the root’s place in the scale.', 'Which notes form chord IV in C major?', 'F, A and C.',
   'Identify C–E–G and G–B–D using Roman numerals in C major.', 'C–E–G is I and G–B–D is V. Their roots are the first and fifth scale degrees; both are three-note triads.',
   detail(false, 'What are the notes of C major?', 'C, D, E, F, G, A and B before returning to C.', 'A scale-degree numeral can be mistaken for the size of the chord.')],
  ['Challenge: compare a resting and an unfinished cadence', 'Explain the different sense of arrival in V–I and a phrase ending on V.',
   'A cadence is a harmonic gesture marking a phrase ending. In a simple tonal context, V–I can provide a strong sense of return to the tonic, while an ending on V often sounds less settled. Melody, rhythm, voicing and style influence the effect, so the chord symbols alone do not guarantee an identical listener response. Analyse the final movement within the surrounding phrase.',
   'Compare C–F–G–C with C–F–C–G in C major.', ['The first progression ends V–I.', 'The second ends on V rather than the tonic.', 'The first typically offers stronger tonal closure in this simple context.'], 'Hear the ending in its phrase, not as isolated labels.', 'Calling every final chord a complete resolution merely because the music stops.', 'Distinguish physical stopping from harmonic settlement.', 'Which chord is the tonic in C major?', 'C major, or I.',
   'How could rhythm strengthen the arrival on I in the first progression?', 'A longer final duration, a clear metrical arrival or a pause after the tonic can reinforce closure. The choice should be tested in context rather than assumed from the chord name alone.',
   detail(true, 'What is a musical phrase?', 'A coherent musical unit comparable to a short idea or sentence.', 'The end of playback may be confused with the harmonic feeling of completion.')]
 ]],
 ['Compound metre and rhythm', [
  ['Group six-eight into two dotted beats', 'Distinguish note count from the usual beat grouping in compound duple metre.',
   'In ordinary 6/8 metre, a bar contains six quaver units commonly grouped as two dotted-crotchet beats, each divided into three. Count ONE-two-three FOUR-five-six to feel the two groups. This differs from treating all six quavers as equally strong beats. Tempo and musical context affect the practical way performers count, but the grouping remains central to interpreting the metre.',
   'Mark the main accents in six evenly spaced quavers in 6/8.', ['Group quavers 1–3 together.', 'Group quavers 4–6 together.', 'Place the main beat accents on 1 and 4.'], 'Six quavers, usually two groups of three.', 'Assuming the top number always states the number of main beats.', 'Distinguish notated units from the larger beat grouping.', 'How many quavers fit in one dotted crotchet?', 'Three.',
   'How many dotted-crotchet beats normally fill one 6/8 bar?', 'Two: each lasts three quavers, giving six quavers in total.',
   detail(false, 'How many quavers equal one crotchet?', 'Two.', 'Simple-time rules may be transferred unchanged to compound metre.')],
  ['Challenge: compare three-four with six-eight', 'Explain why equal total note value does not imply equal metre.',
   'A bar of 3/4 and a bar of 6/8 can each contain six quavers, but their usual grouping differs. In 3/4, three crotchet beats divide into pairs; in 6/8, two dotted-crotchet beats divide into threes. Accent and accompaniment can make that distinction audible. A deliberate regrouping may create tension, but first establish the underlying metre before describing the effect.',
   'Compare accents on quavers 1, 3, 5 with accents on 1 and 4.', ['The first pattern groups six quavers into three pairs.', 'The second groups them into two threes.', 'These suggest ordinary 3/4 and 6/8 respectively, despite equal total quaver count.'], 'Same total duration, different internal organisation.', 'Identifying metre solely by counting notes in a bar.', 'Listen for beat hierarchy and subdivision.', 'Which metre normally has three crotchet beats?', '3/4.',
   'Write counting patterns that make each grouping clear.', 'For 3/4 use ONE-and TWO-and THREE-and. For 6/8 use ONE-two-three TWO-two-three. The stressed counts reveal three divided beats versus two triply divided beats.',
   detail(true, 'What is an accent in rhythm?', 'Emphasis on a particular note or beat.', 'Equal arithmetic duration can conceal different patterns of perceived stress.')]
 ]],
 ['Motif development and arrangement', [
  ['Sequence a melodic motif', 'Repeat a short pitch pattern from a different starting note.',
   'A motif is a short recognisable musical idea. A melodic sequence repeats its pattern at another pitch level, rather than simply repeating exactly the same notes. A diatonic sequence follows notes of the key and may alter exact semitone distances while preserving the general pattern of scale steps. Identify what stays recognisable and what changes; not every new phrase is a sequence.',
   'Sequence C–D–E one scale step higher in C major.', ['Keep the upward stepwise shape.', 'Begin on D instead of C.', 'The diatonic sequence is D–E–F.'], 'Same pattern, new starting level.', 'Repeating C–D–E unchanged and calling that a pitch sequence.', 'Move the starting note while preserving the chosen pattern.', 'Does a diatonic sequence have to preserve every exact semitone interval?', 'No.',
   'Continue the same diatonic pattern starting on E.', 'E–F–G. It keeps the three ascending scale notes while the semitone pattern follows C major rather than exact chromatic transposition.',
   detail(false, 'What does stepwise motion mean?', 'Moving to adjacent notes in the scale.', 'General melodic shape and exact interval size can be confused.')],
  ['Challenge: arrange without obscuring the motif', 'Select texture and register to maintain a clear musical hierarchy.',
   'An arrangement redistributes musical roles across voices or instruments. If every part occupies the melody’s register with equally busy rhythms, the motif may become difficult to hear. Reduce competing activity, separate registers or use timbral contrast to clarify the intended lead. This is not a rule that accompaniment must always be quiet or simple; it is a choice tied to the passage’s purpose.',
   'An accompaniment repeatedly masks a short lead phrase.', ['Identify overlapping register and rhythmic activity.', 'Try a lower, more sustained accompaniment or reduced density.', 'Compare whether the motif becomes clearer while the intended harmonic support remains.'], 'Give important material room to be heard.', 'Adding more parts whenever an arrangement lacks impact.', 'Check the role and audibility of each part before increasing density.', 'What is register?', 'The pitch region in which a part sounds.',
   'Describe an evidence-based way to compare two arrangements.', 'Make comparable recordings or playback versions and ask listeners to identify or sing back the motif. Combine their responses with score-based observations about register and density, noting that listener familiarity affects the result.',
   detail(true, 'What is accompaniment?', 'Musical material supporting or interacting with a principal part.', 'Complexity and fullness may be mistaken for clarity or expressive effectiveness.')]
 ]]
]],
['drama', [
 ['Status and changing relationships', [
  ['Communicate status through behaviour', 'Use interacting performance choices rather than one stereotyped posture.',
   'Dramatic status concerns relative power or authority in an interaction and can differ from social rank. A character with a formal title may lose control of a conversation. Turn-taking, eye contact, stillness, pace and access to space can communicate relationships, but no single gesture always means the same thing. Establish the scene’s context and test how combinations of choices are read.',
   'Show a manager losing control of a meeting without changing costume.', ['Begin with the manager controlling turns and agenda.', 'Let another character interrupt and redirect attention.', 'Adjust the manager’s responses to reveal the loss of conversational authority.'], 'Status exists between characters, not only inside a pose.', 'Assuming the highest-ranking job always has the highest status in every moment.', 'Track who controls the immediate interaction.', 'Can status change within one scene?', 'Yes.',
   'Suggest two observable signs of a status shift without shouting.', 'One character may begin allocating speaking turns while another waits for permission; a previously dominant character may yield space or seek approval. Meaning depends on how the choices work together in context.',
   detail(false, 'What is proxemics?', 'The use of distance and spatial relationships in performance.', 'Social titles and dramatic interactional power can be treated as identical.')],
  ['Challenge: stage a reversible status shift', 'Build a turning point whose cause is legible to an audience.',
   'A convincing status reversal needs a cause that changes what characters can do: new information, a discovered dependency or a refusal can alter the balance. A sudden posture change alone may look arbitrary. Establish the original relationship, reveal the turning-point action and show changed responses. Ask observers to identify when and why power shifted without being told the intended answer.',
   'A confident customer discovers the assistant controls access to an essential booking.', ['Establish the customer making demands.', 'Reveal the assistant’s relevant knowledge or authority.', 'Show the customer changing tactics in response rather than merely changing volume.'], 'Cause, turning point, changed behaviour.', 'Making a reversal visible but giving it no dramatic reason.', 'Tie the behavioural change to new stakes or information.', 'Why seek an audience’s account of the turning point?', 'It tests whether the cause and shift are communicated clearly.',
   'How could the assistant avoid becoming a one-note caricature after gaining power?', 'Give the assistant a specific objective, such as resolving the booking fairly, and retain constraints or uncertainty. Power can alter the interaction without erasing the character’s other motivations.',
   detail(true, 'What is a character objective?', 'What the character is trying to achieve in the scene.', 'A visible contrast can substitute for a motivated change in action.')]
 ]],
 ['Narration and audience knowledge', [
  ['Use narration to frame an action', 'Separate information supplied by a narrator from what characters know.',
   'Narration can provide context, compress time or comment on staged events. A narrator’s account may align with, question or contradict the visible action. Decide whether the narrator is a character, an external voice or an ensemble role, and whether characters can hear the narration. Without a consistent convention, the audience may struggle to distinguish dramatic information from accidental confusion.',
   'A narrator reveals that a cheerful farewell is the characters’ last meeting.', ['The visible action can remain cheerful.', 'The audience receives knowledge not necessarily available to the characters.', 'The contrast can create sadness or anticipation without changing the characters’ immediate behaviour.'], 'Audience knowledge and character knowledge can differ.', 'Making characters respond to narration they are not meant to hear.', 'Agree the convention and maintain it consistently.', 'Can narration reveal a later event before characters experience it?', 'Yes.',
   'Explain one advantage and one risk of using narration to compress a long journey.', 'It can establish changes in time or location efficiently, but may replace playable action with explanation if overused. Select which moments need to be shown rather than narrated.',
   detail(false, 'What is a narrator?', 'A voice or role that tells or frames events for an audience.', 'Information heard by the audience can be mistakenly treated as available to every character.')],
  ['Challenge: create an unreliable account responsibly', 'Make a gap between narration and action interpretable rather than arbitrary.',
   'An unreliable narrator presents an account the audience has reason to question. The unreliability may arise from limited knowledge, self-interest or faulty memory; it need not mean every statement is false. Provide specific clues through contradictions, omissions or other perspectives. The audience needs enough evidence to construct an alternative interpretation, otherwise the device may feel like a random trick.',
   'A narrator claims to have remained calm while a replay shows repeated interruptions.', ['State the narrator’s self-description.', 'Stage observable behaviour that complicates it.', 'Allow the audience to infer a gap between self-image and conduct without explaining every clue.'], 'Give evidence for doubt, not only a surprise label.', 'Revealing unreliability with no earlier clue that permits reinterpretation.', 'Plant relevant discrepancies and test whether viewers can identify them.', 'Must an unreliable narrator deliberately lie?', 'No.',
   'How might two versions of the same event show limited perspective rather than one evil character?', 'Each version can include details its teller noticed and omit events outside their view. The contrast then shows partial knowledge, leaving the audience to compare evidence rather than simply label one teller malicious.',
   detail(true, 'What is a perspective?', 'A position or viewpoint from which events are understood.', 'Unreliability is sometimes reduced to dishonesty instead of including limitations of knowledge.')]
 ]],
 ['Devising with structure and feedback', [
  ['Shape tension through delayed resolution', 'Build a sequence of obstacles instead of holding a scene at one emotional level.',
   'Dramatic tension can grow when a clear objective meets an obstacle and the outcome remains uncertain. Delaying an answer works only if the audience understands what is at stake and what might change. Repetition without new pressure may slow a scene without increasing tension. Plan beats in which information, tactics or consequences develop, then decide where release is useful.',
   'Devise a scene about finding a missing permission form before departure.', ['Establish why the form matters and the time constraint.', 'Introduce an obstacle that changes the search or available options.', 'Make the final discovery or failure resolve a question the audience has followed.'], 'Each delay should change the pressure.', 'Making a scene longer and assuming it is automatically more suspenseful.', 'Add meaningful developments rather than repeated versions of the same obstacle.', 'What gives an audience a reason to care about an outcome?', 'Understandable stakes and investment in the characters or situation.',
   'Suggest a new beat that changes the problem rather than repeating the search.', 'A character might reveal they placed the form elsewhere but cannot access that place before departure. This changes the available strategy and creates a decision rather than another identical search.',
   detail(false, 'What is an obstacle in drama?', 'Something that prevents or complicates a character achieving an objective.', 'Duration can be mistaken for dramatic development.')],
  ['Challenge: turn feedback into a controlled rehearsal revision', 'Separate observation, interpretation and a testable performance change.',
   'Useful feedback distinguishes what a viewer observed from what they inferred. “I could not tell why she left after the letter” identifies a communication problem more precisely than “it was boring”. Propose a change, predict its effect and rehearse again while keeping other choices stable enough to compare. A revision is not automatically better because it follows the loudest observer’s preference.',
   'Viewers miss the connection between a letter and a character’s departure.', ['Record the observed confusion without blaming the audience.', 'Try a clearer reading reaction and a purposeful transition to the exit.', 'Ask fresh viewers what caused the departure and compare their interpretations.'], 'Observation, hypothesis, revision, evidence.', 'Changing every aspect after one vague comment.', 'Target the intended communication problem and evaluate the result.', 'Why distinguish observation from interpretation?', 'The same visible action can support different readings, so the distinction clarifies what needs testing.',
   'What should be recorded after the revised rehearsal?', 'Record the specific change, the viewers’ account of the cause and any new unintended effects. This creates evidence for retaining, adjusting or rejecting the revision.',
   detail(true, 'What is a rehearsal?', 'A process of practising and developing performance choices.', 'Feedback can be treated as an instruction to obey rather than evidence to investigate.')]
 ]]
]]
];
