import type { Subject } from '../authoredActivities';
export const year6Core: Subject[] = [
['maths', [
 ['Ratio and percentage reasoning', [
  ['Share in a ratio', 'Divide a total into unequal parts using a unit share.',
   'A ratio of two to three describes relative parts, not a fraction of two thirds for the first share. There are five parts altogether. Divide the total by five to find one part, then multiply by the required number of parts. Check both that the shares add to the total and that their ratio matches the original.',
   'Share £40 in the ratio 2:3.', ['Count 2 + 3 = 5 equal parts.', 'One part is £40 ÷ 5 = £8.', 'The shares are £16 and £24; they total £40.'], 'Add the parts before sharing the whole.', 'Dividing forty by three because three is the larger ratio number.', 'The total corresponds to all five parts, not just one person’s three parts.',
   'In the ratio 2:3, what fraction of the whole is the first share?', '2/5.', 'Share 72 counters in the ratio 5:3, then check the answer.', '45 and 27. Eight parts give nine counters per part; 45 + 27 = 72 and both shares reduce to the ratio 5:3.'],
  ['Find a percentage through useful parts', 'Calculate non-trivial percentages by combining known fractions of a quantity.',
   'Percent means out of one hundred. Ten percent is one tenth and one percent is one hundredth of a quantity. To find fifteen percent, combine ten percent with five percent, which is half of ten percent. State the base quantity clearly: a percentage is a proportion of a particular whole, not an isolated amount.',
   'Find 15% of £80.', ['10% of £80 is £8.', '5% is half of that: £4.', '15% is £8 + £4 = £12.'], 'Build the percentage from easy pieces.', 'Subtracting fifteen pounds for a fifteen-percent discount on any price.', 'Find fifteen percent of the actual original price first.',
   'What fraction is 25%?', 'One quarter.', 'A £60 item has a 20% reduction. Find the reduction and sale price.', 'The reduction is £12 because 10% is £6 and 20% is £12. The sale price is £48, not £12.']
 ]],
 ['Algebra and multistep fractions', [
  ['Solve a two-step equation', 'Undo operations in reverse order while preserving equality.',
   'An equation states that two expressions have equal value. In 3x + 4 = 19, x is multiplied by three and then four is added. Undo the addition before the multiplication: subtract four from both sides, then divide both sides by three. Check the result in the original equation rather than only trusting the procedure.',
   'Solve 3x + 4 = 19.', ['Subtract 4 from both sides: 3x = 15.', 'Divide both sides by 3: x = 5.', 'Check 3 × 5 + 4 = 19.'], 'Undo the last operation first.', 'Dividing only one term of a sum and changing the equation incorrectly.', 'Apply each inverse operation consistently to both sides.',
   'What inverse operation undoes multiplication by three?', 'Division by three.', 'Solve 4y − 7 = 25, then verify.', 'Add seven to get 4y = 32; divide by four to get y = 8. Check: 4 × 8 − 7 = 25.'],
  ['Divide a fraction by a whole number', 'Explain division as sharing a fractional quantity equally.',
   'Dividing three quarters by two means sharing three quarters between two equal groups. Split each quarter into two eighths; the original quantity becomes six eighths. Each group receives three eighths. The result must be smaller than three quarters because it is one of two equal shares. A diagram explains why the denominator increases in this example.',
   'Calculate 3/4 ÷ 2.', ['Rename three quarters as six eighths.', 'Share the six eighths equally between two groups.', 'Each receives three eighths, so the result is 3/8.'], 'Share the amount, not just the written digits.', 'Dividing the denominator by two and obtaining a larger answer.', 'Check that sharing between more people reduces each share.',
   'Should dividing a positive fraction by three make it larger?', 'No; each of three equal shares is smaller.', 'Calculate 2/3 ÷ 4, then check by multiplying the answer by four.', '1/6. Two thirds equals eight twelfths; each share is two twelfths. Four times one sixth is four sixths, or two thirds.']
 ]]
]],
['english-lang', [
 ['Voice and formality', [
  ['Choose active or passive voice deliberately', 'Explain how sentence voice changes emphasis without necessarily changing the event.',
   'In the active voice, the subject performs the action: “The storm damaged the roof.” In the passive, the subject receives it: “The roof was damaged by the storm.” The passive can foreground an affected thing or omit an unknown agent. It is not automatically more sophisticated; choose the form that suits purpose and clarity.',
   'Rewrite “The caretaker repaired the gate” with the gate as subject.', ['Make the gate the subject.', 'Use was repaired to form the passive.', 'Write “The gate was repaired by the caretaker.”'], 'Who acts, and what receives the action?', 'Calling every sentence with was passive.', 'Check whether the subject receives an action; “The gate was blue” is not passive.',
   'Is “The dog was tired” necessarily passive?', 'No; it describes a state.', 'Why might a report say “The window was broken” without naming an agent?', 'The agent may be unknown or unimportant to the report’s focus, though omission can also conceal responsibility and should be considered critically.'],
  ['Adjust register for audience', 'Select vocabulary and sentence choices appropriate to a formal purpose.',
   'Register is the style of language suited to a context. A formal request may use precise wording, a courteous tone and complete explanations, while a message to a friend can be more conversational. Formality is not the same as using the longest possible words. The best choice communicates the purpose clearly without sounding hostile or unnecessarily elaborate.',
   'Turn “Send me the stuff now” into a formal request for a document.', ['Identify the exact item rather than stuff.', 'Use a courteous request form.', 'Write “Could you please send the completed report by Friday?”'], 'Precise, courteous, purposeful.', 'Replacing simple words with obscure synonyms that reduce clarity.', 'Choose the clearest wording suitable for the audience.',
   'Does formal writing have to be unfriendly?', 'No.', 'Explain why “Please send it soon” may still need revision in a formal request.', 'It leaves the item and deadline unclear; naming the document and date makes the request actionable.']
 ]],
 ['Punctuation and argument structure', [
  ['Link related clauses with a semicolon', 'Use a semicolon only where complete closely related clauses support it.',
   'A semicolon can link two closely related independent clauses: “The path was flooded; we took the higher route.” Each side could stand as a sentence. A colon can introduce an explanation or elaboration when the preceding text sets it up. Neither mark should be inserted merely because a sentence looks long.',
   'Join “The evidence was incomplete” and “we delayed the decision”.', ['Check that both clauses make complete statements.', 'Confirm the close logical connection.', 'Write “The evidence was incomplete; we delayed the decision.”'], 'Complete clause on each side.', 'Putting a semicolon between a verb and its object.', 'Check that each side can stand independently in the intended use.',
   'Could “Because it rained” stand alone as an independent clause here?', 'No.', 'Choose suitable punctuation: “We needed three items a map, a torch and water.”', '“We needed three items: a map, a torch and water.” The colon introduces the specified list after a complete introductory clause.'],
  ['Address a counterargument fairly', 'Present an opposing concern accurately before responding with reasons.',
   'A persuasive argument becomes more credible when it recognises a genuine objection. State the concern in terms its supporters would accept, then answer it with relevant evidence or a qualified proposal. Distorting the other view into something foolish is not a strong rebuttal. Sometimes the objection justifies revising the proposal rather than dismissing it.',
   'Respond to a concern that a new school garden will require maintenance.', ['Acknowledge that regular care takes time and resources.', 'Propose a realistic rota and budget rather than denying the work.', 'Explain how the plan addresses the concern and what still needs checking.'], 'Represent fairly, respond specifically.', 'Answering an objection nobody actually made.', 'Identify the strongest relevant concern before composing the response.',
   'Must a counterargument always be completely rejected?', 'No; it may justify qualification or revision.', 'Why is “Only lazy people oppose it” a weak response?', 'It attacks people rather than addressing the maintenance evidence or practical concern.']
 ]]
]],
['english-lit', [
 ['Interpretation and structural choices', [
  ['Weigh competing interpretations', 'Compare how well different readings account for the same evidence.',
   'A character who refuses a gift might be proud, suspicious or protecting someone else. Interpretations should be tested against details, not treated as equally strong merely because they are possible. Consider what each explains and what it struggles to explain. A careful response can prefer one reading while acknowledging uncertainty.',
   'A character refuses a gift, then secretly buys the giver food.', ['Refusal alone might suggest pride or distrust.', 'The later act of care complicates a purely hostile reading.', 'A concern about obligation or the giver’s needs may fit more of the evidence.'], 'Best fit across the details.', 'Selecting a reading from one line and ignoring conflicting evidence.', 'Compare the reading against later actions as well as the initial clue.',
   'Can new evidence change a reasonable interpretation?', 'Yes.', 'What makes “perhaps the character avoids obligation” stronger than a bare guess?', 'It must be linked to specific actions, language or context that show discomfort about owing something.'],
  ['Explain an unresolved ending', 'Analyse what a text leaves uncertain and why that may matter.',
   'An ending can resolve the main action while leaving a relationship or moral question open. This is different from simply missing necessary information by accident. Identify what is settled, what remains uncertain and how the final image or line directs attention to that uncertainty. Avoid claiming one authorial intention unless supported by evidence.',
   'A story ends with a returned letter left unopened.', ['The letter has reached its destination, resolving delivery.', 'Its contents or the recipient’s response remain unknown.', 'The unopened letter may keep reconciliation or conflict unresolved for the reader.'], 'Resolved action, unresolved question.', 'Saying the ending is incomplete without identifying what remains open.', 'Separate the completed plot event from the continuing interpretive question.',
   'Must every effective ending explain every character’s future?', 'No.', 'How could opening the letter and explaining its contents change the ending?', 'It would remove some uncertainty and direct the reader towards a more explicit resolution, potentially reducing ambiguity.']
 ]],
 ['Comparison and language evaluation', [
  ['Compare viewpoints on the same event', 'Explain how selection of detail shapes different accounts.',
   'Two narrators can describe the same crowded market as lively or overwhelming by selecting different details. One may foreground music and bright stalls, while another emphasises noise and difficulty moving. Compare the chosen evidence, vocabulary and focus before deciding whether the accounts contradict each other factually. Different impressions can coexist.',
   'Compare “voices rose like music” with “voices battered the narrow street”.', ['Both describe many voices.', 'Music suggests harmony or pleasure; battered suggests force and discomfort.', 'The language directs readers towards contrasting experiences of the same sound.'], 'Same event, selected lens.', 'Treating different emotional impressions as proof that one account is factually false.', 'Separate factual claims from evaluative language.',
   'What shared feature appears in both example descriptions?', 'The sound of many voices.', 'What further evidence would help explain the narrators’ different reactions?', 'Their purposes, previous experiences or situation in the scene could explain why the same environment feels welcoming to one and stressful to another.'],
  ['Evaluate an image in its context', 'Explain how an image’s effect depends on its position and surrounding ideas.',
   'A repeated image can change meaning across a text. A locked gate might first suggest safety and later imprisonment. Examine its context at each appearance rather than assigning one permanent symbolic meaning. An evaluation explains why the image is effective or limited for the particular passage, supported by its details and placement.',
   'A garden wall shelters a child early in a story but blocks escape later.', ['Explain the early protective context.', 'Identify the later danger and blocked movement.', 'The same feature develops from shelter into confinement, complicating the idea of safety.'], 'Track the image as the story changes.', 'Assuming an object always has one universal symbolic meaning.', 'Use the local context and changes across the text.',
   'Can a repeated image develop rather than merely repeat an idea?', 'Yes.', 'Why might a writer return to an opening image at the end?', 'The return can invite comparison and reveal changed circumstances, attitudes or meaning.']
 ]]
]],
['science-combined', [
 ['Circulation and scientific enquiry', [
  ['Trace a simplified circulation route', 'Explain how the heart, lungs and body are connected by blood flow.',
   'The heart pumps blood in a double circulation: one route travels to the lungs and back, and another travels to the rest of the body and back. At the lungs, blood gains oxygen and releases carbon dioxide. Body cells use oxygen in respiration and produce carbon dioxide. Blood does not simply disappear when oxygen has been delivered.',
   'Trace blood from the heart through the lungs and then the body.', ['Heart to lungs: gas exchange occurs.', 'Blood returns to the heart and is pumped to body tissues.', 'It returns again carrying less oxygen and more carbon dioxide than after leaving the lungs.'], 'Two linked circuits, one circulating supply.', 'Saying the heart adds oxygen directly to blood.', 'The lungs provide the gas-exchange surface; the heart supplies the pumping action.',
   'Where does blood normally gain oxygen from inhaled air?', 'At the lungs.', 'Why must blood return to the heart after visiting body tissues?', 'It continues the circulation so carbon dioxide can be removed at the lungs and oxygenated blood can be delivered again.'],
  ['Interpret pulse measurements cautiously', 'Distinguish an observed pattern from a fully established causal claim.',
   'Pulse rate often rises during physical activity because the body’s demands change. A fair classroom comparison needs safe activity, consistent measuring intervals and repeated observations where appropriate. Learners should not compare health or worth from pulse values. Stress, temperature, measurement error and individual differences can also affect results, so one reading cannot diagnose fitness.',
   'A learner counts a higher pulse after a suitable activity.', ['Check that both measurements used the same time interval.', 'Describe the observed increase for this learner and task.', 'Avoid diagnosing health or claiming the same numerical increase for everyone.'], 'Measure consistently; interpret modestly.', 'Treating one high reading as proof that someone is unfit.', 'Consider context and leave health assessment to appropriate professionals.',
   'Why repeat a measurement?', 'To check consistency and reduce reliance on a single possibly mistaken reading.', 'What should happen if someone feels unwell during the activity?', 'Stop safely and inform the supervising adult; data collection never takes priority over wellbeing.']
 ]],
 ['Inheritance and electrical reasoning', [
  ['Separate inherited variation from acquired change', 'Explain that offspring resemble parents without being exact copies.',
   'Offspring inherit genetic information from their biological parents, but they are not usually identical copies. Features also develop through environmental influences and experience. A scar is an acquired change and is not passed on as a scar through inherited information. Avoid inferring a person’s family relationships or health from classroom comparisons of visible traits.',
   'Compare a plant’s inherited leaf characteristics with damage from an insect.', ['Leaf features can reflect inherited information and growing conditions.', 'A bite hole results from an event affecting this leaf.', 'The bite itself is not an inherited instruction to offspring.'], 'A changed body is not automatically a changed inheritance.', 'Assuming every feature acquired during life is directly inherited by offspring.', 'Distinguish inherited information from events and environmental effects.',
   'Are siblings usually genetically identical?', 'No, with special cases such as identical twins.', 'Why might genetically similar plants grow to different heights?', 'Differences in light, water, nutrients, damage or other conditions can affect growth.'],
  ['Explain circuit changes with controlled comparisons', 'Predict effects of changing a simple low-voltage series circuit while recognising limits.',
   'For suitable identical lamps in a simple series circuit, adding another lamp usually makes each dimmer with the same cell supply. Increasing the supply voltage within component ratings can make a lamp brighter, but excessive voltage can damage it. Test only approved classroom circuits with adult supervision. Change one feature at a time and do not connect directly across cell terminals.',
   'Compare one lamp and two identical series lamps using the same cells.', ['Keep the cell supply and connecting materials the same.', 'Add the second identical lamp in the single path.', 'Observe that each lamp is typically dimmer and record the actual result.'], 'Same supply, changed circuit demand.', 'Claiming brightness depends only on the number of wires.', 'Consider the components, connections and supply together.',
   'Why must component voltage ratings be respected?', 'Too much voltage can overheat or damage components.', 'Why would changing cells and adding a lamp at the same time weaken the comparison?', 'Two factors changed, so the observed brightness difference cannot be attributed confidently to just one.']
 ]]
]],
['history', [
 ['Industrial change', [
  ['Explain interacting causes of industrial growth', 'Connect resources, technology, labour and transport without reducing change to one cause.',
   'Industrial growth in Britain involved interacting changes in production, energy, transport, finance and labour. Coal supplied energy; machinery changed output; transport helped move materials and goods. These developments varied across regions and industries. A causal explanation shows how factors reinforced one another, rather than listing inventions as though each transformed every community instantly.',
   'Explain a link between coal and transport improvements.', ['Factories and other users needed substantial fuel supplies.', 'Canals and later railways could move heavy loads more efficiently on suitable routes.', 'Improved transport could support production, while growing industry increased demand for transport.'], 'Causes can reinforce one another.', 'Attributing industrialisation to one inventor alone.', 'Connect several factors and specify the industry or region being discussed.',
   'Why did moving heavy materials matter to industry?', 'Production depended on obtaining fuel and raw materials and distributing goods.', 'Why should a national statement be checked against local evidence?', 'The pace and form of change differed between places; one region’s experience may not represent all communities.'],
  ['Compare experiences of factory work', 'Use evidence to recognise different interests and living conditions.',
   'Factory owners, adult workers and working children could experience industrial change differently. Increased production or profit did not guarantee safe conditions or equal benefit. Testimony, inspection reports and employment records answer different questions. Consider who produced a source, why and what it can reveal about particular conditions rather than assuming all factories were identical.',
   'Compare an owner’s advertisement with an inspector’s report.', ['The advertisement may emphasise investment or commercial success.', 'The report may document conditions against an inspection purpose.', 'Use each for relevant questions and compare claims rather than rejecting one solely by its author.'], 'Different positions reveal different evidence.', 'Calling a source useless simply because its author has an interest.', 'An interested source can still reveal valuable facts and perspectives when read critically.',
   'Does increased output prove workers’ conditions improved?', 'No.', 'What evidence could help investigate working hours?', 'Dated employment records, testimony and inspection material can provide information, with attention to scope and reliability.']
 ]],
 ['War, civilians and interpretation', [
  ['Explain evacuation as a response to risk', 'Distinguish a policy’s purpose from varied personal outcomes.',
   'During the Second World War, evacuation moved many children and other vulnerable civilians away from areas thought at risk of bombing. The policy aimed to reduce danger, but experiences varied with placement, separation and local circumstances. A positive or distressing memoir should not be treated as the experience of every evacuee.',
   'Why can two evacuees remember the policy differently?', ['They shared a broad policy context.', 'Their host households, ages and experiences could differ.', 'Their accounts can both be valuable without supporting one universal judgement.'], 'Shared policy, varied lives.', 'Using one memoir to claim all evacuation was happy or harmful.', 'Compare multiple experiences and distinguish intention from outcome.',
   'What danger was wartime evacuation intended partly to reduce?', 'Exposure to bombing in higher-risk areas.', 'Why might a later memoir need comparison with contemporary records?', 'Memory and later interpretation can shape the account, while contemporary records may clarify dates and circumstances.'],
  ['Evaluate why interpretations change', 'Explain how new evidence and new questions can alter historical accounts.',
   'Historical interpretations are argued accounts based on evidence. They can change when new sources emerge, when neglected groups are studied or when historians ask different questions. Change does not mean any version is equally justified. Compare the evidence, methods and scope of each interpretation rather than deciding solely from which account was written most recently.',
   'A later local history includes women’s work omitted from an earlier account.', ['Identify the earlier account’s limited focus.', 'Examine the new sources about women’s employment or unpaid work.', 'Explain how broader evidence changes the picture of the community.'], 'New evidence or a wider question can change the account.', 'Assuming the newest interpretation must always be correct.', 'Evaluate its evidence and reasoning as well as its date.',
   'Is an interpretation the same as an unsupported opinion?', 'No; it should be argued from evidence.', 'What would make a revised interpretation stronger?', 'Relevant additional evidence, transparent reasoning and fair engagement with evidence that challenges the claim.']
 ]]
]]
];
