import type { Subject, ActivityDetail } from '../authoredActivities';
const core: ActivityDetail = { isPremium: false, difficulty: 'Core', estimatedMinutes: 15, revision: 'Tomorrow, rebuild the model sentence and identify its subject and time frame. In a week, change one element and explain the new form rather than only translating it.' };
const challenge: ActivityDetail = { ...core, isPremium: true, difficulty: 'Higher', estimatedMinutes: 20 };
export const year8Spanish: Subject = ['spanish', [
 ['Completed past actions', [
  ['Form regular -ar preterites', 'Use the preterite for a completed event in a bounded past context.',
   'For regular -ar verbs in the preterite, remove -ar and add -é, -aste, -ó, -amos, -asteis or -aron. Ayer canté means yesterday I sang; ayer cantó means yesterday he, she or formal you sang. Written accents distinguish forms and stress. Cantamos can be present or preterite, so context matters. These endings do not apply unchanged to every irregular verb.',
   'Translate “Yesterday she sang” using cantar.', ['Identify the third-person singular subject.', 'Add -ó to cant-.', 'Write Ayer ella cantó, retaining the accent.'], 'Person, past ending, accent.', 'Treating canto and cantó as the same written form.', 'Check the accent because canto is present first person while cantó is past third person.', 'What is the yo preterite of cantar?', 'Canté.',
   'Translate “Yesterday we visited a museum” using visitar un museo.', 'Ayer visitamos un museo. Visitamos has the same form in present and preterite, but ayer establishes the past event here.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What does ayer mean?', answer: 'Yesterday.' }], memoryExplanation: 'The accent is part of the grammatical information, not optional decoration.', misconceptionCause: 'Some present and past forms look similar or identical, inviting reliance on spelling alone.' }],
  ['Challenge: interpret the shared preterites of ir and ser', 'Use the whole clause to decide whether fue describes going or being.',
   'Ir and ser share preterite forms: fui, fuiste, fue, fuimos, fuisteis, fueron. Context determines meaning. Fue al museo means he, she or formal you went to the museum; la visita fue interesante means the visit was interesting. Do not assign one English translation to fue in isolation. Destination phrases and descriptive complements provide important clues.',
   'Interpret Fuimos al museo y la visita fue interesante.', ['Al museo supplies a destination, so fuimos means we went.', 'La visita is the subject of the second clause.', 'Interesante describes the visit, so fue means was.'], 'Same form; the clause supplies the meaning.', 'Translating every fue as went regardless of its complement.', 'Identify the subject and whether the clause gives a destination or a description.', 'Which two infinitives share these preterite forms?', 'Ir and ser.',
   'Translate “I went to the park. It was interesting” using parque.', 'Fui al parque. Fue interesante. Fui is ir in the destination clause; fue is ser in the evaluative description. The second sentence’s reference depends on the surrounding context.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What do ir and ser usually mean as infinitives?', answer: 'To go and to be.' }], memoryExplanation: 'Grammar is interpreted through the relationships within a clause rather than a one-word dictionary match.', misconceptionCause: 'Learning isolated verb forms may hide homonymous forms with different functions.' }]
 ]],
 ['Likes and the experiencer', [
  ['Match gusta and gustan to what is liked', 'Identify the grammatical subject in a gustar construction.',
   'Me gusta el libro means I like the book, but its Spanish structure is closer to the book pleases me. The thing liked controls the verb: me gustan los libros uses gustan because libros is plural. With an infinitive, use singular gusta, as in me gusta leer. Me identifies the experiencer; it does not make the verb first-person singular.',
   'Compare Me gusta la película and Me gustan las películas.', ['Identify película as singular in the first sentence.', 'Identify películas as plural in the second.', 'Choose gusta or gustan according to that grammatical subject.'], 'What is liked controls gusta or gustan.', 'Writing me gusto los libros to match English I like.', 'Keep me for the experiencer and agree the verb with the thing liked.', 'Which form is used before the infinitive leer?', 'Gusta.',
   'Translate “I like books and I like reading”.', 'Me gustan los libros y me gusta leer. The plural noun libros takes gustan, while the infinitive leer takes gusta.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'How do libro and libros differ?', answer: 'Libro is singular and libros is plural.' }], memoryExplanation: 'Reframing the sentence as something pleases someone exposes its agreement pattern.', misconceptionCause: 'The English subject of like is not the grammatical subject of Spanish gustar.' }],
  ['Challenge: clarify whose preference is described', 'Use le and an explicit experiencer without changing agreement with the liked item.',
   'Le gusta can mean he likes, she likes or formal you like, depending on context. A Sara le gusta leer makes the experiencer explicit; the a phrase does not replace le in this pattern. With several liked objects, agreement still follows those objects: A Sara le gustan los libros. Keep separate questions for who experiences the liking and what controls the verb.',
   'Write “Sara likes films”.', ['Name the experiencer with A Sara.', 'Retain le.', 'Use gustan with plural las películas: A Sara le gustan las películas.'], 'Experiencer and agreement answer different questions.', 'Omitting le after naming Sara, or using gusta because Sara is singular.', 'Retain the pronoun and agree with the liked item.', 'Does le alone always specify a male experiencer?', 'No.',
   'Translate “Sara likes reading, but she does not like these books” using estos libros.', 'A Sara le gusta leer, pero no le gustan estos libros. Leer takes gusta; estos libros takes gustan. Sara remains the experiencer in both clauses.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What controls gusta versus gustan?', answer: 'The grammatical subject: the thing or activity liked.' }], memoryExplanation: 'Two independent checks stop information about the experiencer from interfering with verb agreement.', misconceptionCause: 'The first named person can be mistaken for the agreement-controlling subject.' }]
 ]],
 ['Wanting, ability and obligation', [
  ['Use the stem change in querer', 'Distinguish stem-changing present forms from the unchanged infinitive.',
   'Querer means to want. In the present tense, the stem changes e to ie in quiero, quieres, quiere and quieren, but not in queremos or queréis. A following action remains infinitive: quiero leer, queremos cantar. Stem-changing does not mean every occurrence of the verb receives ie, and a conjugated querer is not followed by another independently conjugated verb in this pattern.',
   'Write “She wants to read” and “We want to read”.', ['Use quiere for she wants.', 'Use queremos for we want, without the stem change.', 'Add leer to both: quiere leer; queremos leer.'], 'Change the stressed stem where required; keep the next action infinitive.', 'Writing quieremos or quiere lee.', 'Check the subject form of querer separately from the following infinitive.', 'What is the nosotros form of querer?', 'Queremos.',
   'Translate “I want to sing, but we want to read”.', 'Quiero cantar, pero queremos leer. Quiero changes e to ie; queremos keeps the ordinary stem. Cantar and leer remain infinitives.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What is the infinitive of “to read”?', answer: 'Leer.' }], memoryExplanation: 'Person and stress patterns matter; stem-changing is not a command to replace every letter e.', misconceptionCause: 'A newly learned irregular pattern can be overgeneralised to all persons.' }],
  ['Challenge: distinguish inability, unwillingness and obligation', 'Choose poder, querer or tener que to preserve a speaker’s intended meaning.',
   'No puedo ir means I cannot go; no quiero ir means I do not want to go; tengo que ir means I have to go. These express different claims about ability or possibility, preference and obligation. A reason can clarify the intended relationship: Quiero ir, pero tengo que estudiar. Retain que after tener in the obligation construction and use an infinitive after each taught expression.',
   'Interpret Quiero jugar, pero no puedo porque tengo que estudiar.', ['Quiero jugar expresses the wish to play.', 'No puedo states that the speaker cannot.', 'Tengo que estudiar gives an obligation to study as the reason.'], 'Can, want and must are not interchangeable.', 'Translating no puedo as I do not want to.', 'Preserve the distinction between constraints and preferences.', 'Which taught phrase expresses I have to?', 'Tengo que.',
   'Write “I do not want to study, but I have to study”.', 'No quiero estudiar, pero tengo que estudiar. The first clause negates a desire, while the second states an obligation; neither says the speaker is unable to study.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What does pero mean?', answer: 'But.' }], memoryExplanation: 'Selecting the modal meaning before translating prevents a fluent sentence from saying the wrong thing.', misconceptionCause: 'English and Spanish multiword expressions can be memorised without distinguishing their communicative functions.' }]
 ]]
]];
