import type { Subject } from '../authoredActivities';
export const year6Practical: Subject[] = [
['art', [
 ['Developing a personal response', [
  ['Transform a source rather than copy it', 'Use observation or research to develop a distinct artistic response.',
   'A source can provide a shape, rhythm, texture or question without dictating the finished artwork. Identify what interests you, then test deliberate changes such as cropping, scale, colour or material. Record the relationship to the source honestly. A personal response is not simply copying an image and changing its title, nor does it require ignoring influences.',
   'Develop an artwork from a photograph of tangled branches.', ['Select the intersecting lines as the main interest.', 'Test a cropped arrangement with enlarged negative spaces.', 'Choose a medium that emphasises those relationships and explain the transformation.'], 'Select, transform, justify.', 'Calling an almost exact copy an entirely original invention.', 'Acknowledge the source and identify the substantive choices you made.',
   'Can using a source coexist with original artistic choices?', 'Yes.', 'What would make two studies of the same source meaningfully different?', 'Different selection, composition, material or interpretation can change what the work communicates, not just its label.'],
  ['Use a sketchbook as evidence of decisions', 'Document experiments and explain why one approach was selected.',
   'A sketchbook can record unsuccessful trials as well as polished studies. Label what changed, what you observed and how it affected the next choice. This makes development visible rather than presenting a finished product as if it appeared without exploration. A decision can be valid even when another artist would choose differently, provided it is connected to an intention.',
   'Compare three ways of suggesting rough stone.', ['Test different marks or materials on small samples.', 'Annotate their visual and practical effects.', 'Choose the sample that supports the intended texture and explain why.'], 'Keep the trial and the reason.', 'Removing every failed experiment and losing the development record.', 'Retain useful evidence of what was tested and learned.',
   'Must every sketchbook page look finished?', 'No.', 'Why is “I chose this because I like it” a limited annotation?', 'It gives a preference but not the visual or practical reason connecting the choice to the work’s intention.']
 ]],
 ['Context and presentation', [
  ['Interpret an artwork in historical context', 'Use contextual knowledge without reducing the image to a biography.',
   'An artwork’s date, intended audience, materials and social setting can inform interpretation. Context should clarify observed features rather than replace looking at the work. An artist’s life event does not prove the meaning of every mark. Distinguish documented information from inference and explain how the evidence changes or supports a reading.',
   'A public mural was commissioned after a local rebuilding project.', ['Examine its visible subjects and arrangement.', 'Check the commission’s date and stated purpose.', 'Connect relevant features with rebuilding while avoiding unsupported claims about every figure.'], 'Context supports looking; it does not replace it.', 'Inferring intention from an unrelated biographical fact.', 'Use context that actually bears on the artwork and the claim.',
   'Is a documented commission purpose the same as every viewer’s response?', 'No.', 'Why might an artwork’s intended location matter?', 'Scale, audience, viewing distance and community context can affect how its forms and messages operate.'],
  ['Plan an exhibition label and display', 'Communicate an artwork’s process and intention without dictating every response.',
   'A display label can name the artist, title, medium and relevant process or intention. It should distinguish facts from interpretation and credit sources where needed. The physical display also matters: lighting, height, spacing and accessibility influence how people encounter the work. Avoid claiming that a viewer must feel one prescribed emotion.',
   'Write a label for a layered paper relief about a local river.', ['Name the medium and source observations.', 'Explain one deliberate choice, such as repeated curved layers.', 'Invite viewers to notice movement without insisting on a single reaction.'], 'Inform the viewer; leave room to look.', 'Using an impressive title to hide an unexplained process.', 'State concrete materials and choices plainly.',
   'Why consider viewing height?', 'It affects access and how details or depth can be seen.', 'What should a label do when the work adapts another artist’s image?', 'Acknowledge the source and explain the adaptation rather than implying the source material was independently invented.']
 ]]
]],
['design-tech', [
 ['Integrated design systems', [
  ['Specify inputs, processes and outputs', 'Describe a product as connected subsystems rather than isolated components.',
   'A controlled model can have an input, such as a button; a process, such as a programmed decision; and an output, such as a low-voltage lamp. The housing and power supply must also support safe use. A system diagram shows how these parts relate. Use approved classroom components and adult supervision rather than adapting mains-powered equipment.',
   'Design a model signal that lights when a button is pressed.', ['Identify the button as input and lamp as output.', 'Specify the intended control rule.', 'Show safe power, connections and housing access in the plan.'], 'Input, rule, output, support.', 'Drawing an attractive case without specifying the control behaviour.', 'Describe what should happen for each relevant input before making.',
   'What is an output in this model?', 'The lamp’s visible signal.', 'Why include the power supply in the design even if it is hidden?', 'It affects safety, operation, space, maintenance and whether the chosen components can work as intended.'],
  ['Test interactions between subsystems', 'Locate a failure that emerges when working components are combined.',
   'A lamp, switch and program can each work separately but fail when assembled if connections, dimensions or control assumptions do not match. Test interfaces as well as individual parts. For example, a case may prevent full button movement. Record whether the fault lies in the component, the connection or the way the user operates the assembled product.',
   'A button works outside the case but not after assembly.', ['Check the safe standalone test result.', 'Observe whether the case obstructs travel or strains a connection.', 'Adjust the interface and repeat the assembled-product test.'], 'Working parts still need working connections.', 'Replacing software before checking a physical obstruction.', 'Use evidence to locate the failing subsystem or interface.',
   'What is an interface in a system?', 'A connection or point of interaction between parts or between a user and a product.', 'Why is testing only separate components insufficient?', 'Assembly can introduce new mechanical, electrical or usability problems that do not appear in isolated tests.']
 ]],
 ['Sustainability and evidence-led evaluation', [
  ['Compare material choices across a product’s life', 'Consider production, use, repair and disposal rather than one isolated property.',
   'A material choice affects more than appearance. Consider how it is produced, how long the product lasts, whether it can be repaired and what happens after use. A recyclable material is not automatically recycled in the available local system. Avoid claiming a product is environmentally best without specifying the evidence and comparison being made.',
   'Compare a disposable organiser with a durable repairable one.', ['Consider resources used to make each.', 'Compare expected useful life and repair options.', 'Discuss realistic end-of-life routes rather than relying only on a recycling symbol.'], 'Make, use, repair, next destination.', 'Choosing only by one favourable environmental label.', 'Consider several life stages and the actual local disposal or repair options.',
   'Does technically recyclable mean certainly recycled?', 'No.', 'Why might using more material sometimes reduce waste over time?', 'If it substantially extends useful life and avoids repeated replacement, total resource use may be lower; this needs evidence about actual use.'],
  ['Make a qualified final recommendation', 'Use criteria and limitations to justify a design decision.',
   'A final evaluation should identify which criteria were met, which were not and what evidence supports each judgement. A recommendation can be qualified: a model may suit indoor use but not rain. Do not generalise beyond the tested conditions. Suggest the next most informative test or improvement rather than hiding limitations behind a total score.',
   'A container passes carrying tests but has not been tested in wet conditions.', ['Report the successful carrying evidence.', 'State that water resistance remains untested.', 'Recommend it only for the supported context or propose a safe water-resistance test.'], 'Claim only what the tests support.', 'Treating untested features as successful by default.', 'Mark unknown performance clearly and plan relevant checks.',
   'Can a useful recommendation include limitations?', 'Yes.', 'Why is “best product” usually weaker than “best for this user under these conditions”?', 'The narrower claim specifies criteria and context, making its evidence and limits clearer.']
 ]]
]],
['music', [
 ['Composition and development', [
  ['Develop a theme through controlled variation', 'Change selected musical features while preserving recognisable identity.',
   'A variation transforms a theme while retaining features that help listeners recognise it. Keep the rhythm but alter instrumentation, or keep the melodic outline while changing dynamics and accompaniment. Changing every feature at once may remove the relationship. Decide which feature carries the theme’s identity before planning the variation.',
   'Create a quieter contrasting version of a short melody.', ['Keep its recognisable pitch outline.', 'Change dynamics and simplify the accompaniment.', 'Compare the versions and explain which feature makes them related.'], 'Keep an anchor; change with purpose.', 'Calling an unrelated new tune a variation without identifying a connection.', 'Name the retained motif, rhythm or melodic shape.',
   'Must a variation preserve every note exactly?', 'No.', 'How could changing instrumentation alter effect without changing melody?', 'Different timbres, attack and sustain can change the character and texture while the pitch sequence remains recognisable.'],
  ['Plan musical structure across a longer piece', 'Organise contrast and return to support a compositional intention.',
   'A longer piece needs a plan for how ideas arrive, develop and return. An opening theme, contrasting middle and changed return can create direction rather than a collection of unrelated sections. Mark transitions and intended roles for performers. Structure is not only a letter pattern; explain what the contrasts and returns do for the listener.',
   'Plan an ABA piece whose final A feels calmer.', ['Establish the original A theme clearly.', 'Create a contrasting B section.', 'Return to A with reduced texture or dynamics while keeping its identity.'], 'Return can mean changed perspective.', 'Repeating a section label without checking that its material is recognisable.', 'Connect labels to actual musical features and planned transformations.',
   'What makes the last A a return rather than an unrelated section?', 'Recognisable material from the opening comes back.', 'Why rehearse transitions separately?', 'Changes in tempo, texture or entry points can disrupt coordination even when each section works alone.']
 ]],
 ['Performance and critical listening', [
  ['Evaluate interpretation rather than mere accuracy', 'Explain how expressive choices affect a performance of the same material.',
   'Two accurate performances can differ in phrasing, articulation, dynamics and tempo. Interpretation involves choices about how the music communicates, not simply adding maximum expression everywhere. Use specific moments as evidence and connect them with the piece’s character or intended effect. Respect stylistic differences without claiming every choice is equally supported.',
   'Compare two performances of the same short phrase.', ['Notice differences such as a pause, accent or dynamic shape.', 'Describe the effect at a specific moment.', 'Explain which interpretation better supports the stated intention and why.'], 'Specific choice, audible effect.', 'Judging only speed or loudness as proof of quality.', 'Consider control, coherence and how expressive decisions serve the music.',
   'Can a slower performance still be technically and musically successful?', 'Yes.', 'Why should feedback cite a moment rather than say “more expressive”?', 'A specific location and feature make the suggestion understandable and possible to test in rehearsal.'],
  ['Use recording feedback responsibly', 'Review a performance with permission and a focused listening question.',
   'A rehearsal recording can reveal balance, timing and transitions that performers miss while playing. Obtain appropriate permission and use approved storage; a useful learning tool is not automatic permission for public sharing. Choose a question before listening and compare another attempt after one change. Recording quality can also distort balance, so interpret it cautiously.',
   'Review whether a melody stays audible when percussion enters.', ['Record a short permitted rehearsal from a suitable position.', 'Listen specifically at the percussion entry.', 'Adjust the balance and compare a second take under similar recording conditions.'], 'One question makes listening useful.', 'Publishing rehearsal footage without checking consent and school guidance.', 'Keep the recording within the agreed learning purpose and permissions.',
   'Can microphone position affect apparent balance?', 'Yes.', 'Why keep recording conditions similar when comparing takes?', 'Otherwise a change in microphone placement or settings could be mistaken for a performance improvement.']
 ]]
]],
['pe', [
 ['Strategic decisions and leadership', [
  ['Evaluate risk in a game decision', 'Choose between retaining possession and attempting a more difficult action.',
   'A game decision balances the likely benefit of an action against its chance of success and consequence of failure. A difficult long pass may create an opportunity but also lose possession. Consider the game state, safe achievable distance and teammates’ readiness. Risk here concerns tactical choice within safe rules, not accepting dangerous physical behaviour.',
   'Compare a difficult scoring pass with a clear support pass.', ['Identify the possible benefit and likely failure of each.', 'Consider whether the team needs to retain possession or exploit an opening.', 'Choose a reasoned option and review its decision quality, not only its result.'], 'A lucky result does not prove a wise choice.', 'Judging every decision solely by whether it happened to succeed.', 'Assess the information available at the time and whether the choice was reasonable.',
   'Does tactical risk justify breaking safety rules?', 'No.', 'Why might a safe support pass be valuable even if it does not immediately lead to a score?', 'It can retain possession, reset spacing and create a better later opportunity.'],
  ['Lead an inclusive practice activity', 'Organise a task so roles, rules and adaptations are clear.',
   'Leadership in PE includes explaining a task, checking understanding and creating fair opportunities. Choose a safe space, demonstrate the relevant action and provide adaptations without singling people out negatively. Monitor whether everyone has a meaningful role. Being the fastest performer is not the same as communicating or organising effectively.',
   'Lead a short target-passing practice.', ['Explain the goal, boundaries and ready signal.', 'Offer appropriate distance and equipment choices.', 'Observe participation and make respectful adjustments with adult guidance.'], 'Explain, include, observe, adapt.', 'Assuming identical equipment and distance guarantee fairness.', 'Match access to the learning aim while preserving meaningful challenge.',
   'What should happen if a participant does not understand the rule?', 'Clarify or demonstrate it before continuing.', 'Name evidence that a leader has made a practice inclusive.', 'Participants understand the task, can access an appropriate role and receive useful opportunities to practise rather than merely waiting.']
 ]],
 ['Personal improvement and safe participation', [
  ['Review progress against a baseline', 'Use comparable observations to judge development without overstating precision.',
   'A baseline records performance before a focused practice period. Compare later attempts under similar conditions and use several observations where possible. Improvement may appear in control, decision-making or consistency, not only distance or time. Weather, fatigue and equipment can affect results, so explain changes cautiously and avoid ranking personal worth.',
   'Review a learner’s target accuracy after practice.', ['Use the same target, distance and suitable equipment as the baseline.', 'Compare several attempts rather than one best result.', 'Describe the pattern and note differences in conditions.'], 'Comparable conditions, several observations.', 'Comparing an easy later task with a harder baseline and claiming a precise gain.', 'Record changed conditions and limit the conclusion accordingly.',
   'Can progress include better consistency without a new best score?', 'Yes.', 'Why keep notes on the chosen practice focus?', 'They help connect observed changes with what was practised, while acknowledging that other factors may also contribute.'],
  ['Plan participation around individual needs', 'Identify preparation and support needed for a safe shared activity.',
   'A shared activity plan should consider the environment, equipment, supervision and individual access needs. Participants may need different rest, communication or movement options. Relevant health needs should be handled privately with responsible adults. A plan is revised when conditions change; determination does not override a safety concern or a person’s right to stop.',
   'An outdoor activity moves onto a wet surface.', ['Reassess grip, space and equipment.', 'Adjust or postpone the task under adult supervision.', 'Explain the change without blaming participants for reduced challenge.'], 'Changed conditions require a new check.', 'Following the original plan despite a new hazard.', 'Treat the plan as conditional on the actual environment and participants.',
   'Should private health information be announced to the whole group?', 'No; it should be handled appropriately and discreetly.', 'Why offer more than one communication signal?', 'Visual, spoken or other accessible cues can help participants receive instructions according to their needs.']
 ]]
]],
['pshe', [
 ['Transition and support networks', [
  ['Plan for a school transition', 'Turn an uncertain change into practical questions and support steps.',
   'Moving to a new school can bring excitement and worry together. Separate what is known, what needs checking and who can help. Practical preparation might include understanding the route, timetable and ways to ask for support. Do not promise that every difficulty will disappear immediately; belonging and routines can develop over time.',
   'A learner worries about getting lost in a larger school.', ['Identify the specific concern rather than treating all change as one problem.', 'Find a map, visit or trusted staff contact where available.', 'Practise how to ask for directions and identify a safe help point.'], 'Name the worry; find the next step.', 'Saying “There is nothing to worry about” and dismissing the concern.', 'Acknowledge the feeling and offer realistic support.',
   'Can someone feel excited and worried about the same change?', 'Yes.', 'What should a learner do if the first support plan does not help?', 'Tell a trusted adult, explain what remains difficult and revise the plan rather than assuming the problem is their fault.'],
  ['Respond when a friend needs more help', 'Recognise the limits of peer support and involve a trusted adult.',
   'Listening and kindness can help a friend, but children should not carry responsibility for another person’s safety alone. If a friend describes harm, threats or serious distress, seek trusted adult support even if asked to keep it secret. Do not promise professional confidentiality or attempt to diagnose. Share the concern with an appropriate adult rather than spreading it among peers.',
   'A friend asks you to keep a serious safety concern secret.', ['Listen without blaming or interrogating.', 'Explain that you need help from a trusted adult to support safety.', 'Tell an appropriate adult promptly and keep seeking help if needed.'], 'Support does not mean carrying it alone.', 'Promising never to tell anyone before hearing the concern.', 'Avoid absolute secrecy promises; safety may require adult help.',
   'Is seeking adult support a betrayal when someone may be unsafe?', 'No.', 'Why should the information not be shared as gossip?', 'Unnecessary sharing can cause harm and does not provide the responsible support the person needs.']
 ]],
 ['Financial and digital judgement', [
  ['Calculate the cost of repeated payments', 'Compare an ongoing charge with a one-off payment over a stated period.',
   'A small repeated charge can add to a substantial total. Multiply the payment by the number of payment periods, then include any starting fee or required extra cost. State the comparison period: a monthly subscription and a one-off purchase cannot be compared meaningfully without knowing how long the service is needed. Children should seek adult guidance before any purchase.',
   'Compare £4 each month with a £30 one-off charge over twelve months.', ['Twelve monthly payments total 12 × £4 = £48.', 'The one-off amount remains £30 if no other fees apply.', 'Over this period, the subscription costs £18 more; also compare what each option provides.'], 'Small each time can be large in total.', 'Comparing £4 directly with £30 and ignoring repetition.', 'Use the same time period and include all known charges.',
   'How much is £3 per month over eight months?', '£24.', 'Why might the cheaper total still not settle the decision?', 'The options may provide different features, commitments or cancellation terms, so cost must be considered alongside need and conditions.'],
  ['Check an urgent digital request', 'Recognise common manipulation tactics and use a safer verification route.',
   'A message may imitate a familiar organisation and create urgency to obtain a click, payment or personal information. Logos and a known-looking sender name are not proof. Do not use the suspicious message’s own link to verify it. Ask a trusted adult and, where appropriate, use a separately known official contact route. Mistakes should be reported promptly rather than hidden.',
   'A message says your account will close unless you enter a password immediately.', ['Pause and do not enter the password through the message.', 'Tell a trusted adult and inspect the request safely.', 'Use an independently known official route if the account genuinely needs checking.'], 'Urgency is a cue to verify, not obey.', 'Trusting a link because the message uses a familiar logo.', 'Separate visual appearance from verified origin and purpose.',
   'Does knowing your name prove a sender is genuine?', 'No.', 'What should you do if you already entered information into a suspicious page?', 'Tell a trusted adult promptly and follow appropriate account-protection steps; quick reporting can reduce harm.']
 ]]
]]
];
