import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 22 : 16, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, trace the example without notes. In a week, test a different input or system constraint and explain which parts of the model still apply.' });
export const year9Computing: Subject = ['computer-science', [
 ['Representing images and sound', [
  ['Calculate an uncompressed bitmap payload', 'Distinguish resolution, colour depth, bits and bytes.',
   'A bitmap represents an image as pixels. If every pixel uses b bits, a width w and height h require w × h × b bits for the raw pixel payload. Divide by eight for bytes. This simplified estimate excludes headers, metadata and compression. More colour depth permits more encoded colours but does not by itself add spatial detail; increasing pixel dimensions changes spatial sampling.',
   'Estimate the raw payload for a 100 by 50 pixel image at 8 bits per pixel.', ['There are 100 × 50 = 5,000 pixels.', 'The payload is 5,000 × 8 = 40,000 bits.', 'Dividing by eight gives 5,000 bytes before headers and compression.'], 'Pixels × bits per pixel; divide by eight for bytes.', 'Reporting bits as bytes or claiming colour depth determines image dimensions.', 'Keep spatial dimensions and encoding depth as separate quantities.', 'How many distinct codes can 8 bits represent?', '256.',
   'Calculate the raw bytes for a 40 by 20 pixel image at 24 bits per pixel.', '40 × 20 × 24 = 19,200 bits, or 2,400 bytes. This is a payload estimate rather than a guaranteed saved file size.',
   d(false, 'How many bits make a byte?', 'Eight.', 'Storage units and independent image properties are easily mixed in a single calculation.')],
  ['Challenge: budget sampled audio and explain information loss', 'Compare sample rate and bit depth while keeping their roles distinct.',
   'Uncompressed sampled audio payload equals sample rate × duration × bits per sample × channel count. Sample rate describes how often amplitude is measured; bit depth describes how many levels can represent each measurement. Raising one does not recover information lost through an inadequate other setting. Compression may alter stored size, and lossy compression deliberately discards information rather than merely writing identical samples more compactly.',
   'Calculate one second of mono audio at 8,000 samples/s and 16 bits/sample.', ['Multiply 8,000 × 1 × 16 × 1 = 128,000 bits.', 'Divide by eight to obtain 16,000 bytes.', 'Stereo at the same settings doubles the channel count and raw payload.'], 'How often, how precisely, how many channels, how long?', 'Treating bit depth as the number of samples taken each second.', 'Assign sample rate and amplitude resolution different roles.', 'What factor changes from mono to stereo in this estimate?', 'Channel count.',
   'Would doubling bit depth restore high-frequency information lost through too-low sampling frequency?', 'No. More amplitude levels cannot reconstruct oscillations not adequately sampled in time. The sampling process and amplitude quantisation impose distinct limitations.',
   d(true, 'What is a sample in digital audio?', 'A numerical measurement of signal amplitude at a particular instant.', 'Different forms of digital resolution can be treated as interchangeable improvements.')]
 ]],
 ['Algorithms and program structure', [
  ['Trace insertion sort’s growing sorted prefix', 'Explain how one item is inserted into the correct place among preceding items.',
   'Insertion sort maintains a sorted prefix. For each next item, store it as a key, shift larger prefix items one position right, then place the key in the gap. On [4, 1, 3], inserting 1 gives [1, 4, 3]; inserting 3 gives [1, 3, 4]. Shifting is not the same as discarding values, and the key must be preserved while its original position may be overwritten.',
   'Trace insertion sort on [5, 2, 4].', ['Start with prefix [5]; store key 2 and shift 5 right.', 'Insert 2 to produce [2, 5, 4].', 'Store 4, shift 5 and insert 4, giving [2, 4, 5].'], 'Save the key, shift larger values, fill the gap.', 'Overwriting the key before saving it.', 'Use a separate key variable throughout the shift loop.', 'Is the whole array necessarily sorted after the first insertion?', 'No; only the processed prefix is guaranteed sorted.',
   'After processing the third item of [3, 1, 2, 0], what is the array?', '[1, 2, 3, 0]. The first three values are sorted, but the final 0 has not yet been inserted, so the global minimum is still outside the processed prefix.',
   d(false, 'What is an array index?', 'A position used to identify an element in an array.', 'An intermediate invariant may be confused with the algorithm’s final postcondition.')],
  ['Challenge: specify and test a function’s contract', 'Separate input requirements, returned values and side effects.',
   'A function contract states accepted inputs and promised outputs. For a function mean(values), decide whether an empty list is rejected or represented by a documented special result; silently returning zero confuses missing data with a real zero mean. A pure calculation should not unexpectedly modify the input list. Tests should include ordinary, boundary and invalid inputs and verify both results and relevant side effects.',
   'Design tests for a mean function accepting non-empty numeric lists.', ['Use [2, 4] expecting 3 and [7] expecting 7.', 'Use [−2, 2] expecting 0 to distinguish a genuine zero mean.', 'Check that [] is rejected as documented and that valid input lists remain unchanged.'], 'Contract first, tests against the contract.', 'Choosing an arbitrary result for invalid input and calling the program robust.', 'Document error handling so callers can distinguish a failure from valid data.', 'What is a side effect?', 'An observable change beyond returning a value, such as modifying input data or writing a file.',
   'Why is testing only [1, 2, 3] insufficient?', 'It exercises one ordinary positive case but misses single-element behaviour, negatives, empty inputs and unintended mutation. Passing one example cannot establish the full contract.',
   d(true, 'What is a function parameter?', 'A named input supplied when a function is called.', 'A correct output on one example can hide undefined boundary behaviour and unexpected state changes.')]
 ]],
 ['Networks and dependable communication', [
  ['Explain packet switching and reassembly', 'Distinguish a complete message from the packets carrying it.',
   'Packet-switched networks divide data into units containing payload and control information. Routers forward packets towards destinations; packets may take different routes or arrive out of order. Protocols such as TCP provide mechanisms for ordering, acknowledging and retransmitting data as part of reliable delivery. A router does not need to understand an entire essay or video to forward its packets, and not every network protocol guarantees retransmission.',
   'Packets from a message arrive in the order 2, 1, 3.', ['Sequence information identifies their intended ordering.', 'A suitable receiving transport protocol can reorder the data.', 'The application can then receive the reconstructed sequence rather than treating arrival order as message order.'], 'Arrival order need not be information order.', 'Assuming all packets follow a single fixed route or always arrive in order.', 'Separate network forwarding from transport-level reliability mechanisms.', 'What is a packet payload?', 'The data carried in the packet, apart from its control information.',
   'Why might a lost packet not require retransmitting the entire original file?', 'A reliable protocol can identify missing data and retransmit the relevant portion. The exact behaviour depends on the protocol, rather than on every packet network guaranteeing the same recovery.',
   d(false, 'What does a router do?', 'Forwards network traffic between networks or towards destinations.', 'Everyday ideas of one continuous message can hide the network’s division into separately handled units.')],
  ['Challenge: distinguish bandwidth, latency and observed transfer time', 'Evaluate why a fast connection can still feel slow.',
   'Bandwidth or link capacity describes how much data can be carried per unit time; latency concerns delay. A small request that requires several sequential round trips may be latency-sensitive even when little data is transferred. A large file may be more capacity-sensitive. Congestion, server processing and protocol overhead can also matter. Advertised link rate is not a guarantee of application throughput or immediate response.',
   'A task requires five sequential request-response exchanges, each taking 100 ms round-trip time.', ['Ignoring processing and payload time, the exchanges total at least 500 ms.', 'They cannot all finish in one round trip if each depends on the previous result.', 'Increasing bandwidth alone may leave this latency-driven delay largely unchanged.'], 'Capacity carries volume; latency delays interaction.', 'Assuming doubling bandwidth always halves every page’s loading time.', 'Identify sequential delays, payload size and other bottlenecks.', 'What is a millisecond?', 'One thousandth of a second.',
   'Name a design change that could reduce round-trip delay without changing the link capacity.', 'Combining suitable requests or removing unnecessary sequential dependencies can reduce the number of round trips. The change must preserve correctness and freshness rather than merely cache everything indefinitely.',
   d(true, 'What does sequential mean?', 'One operation follows and may depend on completion of another.', 'A single speed number may be used to explain systems with several different bottlenecks.')]
 ]]
]];
