import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 22 : 16, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, reconstruct the explanation with precise evidence. In a week, compare another case and identify which conclusions depend on the original context.' });
export const year9World: Subject[] = [
['history', [
 ['The First World War: causes and evidence', [
  ['Explain escalation during the July Crisis', 'Connect an immediate trigger with decisions that widened the conflict.',
   'The assassination of Archduke Franz Ferdinand in Sarajevo on 28 June 1914 triggered a crisis, but did not mechanically cause every state to enter war. Austria-Hungary’s response to Serbia, German support, Russian mobilisation and further diplomatic and military decisions widened the conflict. Alliances and war plans shaped choices without eliminating human agency. Britain declared war on Germany on 4 August after Germany invaded Belgium, within a wider strategic and treaty context.',
   'Improve “One assassination made every alliance automatically declare war”.', ['Identify the assassination as a trigger.', 'Trace intervening decisions about demands, mobilisation and declarations.', 'Explain that alliance commitments and strategic fears influenced rather than replaced those decisions.'], 'Trigger, decision, escalation.', 'Treating alliances as machines with no political choices.', 'Locate the actors and choices between each stage of escalation.', 'In which month did the assassination occur?', 'June 1914.',
   'Why does naming militarism alone not explain the exact outbreak in 1914?', 'It identifies a longer-term condition but not the sequence that turned a particular crisis into war. An explanation also needs the July Crisis and the decisions that widened it.',
   d(false, 'What is an alliance?', 'An agreement between states for cooperation or support.', 'A simple causal acronym can hide the chronological mechanism connecting conditions to an outcome.')],
  ['Challenge: evaluate a recruitment poster as evidence', 'Distinguish intended persuasion from proof of audience response.',
   'A wartime recruitment poster can reveal appeals authorities or organisations thought persuasive, such as duty, solidarity or fear of shame. It cannot alone show how many people agreed or why an individual enlisted. Date, commissioning organisation, audience and distribution matter. Compare with recruitment records, letters or diaries while recognising that personal accounts also have purposes and survival biases.',
   'A fictional poster addresses readers as defenders of their community.', ['Identify the implied duty and intended audience.', 'Use it as evidence of a recruitment strategy.', 'Seek other evidence before claiming the appeal caused most enlistments.'], 'An appeal shows intention; response needs further evidence.', 'Inferring universal support from a confident official message.', 'Separate what the source tries to achieve from its measured effects.', 'Can a persuasive source still be historically useful?', 'Yes.',
   'What could a private letter add, and what would it not establish alone?', 'It might reveal one person’s stated reasons for enlisting or refusing, but would not prove those reasons represented the whole population. Comparing several kinds of evidence supports a broader account.',
   d(true, 'What is provenance?', 'Information about a source’s origin, authorship and circumstances.', 'The message a source promotes can be mistaken for an accurate description of its audience’s beliefs.')]
 ]],
 ['Russia in 1917', [
  ['Distinguish the February and October revolutions', 'Explain changes of authority between the fall of the Tsar and Bolshevik seizure of power.',
   'In the February Revolution of 1917, using Russia’s then calendar, unrest and loss of military support contributed to Nicholas II’s abdication. A Provisional Government followed, alongside influential soviets of workers and soldiers. In October, Bolsheviks overthrew the Provisional Government. These are different changes of power, not one event in which Lenin directly removed the Tsar. Calendar differences explain why anniversaries may appear in March and November in the Gregorian calendar.',
   'Correct “Lenin replaced Nicholas II in the October Revolution”.', ['Nicholas II had already abdicated during the earlier revolutionary crisis.', 'The Provisional Government governed in the intervening period, amid competing authority.', 'The Bolsheviks overthrew that government in October.'], 'Tsar to provisional rule; provisional rule to Bolshevik power.', 'Collapsing both revolutions and the intervening government into one succession.', 'Construct the sequence before judging causes.', 'Which government was overthrown by the Bolsheviks in October?', 'The Provisional Government.',
   'Why is the intervening period important to explaining Bolshevik success?', 'Continuing war, land demands and disputes over authority shaped dissatisfaction with the Provisional Government. Without the intervening choices, the explanation misses why support and opportunities changed.',
   d(false, 'What does abdication mean?', 'A monarch giving up the throne.', 'Two revolutions in one year can be compressed into one remembered event.')],
  ['Challenge: weigh war against political organisation', 'Compare structural pressures with the actions of a revolutionary party.',
   'War strained Russia’s economy, army and political legitimacy, but dissatisfaction did not determine which group would gain power. Bolshevik slogans addressed demands for peace, land and bread, while organisation and decisions during the crisis helped turn opportunities into action. A multi-causal explanation should show interaction: conditions create grievances and opportunities, while political actors interpret and use them. Avoid assuming later victory proves universal support at every stage.',
   'Assess “War alone explains the Bolshevik seizure of power”.', ['Explain how war intensified shortages, casualties and distrust.', 'Ask why those pressures benefited the Bolsheviks rather than guaranteeing any particular successor.', 'Include organisation, policy appeals and the actions of opponents to explain the specific outcome.'], 'Pressure creates an opening; organisation can exploit it.', 'Treating widespread discontent as equivalent to unanimous support for one party.', 'Distinguish opposition to a government from support for a particular replacement.', 'Does victory prove every social group supported the victors?', 'No.',
   'Write a qualified judgement linking the two factors.', '“War was central to weakening existing authority, but Bolshevik organisation and appeals helped direct parts of that discontent towards their seizure of power. The outcome therefore requires both the crisis and the actions taken within it.”',
   d(true, 'What is a structural pressure in history?', 'A wider condition shaping what actors can do, rather than one isolated decision.', 'A large background cause may be used to explain a specific political outcome without tracing the intervening mechanism.')]
 ]],
 ['Nazi dictatorship and persecution', [
  ['Explain the destruction of democratic constraints in 1933', 'Distinguish appointment to office from the subsequent consolidation of dictatorship.',
   'Hitler was appointed chancellor in January 1933; the Nazis had not won an absolute majority in a free national election. The Reichstag Fire Decree suspended key civil liberties, while the Enabling Act allowed laws without normal parliamentary approval. Intimidation, violence, exclusion of opponents and institutional cooperation shaped these changes. Studying legal forms does not mean describing the process as freely consensual or inevitable.',
   'Explain why “Hitler was elected dictator” is misleading.', ['Chancellorship began through appointment within a political crisis.', 'Dictatorial power was consolidated through subsequent measures and coercion.', 'The phrase hides both the lack of a free majority mandate for dictatorship and the dismantling of constraints.'], 'Appointment is not the same event as consolidation.', 'Treating the presence of a law or vote as proof of free democratic consent.', 'Examine coercion, exclusions and the powers changed.', 'What did the Enabling Act weaken?', 'Parliamentary constraints on government lawmaking.',
   'Why examine institutions as well as Hitler’s personal decisions?', 'Courts, officials, political elites, police and other bodies could enable, implement or fail to resist measures. Personal leadership alone does not explain how dictatorship operated across society.',
   d(false, 'What is a civil liberty?', 'A basic freedom such as expression or protection against arbitrary state action.', 'Formal procedures can obscure the intimidation and unequal conditions under which they occur.')],
  ['Challenge: explain escalation from persecution to genocide', 'Use chronology and agency without implying that victims caused their persecution.',
   'The Holocaust was the Nazi-led genocide of six million European Jews. Anti-Jewish persecution included exclusion, dispossession and the 1935 Nuremberg Laws; wartime occupation brought ghettos, mass shootings and killing centres. Policies escalated through decisions and implementation across places and institutions. Nazi racial claims were false and dehumanising. Jewish people responded in varied ways under extreme constraints; studying resistance does not transfer responsibility from perpetrators to victims.',
   'Why is a timeline of laws alone insufficient to explain the Holocaust?', ['Laws reveal institutionalised discrimination but not every mechanism of violence.', 'War, occupation, decisions and implementation changed the scale and forms of killing.', 'Testimony and local evidence illuminate experiences and agency that legal documents may conceal.'], 'Chronology shows escalation; evidence identifies decisions and implementation.', 'Presenting genocide as an automatic process with no responsible actors.', 'Name perpetrator decisions and institutions while respecting victims’ experiences and constraints.', 'Were Nazi racial claims scientifically valid?', 'No.',
   'Why should a historian avoid asking why victims “simply did not leave” as if escape were freely available?', 'Exit restrictions, confiscation, closed borders, lack of resources and escalating coercion severely limited options. The question can impose hindsight and blame on people facing conditions they did not create or control.',
   d(true, 'What is persecution?', 'Targeted mistreatment of people because of their identity or beliefs.', 'Hindsight can make constrained choices appear obvious and obscure perpetrator responsibility.')]
 ]]
]],
['geography', [
 ['Drainage basins and river response', [
  ['Link stores and transfers in a drainage basin', 'Explain how water reaches a channel by different pathways.',
   'A drainage basin is the area supplying a river system. Rain may be intercepted by vegetation, infiltrate soil, move as throughflow or groundwater flow, or reach the channel as surface runoff. These pathways differ in speed and depend on conditions such as saturation, permeability, slope and land cover. A basin is not a sealed container: water enters, leaves and moves between temporary stores.',
   'Explain why already saturated soil can contribute to rapid runoff during further rain.', ['Soil storage has limited additional capacity under saturation.', 'More incoming water may remain at or near the surface.', 'Faster routes to channels can increase the river’s short-term response.'], 'Stores affect which pathways remain available.', 'Assuming every raindrop reaches the river immediately by the same route.', 'Trace alternative stores and transfers under the stated conditions.', 'What is infiltration?', 'Water entering the soil surface.',
   'How can vegetation affect the timing of water reaching a river?', 'Interception can temporarily hold rain and root systems can influence infiltration, delaying some transfers. Effects vary with vegetation, soil and event conditions rather than guaranteeing no flooding.',
   d(false, 'What is precipitation?', 'Water falling from the atmosphere, including rain and snow.', 'A simple arrow from rainfall to river can hide intermediate stores and differing travel times.')],
  ['Challenge: interpret a storm hydrograph without assigning a single cause', 'Relate peak discharge and lag time to basin conditions and rainfall.',
   'A storm hydrograph shows river discharge through time alongside rainfall information. Lag time commonly compares peak rainfall with peak discharge. A short lag and high peak may be associated with rapid runoff, but rainfall intensity, basin size, antecedent wetness and drainage modifications also matter. Comparing two hydrographs does not isolate urbanisation unless relevant differences are controlled or accounted for.',
   'Two basins have different peak discharges after different-sized storms.', ['Identify that the rainfall inputs are not equivalent.', 'Avoid attributing the whole discharge difference to land use.', 'Compare rainfall totals, intensity, basin area and prior wetness before assessing land-use effects.'], 'Different outputs need comparable inputs.', 'Calling a high peak proof of impermeable urban surfaces alone.', 'Check storm and basin differences that could also explain the graph.', 'What does discharge measure?', 'The volume of water passing a point per unit time.',
   'Why can equal rainfall totals still produce different hydrographs?', 'Rain falling intensely in a short period may exceed infiltration capacity more than the same total spread over time. Storm timing, spatial distribution and existing basin conditions also affect the response.',
   d(true, 'What is a confounding variable?', 'A factor that can affect the outcome and obscure the effect being investigated.', 'A familiar process explanation can be treated as the only possible cause of a graph pattern.')]
 ]],
 ['Coastal sediment and management', [
  ['Explain longshore transport as repeated oblique movement', 'Connect wave approach, swash and backwash to sediment transfer.',
   'When waves approach a beach at an angle, swash may carry sediment obliquely up the shore while backwash moves more directly downslope under gravity. Repeated movement can create net transport along the coast. The direction varies with wave conditions and local shape; not every beach has a permanently fixed drift direction. Sediment can also move offshore or onshore, so the zigzag model is a simplification.',
   'Describe net sediment movement when swash repeatedly approaches obliquely from the left.', ['The swash has a component along the beach to the right.', 'Backwash follows the downward beach slope more directly.', 'Repeated cycles can produce net rightward longshore transport under those conditions.'], 'Individual cycles combine into net transport.', 'Describing longshore drift as a single wave dragging all sediment sideways.', 'Explain the repeated swash-backwash sequence and its limits.', 'What mainly drives backwash downslope?', 'Gravity.',
   'Why might a photograph of one wave not establish the long-term drift direction?', 'Wave approach varies with weather and coastal conditions. A long-term net sediment budget requires observations across time rather than a single instantaneous direction.',
   d(false, 'What is sediment?', 'Particles such as sand, pebbles or silt moved and deposited by processes.', 'A schematic process diagram can be mistaken for an unchanging direction at every real coastline.')],
  ['Challenge: evaluate downdrift effects of groynes', 'Use a sediment budget to assess benefits beyond one defended frontage.',
   'Groynes can trap sediment moving alongshore and help retain a wider protective beach locally. They may also reduce supply to downdrift sections, potentially increasing erosion there if other inputs do not compensate. Evaluate a management unit rather than only the defended site. Costs, maintenance, habitat, public access and changing sea level also influence a decision; a structure’s local benefit does not prove a coast-wide benefit.',
   'A town reports a wider beach after groynes are installed.', ['Recognise the local sediment-retention benefit.', 'Investigate beach change and supply farther along the transport direction.', 'Compare wider sediment gains and losses before claiming the intervention solved regional erosion.'], 'A trapped input here may be a missing input elsewhere.', 'Assessing success only in front of the funded property.', 'Examine connected coast sections and their sediment budgets.', 'What does downdrift mean?', 'Farther along the net direction of sediment transport.',
   'Suggest evidence needed before attributing downdrift erosion entirely to the new groynes.', 'Use before-and-after profiles, wave conditions, sediment supply and records of other coastal changes. Storms or upstream supply changes may also contribute, so timing alone is not conclusive.',
   d(true, 'What is a sediment budget?', 'A comparison of sediment inputs, outputs and storage change in an area.', 'Management boundaries can be treated as if they stop physical processes.')]
 ]],
 ['Climate mechanisms and responses', [
  ['Distinguish the greenhouse effect from ozone depletion', 'Explain how atmospheric gases affect outgoing thermal radiation.',
   'The natural greenhouse effect helps keep Earth warmer than it would be without greenhouse gases. These gases absorb and emit outgoing infrared radiation; increasing their concentrations changes Earth’s energy balance. This is distinct from depletion of stratospheric ozone, which concerns protection from ultraviolet radiation. The processes interact within a complex atmosphere but are not interchangeable explanations of modern global warming.',
   'Correct “Global warming occurs because the ozone hole lets in more heat”.', ['Identify ozone depletion as primarily a change in ultraviolet protection.', 'Explain greenhouse gases in relation to outgoing infrared radiation.', 'Distinguish the mechanisms instead of substituting one environmental issue for another.'], 'Ozone and ultraviolet; greenhouse gases and infrared.', 'Using a hole-in-the-atmosphere image to explain all warming.', 'Specify the radiation and process involved.', 'Is the natural greenhouse effect itself entirely harmful?', 'No; it contributes to habitable surface temperatures.',
   'Why does reducing greenhouse-gas emissions address a different mechanism from repairing ozone depletion?', 'It limits changes to infrared absorption and emission associated with greenhouse-gas concentrations. Ozone protection targets chemicals and reactions affecting stratospheric ozone; policies may have overlaps but the mechanisms differ.',
   d(false, 'What is radiation in energy transfer?', 'Energy carried by electromagnetic waves.', 'Two widely discussed atmospheric problems can merge into one inaccurate mental model.')],
  ['Challenge: separate mitigation, adaptation and trade-offs', 'Evaluate a climate response against the problem it actually addresses.',
   'Mitigation aims to limit climate change, for example by reducing greenhouse-gas emissions or enhancing carbon storage. Adaptation reduces vulnerability to its effects, such as designing for greater heat or flood risk. A measure can contribute to both but may also have trade-offs. Tree planting can store carbon and provide shade, yet species, water demand, survival and land-use competition affect outcomes; counting planted seedlings does not prove lasting carbon storage.',
   'Evaluate a hypothetical city’s plan for street trees during hotter summers.', ['Shade can reduce heat exposure, an adaptation benefit.', 'Growing biomass may store carbon, a mitigation contribution.', 'Check survival, water supply, species and maintenance before claiming guaranteed long-term benefits.'], 'Ask whether the measure changes the cause, the impact or both.', 'Calling any environmentally friendly action sufficient mitigation regardless of its scale.', 'Identify mechanisms, scale, persistence and unintended effects.', 'Is a flood warning system primarily mitigation or adaptation?', 'Adaptation.',
   'What evidence would improve a tree programme’s evaluation beyond the planting count?', 'Survival and canopy coverage over time, local temperature or shading data, maintenance resources and a defensible carbon assessment help test the intended benefits. Initial planting is an activity measure, not the final outcome.',
   d(true, 'What is vulnerability?', 'Susceptibility to harm under particular conditions.', 'Visible activity counts can be confused with demonstrated long-term outcomes.')]
 ]]
]]
];
