import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 24 : 17, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, reconstruct the biological mechanism without notes. In a week, apply it to a changed example and distinguish a supported inference from an assumption.' });
export const year10Biology: Subject = ['biology', [
 ['Cell organisation and microscopy', [
  ['Compare eukaryotic and prokaryotic organisation', 'Locate genetic material and distinguish shared structures from defining differences.',
   'Animal and plant cells are eukaryotic: their DNA is mainly enclosed in a nucleus, and they contain membrane-bound organelles. Bacteria are prokaryotic: their main DNA is not enclosed in a nucleus and they may contain plasmids. Both have cytoplasm, a cell membrane and ribosomes. A bacterial cell wall is not made of plant cellulose. Not every plant cell has chloroplasts, so absence of chloroplasts alone does not identify a cell as animal.',
   'Classify a cell with ribosomes and circular DNA free in the cytoplasm but no nucleus.', ['Ribosomes alone do not distinguish the groups.', 'The absence of a nucleus around the main DNA supports prokaryotic organisation.', 'A bacterium fits the observations, whereas an ordinary plant cell would have a nucleus.'], 'Shared structures do not erase organisational differences.', 'Calling bacteria cells without DNA because they lack a nucleus.', 'Separate the presence of DNA from its location.', 'Do bacterial cells have ribosomes?', 'Yes.',
   'Why could a root cell lack chloroplasts while still being a plant cell?', 'Many root cells do not photosynthesise and therefore lack chloroplasts. Other features, including their eukaryotic organisation and cellulose walls, support their identity; one absent organelle is not decisive.',
   d(false, 'What does the nucleus contain?', 'Most of a eukaryotic cell’s genetic material.', 'An organelle may be mistaken for the substance or process normally associated with it.')],
  ['Challenge: separate magnification from resolution', 'Calculate image enlargement while explaining whether new detail is distinguishable.',
   'Magnification is image size divided by actual size, with both in the same units. Resolution is the ability to distinguish nearby points as separate. Enlarging a blurred image increases its displayed size without recovering detail. A scale bar can remain useful when an image is resized if it is resized by the same factor; a printed magnification label may then become wrong.',
   'A cell 40 micrometres long appears 60 millimetres long.', ['Convert 60 mm to 60,000 micrometres.', 'Divide image size by actual size: 60,000/40.', 'Magnification is ×1,500, a ratio without length units.'], 'Match units for size; inspect resolution for detail.', 'Calling a larger pixelated image more highly resolved.', 'Distinguish enlargement from the information captured.', 'How many micrometres are in one millimetre?', '1,000.',
   'A 10 micrometre scale bar is displayed as 20 mm. What actual length corresponds to a 70 mm displayed object?', 'The object is 70/20 = 3.5 scale-bar lengths, so it represents 35 micrometres. This comparison does not require trusting an old printed magnification value.',
   d(true, 'What is a ratio?', 'A comparison by division of quantities on a compatible basis.', 'A visually larger image may create an impression of improved information without improved resolving power.')]
 ]],
 ['Cell division and differentiation', [
  ['Trace DNA copying and mitosis for growth', 'Explain how division maintains chromosome number in genetically similar daughter cells.',
   'Before mitosis, a cell grows and copies its DNA. During mitosis the copied chromosomes are separated so each new nucleus receives a set; division of the cytoplasm then produces daughter cells. In the usual model they retain the parent cell’s chromosome number and genetic information, apart from possible mutations. DNA replication is not the same event as splitting the cell, and growth of an organism also involves cell enlargement and differentiation.',
   'A diploid cell with 46 chromosomes divides by mitosis.', ['DNA is copied before chromosome separation.', 'Each new nucleus receives a complete corresponding set.', 'Each daughter cell has 46 chromosomes in the ordinary model, not 23.'], 'Copy first; separate complete sets.', 'Halving chromosome number whenever any cell divides.', 'Distinguish mitosis from the specialised division producing gametes.', 'What must happen to DNA before ordinary mitosis?', 'It must be replicated.',
   'Why would simply splitting unreplicated DNA between two cells be inadequate?', 'Each new cell would lack part of the complete genetic information needed for normal functioning. Replication and organised separation prevent that simple loss.',
   d(false, 'What is a chromosome?', 'A DNA-containing structure carrying genetic information.', 'The everyday idea of dividing a quantity in half can obscure prior duplication.')],
  ['Challenge: evaluate stem-cell treatment claims', 'Connect differentiation potential with evidence, risks and ethical questions.',
   'Stem cells can divide and produce cells that differentiate into specialised types. Different sources have different developmental potential, practical limitations and ethical considerations. A claim that a treatment repairs tissue needs controlled evidence of benefit and safety; laboratory differentiation alone does not prove a safe clinical cure. Immune rejection, uncontrolled growth and delivery to the correct location are relevant questions. Clinical decisions require qualified professionals.',
   'A laboratory produces nerve-like cells from a stem-cell line.', ['Identify the demonstrated result as differentiation under laboratory conditions.', 'Ask whether the cells function appropriately and integrate safely in a patient.', 'Do not turn the laboratory result into proof that every neurological condition is curable.'], 'Potential cells are not yet a proven treatment.', 'Equating a promising mechanism with demonstrated clinical effectiveness.', 'Separate laboratory evidence, clinical trials and established treatment.', 'Does every stem-cell source have identical differentiation potential?', 'No.',
   'Give one scientific and one ethical question for evaluating a proposed therapy.', 'A scientific question is whether controlled trials show benefit without unacceptable harm. An ethical question concerns how cells were sourced and consent obtained; different sources raise different issues.',
   d(true, 'What is differentiation?', 'Development of specialised cell structures and functions.', 'Promising research headlines can collapse several stages of evidence into an immediate cure claim.')]
 ]],
 ['Exchange and membrane transport', [
  ['Relate diffusion rate to exchange-surface adaptations', 'Explain surface area, distance and concentration difference as separate influences.',
   'Diffusion is net movement down a concentration gradient due to random particle motion. A large exchange area provides more routes, a thin barrier shortens the distance and a steep concentration difference supports a higher net transfer rate. Alveoli combine a large surface with thin walls and ventilation and blood flow that help maintain gradients. The lungs do not actively pump each oxygen molecule across the exchange barrier.',
   'Explain how blood flow supports oxygen diffusion from an alveolus.', ['Oxygen enters blood where its concentration is lower than in alveolar air.', 'Flow carries oxygenated blood away and brings relatively deoxygenated blood.', 'This helps maintain the gradient rather than allowing the two sides simply to equalise.'], 'Area, distance, gradient: explain each link.', 'Listing adaptations without explaining their effects on movement.', 'Connect each structure or process to a diffusion variable.', 'Does net diffusion require every molecule to move in the same direction?', 'No.',
   'Predict an effect of a thicker exchange barrier, other factors unchanged.', 'The longer diffusion distance generally reduces transfer rate. This prediction follows from the barrier change and does not by itself diagnose a particular disease.',
   d(false, 'What is a concentration gradient?', 'A difference in concentration across a distance.', 'A memorised adaptation list can substitute for a causal explanation.')],
  ['Challenge: distinguish active transport from concentration-driven movement', 'Explain uphill uptake and its dependence on energy-releasing processes.',
   'Active transport can move substances against their concentration gradient using membrane proteins and energy supplied by the cell. Root hair cells may take up mineral ions from dilute soil solution even when the cell concentration is higher. Diffusion alone would not explain sustained net movement in that direction. Oxygen availability can affect aerobic respiration and therefore energy supply, but a result must be interpreted alongside cell health and other controls.',
   'Ion uptake decreases when a controlled treatment limits respiration.', ['Identify active uptake as requiring cellular energy.', 'Reduced energy supply is a plausible reason for reduced uptake.', 'Check that membrane damage or altered ion concentration did not independently cause the result.'], 'Against the gradient needs an energy-linked mechanism.', 'Calling every movement into a cell diffusion.', 'Compare concentrations and the required direction before naming the process.', 'Is active transport always movement into a cell?', 'No; its defining feature here is energy-dependent movement against a gradient.',
   'Why would temperature alone be an imperfect test for active transport?', 'Temperature can change enzyme activity, diffusion and membrane condition simultaneously. A rate change does not uniquely identify active transport without additional evidence and controls.',
   d(true, 'What process releases usable energy from organic molecules?', 'Respiration.', 'A treatment affecting several mechanisms can be interpreted as a specific test of just one.')]
 ]],
 ['Human organisation and circulation', [
  ['Trace the double circulation', 'Explain separate routes through lungs and body without defining arteries by oxygen content.',
   'Blood travels from the right side of the heart to the lungs, returns to the left side, then travels around the body and back to the right side. Arteries carry blood away from the heart and veins towards it; pulmonary arteries therefore carry relatively deoxygenated blood. Separate circuits support gas exchange and delivery while allowing different pressures. Valves help prevent backflow, but do not themselves generate the pumping pressure.',
   'Trace blood from the right ventricle to the left ventricle.', ['It leaves through the pulmonary artery towards the lungs.', 'After gas exchange it returns through pulmonary veins to the left atrium.', 'It passes through a valve into the left ventricle.'], 'Away defines artery; towards defines vein.', 'Calling every artery oxygenated and every vein deoxygenated.', 'Classify vessels by direction relative to the heart.', 'Which ventricle pumps to the body?', 'The left ventricle.',
   'Why is the left ventricle’s wall thicker than the right’s?', 'It must generate higher pressure to supply the systemic circulation. This connects muscle thickness to pumping demand rather than to a claim that one side contains more important blood.',
   d(false, 'What does a valve help prevent?', 'Backflow.', 'Common systemic examples can be overgeneralised into an incorrect definition of vessel type.')],
  ['Challenge: explain coronary obstruction and evaluate risk evidence', 'Distinguish supplying the heart muscle from blood passing through its chambers.',
   'Coronary arteries deliver oxygen and nutrients to heart muscle. Blood inside the chambers does not adequately replace this supply to the thick muscle wall. Reduced coronary flow can limit aerobic respiration and impair contraction. A statistical association between a risk factor and disease does not mean every exposed individual becomes ill; evaluate mechanisms, confounding and intervention evidence rather than personal blame.',
   'Explain why a blocked coronary artery can harm a heart containing blood.', ['The chambers carry blood being pumped around the circulation.', 'The muscle requires its own exchange through coronary vessels.', 'Obstruction can deprive a region of adequate oxygen despite blood remaining inside the chambers.'], 'The pump needs its own supply.', 'Assuming blood in a heart chamber automatically feeds all surrounding cells.', 'Distinguish transport through chambers from delivery to muscle tissue.', 'What do coronary arteries supply?', 'The heart muscle.',
   'Why does an association with one risk factor not justify predicting an individual outcome with certainty?', 'Disease is influenced by multiple factors and chance; population risk is not a guaranteed personal result. Appropriate clinical assessment needs more than a single association.',
   d(true, 'Why do muscle cells need oxygen during aerobic respiration?', 'It supports energy-releasing reactions needed for sustained function.', 'The visible presence of blood can obscure the separate route needed to reach particular cells.')]
 ]],
 ['Infection prevention and treatment evidence', [
  ['Explain specific and non-specific defences', 'Connect physical barriers, phagocytosis and antibody specificity.',
   'Skin and mucus help prevent entry of pathogens. Phagocytes can engulf pathogens, while lymphocytes contribute to specific responses including production of antibodies with binding sites matching particular antigens. Antibodies do not all bind every pathogen equally. Memory cells can support a faster later response. Barriers reduce risk rather than guaranteeing that infection never occurs, and immune responses have multiple interacting components.',
   'Explain why an antibody against one antigen may not bind another.', ['Binding depends on the shapes and chemical properties involved.', 'Different antigens may not fit the same binding site.', 'Specificity explains why prior exposure to one pathogen does not automatically protect against all infections.'], 'Barriers are broad; recognition can be specific.', 'Describing antibodies as identical substances that kill every microbe.', 'Identify the antigen-antibody match and distinguish immune roles.', 'Which cells can engulf pathogens?', 'Phagocytes.',
   'Why is skin damage relevant to infection risk even when a person has an immune system?', 'A breached barrier can make entry easier. Internal defences still matter, but they do not make the barrier’s preventive role unnecessary.',
   d(false, 'What is an antigen in this context?', 'A molecular feature recognised by a specific immune response.', 'Different protective mechanisms can be blended into one vague description of immunity.')],
  ['Challenge: interpret a randomised treatment comparison', 'Separate a plausible biological action from measured effectiveness.',
   'A controlled trial compares outcomes under a defined treatment and comparison condition. Random allocation reduces systematic starting differences on average, while blinding can reduce expectation and assessment bias where feasible. A statistically or clinically meaningful result still needs attention to sample size, adverse effects and who was studied. Randomisation does not guarantee perfectly identical groups or prove effectiveness for every patient.',
   'A fictional trial assigns participants to a treatment or comparison group at random.', ['Random allocation aims to avoid choosing healthier people for one group.', 'Comparable outcome measurement supports a fair assessment.', 'Interpret both benefits and harms rather than only the most favourable result.'], 'Mechanism suggests; a fair comparison tests.', 'Calling a treatment effective solely because it could work biologically.', 'Seek controlled outcome evidence and relevant safety information.', 'Does random allocation mean participants choose their preferred group?', 'No.',
   'Why would excluding everyone who felt worse after treatment distort a result?', 'It would remove potentially important adverse outcomes and create a biased comparison. The analysis needs transparent rules for withdrawals and missing data, not selective removal of unfavourable evidence.',
   d(true, 'What is a control group?', 'A comparison group used to help assess the effect of an intervention.', 'Selective reporting can make a plausible treatment appear more effective or safer than the full evidence supports.')]
 ]],
 ['Bioenergetics and plant use of glucose', [
  ['Link glucose production to plant materials', 'Explain storage, structural and biosynthetic uses of photosynthetic products.',
   'Glucose from photosynthesis can be used in respiration, converted into insoluble starch for storage, built into cellulose for cell walls or used with mineral-derived elements to make other molecules. Nitrate ions supply nitrogen needed for amino acids and proteins; glucose alone does not contain that nitrogen. Plants therefore require both carbon-containing products and suitable mineral inputs for growth.',
   'Explain why a plant with light and carbon dioxide can still show poor growth in nitrate-deficient conditions.', ['Photosynthesis can supply carbon-containing molecules.', 'Protein production also requires a nitrogen source.', 'A nitrate shortage can limit amino-acid and protein synthesis despite available carbohydrate.'], 'Carbon skeletons do not supply every required element.', 'Assuming photosynthesis makes all required nutrients directly from light.', 'Track where each element enters the plant.', 'What carbohydrate forms plant cell walls?', 'Cellulose.',
   'Why is starch useful for storage compared with leaving all glucose dissolved?', 'Starch is insoluble, so stored carbohydrate has less direct effect on the concentration of dissolved solutes and water movement than an equivalent supply of free glucose molecules.',
   d(false, 'Which reactant supplies carbon for photosynthesis?', 'Carbon dioxide.', 'The central role of glucose can hide the need for additional elements and biosynthetic steps.')],
  ['Challenge: evaluate a leaf starch test as indirect evidence', 'Distinguish detecting a product from measuring photosynthesis rate directly.',
   'A starch test can provide evidence about stored carbohydrate after specified conditions, but it does not directly measure instantaneous photosynthesis rate. Initial starch stores, light history, respiration and transport of sugars affect the result. Classroom testing requires teacher-controlled safety procedures because some methods involve hot water and flammable liquids. Interpret provided observations rather than attempting unsupervised chemical heating.',
   'A previously destarched plant has one leaf region covered during illumination.', ['Initial destarching reduces an important alternative source of stored starch.', 'Covered and uncovered regions provide a comparison for light availability.', 'A difference in later starch supports a role for light under the method, not a direct numerical rate measurement.'], 'An indicator gives evidence through a chain of reasoning.', 'Calling a darker stain a calibrated photosynthesis rate without a validated scale.', 'State what the test detects and what additional inference is made.', 'What does the iodine test detect here?', 'Starch.',
   'Why does one uncovered region provide a useful internal comparison?', 'It shares much of the plant’s history and environment while differing in light access. The comparison improves the design but does not remove every possible influence or replace replication.',
   d(true, 'What is an indirect measurement?', 'An observation used to infer a quantity or process through an established relationship.', 'A visible test result can be mistaken for direct measurement of the underlying rate.')]
 ]],
 ['Ecology and material cycling', [
  ['Trace carbon through biological processes', 'Distinguish moving carbon atoms from transferring energy.',
   'Photosynthesis transfers carbon from atmospheric carbon dioxide into organic molecules. Feeding transfers that carbon between organisms; respiration returns some as carbon dioxide. Decomposition and combustion also return carbon from organic material, while long-term storage can delay its return. Carbon cycles through stores, but energy is transferred and dissipated rather than recycled indefinitely through the same ecosystem.',
   'Trace carbon from air into a herbivore and back to air.', ['A plant incorporates carbon dioxide into organic molecules by photosynthesis.', 'Feeding transfers some carbon to the herbivore.', 'Respiration releases some of that carbon as carbon dioxide.'], 'Atoms cycle; energy flows and dissipates.', 'Saying respiration destroys carbon or that ecosystem energy cycles like matter.', 'Apply conservation of atoms and distinguish it from energy transfer pathways.', 'Which process incorporates atmospheric carbon into plant biomass?', 'Photosynthesis.',
   'Why can deforestation affect atmospheric carbon through more than one route?', 'It can reduce future carbon uptake and release stored carbon through burning or decomposition. The magnitude depends on what happens to biomass and land afterwards.',
   d(false, 'What is biomass?', 'Biological material, often measured as mass of living or recently living matter.', 'Similar arrows in diagrams can conceal different meanings for matter cycling and energy movement.')],
  ['Challenge: distinguish abundance, biodiversity and sampling effort', 'Interpret ecological comparisons without equating a larger count with greater diversity.',
   'Abundance counts organisms; species richness counts species, while broader diversity also concerns how individuals are distributed among species. A site with many individuals of one species is not necessarily more diverse than one with fewer individuals across several species. Sampling area, season and identification effort affect observed richness, so comparisons require a consistent method and recognition of undetected species.',
   'Site A has 100 individuals of one species; B has 50 individuals across five species.', ['A has greater total observed abundance.', 'B has greater observed species richness.', 'Neither statement alone measures every aspect of ecosystem condition or proves a cause for the difference.'], 'Count individuals and species separately.', 'Calling the site with the most organisms automatically the most biodiverse.', 'Specify the metric and standardise sampling effort.', 'What does species richness count?', 'The number of species present or recorded under the method.',
   'Why might doubling search time increase observed richness without any ecological change?', 'Additional effort may detect previously missed species. The site can remain unchanged while the measurement becomes more complete, so effort must be considered in comparisons.',
   d(true, 'What is a sample in fieldwork?', 'A selected observation or subset used to investigate a wider area or population.', 'An observation process can be mistaken for a direct exhaustive inventory of the ecosystem.')]
 ]],
 ['Reproduction and genetic variation', [
  ['Compare mitosis and meiosis by their biological roles', 'Explain why gametes need a reduced chromosome set.',
   'Meiosis produces cells with half the original chromosome number and generates variation through chromosome assortment and other processes. Fusion of gametes at fertilisation restores the diploid number. Mitosis usually retains chromosome number for growth, repair or some forms of asexual reproduction. Halving in meiosis prevents chromosome number from doubling at every generation; it does not mean a gamete has no genetic information.',
   'Predict chromosome numbers for human gametes and a fertilised egg.', ['Ordinary diploid human cells have 46 chromosomes.', 'Meiosis produces gametes with 23.', 'Fusion combines two sets of 23 to restore 46 in the fertilised egg.'], 'Halve for gametes; restore at fertilisation.', 'Describing fertilisation itself as the process that halves chromosomes.', 'Separate gamete formation from gamete fusion.', 'Which division usually maintains chromosome number?', 'Mitosis.',
   'Why does sexual reproduction generate combinations different from either parent?', 'Gametes carry different combinations of parental genetic material, and fertilisation joins contributions from two gametes. This does not require claiming every observed trait is determined by one gene.',
   d(false, 'What is fertilisation?', 'Fusion of gametes, including their genetic contributions.', 'The two processes of producing and joining gametes can be merged into one event.')],
  ['Challenge: evaluate genetic and environmental explanations of phenotype', 'Use controlled comparisons without assuming a trait has only one cause.',
   'Phenotype can depend on genes, environment and interactions between them. Genetically similar plants grown under different light conditions can differ in height or leaf colour without those differences proving a change in inherited DNA. Conversely, equal environments do not guarantee equal phenotypes when genotypes differ. A controlled study isolates selected influences but must still consider random variation and unmeasured conditions.',
   'Clonal plants are allocated to two light conditions with other factors controlled.', ['Clonal material reduces genetic differences as an explanation.', 'A systematic group difference can support an environmental light effect.', 'Replication and control of water, nutrients and temperature are needed for a stronger inference.'], 'Same genes can respond differently to different conditions.', 'Calling every visible difference a genetic mutation.', 'Distinguish inherited information from its expression under environmental conditions.', 'What does clonal mean?', 'Derived with the same starting genetic information in the usual model, apart from mutations.',
   'Would one tall and one short plant prove a light effect?', 'No. Individual variation, unequal starting condition or another factor could explain it. Replicated groups and a controlled allocation are needed to evaluate a consistent effect.',
   d(true, 'What is phenotype?', 'An observable characteristic resulting from genotype and potentially environmental influences.', 'Visible traits may be treated as direct readouts of genes independent of context.')]
 ]]
]];
