import type { Topic, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 24 : 17, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, solve a similar problem without notes and justify the model. In a week, mix it with a different topic and check units, domain and the meaning of the final answer.' });
export const year10Application: Topic[] = [
 ['Right-angle trigonometry and geometry', [
  ['Choose a trigonometric ratio from a labelled triangle', 'Relate opposite, adjacent and hypotenuse to the selected acute angle.',
   'In a right triangle, sin θ = opposite/hypotenuse, cos θ = adjacent/hypotenuse and tan θ = opposite/adjacent. Opposite and adjacent depend on which acute angle is selected; the hypotenuse always lies opposite the right angle. Label the diagram before choosing a ratio, and use degree mode for degree-based questions. These right-triangle ratios cannot simply be applied to an arbitrary non-right triangle.',
   'A right triangle has a 30° angle and hypotenuse 10 cm. Find the opposite side.', ['Select sine because opposite and hypotenuse are involved.', 'Write sin 30° = x/10.', 'Since sin 30° = 0.5, x = 5 cm.'], 'Angle first, side labels second, ratio third.', 'Calling a side adjacent without specifying the reference angle.', 'Relabel opposite and adjacent if the selected angle changes.', 'Which ratio uses opposite and adjacent?', 'Tangent.',
   'For an acute angle with opposite 6 cm and adjacent 8 cm, state the equation used to find the angle.', 'tan θ = 6/8 = 0.75, so θ = tan⁻¹(0.75), approximately 36.87° in degree mode. Inverse tangent finds the angle; it is not division by tan.',
   d(false, 'Which side of a right triangle is longest?', 'The hypotenuse.', 'Side names may be treated as permanent labels rather than relative to a chosen angle.')],
  ['Challenge: model an elevation measurement with a height offset', 'Distinguish height above an instrument from total height above the ground.',
   'An angle of elevation is measured above a horizontal line. If an instrument is above ground, the opposite side in the right-triangle model is the target’s height above the instrument, not its full ground height. Add the instrument height only after calculating that difference. The model assumes level ground, a vertical target and a horizontal distance; sloping distance along the line of sight is a different side.',
   'A target is 12 m horizontally away, with elevation 45° from an instrument 1.5 m above level ground.', ['Let h be the height above the instrument.', 'tan 45° = h/12, so h = 12 m.', 'Total height is 12 + 1.5 = 13.5 m.'], 'Triangle height first; reference-level correction second.', 'Reporting height above eye level as the full ground height.', 'Mark the observation level and ground level separately.', 'What does the adjacent side represent in this model?', 'Horizontal distance to the target.',
   'Why would using a 12 m sloping sightline in place of the horizontal distance change the method?', 'The sightline would be the hypotenuse, so the height difference would use sine rather than tangent. The distance’s meaning determines the correct ratio.',
   d(true, 'What is an angle of elevation?', 'An angle measured upward from the horizontal.', 'A context word such as distance can hide which geometric length was actually measured.')]
 ]],
 ['Circle theorems and linked reasoning', [
  ['Relate central and circumference angles on the same arc', 'Match endpoints and arc before applying the double-angle theorem.',
   'The angle subtended by an arc at the centre is twice the angle subtended by the same arc at a point on the remaining circumference. The shared arc matters: a diagram may contain both minor and reflex central angles. Identify the chord endpoints and the arc not containing the circumference vertex. A semicircle gives a 180° central angle and therefore a 90° circumference angle.',
   'A central angle subtending the relevant arc is 124°.', ['Identify the circumference angle standing on that same arc.', 'Use central angle = twice circumference angle.', 'The circumference angle is 62°.'], 'Same arc before the factor of two.', 'Doubling an unrelated angle merely because it lies in a circle.', 'Trace the common endpoints and relevant arc.', 'What is an angle in a semicircle?', '90°.',
   'A circumference angle on the stated arc is 37°. Find its corresponding central angle.', '74°, because the central angle is twice 37° on the same arc. The theorem’s arc condition is essential to the conclusion.',
   d(false, 'How many degrees form a straight angle?', '180°.', 'Visually nearby angles may be linked without checking whether they subtend the same arc.')],
  ['Challenge: combine a tangent with an isosceles radius triangle', 'Use perpendicularity and equal radii as separate justified steps.',
   'A tangent is perpendicular to the radius at the point of contact. Two radii to points on the same circle are equal, producing an isosceles triangle with a chord. Combining these facts can determine a tangent-chord angle, but every angle must be located precisely. Do not assign 90° between the tangent and any arbitrary chord; perpendicularity specifically involves the radius through contact.',
   'OA and OB are radii, angle AOB is 100°, and a tangent touches at A.', ['Triangle OAB is isosceles, so each base angle is (180 − 100)/2 = 40°.', 'The tangent is perpendicular to OA at A.', 'The acute angle between tangent and chord AB is 90 − 40 = 50°.'], 'Equal radii give base angles; radius to tangent gives ninety.', 'Calling the chord perpendicular to the tangent.', 'Name the line pair to which each theorem applies.', 'Why is triangle OAB isosceles?', 'OA and OB are radii of the same circle.',
   'Repeat the calculation when the central angle is 80°.', 'The base angles are (180 − 80)/2 = 50°. The acute tangent-chord angle is 90 − 50 = 40°, with the same diagram assumptions.',
   d(true, 'What property do equal sides give an isosceles triangle?', 'Equal opposite angles.', 'A correct circle theorem can be applied to the wrong pair of lines in a crowded diagram.')]
 ]],
 ['Quadratic graphs and intersections', [
  ['Find roots, intercept and symmetry of a quadratic graph', 'Use different algebraic forms to extract different graphical features.',
   'For y = x² − 4x + 3, factorisation gives (x − 1)(x − 3), so x-intercepts occur at 1 and 3. Setting x = 0 gives y-intercept 3. The symmetry line lies midway between the roots at x = 2; substituting gives the minimum point (2, −1). Roots are x-values where y is zero, not points where x must be zero.',
   'Describe the graph of y = x² − 6x + 8.', ['Factor to obtain roots x = 2 and x = 4.', 'The symmetry line is x = 3 and y(3) = −1.', 'The minimum is (3, −1), and the y-intercept is 8.'], 'For x-intercepts set y to zero; for y-intercept set x to zero.', 'Swapping intercept coordinates or using a root as the minimum.', 'State each point as an ordered pair after solving.', 'What is the y-intercept of y = x² − 6x + 8?', '(0, 8).',
   'Find the minimum of y = (x − 5)² + 2.', 'The square is smallest at zero, occurring when x = 5. The minimum point is therefore (5, 2), and the graph has no real x-intercepts because y is at least 2.',
   d(false, 'What does an x-intercept mean?', 'A point where the graph meets the x-axis and y = 0.', 'Roots, turning points and intercepts can be treated as interchangeable important numbers.')],
  ['Challenge: solve a line-curve intersection and check coordinates', 'Equate y-expressions and recover both coordinates of each intersection.',
   'An intersection lies on both graphs, so their y-values must agree at the same x. Equating a line and a quadratic gives an equation whose real roots identify possible intersection x-coordinates. Substitute each into either original graph to find y, then check the other. Solving only for x is incomplete when coordinates are requested; roots of the original quadratic alone are not generally intersections with another line.',
   'Find intersections of y = x² and y = x + 2.', ['Equate x² = x + 2 and rearrange to x² − x − 2 = 0.', 'Factor (x − 2)(x + 1) = 0, giving x = 2 or −1.', 'Substitute to obtain (2, 4) and (−1, 1), satisfying both equations.'], 'Same x, same y, both equations.', 'Finding the quadratic’s x-intercepts instead of equating the two graphs.', 'Write the equality between the two y-expressions first.', 'How many coordinates are needed to specify one planar intersection?', 'Two: x and y.',
   'Find intersections of y = x² − 1 and y = 2x + 2.', 'Equate to get x² − 2x − 3 = 0 = (x − 3)(x + 1). The points are (3, 8) and (−1, 0), found by substituting into y = 2x + 2.',
   d(true, 'What does it mean for a point to satisfy a graph’s equation?', 'Its coordinates make the equation true.', 'A familiar zero-solving procedure can be applied before identifying the correct equation for the intersection.')]
 ]],
 ['Grouped data and distribution', [
  ['Estimate a mean from grouped frequencies', 'Use class midpoints while acknowledging lost within-class information.',
   'Grouped data reports counts in intervals rather than every original value. Estimate a mean by multiplying each class midpoint by its frequency, adding those products and dividing by total frequency. This treats each class as represented by its midpoint; the result is not usually an exact mean. Open-ended classes need additional assumptions because they lack a defined midpoint.',
   'Scores lie in 0 ≤ x < 10 with frequency 2 and 10 ≤ x < 20 with frequency 3.', ['Use midpoints 5 and 15.', 'The estimated total is 2 × 5 + 3 × 15 = 55.', 'Divide by 5 observations to estimate a mean of 11, using the stated non-overlapping class convention.'], 'Midpoint times frequency, then divide by total frequency.', 'Averaging the midpoints without their frequencies.', 'Weight each class by how many observations it represents.', 'Why is the grouped mean usually an estimate?', 'The original values within each interval are not known.',
   'Classes 0 ≤ x < 4 and 4 ≤ x < 8 have frequencies 3 and 1. Estimate the mean.', 'Midpoints are 2 and 6. The weighted total is 3 × 2 + 1 × 6 = 12, and total frequency is 4, giving an estimated mean of 3.',
   d(false, 'How is the mean of ungrouped data calculated?', 'Sum of values divided by the number of values.', 'The grouping removes individual values, but the resulting calculation may still look exact.')],
  ['Challenge: read a histogram with unequal class widths', 'Use frequency density so bar area represents frequency.',
   'For a frequency-density histogram, density = frequency/class width, so frequency is bar area. Unequal class widths make raw frequency heights misleading. A class of width 10 with frequency 20 has density 2; a class of width 5 with frequency 15 has density 3. The narrower bar is taller despite containing fewer observations. Always inspect axis labels and scale before reading values.',
   'A histogram class from 20 to 35 has frequency density 4.', ['Its width is 35 − 20 = 15.', 'Frequency equals density multiplied by width.', 'The class contains 4 × 15 = 60 observations.'], 'Histogram area counts; height is density.', 'Reading height directly as frequency for unequal widths.', 'Multiply by the class width and respect the vertical scale.', 'What is frequency density?', 'Frequency divided by class width.',
   'Two classes have width 5, frequency 20 and width 10, frequency 30. Which is taller?', 'Their densities are 4 and 3 respectively, so the first bar is taller even though the second has more observations. The second has larger area because it is wider.',
   d(true, 'How is a rectangle’s area calculated?', 'Width multiplied by height.', 'Experience with bar charts can encourage treating all graph heights as direct counts.')]
 ]],
 ['Conditional probability from data', [
  ['Restrict the sample space in a conditional question', 'Choose the denominator from the group specified after given.',
   'A conditional probability uses a restricted group. In a fictional class, 12 pupils travel by bus, of whom 3 arrive early; another 8 walk, of whom 4 arrive early. The probability of early arrival given bus travel is 3/12, not 3/20. The probability of bus travel given early arrival is 3/7. Reversing the condition changes the denominator and usually the result.',
   'Find the probability of walking given early arrival in the fictional class.', ['There are 3 + 4 = 7 early arrivals.', 'Of these, 4 walk.', 'The conditional probability is 4/7.'], 'Given tells you which group to stand inside.', 'Using the whole class as the denominator for every conditional question.', 'Identify the restricted group before counting favourable cases.', 'How many pupils are in the whole fictional class?', '20.',
   'Calculate the probability of early arrival given walking.', '4/8 = 1/2. The denominator is all walkers, unlike the reversed conditional whose denominator is all early arrivals.',
   d(false, 'What does a probability numerator count?', 'Outcomes satisfying the event within the chosen sample space.', 'The same two labels in reversed order can make distinct conditional questions appear identical.')],
  ['Challenge: test independence using conditional proportions', 'Distinguish independence from mutual exclusivity and from a small observed association.',
   'Events A and B are independent in a probability model when knowing B does not change A’s probability: P(A|B) = P(A), provided P(B) is positive. Mutually exclusive positive-probability events are not independent, because occurrence of one excludes the other. In observed data, unequal proportions suggest an association but sampling variation and confounding limit causal claims. State whether you analyse an exact model or estimate from a sample.',
   'In an exact model P(A) = 0.4, P(B) = 0.5 and P(A and B) = 0.2.', ['Compute P(A|B) = 0.2/0.5 = 0.4.', 'This equals P(A), so the events are independent in the model.', 'They are not mutually exclusive because their intersection has probability 0.2.'], 'Independent means unchanged probability, not impossible together.', 'Using independent as a synonym for non-overlapping.', 'Check the intersection and conditional probability separately.', 'Can independent events occur together?', 'Yes.',
   'If P(A) = 0.4, P(B) = 0.5 and P(A and B) = 0.1, are they independent?', 'No. P(A|B) = 0.1/0.5 = 0.2, which differs from 0.4. Equivalently, P(A)P(B) = 0.2 does not equal the stated intersection 0.1.',
   d(true, 'What does mutually exclusive mean?', 'Two events cannot both occur in the same trial.', 'Everyday meanings of unrelated and separate can obscure distinct probability definitions.')]
 ]]
];
