import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 22 : 16, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, explain the practical’s mechanism and calculate its result without notes. Next week, identify a confounding variable in a changed method and propose a discriminating control.' });
export const year9Combined: Subject = ['science-combined', [
 ['Osmosis and biological measurements', [
  ['Explain net water movement through a partially permeable membrane', 'Connect concentration differences with changes in plant tissue mass.',
   'Osmosis is net movement of water through a partially permeable membrane from a more dilute solution towards a more concentrated solution. Water molecules move both ways, but unequal rates produce a net change. In a supervised plant-tissue investigation, a dilute external solution may cause water entry and increased mass. Standardise surface drying before weighing so attached droplets are not mistaken for water absorbed by the tissue.',
   'A tissue sample rises from 2.00 g to 2.20 g in a dilute solution.', ['The measured increase is 0.20 g.', 'Water entry through cell membranes provides a plausible mechanism.', 'Check consistent surface drying before attributing the full increase to osmosis.'], 'Both ways, but one net direction.', 'Saying water molecules move only in one direction across the membrane.', 'Distinguish random molecular motion from net transfer.', 'Which substance moves in osmosis?', 'Water.',
   'Why compare samples kept in solution for the same time?', 'Exposure time can affect the measured mass change. Unequal times would confound a comparison intended to isolate the effect of solution concentration.',
   d(false, 'What does partially permeable mean?', 'Allowing some substances through more readily than others.', 'A visible net outcome can obscure continuing movement in both directions.')],
  ['Challenge: compare percentage mass change and estimate a balance point', 'Normalise results for initial sample size and interpret a zero crossing cautiously.',
   'Percentage mass change is (final mass − initial mass) / initial mass × 100. It enables comparison of differently sized samples more fairly than raw change alone. Plotting mean percentage change against external solute concentration can locate an approximate zero crossing, where there is no measured net mass change under the method’s conditions. This is an estimate, not proof that all cell contents equal the surrounding solution in every respect.',
   'Sample A rises from 2.0 to 2.2 g; B rises from 4.0 to 4.3 g.', ['A changes by 0.2/2.0 × 100 = 10 percent.', 'B changes by 0.3/4.0 × 100 = 7.5 percent.', 'B gains more grams but A has the larger proportional gain.'], 'Use the starting value as the percentage denominator.', 'Ranking osmotic effects only by the number of grams gained.', 'Account for initial size and remaining controls.', 'What does a negative percentage mass change indicate?', 'A net loss of measured mass.',
   'If neighbouring graph points straddle zero, why collect more data near the crossing?', 'Additional concentrations and repeats can narrow the estimated balance region and reveal scatter or curvature. A line between widely spaced points may give misleading precision.',
   d(true, 'How is a percentage change calculated?', 'Change divided by the original value, multiplied by 100.', 'Large initial samples can generate larger raw changes even when proportional effects are smaller.')]
 ]],
 ['Electrical evidence and component models', [
  ['Calculate resistance from paired voltage and current readings', 'Use R = V/I while distinguishing a ratio from a constant property.',
   'Resistance at a measured operating point is potential difference divided by current. A fixed resistor at constant temperature may show proportional voltage and current, giving an approximately constant ratio. Other components or changing temperatures may not. Use corresponding measurements from the same operating point. Practical circuits must use suitable supervised low-voltage equipment, not mains electricity.',
   'A resistor has 6.0 V across it and current 0.20 A.', ['Use R = V/I.', 'Calculate 6.0/0.20 = 30.', 'The resistance is 30 ohms at that operating point.'], 'Pair the voltage and current before taking the ratio.', 'Combining the largest voltage with an unrelated current reading.', 'Match readings from the same circuit condition.', 'What unit is used for resistance?', 'Ohms.',
   'At another point the readings are 3.0 V and 0.10 A. Is this consistent with constant resistance?', 'Yes: 3.0/0.10 = 30 ohms, matching the earlier ratio. Two matching points support but do not fully establish behaviour across every voltage or temperature.',
   d(false, 'What does current measure?', 'The rate of flow of electric charge.', 'A formula may be applied without preserving which observations belong together.')],
  ['Challenge: interpret a curved filament-lamp graph', 'Link changing temperature to changing resistance without confusing graph axes.',
   'As current heats a metal filament, its resistance increases. On a graph with current vertically and voltage horizontally, the curve becomes less steep as voltage increases in the positive region. V/I at each point can reveal the changing resistance; the local slope dI/dV is not generally identical to I/V for a curved graph. Read axis labels before interpreting steepness.',
   'A lamp gives 2 V at 0.20 A and 6 V at 0.30 A.', ['At the first point R = 2/0.20 = 10 ohms.', 'At the second R = 6/0.30 = 20 ohms.', 'The increase is consistent with heating of the filament, rather than constant resistance.'], 'Axes first; ratio at a point second.', 'Calling every graph’s gradient the resistance without checking axes or linearity.', 'Use the defined voltage-current ratio and identify the graph convention.', 'Does doubling voltage always double lamp current?', 'No.',
   'Why might waiting different lengths of time before taking readings matter?', 'The filament’s temperature may not have settled equally, changing resistance. A consistent method and attention to thermal behaviour improve comparability; the data alone do not justify assuming a constant temperature.',
   d(true, 'What does a straight line through the origin suggest for two quantities?', 'Direct proportionality over the observed range.', 'A rule for a straight resistor graph may be carried over to curved component characteristics.')]
 ]],
 ['Thermal energy and practical uncertainty', [
  ['Use specific heat capacity in an energy balance', 'Calculate temperature change while stating the idealised model.',
   'Specific heat capacity is the energy required per kilogram per degree of temperature rise. The relation E = mcΔT describes heating without a change of state when c is treated as constant. An electrical heater’s energy output need not all reach the sample: the container and surroundings can also gain energy. State whether a calculation assumes negligible losses rather than present an ideal result as a guaranteed measurement.',
   'A 0.50 kg sample with c = 400 J/(kg °C) receives 2,000 J of thermal energy.', ['Calculate mc = 0.50 × 400 = 200 J/°C.', 'Rearrange to ΔT = E/(mc).', 'The ideal temperature rise is 2,000/200 = 10 °C.'], 'Energy per degree depends on both mass and material.', 'Using final temperature instead of temperature change in E = mcΔT.', 'Subtract initial temperature from final temperature.', 'What does ΔT represent?', 'The change in temperature.',
   'If the sample starts at 18 °C and the ideal rise is 10 °C, find its final temperature.', '28 °C. The energy equation gives the rise, which must be added to the initial value; it does not directly return the final thermometer reading.',
   d(false, 'How is a temperature rise calculated?', 'Final temperature minus initial temperature.', 'Thermometer readings can be substituted without distinguishing absolute values from changes.')],
  ['Challenge: explain the direction of a heat-loss error', 'Trace how a biased measurement changes a calculated specific heat capacity.',
   'In a heating experiment, using all electrical energy as if it heated only the sample can overestimate c. If energy escapes or heats the apparatus, the sample’s measured temperature rise is smaller than the ideal rise for that input. In c = E/(mΔT), a smaller denominator with unchanged stated E produces a larger estimate. Repeats reduce some random variation but do not automatically remove this systematic bias.',
   'The model uses E = 2,000 J and m = 0.50 kg, but measures a rise of 8 °C rather than the ideal 10 °C.', ['Calculate c = 2,000/(0.50 × 8) = 500 J/(kg °C).', 'Compare with the ideal 400 J/(kg °C).', 'Attributing lost energy to the sample overestimates its specific heat capacity in this model.'], 'Trace the error through the fraction.', 'Claiming every measurement error makes a calculated value smaller.', 'Identify the affected numerator or denominator and follow its effect.', 'Do repeated identical biased measurements necessarily approach the true value?', 'No.',
   'Suggest a practical improvement and one remaining limitation.', 'Insulation can reduce heat loss to surroundings, but energy absorbed by the container or heater still requires consideration. Better repeatability alone would not prove that those transfers disappeared.',
   d(true, 'What is a systematic error?', 'A consistent influence that biases measurements or calculated results.', 'Improved consistency can be mistaken for improved accuracy when the same bias remains.')]
 ]]
]];
