import type { Subject, ActivityDetail } from '../authoredActivities';
const detail = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({
 isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 20 : 15,
 priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause,
 revision: 'Tomorrow, explain the decision and its reason without notes. In a week, revisit it using a different fictional scenario and identify what extra information would change your judgement.'
});
export const year8Wellbeing: Subject[] = [
['pe', [
 ['Training principles and safe adaptation', [
  ['Connect specificity, overload and recovery', 'Explain why an appropriate training stimulus and recovery both matter.',
   'Specificity means adaptations relate to the demands practised. Progressive overload means increasing an appropriate demand gradually as a learner adapts, not pushing every session to exhaustion. Recovery allows adaptation and helps manage fatigue. School activity should follow a qualified teacher’s guidance and individual needs; pain, dizziness or illness are reasons to stop and seek help, not signs that a programme is working better.',
   'Evaluate a fictional plan that increases duration, speed and frequency at once.', ['Several simultaneous increases make the new demand difficult to judge.', 'Fatigue and inadequate recovery can undermine safe participation.', 'A supervised plan should adjust demands gradually and review the response.'], 'Specific demand, gradual change, recovery.', 'Treating overload as a requirement to ignore pain or maximise effort every day.', 'Distinguish an appropriate challenge from unsafe strain and allow recovery.', 'Does recovery have a role in adaptation?', 'Yes.',
   'Why would only practising short sprints not fully prepare someone for a long steady event?', 'The demands differ in duration and energy use, so adaptation is specific rather than completely transferable. A teacher would select suitable preparation for the actual event and learner.',
   detail(false, 'What is endurance?', 'The ability to sustain an appropriate activity over time.', 'Improvement may be equated with constantly doing more instead of managing stimulus and recovery.')],
  ['Challenge: interpret a training diary without overclaiming', 'Use patterns and contextual information before changing a programme.',
   'A diary can record a supervised session’s type, duration, perceived effort and recovery. One slower performance does not prove lost fitness: sleep, illness, conditions, measurement and fatigue may differ. Look for repeated patterns and discuss concerns with the teacher rather than prescribe harder training from one result. Avoid comparing bodies or using exercise as punishment; the purpose is informed, safe participation.',
   'A fictional learner reports higher effort at the same pace after several tiring days.', ['Check recent activity, recovery and possible illness.', 'Treat the result as information requiring context, not proof of laziness.', 'Discuss an appropriate adjustment or rest with the supervising teacher.'], 'A trend needs context before a prescription.', 'Responding to every slower time by increasing workload.', 'Check fatigue and conditions before interpreting a change as reduced ability.', 'Can perceived effort vary at the same external pace?', 'Yes.',
   'Name two contextual diary entries that could help explain a change without diagnosing a condition.', 'Recent sleep or recovery and the session’s weather or surface conditions may help interpretation. These observations inform a conversation with the teacher; they do not establish a medical diagnosis.',
   detail(true, 'What does perceived effort describe?', 'How demanding an activity feels to the participant.', 'Performance numbers can be treated as complete explanations instead of outcomes influenced by several factors.')]
 ]],
 ['Defensive organisation and transitions', [
  ['Compare player and space-based marking', 'Explain different defensive responsibilities without treating one system as always superior.',
   'Player-based marking prioritises an assigned opponent; zone-based defence prioritises an area and threats entering it. Both require communication, awareness and rules appropriate to the sport. Following an opponent can open a space elsewhere, while defending a zone can fail if responsibility for an entering attacker is unclear. Analyse the situation and teammates’ roles rather than assume one label guarantees successful defence.',
   'An attacker crosses between two defenders’ areas in a non-contact school game.', ['Both defenders track the developing threat.', 'They communicate who takes responsibility as it crosses the boundary.', 'They avoid both abandoning the attacker or both following and exposing another area.'], 'Responsibility must transfer clearly.', 'Treating a zone boundary as a reason to stop noticing an attacker.', 'Maintain awareness and communicate shared responsibility within the chosen system.', 'What does zone-based defence primarily allocate?', 'Responsibility for areas and the threats within them.',
   'Give one possible weakness of strict player-based marking.', 'A defender may be drawn away from a strategically important space by an opponent’s movement. Teammates need agreed cover and communication rather than simply following without awareness.',
   detail(false, 'What is space in a tactical game?', 'An area that players can use, protect or deny to opponents.', 'A system label can obscure the decisions and communication needed to make it work.')],
  ['Challenge: plan the first decisions after possession changes', 'Prioritise immediate threats during an attacking-to-defending transition.',
   'A transition occurs when possession or the phase of play changes. After losing possession, players may need to delay an immediate advance, protect a dangerous space and recover useful positions. Running straight towards the ball can leave a passing route open. Choose actions based on distance, teammates and the sport’s rules; this written analysis does not replace safe, supervised practice.',
   'In a non-contact game, a team loses the ball with an opponent free nearer the target.', ['Identify the immediate scoring or progression threat.', 'One player can delay the ball carrier safely while another covers the dangerous route.', 'Recover the team shape and communicate instead of everyone chasing the ball.'], 'Protect the threat, not just the ball.', 'Sending every defender towards the ball carrier.', 'Divide delaying, covering and recovering roles according to position.', 'What is a transition in this context?', 'A change of possession or phase requiring a change of tactical role.',
   'What information could change which defender should delay the ball carrier?', 'Relative distance, the direction of the threat, teammate coverage and sport-specific rules can change the best choice. Assigning the role to the nearest player is a starting consideration, not an exceptionless rule.',
   detail(true, 'What is an overload?', 'A numerical advantage in a relevant area or phase of play.', 'Attention can fix on the ball while more dangerous space or passing options are ignored.')]
 ]],
 ['Feedback and practice design', [
  ['Distinguish result feedback from movement feedback', 'Explain knowledge of results and knowledge of performance.',
   'Knowledge of results describes the outcome, such as where a beanbag landed relative to a target. Knowledge of performance describes the action, such as release direction or balance. A miss identifies an outcome but not its cause. Useful feedback is specific, manageable and appropriate to the learner; too many corrections at once can make the next attempt harder to focus on.',
   'A throw lands to the left of a target.', ['Landing left is result information.', 'A teacher’s observation of release direction provides performance information.', 'Choose one relevant adjustment and observe the next attempt rather than infer every technical fault from the miss.'], 'Result says what happened; performance describes how.', 'Assuming a missed target identifies one definite technical cause.', 'Use observation of the movement alongside the outcome.', 'Is a score knowledge of results or knowledge of performance?', 'Knowledge of results.',
   'Give one example of each feedback type for a simple supervised throw.', '“The beanbag landed short” is knowledge of results. “Your release was lower than in the previous attempt” is knowledge of performance; its relevance still needs checking rather than assuming higher is always better.',
   detail(false, 'What is feedback?', 'Information used to understand and potentially improve an action.', 'Outcome data may be mistaken for a complete explanation of the movement that produced it.')],
  ['Challenge: choose practice variation for transfer', 'Balance repeated practice with changing demands according to the learning goal.',
   'Blocked practice repeats one task or condition; varied or interleaved practice changes demands or alternates tasks. Repetition can help a beginner establish a movement, while variation can require selection and adaptation closer to a game. Short-term practice success is not identical to durable learning or transfer. Compare later performance in an appropriate new situation rather than judge a method only by how smooth the practice looked.',
   'Compare repeatedly passing to one fixed target with passing to changing signalled targets.', ['The fixed target reduces decision demands and supports initial control.', 'The changing targets add perception and selection demands.', 'Choose or combine approaches according to the learner’s stage and transfer goal.'], 'Practice appearance is not the whole learning outcome.', 'Declaring one method best because immediate practice scores are higher.', 'Examine retention and application under the intended conditions.', 'What is transfer of learning?', 'Using learned skill in another relevant situation.',
   'Suggest a fair way to check whether varied practice helped a small group.', 'Use a supervised later task with comparable new target choices, record accuracy and appropriate decisions, and account for starting ability and unequal practice time. A small classroom comparison supports cautious conclusions, not a universal training rule.',
   detail(true, 'What is retention?', 'Keeping a skill or knowledge over time.', 'Immediate success is easier to observe than later independent performance, so it can dominate evaluation.')]
 ]]
]],
['pshe', [
 ['Boundaries, consent and support', [
  ['Recognise freely given and changeable agreement', 'Apply consent principles to everyday boundaries without requiring personal disclosures.',
   'Agreement should be freely chosen, specific and changeable. Silence, fear, pressure or an earlier yes does not establish permission now. These principles apply to everyday choices such as sharing a photo, borrowing belongings or physical contact. Respect a no or uncertainty without bargaining. If a boundary is ignored, move to safety where possible and tell a trusted adult; responsibility for the violation lies with the person crossing the boundary.',
   'A friend agreed to one photo but now says not to post it.', ['The earlier agreement to taking a photo was not blanket permission to share it.', 'The current refusal must be respected.', 'Do not post it; if it is already shared, seek removal and adult support if needed.'], 'Specific, free, current and changeable.', 'Treating one earlier yes as permanent permission for anything related.', 'Check the actual action and respect a changed decision immediately.', 'Does silence automatically mean agreement?', 'No.',
   'Write a respectful response to “I don’t want that photo shared”.', '“Okay, I won’t share it.” If it was already posted, explain that honestly, remove it where possible and help seek further removal without blaming the person for changing their mind.',
   detail(false, 'What is a personal boundary?', 'A limit concerning how someone wants their body, information, belongings or time treated.', 'Friendship or earlier agreement can be wrongly treated as entitlement to further access.')],
  ['Challenge: evaluate a bystander’s options without escalating harm', 'Compare safe supportive actions in a fictional boundary violation.',
   'A bystander may help by checking privately on the affected person, refusing to forward material, reporting through safe channels or seeking a trusted adult. Public confrontation can sometimes increase risk or spread the material further. Support should preserve the person’s dignity without promising secrecy when someone is unsafe. You do not need to investigate or confront a threatening person to deserve help.',
   'A group chat circulates an embarrassing ordinary photo after its subject asked for it not to be shared.', ['Do not forward or repost it as evidence to the whole group.', 'Offer private support and use reporting or trusted-adult help.', 'Consider whether a brief refusal to participate is safe, without making confrontation the only valid response.'], 'Support the person; do not amplify the harm.', 'Reposting the image publicly to condemn its circulation.', 'Report with minimum necessary exposure and ask an adult how to handle evidence safely.', 'Must a bystander confront someone publicly to be helpful?', 'No.',
   'Explain why promising “I will never tell anyone” may be unhelpful.', 'If someone is at risk, safe adult support may be needed. A better promise is to listen, explain what help you are seeking and share only what is necessary with appropriate people.',
   detail(true, 'Who could be a trusted adult at school?', 'A safeguarding lead, teacher or another adult responsible for pupil welfare.', 'A dramatic public response can seem supportive while increasing exposure or risk.')]
 ]],
 ['Managing money and recurring costs', [
  ['Build a budget with fixed and flexible commitments', 'Distinguish a planned balance from money already available.',
   'A budget compares expected income with planned spending over a specified period. Some commitments are fixed for that period, while others can be adjusted. Include saving and a buffer where possible, but do not assume every household has spare money. A positive planned balance depends on the income actually arriving and the estimates being realistic. Use fictional figures rather than disclose private household finances.',
   'A fictional club has £40 income, £18 materials and £12 transport costs.', ['Add planned costs: £18 + £12 = £30.', 'Subtract from income: £40 − £30 = £10.', 'Treat the £10 as the planned remainder, subject to the estimates and actual income.'], 'Choose a period, then compare inflows and commitments.', 'Mixing weekly income with monthly spending without conversion.', 'Put all figures on a consistent time basis.', 'What is the planned balance if income is £25 and costs are £19?', '£6.',
   'If materials actually cost £23 instead of £18, what happens to the club’s remainder?', 'Costs become £23 + £12 = £35, leaving £5 rather than £10. Updating the budget shows the effect of the changed estimate.',
   detail(false, 'What does subtraction help calculate in a simple budget?', 'The difference between income and spending.', 'Numbers with different periods or uncertain estimates can look more comparable than they are.')],
  ['Challenge: compare recurring offers by total cost', 'Look beyond a headline price when evaluating a fictional subscription.',
   'A low introductory price may be followed by a higher recurring charge. Compare the total over the same period, including stated fees, minimum terms and cancellation conditions. Do not enter payment details or accept a contract without appropriate adult permission. A cheaper total is not automatically better value if the service is unnecessary, unsuitable or hard to stop.',
   'Offer A costs £2 for one month then £6 for each of five months; B costs £5 per month for six months.', ['A totals £2 + 5 × £6 = £32.', 'B totals 6 × £5 = £30.', 'B is £2 cheaper over this six-month comparison, assuming no other charges.'], 'Compare the whole period, not only the first payment.', 'Choosing the smaller introductory price as the cheapest overall.', 'Calculate recurring charges and read the relevant conditions.', 'What does recurring mean?', 'Repeating at stated intervals.',
   'Name two non-price questions needed before recommending either offer.', 'Ask whether it meets a genuine need and how cancellation or renewal works. Age restrictions, permission, privacy and accessibility may also matter; the arithmetic alone does not settle suitability.',
   detail(true, 'What is a subscription?', 'An arrangement involving repeated payments or access over a period.', 'Prominent introductory prices can distract from renewal costs and conditions.')]
 ]],
 ['Emotional wellbeing and help-seeking', [
  ['Distinguish everyday coping from needing further support', 'Recognise that persistent distress or difficulty functioning deserves help.',
   'Feeling worried, sad or frustrated sometimes is common, but persistent distress, worsening symptoms or difficulty with sleep, learning and relationships can indicate a need for support. Coping actions such as a manageable routine, a break or talking may help, but they are not guaranteed cures and do not replace professional advice when needed. Speak to a trusted adult or health professional. If someone is in immediate danger in the UK, call 999 or seek emergency help.',
   'A fictional learner has felt overwhelmed for several weeks and is struggling to attend school.', ['Notice duration and effects on daily life rather than applying a label.', 'Encourage a conversation with a trusted adult or suitable health professional.', 'Offer practical support in seeking help without diagnosing or promising a quick cure.'], 'Notice impact; seek support rather than diagnose.', 'Assuming a person must manage alone until distress becomes an emergency.', 'Early support is appropriate; asking for help is not a failure.', 'Can someone ask for help without knowing a diagnosis?', 'Yes.',
   'Suggest an opening sentence for seeking support.', '“I’ve been feeling overwhelmed for several weeks and it is affecting school and sleep. Can we talk about getting help?” This communicates duration and impact without needing a medical label.',
   detail(false, 'What does wellbeing include?', 'How people are doing emotionally, physically and socially, among other aspects of life.', 'Distress may be dismissed as ordinary stress even when its duration and impact have changed.')],
  ['Challenge: evaluate an online wellbeing claim', 'Identify unsupported promises and separate personal testimony from reliable advice.',
   'A video claiming one product or routine cures everyone’s anxiety makes a sweeping health claim. Personal experience may be genuine without showing the same result for others. Check who is speaking, whether there is a commercial incentive, what evidence supports the claim and whether appropriate professional help is discouraged. Do not stop prescribed treatment or replace support with online advice; discuss concerns with a qualified professional.',
   'A sponsored post says its supplement means nobody needs counselling.', ['Recognise the universal promise and dismissal of other support.', 'Identify the sponsorship as a reason to examine incentives, not automatic proof every statement is false.', 'Seek trustworthy health information and professional advice instead of acting on the post alone.'], 'Test the evidence behind a promise, not the confidence of its delivery.', 'Treating a compelling personal story as proof of a universal treatment effect.', 'Distinguish testimony, advertising and research evidence.', 'Does a testimonial establish that a treatment works for everyone?', 'No.',
   'Write a cautious response to a friend considering the advertised claim.', '“That is a very broad promise, and one story cannot show it works for everyone. Let’s check reliable health information and speak to a qualified professional before changing any support or treatment.”',
   detail(true, 'What is a commercial incentive?', 'A financial reason to promote a product or service.', 'Relatable stories and confident presentation can be mistaken for strong evidence.')]
 ]]
]]
];
