import type { Subject, ActivityDetail } from '../authoredActivities';
const free: ActivityDetail = { isPremium: false, difficulty: 'Core', estimatedMinutes: 15, revision: 'Reconstruct the method tomorrow, then critique a different investigation next week. Separate observations from causal claims.' };
const extension: ActivityDetail = { ...free, isPremium: true, difficulty: 'Higher', estimatedMinutes: 20 };
export const year8Combined: Subject = ['science-combined', [
 ['Measurement and derived quantities', [
  ['Measure density using mass and volume', 'Choose a volume method suitable for a regular or irregular solid.',
   'Density is mass per unit volume. A cuboid’s volume can be calculated from dimensions, while a suitable insoluble irregular object can displace a measured volume of water. Trapped bubbles, absorbed water or incomplete submersion affect the result. State compatible units: grams divided by cubic centimetres gives g/cm³.',
   'An object has mass 54 g and displaces 20 cm³ of water.', ['Identify displaced volume as the submerged object’s volume under the method’s assumptions.', 'Calculate 54 ÷ 20.', 'Density is 2.7 g/cm³.'], 'Measure both quantities before taking the ratio.', 'Dividing volume by mass and reporting density.', 'Check that density means mass for each unit of volume.', 'What is a limitation of water displacement for a soluble solid?', 'Dissolving changes the object and invalidates the assumed volume measurement.',
   'A cuboid measures 2 cm by 3 cm by 5 cm and has mass 90 g. Find density.', 'Volume is 30 cm³. Density is 90/30 = 3 g/cm³, using all three dimensions rather than one face area.',
   { ...free, memoryExplanation: 'The ratio describes how much mass occupies a chosen volume.', misconceptionCause: 'Two measured quantities can be inverted if the physical meaning is not stated.' }],
  ['Challenge: evaluate an anomalous density result', 'Use method evidence to explain a biased derived value.',
   'Derived results inherit errors from their measurements. If measured volume is too large while mass is correct, calculated density is too low. A gas bubble trapped under a submerged object may increase the apparent displaced volume. Repeating the same flawed arrangement can produce consistent but biased values; investigate the method as well as repeatability.',
   'A true 10 cm³ object appears to displace 12 cm³ because of trapped air.', ['The denominator in mass/volume is overestimated.', 'Dividing by a larger denominator reduces the calculated value.', 'The density estimate is lower than the true value if mass is unchanged.'], 'Trace the error through the fraction.', 'Assuming repeatability proves accuracy.', 'A repeated systematic problem can preserve the same directional bias.', 'What happens to mass/volume if volume is overestimated?', 'The calculated density decreases.',
   'An object of mass 60 g is assigned volume 15 cm³ instead of 12 cm³. Compare calculated and true densities.', 'The estimate is 4 g/cm³; the true value is 5 g/cm³. The volume overestimate causes a 1 g/cm³ underestimate.',
   { ...extension, memoryExplanation: 'Following numerator and denominator effects reveals the direction of error.', misconceptionCause: 'A final number can conceal how separate measurement errors propagate.' }]
 ]],
 ['Planning and analysing rates', [
  ['Define a rate measurement operationally', 'Choose a measurable change and a consistent time interval.',
   'Rate describes change per unit time. A reaction producing gas can be compared using gas volume collected during a fixed interval, or time taken to collect a fixed volume. These are different measures and need clear units. A shorter time to the same endpoint implies a faster average rate, provided the endpoint and relevant conditions are comparable.',
   'Two reactions each collect 40 cm³ of gas, in 20 s and 50 s.', ['Calculate average volume rates: 40/20 and 40/50.', 'The results are 2 and 0.8 cm³/s.', 'The first is faster over the stated measurement interval.'], 'Specify what changes and per how much time.', 'Comparing times when the target gas volumes differ.', 'Use the same endpoint or compute comparable rates.', 'What does cm³/s measure here?', 'Gas volume collected per second.',
   'A reaction yields 30 cm³ in 15 s and another 45 cm³ in 30 s. Which average rate is greater?', '2 cm³/s versus 1.5 cm³/s. The first is faster even though its collected total is smaller.',
   { ...free, memoryExplanation: 'A common per-second basis permits comparisons of unequal totals.', misconceptionCause: 'Larger amounts can be mistaken for faster production without considering time.' }],
  ['Challenge: infer a changing rate from a graph', 'Use steepness and interval changes without confusing a final plateau with zero product.',
   'On a graph of cumulative gas volume against time, a steeper section means more gas produced per unit time. A horizontal plateau means no additional gas is being collected, not that the gas already made has disappeared. Average rates over long intervals can conceal a faster start and slower finish. Measurement delays may also affect early points.',
   'Volume rises from 10 to 34 cm³ between 5 and 13 s.', ['The volume change is 24 cm³.', 'The interval is 8 s.', 'Average rate for that interval is 3 cm³/s, not 34/13.'], 'Interval rate uses change over change.', 'Dividing a later total by its clock time for every interval question.', 'Subtract the starting values of both axes for the requested interval.', 'What does a horizontal cumulative-volume graph mean?', 'No further collected volume during that interval.',
   'Volume is 50 cm³ at both 40 s and 60 s. Find the interval rate and explain the total.', 'The interval rate is zero because volume changed by zero. Fifty cubic centimetres has still been collected; a zero rate does not mean zero accumulated amount.',
   { ...extension, memoryExplanation: 'Accumulated quantity and current rate answer different questions.', misconceptionCause: 'The graph height can be confused with its steepness.' }]
 ]],
 ['Biological sampling and uncertainty', [
  ['Estimate abundance with quadrats', 'Use a stated sampling area to estimate a larger population cautiously.',
   'Quadrats sample organisms within a known area. Random placement reduces selection bias compared with choosing visibly dense patches. Estimate mean count per quadrat, then scale by the number of equivalent quadrat areas in the site. The estimate assumes the sample adequately represents the site; patchiness and counting rules matter.',
   'Five 1 m² quadrats contain 3, 5, 4, 6 and 2 plants in a 100 m² plot.', ['The mean is 20/5 = 4 plants per square metre.', 'Multiply 4 by 100.', 'Estimate 400 plants, with uncertainty from sampling and spatial variation.'], 'Representative sample before scaling.', 'Choosing the greenest patches and calling the estimate unbiased.', 'Use an appropriate random or systematic design suited to the question.', 'Why define which plants count when crossing a quadrat edge?', 'A consistent boundary rule prevents selective counting.',
   'What would improve confidence beyond repeating calculations on the same five counts?', 'Collect more suitably placed independent samples and examine variation; recalculating the same data adds no new information.',
   { ...free, memoryExplanation: 'Multiplication magnifies sampling bias as well as measured abundance.', misconceptionCause: 'A precise final total can disguise the limited evidence behind an estimate.' }],
  ['Challenge: evaluate a transect explanation', 'Separate an environmental association from a demonstrated cause.',
   'A transect records changes along a line, useful across a gradient such as shade or distance from water. If plant abundance changes with light, light is a plausible influence but soil moisture, disturbance and other factors may change too. A well-designed report distinguishes the observed relationship from a causal explanation requiring further evidence.',
   'A transect shows fewer daisies nearer a shaded hedge.', ['State the spatial pattern and measured light change.', 'Consider co-varying moisture, roots or disturbance.', 'Propose further measurements or a controlled study before attributing the entire pattern to light.'], 'A gradient can change several things at once.', 'Claiming correlation alone isolates one cause.', 'Identify alternative variables and test the proposed mechanism.', 'Why is a transect different from purely random quadrat sampling?', 'It deliberately follows a spatial line or gradient.',
   'Why might repeating the transect at several comparable locations help?', 'It tests whether the pattern recurs beyond one local arrangement, though recurrence alone still does not fully isolate causation.',
   { ...extension, memoryExplanation: 'A shared spatial pattern may reflect more than the variable first noticed.', misconceptionCause: 'A visible gradient encourages a single-factor story.' }]
 ]]
]];
