import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 22 : 16, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, reconstruct the argument or belief accurately before evaluating it. In a week, address a different objection and distinguish an internal criticism from a disagreement about starting assumptions.' });
export const year9Religion: Subject = ['religious-studies', [
 ['Existence and explanatory arguments', [
  ['Distinguish a causal argument from a chronological story', 'Explain what an argument about ultimate dependence is trying to establish.',
   'Some cosmological arguments ask why dependent or contingent things exist at all, rather than merely what happened first in time. A contingent thing could have failed to exist and depends on conditions beyond itself. A proposed necessary foundation is intended to explain that dependence. This outline does not prove the argument: its premises about explanation and its move from individual things to the whole require examination.',
   'Explain why “the universe is old” does not directly answer a question about its dependence.', ['Age states how long something has existed.', 'Dependence asks what accounts for its existence or continuation.', 'An ancient object could still depend on conditions, so the questions are distinct.'], 'Earlier in time is not identical to deeper in explanation.', 'Assuming every cosmological argument merely names the first event.', 'Identify the specific version and the explanatory claim it makes.', 'What does contingent mean here?', 'Something that could have failed to exist and is not necessary in itself.',
   'Why should an evaluation state the premises before objecting?', 'Different arguments use different claims about causes, dependence and explanation. An objection to a universal claim that everything has a temporal cause may miss a version about contingent existence.',
   d(false, 'What is a premise?', 'A claim offered as a starting reason for a conclusion.', 'Different arguments can be merged under one familiar label and criticised as if they were identical.')],
  ['Challenge: test the move from a foundation to a particular God', 'Separate stages in an argument rather than accept a larger conclusion than its premises support.',
   'Even if an argument established an ultimate explanatory foundation, further reasoning would be needed to identify it with a particular religion’s God and attributes. Questions about personhood, goodness, revelation or worship do not automatically follow from the word cause. A careful evaluation can grant one stage for discussion while challenging another, without claiming either that the entire argument is proved or that every part is worthless.',
   'Assess “A first cause exists, therefore every teaching of my religion is true”.', ['Grant the first-cause claim temporarily to test the inference.', 'Identify the additional claims about identity and religious teachings.', 'Ask for independent reasoning linking the first conclusion to those further claims.'], 'A conclusion cannot silently grow beyond its support.', 'Treating one philosophical result as proof of an entire religious tradition.', 'Separate the stages and justify each inferential link.', 'Does granting a premise for discussion mean personally accepting it?', 'No.',
   'Write a respectful objection to the inference rather than to believers.', '“Even if the proposed foundation exists, the argument still needs to show that it has the specific qualities attributed to God in this tradition. That additional step cannot simply be assumed.”',
   d(true, 'What is an inference?', 'A reasoning step from premises towards a conclusion.', 'A familiar name for a proposed cause may import attributes the argument has not established.')]
 ]],
 ['Buddhist accounts of suffering and change', [
  ['Relate dukkha, craving and the path', 'Explain the Four Noble Truths without reducing Buddhism to pessimism.',
   'The Four Noble Truths concern dukkha, its arising, its cessation and a path towards cessation. Dukkha includes suffering and the unsatisfactoriness of clinging to unstable experiences. Craving and attachment are central to its explanation, but this is not a claim that every pain is a person’s fault. The Noble Eightfold Path integrates ethical conduct, mental cultivation and understanding; it is not merely a promise that positive thinking removes difficulty.',
   'Explain why the teaching includes both diagnosis and response.', ['Dukkha identifies a feature of experience requiring understanding.', 'Its arising and cessation explain a problem and a possible transformation.', 'The path concerns practices and understanding rather than a passive acceptance that nothing can improve.'], 'Problem, arising, cessation, path.', 'Calling Buddhism only a belief that life is miserable.', 'Include the account of liberation and the practical path.', 'Does the Eightfold Path concern ethics as well as mental cultivation?', 'Yes.',
   'Why avoid translating the teaching as “all wanting is always evil”?', 'It collapses distinctions between craving and beneficial intentions, and replaces a nuanced account of attachment with a moral slogan. Explain the relevant term and context rather than universalise an English word.',
   d(false, 'What does impermanence mean?', 'Things and experiences change rather than remain permanently fixed.', 'A broad translated term can be given a narrower everyday meaning that distorts the teaching.')],
  ['Challenge: connect non-self with ethical responsibility', 'Explain why rejecting an unchanging self need not mean actions have no consequences.',
   'Anatta is commonly explained as the absence of a permanent, independent self. This differs from claiming nobody exists in any ordinary sense or that actions do not matter. Buddhist accounts of continuity and karma link intentions, actions and consequences without requiring an eternal unchanging identity. Traditions develop these questions differently, so distinguish a careful introductory account from a complete theory of personal identity.',
   'Evaluate “If there is no permanent self, there can be no responsibility”.', ['Identify the hidden assumption that responsibility requires an unchanging essence.', 'Consider continuity of intentions, habits and consequences despite change.', 'Explain that rejecting permanence does not by itself reject causal or ethical continuity.'], 'Changing is not the same as consequence-free.', 'Interpreting non-self as permission to ignore harm.', 'Relate the teaching to ethical conduct and causal continuity.', 'Does anatta simply mean an immortal unchanging soul exists?', 'No.',
   'Give an analogy that helps distinguish continuity from complete sameness, and state its limit.', 'A river continues to be identified while its water changes. This can illustrate continuity without identical material, but it is only an analogy and does not establish a full Buddhist account of personhood or karma.',
   d(true, 'What is an analogy?', 'A comparison used to illuminate one relationship through another.', 'A difficult metaphysical teaching can be turned into a simplistic denial of ordinary experience.')]
 ]],
 ['Justice, service and public action', [
  ['Compare religious and humanist reasons for helping', 'Identify distinct justifications without assigning compassion exclusively to one worldview.',
   'A Christian may connect service with love of neighbour and human dignity before God; a Muslim may relate giving to duties including zakat and accountability; a humanist may ground assistance in shared humanity, wellbeing and responsibility. These are examples, not identical views held by every member. Similar actions can arise from different foundations, and people may combine several motives.',
   'Compare two volunteers doing the same food-distribution work for different stated reasons.', ['Identify the shared action and its practical aim.', 'Describe each person’s actual justification rather than infer it from a label.', 'Compare foundations without ranking sincerity from religious identity alone.'], 'Same action can have different foundations.', 'Assuming moral concern belongs only to religious or only to non-religious people.', 'Use stated reasons and recognise internal diversity.', 'Does a shared action prove identical beliefs?', 'No.',
   'What is missing from “They help because they are religious”?', 'It does not identify a particular teaching, interpretation or personal reason, and it ignores variation. A stronger explanation connects the person’s stated belief with the specific action.',
   d(false, 'What is a worldview?', 'A connected set of beliefs and commitments shaping how someone understands life and action.', 'Group labels may replace investigation of actual reasons and practices.')],
  ['Challenge: distinguish immediate relief from structural justice', 'Evaluate complementary responses to need without dismissing either automatically.',
   'Relief addresses an immediate need such as food or shelter. Structural action aims to change conditions that repeatedly produce need, such as exclusion, insecure access or unjust rules. Religious and non-religious organisations may pursue both. Evaluate urgency, affected people’s participation and likely effects; campaigning does not feed someone immediately, while immediate aid alone may leave the underlying cause unchanged.',
   'A fictional charity supplies meals and advocates changes to inaccessible benefit applications.', ['Meals respond to present hunger.', 'Application reform addresses a barrier contributing to repeated need.', 'The actions operate on different timescales and can complement each other.'], 'Meet the need and examine why it recurs.', 'Treating charity and justice as necessarily competing alternatives.', 'Compare mechanisms, timescales and the voices of affected people.', 'Does effective immediate relief prove the underlying problem has ended?', 'No.',
   'Why include recipients in evaluating the programme?', 'They can identify practical barriers, dignity concerns and unintended effects that donors may miss. Their participation helps test whether both relief and reform address actual needs rather than assumptions.',
   d(true, 'What is a structural cause?', 'A recurring feature of institutions or social arrangements that shapes outcomes.', 'Visible acts of help may draw attention away from repeated causes, or abstract reform may overlook urgent needs.')]
 ]]
]];
