import type { Topic, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 24 : 17, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, solve the worked example without notes and verify it independently. In a week, solve a changed problem and explain the domain, units and any approximation used.' });
export const year10Number: Topic[] = [
 ['Exact values and numerical bounds', [
  ['Simplify surds while retaining exactness', 'Extract square factors and combine only like surd terms.',
   'For non-negative values, √(ab) = √a × √b. Extracting a square factor gives √72 = √(36 × 2) = 6√2. Terms such as 3√2 and 5√2 combine like algebraic terms, but √2 + √3 does not become √5. Keeping a surd exact avoids rounding during later calculations; a decimal approximation is useful for checking magnitude, not replacing exact working without reason.',
   'Simplify √50 + √8.', ['Write √50 = 5√2 and √8 = 2√2.', 'Both terms have the same √2 factor.', 'Add coefficients to obtain 7√2.'], 'Extract square factors; combine matching roots.', 'Adding the numbers under separate square roots.', 'Test the proposed rule with a simple counterexample such as √1 + √1.', 'What is √18 in simplest surd form?', '3√2.',
   'Simplify 2√12 − √27.', '2√12 = 4√3 and √27 = 3√3, so the result is √3. The coefficients combine only after the radical factors match.',
   d(false, 'What is a square factor of 12?', '4.', 'The square-root operation may be assumed to distribute over addition as multiplication does.')],
  ['Challenge: calculate a bound for a quotient', 'Choose numerator and denominator extremes consistent with positive quantities.',
   'A measurement rounded to the nearest unit has an interval of possible values. If a positive speed is distance divided by time, its upper limiting value uses the largest possible distance and smallest possible time, not both upper bounds. State endpoint inclusion carefully: a value rounded to the nearest metre as 100 m conventionally represents 99.5 ≤ d < 100.5 m. Bounds describe an interval, not a guarantee that the true value is its midpoint.',
   'Distance is 100 m and time 20 s, each rounded to the nearest unit.', ['Use 99.5 ≤ d < 100.5 and 19.5 ≤ t < 20.5.', 'The upper limiting speed is 100.5/19.5, approximately 5.154 m/s.', 'The lower limiting speed is 99.5/20.5, approximately 4.854 m/s; endpoint attainability follows the original intervals.'], 'For a larger positive quotient: bigger top, smaller bottom.', 'Dividing upper distance by upper time to maximise speed.', 'Consider how each variable separately changes the quotient.', 'Does increasing a positive denominator increase the quotient when the numerator is fixed?', 'No.',
   'A positive length is 8.0 cm to the nearest 0.1 cm. State its error interval.', '7.95 ≤ L < 8.05 cm using the standard rounding convention. The half-step is 0.05 cm, not 0.1 cm.',
   d(true, 'What is half of one tenth?', '0.05.', 'Applying the same extreme to every measurement ignores whether a variable appears in the numerator or denominator.')]
 ]],
 ['Indices and standard form', [
  ['Interpret negative and fractional indices', 'Use reciprocals and roots while stating conditions on the base.',
   'For a non-zero base, a^(−n) = 1/a^n: a negative exponent signals a reciprocal, not a negative answer. For positive a, a^(1/2) = √a and a^(m/n) can be interpreted using roots and powers. Thus 16^(3/4) = (the fourth root of 16) cubed = 8. Restricting the base to positive values avoids additional real-domain issues in these introductory examples.',
   'Evaluate 27^(−2/3).', ['The cube root of 27 is 3.', 'Squaring gives 9.', 'The negative exponent takes the reciprocal, giving 1/9.'], 'Root, power, reciprocal as required.', 'Turning a negative exponent into a negative numerical result.', 'Separate the sign of the exponent from the sign of the base.', 'What is 5^(−2)?', '1/25.',
   'Evaluate 81^(3/4) and 16^(−1/2).', 'The fourth root of 81 is 3, so 81^(3/4) = 27. The square root of 16 is 4, so 16^(−1/2) = 1/4.',
   d(false, 'What does a reciprocal do?', 'Multiplies the original non-zero number to give one.', 'A minus sign in an exponent can be confused with a minus sign before the value.')],
  ['Challenge: normalise a standard-form calculation', 'Combine coefficients and powers, then enforce the standard-form coefficient range.',
   'Standard form is A × 10^n with 1 ≤ A < 10 for a positive number and integer n. Multiplying coefficients and combining powers can produce a non-standard intermediate result. For example, (6 × 10^5)(4 × 10^(−3)) = 24 × 10² = 2.4 × 10³. Renormalising changes coefficient and exponent together without changing the value.',
   'Calculate (8 × 10^7)/(2 × 10^(−2)).', ['Divide coefficients: 8/2 = 4.', 'Subtract exponents: 7 − (−2) = 9.', 'The result is 4 × 10^9, already in standard form.'], 'Coefficient arithmetic, exponent arithmetic, normalisation.', 'Subtracting exponents as 7 − 2 despite the denominator’s negative exponent.', 'Write the signed subtraction explicitly.', 'Is 0.6 × 10^8 in standard form?', 'No; its standard form is 6 × 10^7.',
   'Evaluate (3 × 10^4)(5 × 10^3) in standard form.', 'The intermediate result is 15 × 10^7. Moving one factor of ten into the power gives 1.5 × 10^8.',
   d(true, 'What happens to powers of the same base when multiplied?', 'Their exponents add.', 'Correct arithmetic can be followed by an incorrect normalisation that changes the represented value.')]
 ]],
 ['Quadratic equations and domain restrictions', [
  ['Use the zero-product rule to solve a factorised equation', 'Distinguish factorising an expression from finding values that make it zero.',
   'If a product is zero, at least one factor must be zero. Therefore (x − 4)(x + 2) = 0 gives x = 4 or x = −2. Factorising x² − 2x − 8 alone rewrites an expression; solving requires an equation and a specified right-hand side. The zero-product rule does not say one factor is zero when the product is a non-zero number.',
   'Solve x² + x − 6 = 0.', ['Factorise as (x + 3)(x − 2) = 0.', 'Set each factor equal to zero.', 'The solutions are x = −3 and x = 2; both satisfy the original equation.'], 'Zero product allows zero factors.', 'Setting factors to zero when the product equals a non-zero value.', 'Rearrange the equation to equal zero before applying the rule.', 'Does ab = 6 imply a = 0 or b = 0?', 'No.',
   'Solve x² − 9x = 0 without dividing away a solution.', 'Factorise as x(x − 9) = 0, giving x = 0 or x = 9. Dividing by x without considering x = 0 would lose a valid solution.',
   d(false, 'What is a factor?', 'A quantity multiplied with another to produce an expression or number.', 'A simplification step may divide by a variable that could legitimately equal zero.')],
  ['Challenge: simplify an algebraic fraction and retain excluded values', 'Cancel factors rather than terms and preserve the original expression’s domain.',
   'The fraction (x² − 9)/(x − 3) factorises to ((x − 3)(x + 3))/(x − 3). For x ≠ 3 it simplifies to x + 3, but the original expression remains undefined at x = 3. Cancellation does not fill the missing domain point. Only common multiplicative factors cancel; separate added terms cannot be cancelled across a fraction bar.',
   'Simplify (x² − 4)/(x + 2) and state the restriction.', ['Factor the numerator as (x − 2)(x + 2).', 'Cancel x + 2 for values where it is non-zero.', 'The result is x − 2 with x ≠ −2.'], 'Cancel factors; carry the exclusions.', 'Claiming the simplified formula is equivalent at the original zero denominator.', 'State the excluded value before cancelling.', 'What makes the original denominator x + 2 zero?', 'x = −2.',
   'Explain why (x + 4)/x is not simply 4.', 'The numerator is a sum, not a product with x as a common factor across every term. For x ≠ 0 it can be written 1 + 4/x, which is not generally 4.',
   d(true, 'Why is division by zero undefined in ordinary arithmetic?', 'There is no consistent quotient satisfying the usual multiplication relationship.', 'Visual matching of symbols can encourage cancelling terms that are not common factors.')]
 ]],
 ['Proportion and multiplicative change', [
  ['Model inverse proportion with a constant product', 'Find and use k when y is inversely proportional to x.',
   'Inverse proportion means y = k/x for non-zero x, or equivalently xy = k. Doubling x halves y in this model; it is not the same as any relationship in which y decreases as x increases. A fixed work task shared by equally productive workers can illustrate it only under strong assumptions about coordination and divisible work. State those assumptions instead of treating a real project as perfectly scalable.',
   'y is inversely proportional to x and y = 6 when x = 4.', ['Find k = xy = 4 × 6 = 24.', 'Write y = 24/x.', 'At x = 8, y = 3.'], 'Inverse proportion keeps the product fixed.', 'Using a constant difference or y = kx instead.', 'Check which quantity stays invariant.', 'If x triples in an inverse-proportion model, what happens to y?', 'It becomes one third as large.',
   'For y = k/x with y = 5 at x = 12, find y at x = 15.', 'k = 60, so y = 60/15 = 4. The constant product 15 × 4 = 60 verifies the result.',
   d(false, 'What does direct proportion look like algebraically?', 'y = kx.', 'A general decreasing trend can be mistaken for the specific constant-product relationship.')],
  ['Challenge: reverse successive percentage changes', 'Undo multiplicative factors in reverse without adding percentages.',
   'Successive percentage changes multiply factors because each operates on a new base. Increasing a price by 20 percent then reducing it by 20 percent multiplies by 1.2 × 0.8 = 0.96, not one. To recover an original amount, divide the final amount by the combined multiplier. Keep intermediate values exact where possible rather than round each step prematurely.',
   'An item rises by 10 percent then falls by 20 percent to £88.', ['The combined multiplier is 1.1 × 0.8 = 0.88.', 'Let the original be p, so 0.88p = 88.', 'Divide to obtain p = £100.'], 'Percentages act on changing bases; multiply the factors.', 'Subtracting 20 from 10 and calling the net change −10 percent.', 'Use one multiplier per change and combine them.', 'What multiplier represents a 15 percent reduction?', '0.85.',
   'After a 25 percent rise, what percentage reduction returns the amount to its original value?', 'The required multiplier is 1/1.25 = 0.8, so the reduction is 20 percent. The increase and reversal use different bases.',
   d(true, 'What multiplier represents a 10 percent increase?', '1.10.', 'Equal percentage magnitudes can be mistaken for inverse operations despite different reference amounts.')]
 ]]
];
