import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 24 : 17, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, reconstruct the reasoning using a short quotation. In a week, apply the skill to an unfamiliar passage and edit any claim that outruns its evidence.' });
export const year10EnglishLanguage: Subject = ['english-lang', [
 ['Close reading and lexical patterns', [
  ['Develop an inference through a cluster of words', 'Connect several related choices rather than overanalyse one isolated adjective.',
   'In the original model “The queue tightened. Shoulders pressed together; a mutter travelled from face to face”, several choices present crowd pressure. Tightened suggests reduced space, pressed adds contact and the moving mutter spreads unease. A lexical pattern supports an inference more securely than a claim based on one word alone. Avoid calling every related word a semantic field unless you explain the particular relationship and its contribution.',
   'Explain how the model creates collective tension.', ['Identify physical compression in tightened and pressed.', 'Connect the mutter with communication spreading through the group.', 'Argue that physical and social pressure combine, rather than assuming the crowd is already violent.'], 'Connect evidence into a pattern, then bound the inference.', 'Turning tension into certainty of violence without supporting action.', 'Distinguish what the text suggests from what it establishes.', 'Which word describes direct physical contact?', 'Pressed.',
   'Write a concise analytical sentence using two choices.', '“The verbs ‘tightened’ and ‘pressed’ reduce the crowd’s sense of personal space, while the travelling ‘mutter’ suggests unease spreading between people.” The sentence explains relationships instead of merely listing quotations.',
   d(false, 'What is an inference?', 'A conclusion drawn from details rather than directly stated.', 'A striking individual word can attract speculation that the wider passage does not support.')],
  ['Challenge: compare literal action with figurative agency', 'Explain personification without assigning a fixed emotion to every example.',
   'The original sentence “The corridor swallowed her footsteps” transfers an action associated with a living mouth to a space. It can suggest sound being absorbed and the person becoming less perceptible. Context determines whether that feels protective, lonely or threatening. A strong analysis moves from the particular verb and its ordinary associations to a justified reading, rather than declaring all personification makes a setting scary.',
   'Analyse swallowed in a passage about a character hiding from a pursuer.', ['Identify the figurative agency given to the corridor.', 'Connect swallowed with sound disappearing or being enclosed.', 'Use the pursuit context to argue that concealment may offer temporary protection while also making the space oppressive.'], 'Technique names the transfer; context selects the effect.', 'Using the same ready-made effect for every personification.', 'Explain the chosen verb’s associations and the surrounding situation.', 'Is the corridor literally eating footsteps?', 'No.',
   'How might the interpretation change in a passage about bereavement?', 'The disappearing sound could emphasise absence or isolation rather than pursuit. The language permits associations, but the surrounding narrative must support the selected interpretation.',
   d(true, 'What is personification?', 'Giving human or animate qualities to something non-human or abstract.', 'Memorised device-effect pairs can replace reading the actual passage.')]
 ]],
 ['Structural analysis across an extract', [
  ['Explain a turning point through contrast before and after', 'Locate a change in the reader’s understanding rather than only a dramatic event.',
   'A structural turning point changes the direction, focus or interpretation of a passage. In an original model, a character carefully polishes an empty trophy cabinet before a phone call reveals a disqualification. The call reinterprets the earlier care as denial or preparation for loss. Analyse what the reader knew before, what changes and how subsequent detail develops the shift. Naming a climax without these relationships is incomplete.',
   'Explain the role of the disqualification call.', ['Before it, the cabinet may suggest pride or expectation.', 'The call supplies information that undermines that reading.', 'Later attention to the empty cabinet can now carry disappointment rather than simple display.'], 'Before, new information, revised understanding.', 'Calling the loudest moment the turning point without considering meaning.', 'Trace the passage’s informational and emotional direction.', 'Can a quiet revelation be a turning point?', 'Yes.',
   'Suggest an ending detail that develops the changed meaning without stating an emotion directly.', 'A character might leave the polishing cloth inside the empty cabinet and close it. The action can signal withdrawal from the earlier ritual, though its effect depends on the full passage.',
   d(false, 'What does chronology describe?', 'The order in which events occur.', 'Event order can be mistaken for an explanation of how the writer organises understanding.')],
  ['Challenge: evaluate a cyclical ending that changes its opening image', 'Distinguish purposeful recurrence from simple repeated wording.',
   'A cyclical structure returns to an opening image or situation, but the intervening passage can alter its significance. An opening “The gate stood open” may promise freedom; the same image after a failed search may suggest exposure or loss. Explain both continuity and change. Repetition alone does not guarantee closure, and a return can leave a question unresolved rather than neatly conclude it.',
   'A narrative begins and ends with an unclaimed coat hanging by a door.', ['The opening establishes an unexplained object.', 'The narrative supplies information about an absent owner.', 'The final return can make the unchanged coat register absence more strongly.'], 'Same image, changed knowledge.', 'Saying a repeated image creates closure without explaining its revised meaning.', 'Compare the reader’s understanding at each occurrence.', 'Must a cyclical ending resolve every question?', 'No.',
   'Write a structural claim that acknowledges an unresolved ending.', '“Returning to the coat frames the narrative, but its continued presence leaves the owner’s absence unresolved. The repetition therefore creates formal completion while preserving emotional uncertainty.”',
   d(true, 'What is a motif?', 'A recurring element that contributes to a work’s patterns of meaning.', 'Formal repetition may be confused with a completely resolved narrative outcome.')]
 ]],
 ['Evaluation and balanced evidence', [
  ['Test a supplied judgement against supporting and limiting details', 'Build an evidence-led response instead of treating agreement as the task.',
   'An evaluative prompt may propose that a character appears entirely confident. Test entirely as well as confident: fluent speech might support the impression while a repeated glance at the exit complicates it. A judgement can largely agree while qualifying its scope. Select details that genuinely bear on the claim, then explain how they interact rather than count quotations on each side.',
   'Evaluate an original character who speaks firmly but folds and refolds a note.', ['Firm delivery supports outward confidence.', 'Repeated handling of the note may suggest unease, depending on context.', 'A qualified judgement can distinguish public control from possible private anxiety.'], 'Test the qualifier as carefully as the main adjective.', 'Ignoring contradictory evidence to preserve a simple agree-or-disagree answer.', 'Use tension between details to refine the judgement.', 'Does partly agreeing mean avoiding a conclusion?', 'No, if the qualification is explained.',
   'Write a balanced judgement without diagnosing the character.', '“The firm delivery creates a controlled public impression, but the repeated folding of the note complicates complete confidence. It may suggest unease, although the passage would need further evidence to establish its cause.”',
   d(false, 'What does evaluation require beyond identification?', 'A justified judgement using relevant criteria and evidence.', 'A prompt’s wording may be repeated as a fact rather than tested as a proposition.')],
  ['Challenge: distinguish narrator endorsement from represented opinion', 'Evaluate whose judgement a passage invites the reader to question.',
   'A narrator can report a character’s boast without endorsing it. In the original model “He called himself indispensable; the meeting began comfortably without him”, the second clause undermines the first. Evaluate how framing creates distance between the represented claim and the account’s broader implications. Do not attribute every statement inside a text directly to its writer’s personal beliefs.',
   'Analyse the relationship between indispensable and comfortably without him.', ['The boast claims essential importance.', 'The meeting’s ease without him contradicts that claim.', 'The juxtaposition invites scepticism towards his self-assessment.'], 'Quoted opinion is evidence about a voice, not automatic endorsement.', 'Treating a character’s claim as the narrator’s final judgement.', 'Examine the framing and competing details.', 'Which part most directly undermines the boast?', 'The meeting beginning comfortably without him.',
   'Why is “the writer thinks nobody matters” too broad a conclusion?', 'The contrast targets this character’s self-importance in a particular situation. Extending it into a universal belief about all people goes beyond the provided evidence.',
   d(true, 'What is juxtaposition?', 'Placing elements close together so their relationship or contrast becomes significant.', 'A local ironic contrast can be expanded into an unsupported universal claim about the author.')]
 ]],
 ['Comparing non-fiction methods', [
  ['Integrate evidence from both sources around one claim', 'Compare how writers frame responsibility rather than summarise each text separately.',
   'Original source A says “Residents must reduce waste”; source B says “Manufacturers must design out unnecessary packaging.” Both advocate less waste but allocate responsibility differently. A comparative claim can analyse the grammatical subjects and imperative force of must, then consider what each foregrounds or omits. A common concern does not imply an identical solution, audience or distribution of responsibility.',
   'Compare the role of residents and manufacturers in the model statements.', ['Identify the shared problem of waste.', 'Compare the groups made responsible by each sentence.', 'Explain that A foregrounds household behaviour while B foregrounds production decisions.'], 'One comparison question, evidence from both sources.', 'Writing two disconnected summaries with only both added at the end.', 'Organise the paragraph around a shared analytical focus.', 'What modal verb gives both statements obligation?', 'Must.',
   'Write a comparative sentence that does not claim the views are necessarily incompatible.', '“Both writers press for reduced waste, but A’s focus on ‘Residents’ emphasises individual behaviour whereas B’s ‘Manufacturers’ shifts attention to production; the approaches could be complementary rather than mutually exclusive.”',
   d(false, 'What does a sentence’s grammatical subject identify?', 'The participant or entity about which the clause is structured.', 'Difference of emphasis can be mistaken for complete disagreement.')],
  ['Challenge: compare anecdote and aggregate evidence', 'Explain their different persuasive roles without declaring one universally superior.',
   'A personal account can make consequences vivid, while aggregate data can indicate a wider pattern when collected appropriately. Neither automatically establishes the other’s claim: one experience does not prove prevalence, and a percentage alone may hide lived effects or sampling weaknesses. Compare how the sources combine evidence with language, acknowledging what each can and cannot support.',
   'An original account describes one inaccessible bus journey; another reports a survey of route accessibility.', ['The account can illuminate an individual barrier and its consequences.', 'The survey may estimate a pattern if its sample and measures are appropriate.', 'A strong comparison evaluates both evidential scope and presentation rather than dismissing either format.'], 'Anecdote shows an experience; data needs a defined population.', 'Calling every statistic objective proof or every anecdote worthless.', 'Inspect method, scope and rhetorical framing.', 'Does a single experience establish how common an issue is?', 'No.',
   'Why might the two sources together be more informative than either alone?', 'The account can show how a barrier operates, while a sound survey can indicate its extent. Combining them still requires checking whether they concern comparable situations and populations.',
   d(true, 'What does representative mean for a sample?', 'Adequately reflecting the relevant population for the intended inference.', 'Evidence types may be ranked abstractly without considering the question they answer.')]
 ]],
 ['Transactional writing and audience', [
  ['Shape a formal letter around a practical request', 'Organise purpose, evidence and a realistic action for the recipient.',
   'A formal letter should help its recipient understand the issue and what response is requested. State the purpose, explain relevant evidence and propose a feasible action with an appropriate tone. Formality does not require inflated vocabulary or hostility. A complaint about unsafe access is clearer when it identifies the location and problem than when it relies on insults or unsupported universal claims.',
   'Plan an original letter requesting review of an inaccessible entrance.', ['Identify the entrance and the specific access barrier.', 'Explain its effects using supplied or accurately observed information.', 'Request a review and a response about possible improvements rather than inventing legal guarantees.'], 'Purpose, evidence, requested action.', 'Using an angry tone instead of a clear account of the problem.', 'Make the request specific and support it with relevant details.', 'Does formal writing require the longest available words?', 'No.',
   'Write a focused opening sentence without inventing facts.', '“I am writing to request a review of the main entrance’s accessibility, particularly the step that prevents independent access for some visitors.” A real letter should include only details the writer can support.',
   d(false, 'What is an audience?', 'The people a text is intended to reach.', 'Strong feeling can be mistaken for sufficient organisation or evidence.')],
  ['Challenge: adapt the same argument for a speech', 'Use spoken signposting and audience connection without losing precision.',
   'A speech must be understandable as it unfolds, often without rereading. Clear signposts, controlled repetition and shorter units can help listeners follow an argument. Adapting a letter means more than adding a greeting: reconsider evidence density, transitions and delivery. Rhetorical questions should advance the reasoning rather than substitute emotional pressure for a supported proposal.',
   'Adapt an access-review request for a school assembly.', ['Open with the issue in direct, clear language.', 'Organise a small number of reasons with audible signposts.', 'End with a specific action listeners can understand and support.'], 'Write for ears without abandoning evidence.', 'Reading a dense written report unchanged and expecting listeners to retain every detail.', 'Select essential evidence and mark transitions explicitly.', 'Why can controlled repetition help a speech?', 'It reinforces key relationships for listeners who cannot reread earlier sentences.',
   'Write a closing line that combines principle and action.', '“Access should not depend on who can manage a step; let us ask for a practical review and make sure those affected help shape the solution.” The line links a value to a defined process rather than promising instant results.',
   d(true, 'What is signposting in writing or speech?', 'Language that makes the argument’s structure and transitions clear.', 'Changing format can be treated as a cosmetic edit rather than a change in how the audience receives information.')]
 ]],
 ['Narrative craft and exam control', [
  ['Use a recurring object to organise a short narrative', 'Develop a manageable time span and changed meaning instead of an overloaded plot.',
   'A short narrative can gain coherence through one object whose meaning changes. An unopened envelope may begin as hope, become a source of hesitation and end as a deliberate decision to wait. Limit characters and time so the change can be developed through actions and details. An elaborate chain of disasters often leaves little room for controlled description, syntax or believable motivation.',
   'Plan a short original narrative centred on a spare key.', ['Establish who holds it and what access it represents.', 'Introduce a choice or discovery that changes its significance.', 'Return to the key through a concrete action reflecting the changed relationship.'], 'One object can carry a developed change.', 'Adding multiple unrelated twists instead of developing the initial situation.', 'Choose a clear focus and make details serve its progression.', 'Must a short narrative cover many years to be meaningful?', 'No.',
   'Suggest a restrained ending action for a story about giving up control of a room.', 'The character could leave the key on the table and walk out without checking the lock. Its meaning depends on the earlier situation; the action can imply change without an explanatory moral.',
   d(false, 'What is a motif?', 'A recurring element that gathers significance across a text.', 'Plot quantity can be mistaken for depth or narrative control.')],
  ['Challenge: revise against the task rather than a memorised response', 'Use planning and editing to preserve relevance and technical accuracy.',
   'An exam response must answer the actual task and source, not display a prewritten essay regardless of fit. Before writing, identify the command, focus, audience and any specified range. During editing, check relevance, paragraph links, sentence boundaries and evidence accuracy. Timing strategies depend on the paper’s instructions; this lesson teaches transferable control rather than inventing a universal mark scheme or required paragraph formula.',
   'A task asks for tension in the final section, but a draft analyses only the opening setting.', ['Identify the requested focus and range.', 'Select relevant final-section evidence instead of stretching opening comments.', 'Revise the argument so each paragraph addresses tension in the specified section.'], 'Task first; technique only when it serves the answer.', 'Forcing a memorised paragraph onto unrelated evidence.', 'Check each claim against the question’s exact boundaries.', 'Does naming many techniques guarantee relevance?', 'No.',
   'What should a last-minute edit prioritise over adding an unrelated sophisticated word?', 'Correct a misleading claim, incomplete sentence or unclear link to the task. Accuracy and relevance are more useful than decorative vocabulary detached from the argument.',
   d(true, 'What is a command word in a question?', 'The word indicating the requested action, such as explain, compare or evaluate.', 'Prepared material can feel valuable enough to include even when it does not answer the question.')]
 ]]
]];
