import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 22 : 16, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, redraw the particle model or repeat the calculation. In a week, apply the explanation to a different substance and state which assumptions still hold.' });
export const year9Chemistry: Subject = ['chemistry', [
 ['Atomic structure and isotopes', [
  ['Calculate particles from atomic and mass numbers', 'Distinguish nuclear particle counts from electrical charge.',
   'Atomic number counts protons; mass number counts protons plus neutrons in one isotope. A neutral atom has as many electrons as protons. Forming an ion changes electron number without changing which element it is. For sodium with atomic number 11 and mass number 23, there are 11 protons and 12 neutrons; neutral sodium has 11 electrons, while Na+ has 10.',
   'Find the particle counts in a magnesium-24 ion, Mg2+, with atomic number 12.', ['There are 12 protons.', 'Neutrons equal 24 − 12 = 12.', 'A 2+ charge means two fewer electrons than protons, giving 10 electrons.'], 'Protons identify; neutrons change isotope; electrons change charge.', 'Adding electrons to make a positive ion.', 'Remember electrons are negatively charged, so losing them produces positive charge.', 'Does forming Mg2+ change magnesium’s proton number?', 'No.',
   'Find protons, neutrons and electrons in Cl− with atomic number 17 and mass number 35.', 'There are 17 protons, 18 neutrons and 18 electrons. The extra electron supplies the negative charge; mass number is determined by nuclear particles.',
   d(false, 'What charge does an electron have?', 'Negative.', 'The plus sign may be interpreted as adding particles without checking which charge they carry.')],
  ['Challenge: calculate a weighted relative atomic mass', 'Use isotope abundances rather than an unweighted average.',
   'An element’s relative atomic mass reflects a weighted mean of its naturally occurring isotopes relative to the carbon-12 scale. In a simplified example with isotope masses 10 and 11 at 20 percent and 80 percent abundance, the mean is 10 × 0.20 + 11 × 0.80 = 10.8. No individual atom needs to have mass number 10.8; the decimal describes a population average.',
   'Calculate the mean for fictional abundances of masses 24 at 75 percent and 26 at 25 percent.', ['Convert abundances to 0.75 and 0.25.', 'Calculate contributions 18 and 6.5.', 'Their sum is 24.5, closer to the more abundant mass 24.'], 'Weight each isotope before adding.', 'Taking the midpoint when isotope abundances differ.', 'Multiply each isotope mass by its fractional abundance.', 'Must the mean correspond to one isotope’s mass number?', 'No.',
   'For masses 30 and 32 with equal abundances, calculate the mean and explain why the midpoint works here.', 'The mean is 30 × 0.5 + 32 × 0.5 = 31. The midpoint works specifically because the weights are equal, not because all isotope calculations use a simple midpoint.',
   d(true, 'What fraction is 25 percent?', 'One quarter, or 0.25.', 'An ordinary arithmetic mean can be used without recognising unequal contributions.')]
 ]],
 ['Bonding and bulk properties', [
  ['Explain ionic lattices and conductivity', 'Relate movement of charged particles to the physical state.',
   'Ionic bonding is electrostatic attraction between oppositely charged ions in a lattice. Solid sodium chloride contains ions, but they cannot move freely through the solid, so it does not conduct electricity in the usual way. When molten, its ions can move and carry charge. Many soluble ionic substances also conduct in aqueous solution. Do not confuse having charged particles with having mobile charge carriers.',
   'Compare solid and molten sodium chloride.', ['Both contain sodium and chloride ions.', 'In the solid, the lattice fixes their positions apart from vibration.', 'Melting allows ions to move, enabling conduction; it does not require turning them into neutral atoms.'], 'Conduction needs charges that can move.', 'Claiming solid salt has no ions because it does not conduct.', 'Separate particle identity from particle mobility.', 'Which particles carry charge in molten sodium chloride?', 'Mobile ions.',
   'Why does dissolved sodium chloride conduct while a solution of a simple molecular sugar usually does not appreciably conduct?', 'Dissolved salt supplies mobile ions. Dissolving sugar mainly disperses neutral molecules, so it does not supply comparable ionic charge carriers; concentration and impurities affect real measurements.',
   d(false, 'What attracts a positive and a negative charge?', 'Electrostatic attraction.', 'Observations of conductivity may be taken as evidence about whether charge exists rather than whether it moves.')],
  ['Challenge: distinguish intermolecular forces from covalent bonds', 'Explain melting without claiming every internal molecular bond breaks.',
   'A simple molecular substance has strong covalent bonds within molecules and attractions between molecules. Melting or boiling usually separates molecules by overcoming intermolecular attractions without breaking their internal covalent bonds. This differs from giant covalent structures, where an extended network influences properties. A low boiling point does not prove the covalent bonds within a molecule are weak.',
   'Explain liquid water becoming water vapour.', ['Water molecules move farther apart during vaporisation.', 'Attractions between molecules are overcome.', 'The molecules remain H2O rather than routinely splitting into hydrogen and oxygen.'], 'Between molecules is not within molecules.', 'Explaining boiling as decomposition of every molecule.', 'Track whether the chemical identity changes, not only the state.', 'Does boiling pure water normally change H2O into H2 and O2?', 'No.',
   'Why is “all covalent substances have low melting points” false?', 'It confuses simple molecular substances with giant covalent networks such as diamond or silicon dioxide. Extended strong bonding gives different bulk properties; structure must be identified before applying a property rule.',
   d(true, 'What is a covalent bond?', 'A shared pair of electrons attracted to the bonded nuclei.', 'The word bond is used loosely for different interactions at different structural levels.')]
 ]],
 ['Rates and particle explanations', [
  ['Use collision theory to explain concentration effects', 'Connect more frequent successful collisions with reaction rate.',
   'For a reaction between particles, collisions must occur with sufficient energy and an appropriate arrangement to lead to reaction. Increasing reactant concentration puts more particles in a given volume, often increasing collision frequency and therefore successful collisions per second. It does not by itself mean each particle moves faster. Temperature, exposed surface and other conditions must be controlled to isolate concentration’s effect.',
   'Explain a faster reaction after increasing acid concentration at the same temperature.', ['More acid particles occupy each unit volume.', 'Collisions with the other reactant can occur more often.', 'More successful collisions per second increase rate, without requiring a higher particle speed from concentration alone.'], 'Concentration changes crowding, not temperature.', 'Explaining every faster reaction as particles moving faster.', 'Identify which physical factor was changed and its mechanism.', 'What does reaction rate describe?', 'How quickly reactants are used or products form.',
   'Why might increasing the total volume of the same concentration not increase the initial rate for an unchanged exposed solid surface?', 'The local concentration at the surface has not necessarily changed, so initial collision conditions may be similar. More total reactant can change the duration or final quantity rather than automatically changing initial rate.',
   d(false, 'What does concentration compare?', 'The amount of a substance with the volume containing it.', 'Amount and concentration can be treated as interchangeable quantities.')],
  ['Challenge: explain a catalyst without changing the energy difference', 'Distinguish activation energy from overall reaction energy change.',
   'A catalyst provides an alternative reaction pathway with lower activation energy and is regenerated overall. Lowering this barrier allows a greater proportion of collisions to succeed at the same temperature. It does not change the energy difference between the same reactants and products, and it does not supply unlimited reactant. On an energy profile, the catalysed peak is lower while starting and ending levels remain unchanged.',
   'Describe catalysed and uncatalysed profiles for the same exothermic reaction.', ['Both start at the same reactant level and end at the same lower product level.', 'The catalysed pathway has a lower maximum barrier.', 'The energy released overall remains the difference between the unchanged endpoints.'], 'Lower barrier, same endpoints.', 'Drawing the products lower merely because a catalyst is present.', 'Separate the pathway barrier from the reactant-product energy difference.', 'Is a catalyst consumed overall in its catalytic cycle?', 'No.',
   'Why does a catalyst not guarantee more final product when the same limiting reactant is completely consumed?', 'It changes the rate and pathway, not the starting amount of limiting reactant or the stoichiometric yield for complete conversion. A faster arrival at the endpoint is not necessarily a larger endpoint.',
   d(true, 'What does exothermic mean?', 'Energy is transferred from the reacting system to the surroundings.', 'A faster energy release can be mistaken for a greater total energy release.')]
 ]]
]];
