import type { Subject, ActivityDetail } from '../authoredActivities';
const detail = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({
 isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 22 : 16,
 priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause,
 revision: 'Tomorrow, solve the worked problem without notes and justify each step. In a week, try changed values and verify the answer by substitution, estimation or an independent calculation.'
});
export const year9Maths: Subject = ['maths', [
 ['Quadratics and simultaneous equations', [
  ['Expand a product of two linear expressions', 'Account for all four products and collect like terms.',
   'Multiplying two brackets requires every term in the first bracket to multiply every term in the second. For (x + 3)(x + 5), the products are x², 5x, 3x and 15, giving x² + 8x + 15. The middle term comes from two cross-products. An area diagram or a four-cell table can organise the reasoning; it is the distributive law, not a rule that only the first and last terms multiply.',
   'Expand (x − 2)(x + 7).', ['Multiply to obtain x² + 7x − 2x − 14.', 'Collect the two linear terms to give 5x.', 'The result is x² + 5x − 14.'], 'Every term meets every term.', 'Omitting the cross-products or making the negative constant positive.', 'Record all four products with their signs before simplifying.', 'What is 7x − 2x?', '5x.',
   'Expand (x − 4)(x + 3) and check at x = 2.', 'The expansion is x² − x − 12. At x = 2 the brackets give (−2)(5) = −10 and the expansion gives 4 − 2 − 12 = −10, supporting the calculation.',
   detail(false, 'What does 3(x + 2) expand to?', '3x + 6.', 'A one-bracket distribution pattern may be incompletely applied when both factors contain two terms.')],
  ['Factorise a monic quadratic using sum and product', 'Reverse expansion by finding a pair with the required sum and product.',
   'For x² + bx + c, a factorisation (x + p)(x + q) requires p + q = b and pq = c. Both conditions matter. A positive product can come from two positive or two negative numbers; the middle coefficient decides the appropriate sum. Not every quadratic factorises with integer values, so an unsuccessful integer search is not proof the expression is invalid.',
   'Factorise x² − 7x + 12.', ['Find factors of 12 whose sum is −7.', 'The pair −3 and −4 has product 12 and sum −7.', 'Write (x − 3)(x − 4) and expand to check.'], 'Product gives the constant; sum gives the middle coefficient.', 'Choosing 3 and 4 because their product is correct while ignoring the negative sum.', 'Test both conditions, including signs.', 'What is the sum of −3 and −4?', '−7.',
   'Factorise x² + x − 12.', '(x + 4)(x − 3), because 4 + (−3) = 1 and 4 × (−3) = −12. Expansion gives x² + x − 12.',
   detail(false, 'What is factorisation?', 'Rewriting an expression as a product of factors.', 'Checking only a product overlooks the cross-term requirement revealed by expansion.')],
  ['Challenge: eliminate a variable and verify both equations', 'Solve a simultaneous pair by creating matching coefficients.',
   'A simultaneous solution must satisfy both equations at once. Elimination creates equal or opposite coefficients so one variable cancels when the equations are subtracted or added. Multiplying an equation requires multiplying every term on both sides. After finding one variable, substitute to find the other and check the ordered pair in both original equations, not only in a transformed equation.',
   'Solve 2x + 3y = 17 and 3x + 2y = 18.', ['Multiply the first equation by 3: 6x + 9y = 51; multiply the second by 2: 6x + 4y = 36.', 'Subtract to obtain 5y = 15, so y = 3.', 'Then 2x + 9 = 17 gives x = 4; checking the second gives 12 + 6 = 18.'], 'One pair must satisfy both originals.', 'Multiplying the left side but leaving the right side unchanged.', 'Apply the same operation to the entire equation.', 'What happens to equal x terms when the equations are subtracted?', 'They cancel.',
   'Solve x + 2y = 11 and 3x + y = 13.', 'Multiply the first by 3 to obtain 3x + 6y = 33. Subtract the second: 5y = 20, so y = 4. Then x = 3. Checks: 3 + 8 = 11 and 9 + 4 = 13.',
   detail(true, 'What does a solution to an equation mean?', 'A value making its two sides equal.', 'A value that works in one equation may be mistaken for a solution to the whole system.')]
 ]],
 ['Right triangles and similarity', [
  ['Choose the correct form of Pythagoras’ theorem', 'Find a missing side only after identifying the right angle and hypotenuse.',
   'In a right-angled triangle, a² + b² = c² when c is the hypotenuse opposite the right angle. To find a shorter side, subtract the other shorter side’s square from the hypotenuse’s square before taking a square root. The theorem is not valid for every triangle without modification. Identify the geometry before choosing a calculation, and keep the side-length units separate from squared intermediate quantities.',
   'A right triangle has hypotenuse 13 cm and one shorter side 5 cm.', ['Let the missing shorter side be b, so 5² + b² = 13².', 'Then b² = 169 − 25 = 144.', 'The positive side length is b = 12 cm.'], 'Hypotenuse square equals the sum of the other two squares.', 'Adding the squares when the missing side is not the hypotenuse.', 'Name the hypotenuse before rearranging.', 'Where is the hypotenuse?', 'Opposite the right angle.',
   'A right triangle has shorter sides 9 cm and 12 cm. Find its hypotenuse.', 'c² = 81 + 144 = 225, so c = 15 cm. It is longer than either shorter side, which is a useful plausibility check.',
   detail(false, 'What is the positive square root of 144?', '12.', 'A memorised add-and-root procedure can be used without checking which side is unknown.')],
  ['Distinguish length and area scale factors', 'Square the linear factor when comparing areas of similar shapes.',
   'Similar shapes have equal corresponding angles and proportional corresponding lengths. If every length is multiplied by k, area is multiplied by k² because two independent dimensions scale. Doubling a rectangle’s length and width produces four times its area, not twice. Match corresponding lengths first and state whether a question asks about length, area or volume before selecting a factor.',
   'Similar triangles have corresponding sides 3 cm and 9 cm; the smaller area is 8 cm².', ['The linear scale factor from small to large is 9/3 = 3.', 'The area factor is 3² = 9.', 'The larger area is 8 × 9 = 72 cm².'], 'Two dimensions make the area factor square.', 'Multiplying an area by the linear factor alone.', 'Identify the dimension of the quantity being scaled.', 'What area factor corresponds to a linear factor of 4?', '16.',
   'Two similar shapes have area ratio 1:25. Find the corresponding length ratio.', 'The length ratio is 1:5 because the positive square root of 25 is 5. Using 1:25 for lengths would make the area ratio 1:625 instead.',
   detail(false, 'How is a rectangle’s area calculated?', 'Length multiplied by width.', 'The visible change in a single side may distract from both dimensions contributing to area.')],
  ['Challenge: split a compound distance into right triangles', 'Use Pythagoras in stages without adding perpendicular distances directly.',
   'A three-dimensional diagonal can be calculated using two right triangles: first find a diagonal on a rectangular face, then combine it with the perpendicular height. Keeping squared values exact until the final square root avoids unnecessary rounding. A straight-line diagonal differs from the distance along edges, so identify the path the question actually requests.',
   'Find the straight internal diagonal of a cuboid measuring 3 cm by 4 cm by 12 cm.', ['The 3-by-4 face diagonal has square 9 + 16 = 25.', 'The full diagonal has square 25 + 144 = 169.', 'Its positive length is 13 cm, not the edge-route total of 19 cm.'], 'Face diagonal first, perpendicular height next.', 'Adding three edge lengths to find a straight internal diagonal.', 'Distinguish an edge-following route from a direct line.', 'Why are the face diagonal and vertical height perpendicular in this cuboid?', 'The height is perpendicular to the entire rectangular base plane.',
   'Find the internal diagonal of a 2 cm by 3 cm by 6 cm cuboid.', 'The diagonal squared is 2² + 3² + 6² = 4 + 9 + 36 = 49, so the length is 7 cm. The calculation represents two applications of Pythagoras.',
   detail(true, 'What is a cuboid?', 'A solid with six rectangular faces.', 'A drawing on flat paper can hide the perpendicular relationships needed for the second triangle.')]
 ]],
 ['Conditional probability and sampling', [
  ['Update probabilities after a draw without replacement', 'Use the reduced total and changed category counts on a probability tree.',
   'Without replacement, the first draw changes what remains, so second-draw probabilities depend on the first result. From a bag with three red and two blue counters, a red first draw leaves two red and two blue out of four. Multiply probabilities along a sequence to find the probability of that path. Keeping the original denominator for the second draw would model replacement rather than this experiment.',
   'Find the probability of two reds without replacement from three red and two blue counters.', ['The first red probability is 3/5.', 'After red, the second red probability is 2/4.', 'Multiply to obtain 6/20 = 3/10.'], 'Update the remaining bag before the next branch.', 'Using 3/5 again for the second red after a red was removed.', 'Change both the category count and total where appropriate.', 'How many counters remain after the first draw?', 'Four.',
   'Find the probability of two blues from the same bag without replacement.', '(2/5) × (1/4) = 2/20 = 1/10. After a blue is removed, only one blue remains among four counters.',
   detail(false, 'What does without replacement mean?', 'A selected item is not returned before the next draw.', 'A familiar constant-probability model may be retained after the sample space changes.')],
  ['Recognise selection bias in a proposed sample', 'Distinguish a large sample from a representative selection process.',
   'A survey can contain many responses yet misrepresent its target population if some groups are much more likely to be included. Asking only pupils at a lunchtime sports club about preferred school activities may overrepresent pupils already interested in sport. Increasing the number of responses from the same restricted group does not automatically remove that selection bias. Define the target population and examine who can realistically be selected.',
   'Evaluate an online survey shared only in a competitive gaming group about all pupils’ leisure preferences.', ['The target is all pupils, not just group members.', 'Group membership is related to the topic, so preferences may differ systematically.', 'Recruit through a sampling method reaching the wider pupil population rather than simply collecting more group responses.'], 'Who can enter the sample matters as well as how many enter.', 'Calling a survey representative solely because its response count is large.', 'Inspect the sampling frame and participation process.', 'What is the target population?', 'The whole group the survey aims to describe.',
   'Would asking twice as many members of the same gaming group necessarily fix the bias?', 'No. It may reduce some random variability within that group while retaining systematic exclusion of other pupils. The selection process needs attention.',
   detail(false, 'What is a sample?', 'A subset used to learn about a larger population.', 'Sample size is visible and easy to compare, while systematic exclusion is less obvious.')],
  ['Challenge: use a complement for at least one event', 'Calculate an inclusive event without forgetting alternative orders.',
   'At least one red in two draws includes exactly one red and two reds. Its complement is no reds, which here means two blues. Subtracting the complement from one can be simpler than adding several disjoint paths. The experiment still matters: without replacement changes the second draw. Check that the proposed complement includes every outcome outside the desired event and none inside it.',
   'From three red and two blue counters, find the chance of at least one red in two draws without replacement.', ['The only no-red path is blue then blue.', 'Its probability is (2/5)(1/4) = 1/10.', 'The required probability is 1 − 1/10 = 9/10.'], 'At least one equals one minus none.', 'Using the probability of exactly one red as the probability of at least one red.', 'Include the possibility of two reds, or use the complete complement.', 'Does at least one include two?', 'Yes.',
   'With two red and three blue counters, find the probability of at least one red in two draws without replacement.', 'No red has probability (3/5)(2/4) = 3/10. Therefore at least one red has probability 1 − 3/10 = 7/10. This includes both one-red orders and the two-red path.',
   detail(true, 'What do probabilities of an event and its complement sum to?', 'One.', 'Everyday wording such as one can distract from the inclusive phrase at least one.')]
 ]]
]];
