import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 22 : 16, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, explain the performance choice without notes. In a week, apply it to new material and use a comparable recording or audience observation to evaluate the intended effect.' });
export const year9Performing: Subject[] = [
['music', [
 ['Minor keys and harmonic choices', [
  ['Compare natural and harmonic minor in A', 'Identify the raised seventh and its melodic consequence.',
   'A natural minor uses A, B, C, D, E, F and G. A harmonic minor raises the seventh to G sharp, giving a semitone from G sharp to A and an augmented second from F to G sharp. The raised leading note can strengthen a pull towards the tonic. Minor does not simply mean sad: tempo, texture, rhythm and context also shape expression.',
   'Locate the changed note and intervals in A harmonic minor.', ['Compare natural-minor G with harmonic-minor G sharp.', 'Identify G sharp to A as a semitone.', 'Identify F to G sharp as the larger augmented-second gap.'], 'Raise seven; inspect both neighbouring intervals.', 'Raising every G in every passage solely because the key is minor.', 'Use the scale form and harmonic context specified rather than an absolute key rule.', 'Which note is the tonic of A minor?', 'A.',
   'Why does changing G to G sharp alter both melodic and harmonic possibilities?', 'It changes intervals involving that note and allows an E major dominant triad E–G sharp–B. The change therefore affects more than one scale step in isolation.',
   d(false, 'What is a semitone?', 'The smallest step between adjacent pitches in the standard Western chromatic scale.', 'A key label may be treated as one unchanging note collection rather than a context with several minor forms.')],
  ['Challenge: compare a minor and major dominant', 'Explain the role of the leading note in a minor-key cadence.',
   'In A natural minor, E–G–B forms a minor chord on scale degree five. Raising G to G sharp gives E major, often used as a dominant leading to A minor. G sharp’s semitone movement to A can strengthen resolution. This describes a tonal convention, not a law that a minor dominant is incorrect; musical style and intended colour determine whether the leading-note pull is wanted.',
   'Compare E minor–A minor with E major–A minor.', ['The first dominant-position chord contains G natural.', 'The second contains G sharp, a semitone below A.', 'Listen for the changed approach to the tonic and describe its effect in context.'], 'One altered note can change harmonic direction.', 'Calling E minor wrong in every A-minor passage.', 'Distinguish a conventional cadence from a universal prohibition.', 'Which third gives E major rather than E minor?', 'G sharp.',
   'Suggest a reason a composer might retain E minor.', 'It may support a modal colour or a less strongly directed cadence. The choice should be explained by its audible context rather than judged only against one common tonal pattern.',
   d(true, 'What notes form an E minor triad?', 'E, G and B.', 'A common harmonic convention can be mistaken for the only valid compositional choice.')]
 ]],
 ['Blues structure and expressive practice', [
  ['Map a basic twelve-bar blues progression', 'Track harmonic position independently of the melody’s length.',
   'One introductory twelve-bar blues pattern is I–I–I–I, IV–IV–I–I, V–IV–I–I, one chord per bar. Variants are common, including different final-bar turnarounds. In C, I is C, IV is F and V is G; dominant-seventh sonorities are also common in blues practice. The blues developed through African American musical traditions, so its history and expressive conventions matter alongside a chord grid.',
   'Name the chords in bars 5, 9 and 10 of the stated C pattern.', ['Bar 5 begins the IV section, so use F.', 'Bar 9 is V, so use G.', 'Bar 10 returns to IV, so use F.'], 'Track the bar number as well as the chord name.', 'Assuming every performance uses exactly this introductory variant.', 'State the selected pattern and listen for variations.', 'How many bars are in the named form?', 'Twelve.',
   'Why can a melody phrase cross a chord change without changing the twelve-bar form?', 'Melodic phrasing and harmonic bar structure are different layers. The melody can sustain or continue while the accompaniment moves to the next scheduled chord.',
   d(false, 'What does I identify in a key?', 'The tonic chord built on the first scale degree.', 'A teaching grid can be mistaken for an exhaustive description of a living musical tradition.')],
  ['Challenge: improvise with phrasing rather than continuous scale running', 'Use space, repetition and response within a known harmonic cycle.',
   'An improvisation is shaped in real time through choices, not merely by playing every available note. A short call, a varied response and a pause can establish a recognisable idea within the twelve-bar cycle. Blues pitch inflections may not map neatly to fixed piano keys; a scale diagram is an entry point rather than a complete account of style. Work respectfully with reliable listening examples and the chosen instrument’s possibilities.',
   'Plan a three-phrase improvisation over a stated twelve-bar backing.', ['Introduce a short rhythmically clear idea in the first four bars.', 'Repeat or vary it in response to the middle section.', 'Use a final answering phrase and deliberate space to acknowledge the cycle’s return.'], 'A phrase needs shape and space, not maximum notes.', 'Judging improvisation only by speed or note count.', 'Listen for coherence, response and relation to the backing.', 'Can silence be a deliberate part of an improvisation?', 'Yes.',
   'How could a recording help evaluate the improvisation?', 'Mark where the motif returns, where phrases breathe and whether the player tracks the cycle. Evaluate those intentions rather than treating every unexpected note as either automatically creative or automatically wrong.',
   d(true, 'What is improvisation?', 'Creating or shaping musical material during performance.', 'Freedom may be confused with having no structure, listening or selective restraint.')]
 ]],
 ['Rhythmic transformation and composition', [
  ['Augment and diminish a rhythmic motif', 'Scale note durations while preserving their proportional pattern.',
   'Rhythmic augmentation lengthens a pattern proportionally; diminution shortens it. Doubling crotchet–quaver–quaver gives minim–crotchet–crotchet, preserving the 2:1:1 duration ratio. This differs from simply performing the entire piece more slowly: a transformed motif may appear against an unchanged accompaniment. Keep total duration and bar placement clear when notating or planning the transformation.',
   'Halve minim–crotchet–crotchet.', ['A minim becomes a crotchet.', 'Each crotchet becomes a quaver.', 'The result is crotchet–quaver–quaver, half the original duration.'], 'Scale every duration by the same factor.', 'Lengthening only the first note and calling the whole motif augmented.', 'Check proportional relationships across all notes.', 'Does doubling every duration preserve the rhythm’s ratios?', 'Yes.',
   'A motif lasts two crotchet beats. How long does double augmentation make it?', 'Four crotchet beats. If the metre stays unchanged, its placement across the bar structure must be planned rather than assuming it still occupies the same space.',
   d(false, 'How many crotchet beats equal a minim?', 'Two.', 'Changing one conspicuous note can be confused with a proportional transformation of a complete pattern.')],
  ['Challenge: combine transformation with a contrasting layer', 'Plan a texture in which two rhythmic versions remain perceptible.',
   'An augmented motif can be combined with a faster original version, but rhythmic density, register and timbre affect whether listeners recognise the relationship. Establish the idea clearly before layering it, then control entries and balance. A technically correct transformation does not guarantee an effective composition; the listener needs enough continuity to hear connection and enough contrast to distinguish roles.',
   'Layer a two-beat motif with its four-beat augmented form.', ['Find a shared cycle in which the faster motif can repeat twice.', 'Choose contrasting registers or timbres for the two layers.', 'Test whether the relationship remains audible and simplify competing material if necessary.'], 'Align the cycle; distinguish the layers.', 'Adding every transformed version at once without an audible hierarchy.', 'Introduce and balance layers according to the intended listening focus.', 'How many two-beat cycles fit within four beats?', 'Two.',
   'What would justify removing an otherwise correct layer?', 'If it masks the main relationship or weakens the intended texture, removing it can improve communication. Compositional quality depends on the whole effect, not on retaining every technique demonstrated.',
   d(true, 'What is musical texture?', 'How simultaneous musical parts or layers relate.', 'Demonstrating more techniques can be mistaken for communicating a clearer musical idea.')]
 ]]
]],
['drama', [
 ['Given circumstances and changing tactics', [
  ['Use circumstances to constrain playable choices', 'Connect a character’s action to information established by the script.',
   'Given circumstances include facts such as place, time, relationships and events established by the text. They shape what a character knows and can plausibly do. If a scene states that one person must remain quiet to avoid waking someone, volume and movement choices need to account for that constraint. An actor may invent useful detail, but should distinguish it from textual fact and avoid contradicting the scene.',
   'A character needs help but cannot wake a sleeping neighbour.', ['Identify the objective of obtaining help.', 'Identify the restriction on noise.', 'Explore whispered urgency, gesture or proximity rather than automatically shouting to show emotion.'], 'Objective meets circumstances to produce action.', 'Selecting a dramatic effect that contradicts an explicit scene condition.', 'Check the script’s facts before adding interpretation.', 'Are all invented character details given circumstances?', 'No.',
   'Why record which rehearsal assumptions are invented?', 'It keeps interpretation open to revision and prevents an unsupported invention from being treated as a script requirement. The group can test whether it helps communicate the scene.',
   d(false, 'What is a playable objective?', 'Something the character tries to achieve through action in the scene.', 'A vivid backstory can become more authoritative than the actual text.')],
  ['Challenge: mark a beat change through a new tactic', 'Identify a motivated shift in action rather than a random emotional change.',
   'A dramatic beat can change when new information or a failed tactic alters how a character pursues an objective. A request might move from reassurance to bargaining after refusal. Label actions that can be played towards another person rather than only emotional states such as sad or angry. The transition should respond to the partner and scene, not merely to a preplanned point in the actor’s speech.',
   'A character’s friendly request is refused.', ['Identify the objective that remains unmet.', 'Choose a new tactic such as offering a compromise.', 'Make the transition responsive to the refusal while preserving the objective’s continuity.'], 'Same aim, changed means, visible cause.', 'Switching emotion without a change in circumstances or tactic.', 'Locate what happened that motivates the new action.', 'Must every beat change mean the character changes their overall objective?', 'No.',
   'How would observing the scene partner improve the transition?', 'The timing and manner of the refusal can shape the next tactic. Responsive listening makes the change appear caused within the scene rather than mechanically executed.',
   d(true, 'What is a tactic in drama?', 'A particular means a character uses to pursue an objective.', 'Emotion labels may replace the observable action that produces a dramatic change.')]
 ]],
 ['Epic theatre and critical distance', [
  ['Explain direct address as a change in audience relationship', 'Distinguish speaking to spectators from treating them as invisible observers.',
   'Direct address can interrupt an illusion of private action and invite spectators to consider a claim or situation openly. In theatre influenced by Brecht, such devices may encourage critical examination of social arrangements rather than only identification with a character. The effect depends on wording and context: direct address can also entertain, confess or recruit agreement. Naming a technique does not prove the audience thinks critically.',
   'A performer pauses a workplace scene to ask who benefits from a rule.', ['The address acknowledges spectators directly.', 'It reframes the action as a situation open to analysis.', 'The following staging must support reflection rather than assume the question alone achieves it.'], 'Change the relationship to change the question.', 'Calling any speech to the audience automatically Brechtian in purpose.', 'Connect the device to the production’s critical aim and context.', 'Does direct address require pretending the audience is absent?', 'No.',
   'Suggest evidence that the address helped the intended critical focus.', 'Audience responses might identify the rule’s beneficiaries and alternatives rather than only whether they liked the character. Such feedback tests the specific aim without proving every spectator responded identically.',
   d(false, 'What is the fourth-wall convention?', 'Treating the staged world as if it is not directly addressing the audience.', 'A recognisable technique can be treated as sufficient evidence of a whole theatrical approach.')],
  ['Challenge: use a scene title to reveal an outcome deliberately', 'Evaluate how foreknowledge can shift attention towards social causes.',
   'A projected or spoken title may announce a scene’s outcome before it unfolds. This can redirect attention from surprise towards how and why events occur. In an episodic structure, juxtaposed scenes can expose patterns across situations. The device should have a clear analytical purpose; revealing every event without a new question can merely reduce engagement. Critical distance is not the same as preventing all emotion.',
   'A scene title announces that a worker will lose an appeal.', ['The outcome becomes known in advance.', 'The audience can examine the rules, power and decisions producing it.', 'Performance choices should make those mechanisms legible rather than only repeat the announced result.'], 'Reveal what happens to investigate how it happens.', 'Assuming critical theatre must make spectators feel nothing.', 'Allow emotion while shaping reflective questions and comparisons.', 'Can a known outcome still support dramatic interest?', 'Yes.',
   'How could a second contrasting scene deepen the analysis?', 'Showing a similar appeal treated differently under changed social conditions can invite comparison of institutions and power. The contrast should be specific enough to support reasoning rather than a general claim that everything is unfair.',
   d(true, 'What does episodic structure mean?', 'A sequence of distinct scenes or episodes whose relationship contributes to meaning.', 'Reduced surprise can be mistaken for reduced purpose when the dramatic question has changed.')]
 ]],
 ['Design, cues and access', [
  ['Write a clear technical cue', 'Specify an observable trigger and intended change for a rehearsal team.',
   'A cue needs a repeatable trigger, an identified action and any timing information. “Make it tense” states an aim but not an executable instruction. A cue might specify a sound fade after a particular line and its duration. Use safe school-approved equipment and discuss accessibility, sound levels and sensory needs; a dramatic effect does not justify avoidable discomfort or inaccessible information.',
   'Plan a gentle sound fade after the line “The train has gone”.', ['Record the exact line as the trigger.', 'Specify which sound is fading and the target level.', 'State a duration and test it at a safe level in rehearsal.'], 'Trigger, action, timing.', 'Using an emotional description as the only technical instruction.', 'Translate the intention into an observable, repeatable cue.', 'Why identify the exact sound being changed?', 'Different tracks or sources may require different actions.',
   'What could go wrong with a cue simply labelled “after the pause”?', 'Pause length and interpretation may vary between runs. A clearer agreed trigger supports reliable coordination, with contingency planning for altered delivery.',
   d(false, 'What is a cue?', 'A signal or agreed trigger for an action during performance.', 'A designer’s intention can be mistaken for enough information for another person to execute it.')],
  ['Challenge: communicate essential information through more than one channel', 'Improve access without assuming every audience member perceives the same signals.',
   'If a plot change is communicated only by a faint sound, some audience members may miss essential information. Thoughtful design can support it through dialogue, visible action, captions or other suitable means while preserving the artistic purpose. Access is not achieved by making everything louder or brighter. Consult users and staff about needs and evaluate the complete experience rather than add a disconnected adjustment at the end.',
   'A crucial offstage announcement cannot be heard clearly by some spectators.', ['Identify exactly what narrative information the announcement carries.', 'Consider a visible or captioned equivalent integrated into the staging.', 'Test legibility, timing and the relationship with the live action.'], 'Essential meaning should not depend on one fragile channel.', 'Treating increased volume as the only accessibility solution.', 'Match alternatives to the information and audience needs.', 'Does adding captions remove the need to check their timing and visibility?', 'No.',
   'Why consult affected audience members when choosing an adaptation?', 'Designers may otherwise guess incorrectly about barriers or introduce new ones. Consultation and testing reveal practical effects while recognising that access needs differ between people.',
   d(true, 'What is accessibility in performance?', 'Reducing barriers to perceiving, understanding and participating in the experience.', 'An adjustment may be judged by its presence rather than by whether it actually removes a barrier.')]
 ]]
]]
];
