import type { Subject, ActivityDetail } from '../authoredActivities';
const free: ActivityDetail = { isPremium: false, difficulty: 'Core', estimatedMinutes: 15, revision: 'Tomorrow, annotate a fresh sentence using the same analytical question. Next week, write a short response and check every inference against quoted evidence.' };
const extension: ActivityDetail = { ...free, isPremium: true, difficulty: 'Higher', estimatedMinutes: 20 };
export const year8English: Subject[] = [
['english-lang', [
 ['Rhetoric and framing', [
  ['Analyse inclusive pronouns and implied groups', 'Explain how a writer constructs agreement through we and our.',
   'A writer’s we can invite solidarity while quietly deciding who belongs to the group. “We must protect our streets” presents a shared duty but does not establish that everyone supports the proposed action. Ask who the pronoun includes, excludes or assumes. The effect depends on the audience and context, not a rule that every we automatically persuades.',
   'Analyse “We all know that the new rule is fair”.', ['We all claims shared membership and agreement.', 'Know presents a debatable judgement as settled.', 'The wording pressures readers towards consensus without supplying evidence of fairness.'], 'Who is inside the we?', 'Treating an inclusive pronoun as evidence of actual unanimous agreement.', 'Separate the rhetorical invitation from verified audience opinion.', 'What does “we all know” imply about disagreement?', 'It can frame disagreement as outside the assumed shared understanding.',
   'Rewrite the claim to acknowledge uncertainty without abandoning the argument.', 'For example: “The rule may improve fairness because it gives each group equal access.” This replaces assumed consensus with an explicit reason that can be examined.',
   { ...free, memoryExplanation: 'Identifying group boundaries makes an apparently ordinary pronoun analytically significant.', misconceptionCause: 'A friendly collective voice can conceal unsupported assumptions.' }],
  ['Challenge: evaluate a rhetorical question and its premise', 'Distinguish emotional pressure from a reasoned answer to a policy question.',
   '“Who would deny children a safe journey?” makes refusal sound morally unacceptable, but it does not prove that one particular transport proposal is effective. The question embeds a shared value and may bypass discussion of means. Analyse the premise, the implied answer and the missing link between value and proposal. A fair critique recognises the legitimate concern rather than dismissing all emotion.',
   'Evaluate a campaign using the question to demand a specific road scheme.', ['Identify the reasonable value of child safety.', 'Identify the implied answer that nobody should oppose safety.', 'Ask for evidence that this scheme improves safety better than alternatives.'], 'Agreeing with the value is not endorsing every method.', 'Calling an argument proved because its question has an obvious emotional answer.', 'Test the link between the premise and the proposed action.', 'What is a premise?', 'A starting claim or assumption used to support an argument.',
   'Write a two-sentence response that recognises safety but challenges the inference.', '“Safe travel is essential. We still need evidence that this design reduces danger and that it serves pupils who walk, wheel, cycle and use buses.” The response questions means without rejecting the value.',
   { ...extension, memoryExplanation: 'Separating ends from means reveals an argument’s unsupported step.', misconceptionCause: 'A moral consensus can be substituted for evidence about practical effectiveness.' }]
 ]],
 ['Reading structure and information', [
  ['Track a shift in focus', 'Explain how a text moves from a broad setting to a selected detail.',
   'A description can begin with a busy street, narrow to one doorway and then to a shaking hand. This structural narrowing guides attention from public activity towards private tension. Name both the starting and ending focus, and explain the relationship. “The writer zooms in” remains incomplete unless the selected detail and its significance are identified.',
   'Analyse a passage moving from a cheering crowd to a silent runner at its edge.', ['The opening presents collective celebration.', 'The focus narrows to an isolated individual.', 'The contrast can complicate the apparent shared happiness and prompt questions about the runner.'], 'From what, to what, with what consequence?', 'Using a camera metaphor instead of analysing the actual change.', 'Identify the selected information and its effect on interpretation.', 'Does a shift in focus require a change of physical location?', 'No.',
   'Why might returning to the crowd after the runner’s silence change its meaning?', 'Readers now know that the celebration is not everyone’s experience, so the same crowd can appear less unified or more oblivious.',
   { ...free, memoryExplanation: 'The three questions turn a technique label into a structural explanation.', misconceptionCause: 'Memorised terminology can hide the absence of a text-specific argument.' }],
  ['Challenge: distinguish chronology from disclosure order', 'Explain what a delayed revelation changes about earlier information.',
   'Events happen in one order, but a narrator can disclose them in another. A journey described as routine may be reinterpreted when a late sentence reveals the traveller is escaping danger. Separate the chronological sequence from the reader’s sequence of discovery. The delay can produce surprise or complicity, but evaluate its effect using the actual omitted information.',
   'A story first shows a locked suitcase and later reveals it contains evidence of a crime.', ['Initially the suitcase is an unexplained object.', 'The late disclosure gives its secrecy a specific significance.', 'Earlier guarded behaviour becomes meaningful on rereading.'], 'Event order and knowledge order can differ.', 'Calling every late detail a flashback.', 'A flashback shifts narrated time; delayed explanation may remain in the present sequence.', 'What changes for a reader after a delayed revelation?', 'Their interpretation of information already encountered may change.',
   'Explain how revealing the suitcase’s contents in the first sentence would alter the opening.', 'The opening would create informed suspense about what happens to the evidence rather than uncertainty about the suitcase’s significance. Neither method is automatically better; they produce different reader questions.',
   { ...extension, memoryExplanation: 'The reader’s question depends on what has been disclosed, not only on what has happened.', misconceptionCause: 'All non-immediate information is sometimes mislabelled as a time shift.' }]
 ]],
 ['Argument writing and revision', [
  ['Integrate a concession into an argument', 'Acknowledge a valid limitation while preserving a qualified main claim.',
   'A concession grants a reasonable point without surrendering the whole argument. “Although longer opening hours require staffing, a trial on two evenings could test demand” acknowledges cost and proposes a bounded response. The concession should be genuine, not a caricature. Link the qualification to a realistic plan or evidence rather than adding however mechanically.',
   'Argue for a school club while recognising limited rooms.', ['Acknowledge that rooms are already heavily used.', 'Propose a shared timetable or small initial trial.', 'Explain how that responds to the constraint while testing the club’s value.'], 'Grant the true point; refine the proposal.', 'Admitting a limitation and then ignoring it in the recommendation.', 'Make the proposal respond to the conceded fact.', 'Does a concession have to destroy the main claim?', 'No.',
   'Improve “It costs money, but we should do it anyway”.', 'For example: “The cost is a real constraint, so a capped pilot budget and a review after six weeks would let us test the benefit before committing further funds.” This answers the cost concern rather than merely acknowledging it.',
   { ...free, memoryExplanation: 'A useful concession changes the shape of the argument.', misconceptionCause: 'Writers sometimes treat balance as a decorative sentence rather than a reasoning requirement.' }],
  ['Challenge: revise inflated claims into credible persuasion', 'Preserve force while removing unsupported statistics and absolutes.',
   'Persuasive strength depends on defensible claims as well as confident style. Words such as always, everyone and proves demand strong support. An invented statistic damages credibility even if the proposal is worthwhile. Revise the scope, attribute real evidence and explain its relevance. Uncertainty can be expressed precisely without making the entire argument vague.',
   'Revise “This club will definitely improve every pupil’s wellbeing”.', ['Remove the universal guarantee.', 'State a plausible benefit and the learners the proposal aims to support.', 'Propose evaluating participation and reported experience during a trial.'], 'Bounded claim, stronger credibility.', 'Believing qualification necessarily makes writing weak.', 'Specific limits show what the evidence can genuinely support.', 'Why is an invented percentage unacceptable evidence?', 'It falsely presents unsupported content as measured fact.',
   'Write a credible alternative to “Ninety-nine percent want this”, when no survey exists.', '“Several pupils have expressed interest, but we need a properly designed survey before estimating wider demand.” This distinguishes observed interest from an unmeasured proportion.',
   { ...extension, memoryExplanation: 'The strongest justified claim is more useful than the loudest unsupported one.', misconceptionCause: 'Rhetorical certainty can be mistaken for evidential strength.' }]
 ]]
]],
['english-lit', [
 ['Shakespeare: ambition and performance in Macbeth', [
  ['Analyse concealment in Macbeth’s aside', 'Connect imagery and dramatic form with hidden ambition.',
   'In Act 1 Scene 4, Macbeth says, “Stars, hide your fires; / Let not light see my black and deep desires.” Light and darkness frame his wishes as something to conceal. The aside gives the audience access to thoughts other characters do not hear. Analyse the opposition and dramatic access together rather than treating darkness as a universal symbol without context.',
   'Explain the imperative “hide” in the quoted aside.', ['Hide commands concealment rather than examination.', 'The stars’ light becomes an imagined witness.', 'Macbeth’s request exposes his awareness that the desires are morally troubling.'], 'Imagery plus audience access.', 'Assuming every other character hears the aside.', 'Distinguish the audience’s privileged knowledge from characters’ knowledge.', 'What is an imperative?', 'A verb form used here to issue a command or request.',
   'Write two sentences connecting “black and deep desires” with audience response.', 'The description suggests Macbeth regards his ambition as secret and morally dark. Because the audience hears this concealed thought, it can distrust a public appearance of loyalty even while other characters cannot.',
   { ...free, memoryExplanation: 'Dramatic form controls who knows what; imagery tells us how the thought is framed.', misconceptionCause: 'Language analysis can overlook how the words reach an audience within a play.' }],
  ['Challenge: compare Macbeth and Lady Macbeth’s appeals', 'Compare two passages without reducing a character to one fixed label.',
   'Lady Macbeth’s “Come, you spirits” in Act 1 Scene 5 also uses an imperative to call on forces beyond ordinary human action. Compare its apparent invitation to empowerment with Macbeth’s request for concealment. These early speeches show particular moments, not permanent proof that one character is always strong and the other always weak. Later hesitation and distress can complicate initial impressions.',
   'Compare the functions of “hide” and “Come”.', ['Both are imperative forms in appeals beyond immediate human listeners.', 'Hide seeks cover for desire; Come summons assistance.', 'The contrast suggests different approaches to ambition at these moments.'], 'Compare the function, not just the shared technique.', 'Declaring one character unchanging from a single speech.', 'Limit the conclusion to the passage and test it against later developments.', 'Why is naming both verbs as imperatives not enough?', 'It identifies a similarity but does not explain their different purposes.',
   'Construct a qualified comparative claim using the two short quotations.', '“Where Macbeth asks the stars to ‘hide’ his desires, Lady Macbeth’s ‘Come’ more openly summons imagined power. This contrast suggests different responses to ambition here, rather than proving fixed courage or weakness throughout the play.”',
   { ...extension, memoryExplanation: 'A comparison needs both a shared basis and a meaningful difference.', misconceptionCause: 'Character labels can replace analysis of changing dramatic situations.' }]
 ]],
 ['Poetry: constraint and social criticism', [
  ['Read repeated restriction in Blake’s London', 'Connect specific words with the poem’s representation of power.',
   'William Blake’s “London” describes a “charter’d street” and a “charter’d Thames”. Repeating a word associated with formal permission or control extends restriction from built streets to a natural river. The speaker’s observation is a crafted poetic viewpoint, not a neutral survey. Explain what the repeated description suggests rather than merely counting repetition.',
   'Analyse applying “charter’d” to the Thames.', ['A river might ordinarily suggest natural flow.', 'The repeated administrative word presents even it as controlled.', 'The contrast can intensify the poem’s criticism of pervasive restriction.'], 'Repeat the word; extend its reach.', 'Treating the poem as a literal claim that water stops flowing.', 'Distinguish figurative framing from a physical statement about the river.', 'Which natural feature receives the repeated description?', 'The Thames.',
   'Why is it useful to analyse street and river together?', 'The pairing shows the description spreading across human-made and natural environments, supporting an argument about how extensive control appears to the speaker.',
   { ...free, memoryExplanation: 'The second application broadens the idea rather than simply duplicating a sound.', misconceptionCause: 'Technique spotting can miss the relationship between the objects described.' }],
  ['Challenge: interpret “mind-forg’d manacles”', 'Evaluate both psychological and social dimensions of a metaphor.',
   'Manacles are restraints; “mind-forg’d” locates their making or operation partly within thought. The phrase can suggest internalised constraints shaped by institutions, beliefs or experience. It should not be reduced to blaming people for suffering entirely of their own choosing. Compare the metaphor with the poem’s surrounding public and social images to test the scope of an interpretation.',
   'Explain why “people simply imagine all their problems” is an inadequate reading.', ['The manacles metaphor names powerful restriction.', 'Mind-forg’d suggests a psychological dimension, not the absence of external conditions.', 'The wider poem’s institutions and suffering complicate a purely individual-blame interpretation.'], 'Psychological does not mean unreal or freely chosen.', 'Ignoring social context and turning the metaphor into blame.', 'Relate mental restraint to the wider conditions represented in the poem.', 'What are manacles?', 'Physical restraints such as shackles.',
   'Write a qualified interpretation that keeps both dimensions.', '“The metaphor suggests that social restrictions can become internalised ways of thinking. Yet the poem’s broader criticism of public institutions prevents reducing suffering to an individual failure of imagination.”',
   { ...extension, memoryExplanation: 'A metaphor can connect internal experience and external power rather than choose only one.', misconceptionCause: 'A single compound adjective can be isolated from the poem’s larger argument.' }]
 ]],
 ['Narrative voice in Great Expectations', [
  ['Distinguish the child Pip from the retrospective narrator', 'Explain how a later voice can shape an earlier experience.',
   'At the opening of Great Expectations, Pip’s childhood perceptions are narrated retrospectively. His imaginative conclusions about family gravestones reveal a child making sense of limited evidence, while the arrangement and wording belong to the crafted later account. Distinguish what the child understands from what the reader can infer through the narrative voice. This does not require treating either layer as a literal biography of Dickens.',
   'Explain a child inferring a parent’s appearance from lettering on a gravestone.', ['The child has little direct knowledge.', 'He turns visible shapes into imaginative evidence.', 'Readers can perceive both vulnerability and the limits of the inference through retrospective narration.'], 'Child’s perception, later telling.', 'Assuming the narrator’s full understanding equals the child’s at that moment.', 'Track the two temporal perspectives separately.', 'Is Pip identical to Dickens because the novel uses first person?', 'No.',
   'Why might retrospective narration make a frightening memory feel both immediate and reflective?', 'It can reproduce sensory impressions from the child’s experience while selecting or framing them through a later narrative consciousness.',
   { ...free, memoryExplanation: 'Two time positions can coexist in one first-person account.', misconceptionCause: 'The pronoun I can conceal a gap between experiencing and narrating.' }],
  ['Challenge: evaluate contextual claims about vulnerability', 'Use historical context to illuminate a scene without replacing textual evidence.',
   'Knowledge of poverty, punishment and social hierarchy in nineteenth-century Britain can help frame Pip’s encounter with a convict, but context must connect to the actual scene. A broad claim that all Victorians thought the same is not defensible. Analyse threats, power and dependence in the encounter, then use specific relevant context to refine rather than dictate the interpretation.',
   'Evaluate “The convict is frightening only because Victorians disliked poor people”.', ['Only makes an unsupported exclusive claim.', 'The scene’s direct threats and Pip’s vulnerability provide immediate textual explanations.', 'Context about punishment and social status may add meaning but does not replace those features.'], 'Context illuminates evidence; it is not a substitute.', 'Inserting a historical paragraph with no connection to the passage.', 'Link one relevant contextual point to a specific textual choice.', 'Why avoid “all Victorians believed” without strong evidence?', 'A long period and diverse population contained differing views.',
   'Form a balanced claim about the encounter’s power relationship.', '“Pip’s youth and isolation make the convict’s demands immediately threatening; the criminal-justice context adds a wider dimension of social exclusion. The scene therefore combines personal danger with questions about vulnerability on both sides.”',
   { ...extension, memoryExplanation: 'A narrow contextual link is more defensible than an all-purpose historical label.', misconceptionCause: 'Memorised context can be attached to any passage without testing relevance.' }]
 ]]
]]];
