import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 24 : 17, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, reconstruct the model and its causal chain. In a week, change one assumption and explain how the prediction changes, separating a model result from an unconditional real-world claim.' });
export const year10Economics: Subject = ['economics', [
 ['Scarcity, choice and productive capacity', [
  ['Identify opportunity cost as the next-best alternative', 'Distinguish the value forgone from every possible alternative added together.',
   'Scarcity means resources have competing uses relative to wants. Choosing one use involves an opportunity cost: the value of the next-best alternative forgone. It is not necessarily a monetary payment and is not the sum of every rejected option. A school allocating a room to a laboratory may forgo the best alternative use, such as a music space, depending on priorities and available substitutes.',
   'A fictional council can fund either a park repair or its next-best alternative, library equipment.', ['Identify the resources that cannot be used for both under the constraint.', 'Specify library equipment as the best forgone option in the stated ranking.', 'The opportunity cost is that forgone benefit, not all possible council projects combined.'], 'Next best, not every other possibility.', 'Treating an option as costless because no extra cash changes hands.', 'Consider the valuable alternative use of time, space or resources.', 'Can time have an opportunity cost?', 'Yes.',
   'Why might the opportunity cost of using an empty room change later?', 'If a valuable alternative use becomes available, the next-best forgone benefit changes. Opportunity cost depends on actual alternatives rather than a permanent label attached to the room.',
   d(false, 'What does scarce mean in economics?', 'Limited relative to competing wants or uses.', 'A visible cash payment can overshadow non-monetary alternatives forgone.')],
  ['Challenge: interpret movement, inefficiency and growth on a PPF', 'Distinguish reallocating resources from expanding productive capacity.',
   'A production possibility frontier shows combinations of two outputs possible with specified resources and technology under efficient use. Moving along it reallocates production and involves a trade-off. A point inside can indicate unused or inefficiently used capacity; an outward shift represents increased potential. The diagram does not by itself identify the fairest output mix or guarantee every point is equally desirable.',
   'A fictional economy moves from an interior point to its existing frontier.', ['Output possibilities were not fully used at the initial point.', 'The movement can represent better utilisation rather than new productive capacity.', 'Do not label it an outward shift unless the frontier itself changes.'], 'Moving to capacity is different from moving capacity.', 'Calling every production increase economic growth of potential capacity.', 'Separate actual output from the boundary of what could be produced.', 'What does a point beyond the current frontier represent?', 'An output combination not currently attainable under the stated assumptions.',
   'Why might investment shift a future frontier while reducing current consumption?', 'Resources used for investment cannot all produce current consumer goods, but the resulting capital may increase future productive capacity. The trade-off concerns different time periods.',
   d(true, 'What is productive efficiency in this model?', 'Producing without avoidable waste so more of one output requires less of another.', 'Current utilisation and long-term capacity are often described by the same loose word growth.')]
 ]],
 ['Demand, supply and responsiveness', [
  ['Distinguish a demand shift from movement along a curve', 'Separate own-price effects from other determinants.',
   'A demand curve relates quantity demanded to the good’s own price while other influences are held constant. A change in that price causes movement along the curve; changing income, preferences or related-good prices can shift the curve. In a simple competitive market, an increase in demand with supply unchanged tends to raise equilibrium price and quantity. Demand means willingness and ability to buy, not desire alone.',
   'More commuters prefer cycling while bicycle production conditions are unchanged.', ['The preference change can increase demand at each bicycle price.', 'Represent that as a demand-curve shift, not a movement caused by the old price.', 'The simple model predicts a higher equilibrium price and quantity, subject to supply conditions.'], 'Own price moves along; another determinant can shift.', 'Saying a price rise itself shifts the demand curve left.', 'State which variable changed and which are held constant.', 'Does wanting an item without ability to pay necessarily count as effective demand?', 'No.',
   'A café raises its own price and fewer drinks are bought, other factors unchanged. Describe the demand change precisely.', 'Quantity demanded decreases along the existing demand curve. It is not, in this model, a decrease in demand represented by a whole-curve shift.',
   d(false, 'What is equilibrium in a simple market?', 'A price and quantity at which planned quantity demanded equals planned quantity supplied.', 'Every observed fall in sales may be called a demand shift without identifying its cause.')],
  ['Challenge: use elasticity to analyse a revenue change', 'Relate percentage quantity response to a percentage price change.',
   'Price elasticity of demand compares percentage change in quantity demanded with percentage change in price. Using the magnitude, a value above one is elastic and below one inelastic. For a small price change, elastic demand means quantity responds proportionally more, so a price rise tends to reduce total revenue. Large finite changes and the percentage convention need explicit treatment; elasticity can vary along a curve.',
   'Price rises from £10 to £11 and quantity falls from 100 to 80 in a stated before-base calculation.', ['Price increases by 10 percent and quantity falls by 20 percent.', 'The elasticity magnitude is 20/10 = 2.', 'Revenue falls from £1,000 to £880, consistent with the observed elastic response.'], 'Compare percentages, then check price times quantity.', 'Comparing raw unit changes in pounds and units.', 'Use a stated percentage basis and verify revenue directly.', 'What does an elasticity magnitude below one indicate?', 'A proportionally smaller quantity response than price change.',
   'Why should a business not assume this observed elasticity applies at every price?', 'Customer alternatives, budgets and positions on the demand curve can change. One interval estimates responsiveness under those conditions, not a permanent universal constant.',
   d(true, 'How is total revenue calculated?', 'Price multiplied by quantity sold.', 'A measured response over one interval may be extrapolated beyond its evidence.')]
 ]],
 ['External effects and intervention', [
  ['Explain a negative externality as an unpriced third-party cost', 'Distinguish private production costs from wider social costs.',
   'A negative externality occurs when an activity imposes costs on third parties not fully reflected in the decision-maker’s private calculation. Pollution may affect nearby residents even when a producer pays its own wages and materials. The issue is not simply that the firm earns profit or that every cost is external. Social cost combines relevant private and external costs in the model.',
   'A fictional factory’s emissions increase cleaning costs for neighbours.', ['The factory’s own input costs are private costs.', 'Neighbours bear an additional effect not fully included in the factory’s price decision.', 'That external cost can make the market output exceed the socially efficient level under the model.'], 'External means borne beyond the transaction’s private calculation.', 'Calling every expensive input an externality.', 'Identify who bears the effect and whether it is reflected in the decision.', 'Is a wage paid by the factory ordinarily an external cost?', 'No; it is a private production cost.',
   'Why can a policy aimed at the externality differ from simply closing every factory?', 'The objective may be to balance benefits and full costs through cleaner methods, standards or pricing rather than eliminate all production. Policy design needs evidence about damage, alternatives and enforcement.',
   d(false, 'Who is a third party in this context?', 'Someone affected who is not simply the buyer or seller in the relevant transaction.', 'A moral judgement about a business can replace the specific economic definition of an external effect.')],
  ['Challenge: evaluate an indirect tax using incidence and alternatives', 'Distinguish who remits a tax from who bears its economic burden.',
   'A tax collected from sellers can be partly passed to buyers through higher prices. The division of burden depends on relative responsiveness of demand and supply, not only who sends the payment to government. An environmental tax may reduce a harmful activity, raise revenue and encourage substitutes, but the size of those effects depends on available alternatives and enforcement. Revenue alone is not proof that the environmental objective was met.',
   'A taxed product has few short-run substitutes for consumers.', ['Demand may be relatively inelastic in the short run.', 'Buyers may bear a substantial share through higher prices, depending also on supply.', 'Quantity may fall less than policymakers hoped, so complementary alternatives can matter.'], 'Legal payer and economic bearer need not be the same.', 'Assuming a producer tax cannot affect consumers.', 'Trace price and quantity responses on both sides of the market.', 'Does collecting much tax revenue prove a large reduction in harmful use?', 'No.',
   'Why might the policy work differently after public transport improves?', 'More substitutes can make demand for the taxed travel activity more responsive. The same price incentive may then produce a larger behavioural response, subject to actual access and preferences.',
   d(true, 'What is an indirect tax?', 'A tax on spending or a transaction in goods or services.', 'Administrative payment responsibility can be mistaken for the final distribution of costs.')]
 ]],
 ['Inflation, employment and measurement', [
  ['Calculate inflation from a price index', 'Distinguish a rising price level from a falling rate of increase.',
   'Inflation is a sustained increase in a general price level, commonly measured through a weighted price index. If an index rises from 120 to 126, the rate is 6/120 × 100 = 5 percent. A fall in inflation from 5 to 2 percent usually means prices rise more slowly, not that they return to earlier levels. Individual households can experience different changes because their spending patterns differ.',
   'An index rises from 150 to 156.', ['The index increase is 6.', 'Divide by the original 150 and multiply by 100.', 'Inflation over the period is 4 percent, not 6 percent.'], 'Index-point change needs the starting index as denominator.', 'Equating a lower inflation rate with falling prices.', 'Separate price level from its rate of change.', 'What term commonly describes a falling general price level?', 'Deflation.',
   'If prices rise 10 percent one year and 10 percent the next, is the two-year increase 20 percent?', 'No. The multiplier is 1.1 × 1.1 = 1.21, giving a 21 percent rise. Each increase applies to the new level.',
   d(false, 'How is percentage change calculated?', 'Change divided by original value, multiplied by 100.', 'Rates, levels and index points can be confused because all describe changes in prices.')],
  ['Challenge: interpret unemployment rates with changing participation', 'Use the labour-force denominator and distinguish employment from inactivity.',
   'A labour-force unemployment rate compares unemployed people with the labour force, normally employed plus unemployed under the chosen statistical definition. People outside that group are not automatically counted as unemployed. The rate can fall because people find work or because some stop participating in the measured labour force. Definitions, reference periods and reasons for inactivity matter before judging economic improvement.',
   'A fictional labour force contains 900 employed and 100 unemployed people.', ['Total labour force is 1,000.', 'Unemployment rate is 100/1,000 = 10 percent.', 'If 50 unemployed people leave the labour force, the rate becomes 50/950, about 5.26 percent, with employment still 900.'], 'A falling rate needs a story about both numerator and denominator.', 'Assuming every reduction in unemployment rate means more people are employed.', 'Inspect employment, participation and the measurement definition together.', 'Are all people without a job necessarily in the statistical unemployed group?', 'No.',
   'What additional data would help interpret the fall in the worked example?', 'Participation rates, reasons for leaving the labour force, employment levels and hours worked would help distinguish improved job access from withdrawal or other changes.',
   d(true, 'What is a rate’s denominator?', 'The reference group against which the counted outcome is compared.', 'A desirable headline movement can hide a changing reference population.')]
 ]],
 ['Macroeconomic policy and trade-offs', [
  ['Trace a higher-interest-rate demand channel', 'Explain a mechanism without predicting identical responses by every household.',
   'Higher interest rates can raise borrowing costs and reward saving, reducing some consumption and investment and therefore demand pressure. Effects differ for borrowers, savers and those on fixed-rate contracts, and arrive with delays. Exchange-rate and confidence channels can also matter. This is an economic mechanism, not personal borrowing advice or a guarantee that every price immediately falls after a rate rise.',
   'Explain why a proposed business investment may be postponed after financing costs rise.', ['Higher interest increases the cost of borrowing for the project.', 'Expected returns may no longer justify that cost or risk.', 'Reduced investment spending can weaken aggregate demand through this channel.'], 'Price of credit changes incentives, with lags and differences.', 'Assuming all consumers instantly reduce spending by the same amount.', 'Identify exposure, contracts, expectations and timing.', 'Can higher rates benefit some savers?', 'Yes.',
   'Why might a household on a temporary fixed-rate mortgage initially see no payment change?', 'Its contract fixes the rate for that period. The wider policy may still affect other prices or future refinancing, but this specific payment channel is delayed.',
   d(false, 'What is interest?', 'A charge for borrowing or return for lending/saving under specified terms.', 'A general policy channel can be treated as an immediate universal household effect.')],
  ['Challenge: distinguish a budget deficit from public debt', 'Evaluate a fiscal change using flows, stocks and economic conditions.',
   'A budget deficit is a flow over a period when government spending exceeds revenue under the specified accounts. Public debt is an accumulated stock of borrowing obligations. Reducing a deficit can still mean debt rises, just more slowly, if borrowing remains positive. Fiscal policy can support demand or public services while creating financing and opportunity-cost questions; evaluation depends on spare capacity, interest costs and the purpose of spending.',
   'A fictional government’s annual deficit falls from £20 billion to £8 billion.', ['The annual borrowing flow is smaller.', 'It remains positive in this simplified account.', 'Debt can therefore continue increasing by the remaining borrowing, absent other adjustments.'], 'Deficit is a flow; debt is a stock.', 'Saying debt must fall whenever the deficit falls.', 'Check whether the flow is still positive and consider other stock adjustments.', 'Is a yearly spending gap the same quantity as total outstanding debt?', 'No.',
   'Why might the effect of additional public spending differ during a slump and near full capacity?', 'With unused resources it may raise output more readily; near capacity it may create stronger price pressures or displace other uses. The actual effect also depends on what is bought and how it is financed.',
   d(true, 'What distinguishes a stock from a flow?', 'A stock is measured at a point in time; a flow over an interval.', 'Related fiscal quantities may be confused because both are reported as money amounts.')]
 ]],
 ['Trade, specialisation and currencies', [
  ['Compare opportunity costs in a simple trade model', 'Distinguish comparative from absolute advantage.',
   'Absolute advantage means producing more with the same resources; comparative advantage means a lower opportunity cost. A country can have an absolute advantage in both goods while still benefiting from specialisation and trade in a simplified model. Assumptions include feasible exchange, suitable demand and adjustment; transport costs, distribution and transition harms require separate evaluation. The model identifies potential gains, not guaranteed equal gains for everyone.',
   'A can make 10 cloth or 5 grain; B can make 6 cloth or 4 grain with comparable resources.', ['One grain costs A two cloth.', 'One grain costs B 1.5 cloth.', 'B has comparative advantage in grain, while A has it in cloth, despite A’s greater maximum output of both.'], 'Compare what is given up, not only what is produced.', 'Assuming a more productive country must have comparative advantage in everything.', 'Calculate the opportunity-cost ratios for each good.', 'What is A’s opportunity cost of one cloth?', '0.5 grain.',
   'Why could a grain trade price between 1.5 and 2 cloth per grain offer potential gains to both?', 'B could receive more cloth than its internal opportunity cost of producing grain, while A could obtain grain for less cloth than producing it itself would cost. This is conditional on the model’s assumptions.',
   d(false, 'What is opportunity cost?', 'The value of the next-best alternative forgone.', 'Total productivity can overshadow the relative trade-offs that determine comparative advantage.')],
  ['Challenge: trace an exchange-rate change through import prices', 'Keep the quotation direction and currency conversion consistent.',
   'An exchange rate states how much of one currency exchanges for another. If £1 buys fewer dollars, sterling has depreciated against the dollar under that quotation. A dollar-priced import then costs more pounds, holding its dollar price and other conditions constant. Export demand and trade balances may respond, but contracts, imported inputs, elasticities and timing prevent a simple guaranteed improvement.',
   'A $120 item is priced when £1 = $1.50 and later when £1 = $1.20.', ['Initially the pound cost is 120/1.50 = £80.', 'Later it is 120/1.20 = £100.', 'The depreciation raises this import’s pound price by £20 under unchanged dollar pricing.'], 'Read the quote before choosing multiplication or division.', 'Calling fewer dollars per pound an appreciation of sterling.', 'State what one unit buys and compare purchasing power.', 'What happens to this import if its dollar price rises as well?', 'Its pound cost can rise further, other factors unchanged.',
   'Why might an exporter not gain as much as expected from depreciation?', 'If it imports important inputs, its costs can rise. Foreign demand responsiveness, capacity and pricing decisions also affect the outcome, so a currency move alone does not determine profit or export volume.',
   d(true, 'What is an import?', 'A good or service purchased from abroad in the relevant national account.', 'A beneficial effect on one side of trade can hide costs elsewhere in the same production chain.')]
 ]]
]];
