import type { Subject, ActivityDetail } from '../authoredActivities';
const core: ActivityDetail = { isPremium: false, difficulty: 'Core', estimatedMinutes: 15, revision: 'Tomorrow, reconstruct the worked sentence without looking. In a week, change the subject or time expression and explain every verb and article choice.' };
const challenge: ActivityDetail = { ...core, isPremium: true, difficulty: 'Higher', estimatedMinutes: 20 };
export const year8French: Subject = ['french', [
 ['Completed actions with avoir', [
  ['Build the passé composé of regular -er verbs', 'Combine a present-tense auxiliary with a past participle.',
   'For many French verbs, a completed past action is expressed using a present-tense form of avoir plus a past participle. Regular -er verbs normally form that participle in -é: jouer becomes joué. J’ai joué means I played or I have played, depending on context. Nous avons joué changes the auxiliary, not the participle in this construction. Not all verbs use avoir or have regular participles.',
   'Translate “Yesterday we played” using hier and jouer.', ['Choose nous avons for the subject and auxiliary.', 'Change jouer to the participle joué.', 'Write Hier, nous avons joué.'], 'Conjugated auxiliary plus participle.', 'Writing nous avons jouer with an infinitive.', 'Use joué after the auxiliary in this completed-action construction.', 'What is the regular past participle of regarder?', 'Regardé.',
   'Translate “I watched a film” using regarder un film.', 'J’ai regardé un film. Ai supplies the conjugated auxiliary and regardé marks the completed action; the accent distinguishes the participle from regarde.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What is the nous form of avoir?', answer: 'Nous avons.' }], memoryExplanation: 'Each part has a separate job: the auxiliary carries person, while the participle identifies the past action.', misconceptionCause: 'The infinitive can be mistaken for an unchanged second verb in every two-verb construction.' }],
  ['Challenge: negate and contrast completed actions', 'Place negation around the auxiliary while preserving a coherent past sequence.',
   'In Je n’ai pas joué, ne or n’ and pas surround the conjugated auxiliary, not the past participle. A contrast can then introduce what actually happened: Je n’ai pas joué, mais j’ai regardé un film. Check each clause independently. A past time word does not remove the need for the correct verb construction, and mais should connect a meaningful contrast rather than unrelated additions.',
   'Negate Nous avons chanté hier.', ['The conjugated auxiliary is avons.', 'Put n’ before avons and pas immediately after it.', 'Write Nous n’avons pas chanté hier.'], 'The negative brackets the finite auxiliary.', 'Writing nous avons ne chanté pas.', 'Find the conjugated verb before placing the negative.', 'Which word follows ai in je n’ai pas joué?', 'Pas.',
   'Write “I did not play, but I watched a film”.', 'Je n’ai pas joué, mais j’ai regardé un film. The first clause negates ai; the second uses a new affirmative auxiliary and participle.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'Which two parts form j’ai joué?', answer: 'The auxiliary ai and the past participle joué.' }], memoryExplanation: 'Locating the finite verb gives negation a stable position even in a two-part tense.', misconceptionCause: 'Learners may try to place ne ... pas around the lexical action instead of its auxiliary.' }]
 ]],
 ['Plans and time frames', [
  ['Use aller plus an infinitive for an intention', 'Keep the second verb in the infinitive after a conjugated form of aller.',
   'Je vais lire expresses an intention or near-future plan: I am going to read. Other subjects require their own form of aller: tu vas, il or elle va, nous allons, vous allez, ils or elles vont. The following action stays in the infinitive. A time phrase such as demain clarifies when the plan concerns, but the grammar is not restricted to something occurring within a fixed number of minutes.',
   'Say “Tomorrow we are going to visit a museum”.', ['Use nous allons for we are going.', 'Keep visiter in the infinitive.', 'Write Demain, nous allons visiter un musée.'], 'Change aller; keep the planned action infinitive.', 'Writing nous allons visitons.', 'Only aller is conjugated in this construction.', 'What follows vais in “I am going to read”?', 'Lire.',
   'Translate “They are going to watch a film” for a group described with elles.', 'Elles vont regarder un film. Vont agrees with elles; regarder remains the infinitive.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What is an infinitive?', answer: 'The basic dictionary form of a verb, such as lire or visiter.' }], memoryExplanation: 'Assigning one job to each verb prevents two competing conjugations.', misconceptionCause: 'Both verbs may be conjugated when an English multiword phrase is translated word by word.' }],
  ['Challenge: maintain two time frames in one response', 'Contrast a completed event with a future intention without mixing constructions.',
   'A short account can compare yesterday’s action with tomorrow’s plan. Hier, j’ai visité un musée uses an auxiliary and participle for a completed event; demain, je vais visiter un château uses aller and an infinitive for a plan. Notice visité versus visiter. A connector such as mais should express a genuine contrast; et can simply add the second event.',
   'Explain the difference between j’ai regardé and je vais regarder.', ['Ai regardé presents a completed action.', 'Vais regarder presents an intention or prospective action.', 'The second verb is a participle in the first phrase and an infinitive in the second.'], 'Time meaning chooses the two-verb pattern.', 'Using a future time word with a past construction unintentionally.', 'Check time marker, auxiliary and second-verb form together.', 'Which phrase contains an infinitive: j’ai joué or je vais jouer?', 'Je vais jouer.',
   'Write “Yesterday I watched a film and tomorrow I am going to play”.', 'Hier, j’ai regardé un film et demain, je vais jouer. Regardé is a past participle after ai, whereas jouer is an infinitive after vais.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What do hier and demain mean?', answer: 'Yesterday and tomorrow.' }], memoryExplanation: 'Comparing whole constructions prevents similar-looking endings from being selected at random.', misconceptionCause: 'Regular -er infinitives and -é participles sound alike in many common verbs.' }]
 ]],
 ['Food, quantity and reference', [
  ['Choose partitive articles for an unspecified amount', 'Use du, de la and de l’ in controlled food sentences.',
   'French often uses a partitive article where English uses some or no article: du pain, de la soupe, de l’eau. Du goes with a masculine singular noun, de la with a feminine singular noun, and de l’ before a vowel sound or mute h. These examples refer to an unspecified amount rather than a whole countable unit. Learn the noun’s gender alongside the phrase.',
   'Say “I drink water and I eat bread”.', ['Use de l’eau before the vowel sound in eau.', 'Use du pain with masculine pain.', 'Write Je bois de l’eau et je mange du pain.'], 'Amount plus noun form determines the article.', 'Writing de la eau without elision.', 'Use de l’ before the relevant initial vowel sound.', 'Which partitive phrase means some soup?', 'De la soupe.',
   'Complete Je mange ... pain et ... soupe and explain the difference.', 'Je mange du pain et de la soupe. Pain is masculine and soupe is feminine, so their partitive forms differ.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What is grammatical gender?', answer: 'A noun classification, such as masculine or feminine in French.' }], memoryExplanation: 'The article signals an amount while its form responds to the noun.', misconceptionCause: 'English often omits an article where French requires one.' }],
  ['Challenge: distinguish absence from a general preference', 'Explain why negative consumption and negative liking can use different articles.',
   'Je ne mange pas de pain means I do not eat bread; in this straightforward negative, the partitive becomes de. Je n’aime pas le pain means I do not like bread: the definite article le refers to bread generally and stays. Do not replace every article after every negative with de. Identify the construction and meaning before changing the article.',
   'Compare Je mange du pain and J’aime le pain when negated.', ['Negate consumption as Je ne mange pas de pain.', 'Negate general liking as Je n’aime pas le pain.', 'Explain that de replaces the partitive here but not the definite article expressing a general category.'], 'Negative amount is not negative preference.', 'Changing le to de merely because pas appears earlier.', 'Check whether the original article is partitive or definite and what it expresses.', 'Does the definite article always disappear in a negative sentence?', 'No.',
   'Translate “I do not drink water, but I like water”.', 'Je ne bois pas d’eau, mais j’aime l’eau. D’eau expresses the negated consumption amount; l’eau presents water generally as the object of aimer.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What does j’aime mean?', answer: 'I like or I love.' }], memoryExplanation: 'Comparing two meanings prevents a useful negative pattern from becoming an incorrect universal rule.', misconceptionCause: 'A rule learned for un, une, des or partitives may be overextended to definite articles.' }]
 ]]
]];
