import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 22 : 16, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, reconstruct the argument using a short quotation. In a week, apply the analytical question to a different passage and remove any claim the evidence does not support.' });
export const year9English: Subject[] = [
['english-lang', [
 ['Evaluating viewpoints and evidence', [
  ['Analyse degrees of certainty in modal verbs', 'Explain how a writer qualifies a prediction rather than treating all claims as equally certain.',
   'Compare the original model sentences “The scheme will reduce delays” and “The scheme may reduce delays if enough drivers participate.” Will presents a confident forecast; may and the condition limit its certainty and scope. Qualification is not necessarily weakness: it can accurately represent uncertain evidence. Analyse what the wording commits the writer to and whether the supplied evidence supports that commitment.',
   'Evaluate “The trial could improve access, although results remain uncertain”.', ['Could presents a possibility rather than a guarantee.', 'Although introduces an explicit limitation.', 'The wording invites consideration while avoiding a claim that improvement is already established.'], 'Identify the strength of the claim before judging its support.', 'Treating every cautious phrase as a sign of ignorance or dishonesty.', 'Compare the wording with the actual evidence and conditions.', 'Which is more certain in these models: will or may?', 'Will.',
   'Revise “This proves the scheme will help everyone” when the evidence is one small trial.', '“The small trial suggests the scheme may help some users, but wider testing is needed.” This bounds the conclusion to the evidence rather than turning limited findings into universal proof.',
   d(false, 'What is a claim?', 'A statement presented as something to accept or consider.', 'Confident style can be mistaken for stronger evidence.')],
  ['Challenge: evaluate a text without merely agreeing with its message', 'Separate a persuasive aim from the quality of its reasoning and methods.',
   'A reader may support a proposal yet find its argument poorly supported, or disagree with a proposal while recognising an effective presentation. Evaluation requires a criterion: relevance of evidence, acknowledgement of alternatives, coherent reasoning or intended audience response. Use the writer’s actual choices and explain the limitation of your judgement. “I agree” reports an opinion but does not evaluate how the text works.',
   'An original model appeal calls a library “the heart of our town” but gives no evidence about demand.', ['The metaphor frames the library as central and life-giving.', 'That may strengthen emotional identification with the institution.', 'It does not independently establish demand for the proposed opening hours.'], 'Value, method and evidence are different questions.', 'Treating sympathy with the cause as proof of a fully convincing argument.', 'Evaluate the link between method, audience and supporting reasons.', 'Does naming a metaphor alone evaluate its effectiveness?', 'No.',
   'Write a balanced evaluation of the model appeal.', '“The heart metaphor gives the library communal significance and may engage residents emotionally. However, the appeal needs evidence about likely use and staffing to justify the specific extension of hours.”',
   d(true, 'What is evaluation?', 'A reasoned judgement using relevant criteria and evidence.', 'Agreement with a conclusion can hide weaknesses in how it is justified.')]
 ]],
 ['Comparative reading', [
  ['Compare perspectives on the same event', 'Organise a comparison around a shared focus rather than two isolated summaries.',
   'Original model A describes a station as “a gateway to possibility”; model B calls it “a corridor of interrupted sleep”. Both represent travel, but A foregrounds opportunity while B foregrounds exhaustion and repeated disruption. A comparative paragraph should establish the shared subject, analyse a meaningful difference and support both sides. Similar vocabulary or a common topic does not guarantee a shared attitude.',
   'Compare gateway and corridor in the two models.', ['Both use spatial nouns to frame the station.', 'Gateway implies entry to opportunities, while corridor can suggest prolonged passage rather than arrival.', 'The accompanying phrases direct the contrast towards optimism and fatigue.'], 'Shared focus, different framing, evidence from both.', 'Writing one summary of A and then one summary of B without linking them.', 'Use a comparative claim that both selections help test.', 'What common subject makes these models comparable?', 'The experience of a station and travel.',
   'Write a comparative sentence using both short quotations.', '“While A’s ‘gateway’ frames travel as an opening towards possibility, B’s ‘corridor’ and ‘interrupted sleep’ present it as tiring passage, making the same setting feel burdensome rather than liberating.”',
   d(false, 'What is a perspective in a text?', 'The viewpoint through which a subject is presented.', 'A common setting may lead readers to assume similar attitudes without testing the wording.')],
  ['Challenge: integrate differences in situation and purpose', 'Use contextual information without allowing it to predetermine every interpretation.',
   'A travel advertisement and a commuter diary may describe the same route for different purposes. The advertisement may select attractions to encourage bookings; the diary may record frustration after disruption. Genre and purpose suggest questions, not automatic conclusions that every advertisement lies or every diary is accurate. Evaluate the supplied content and consider how the circumstances influence selection and tone.',
   'Compare an advertisement’s “effortless escape” with a diary’s “another cancelled connection”.', ['Identify the advertisement’s promotional purpose and idealised phrasing.', 'Identify the diary’s specific disruption and repeated-experience implication in another.', 'Explain how purposes and situations shape selection without claiming either represents all journeys.'], 'Context guides questions; wording supports answers.', 'Calling one text trustworthy solely because it is personal.', 'Examine what each account can establish and what it omits.', 'Does a diary necessarily describe a representative experience?', 'No.',
   'Why might both texts be useful to a reader planning travel?', 'The advertisement may identify intended attractions or services, while the diary can reveal one experienced problem. Neither alone establishes typical reliability; independent service evidence would be needed for that broader judgement.',
   d(true, 'What is a text’s purpose?', 'What it aims to do for or to its audience.', 'Genre labels can replace analysis of actual content and evidential limits.')]
 ]],
 ['Crafting and editing prose', [
  ['Control narrative distance', 'Choose how closely narration follows a character’s immediate perception.',
   'Narrative distance concerns how close the telling feels to a character’s experience. “Mara entered the unfamiliar room” reports an action from outside; “Too bright. Where was the door?” moves closer to immediate perception. Neither is inherently superior. A shift can intensify anxiety or create reflection, but the reader must still follow who perceives and what happens. Deliberate fragments differ from accidentally incomplete sentences.',
   'Move from external reporting to a character’s worried perception.', ['Establish the room and character clearly.', 'Select a sensory detail the character would notice under stress.', 'Use a controlled internal question or fragment without losing the scene’s physical continuity.'], 'Decide who perceives before choosing the sentence shape.', 'Using fragments throughout simply to make a passage sound dramatic.', 'Vary distance and syntax in service of a specific experience.', 'Does close narration require first-person pronouns?', 'No.',
   'Write one external sentence followed by a closer sentence about waiting for a result.', '“Amir unfolded the letter beside the window. One line first—surely the answer would be there.” The first establishes action; the second narrows towards immediate expectation without claiming a real event.',
   d(false, 'What is a narrator?', 'The voice or perspective through which a story is told.', 'Pronoun choice can be treated as the only control on a reader’s closeness to a character.')],
  ['Challenge: revise syntax while preserving meaning', 'Use a semicolon, full stop or conjunction according to clause relationships.',
   'A semicolon can join closely related independent clauses; it does not repair any arbitrary fragment. Compare “The platform emptied; the announcement continued” with “Because the platform emptied; the announcement continued.” The second leaves a subordinate clause incorrectly linked. Editing must check grammatical independence and intended relationship, not merely insert sophisticated punctuation. A full stop may be clearer when the connection does not need emphasis.',
   'Edit “The rain stopped, nobody moved” without changing its contrast.', ['Identify two independent clauses joined by a comma alone.', 'Choose a semicolon, full stop or an appropriate conjunction.', '“The rain stopped, but nobody moved” makes the unexpected contrast explicit.'], 'Check clause independence before punctuation prestige.', 'Using semicolons wherever a pause feels long.', 'Identify grammar and meaning rather than rely only on reading breath.', 'Can a subordinate clause normally stand alone as a complete standard sentence?', 'No.',
   'Explain a valid edit of “Although the doors opened; the crowd waited”.', '“Although the doors opened, the crowd waited.” Although makes the first clause subordinate, so a comma links it to the main clause; the semicolon is not appropriate for this relationship.',
   d(true, 'What is an independent clause?', 'A clause able to stand as a complete sentence.', 'Punctuation can be learned as decoration or pause length instead of grammatical organisation.')]
 ]]
]],
['english-lit', [
 ['Tragedy and conflict in Romeo and Juliet', [
  ['Analyse the prologue’s disclosed ending', 'Explain how foreknowledge changes the audience’s dramatic questions.',
   'The prologue to Romeo and Juliet calls the lovers “star-cross’d” and announces their deaths. Rather than hide the outcome, the play invites attention to how conflict, choices and circumstances lead there. The language of stars suggests fate, but it does not remove the need to analyse human actions. Foreknowledge can intensify tension because an audience recognises the significance of apparently hopeful moments.',
   'Explain why revealing the lovers’ deaths need not destroy suspense.', ['The audience knows the broad outcome.', 'It can still ask how and why the tragedy develops.', 'Hopeful decisions may gain painful significance when viewed against that foreknowledge.'], 'Known ending shifts attention towards causes.', 'Assuming suspense depends only on not knowing the final event.', 'Distinguish uncertainty about outcome from tension about process and responsibility.', 'What does the prologue disclose about the lovers?', 'That they will die.',
   'Construct a qualified claim about “star-cross’d”.', '“The phrase frames the lovers as obstructed by fate, but the play also dramatises choices and social conflict. It therefore invites debate about responsibility rather than proving that every action is meaningless.”',
   d(false, 'What is a prologue?', 'An introductory section preceding the main action.', 'Fate imagery can be treated as a complete causal explanation instead of one interpretive framework.')],
  ['Challenge: connect private love with public conflict', 'Build a thematic argument using the relationship between scenes rather than isolated labels.',
   'The feud shapes the lovers’ identities and the risks of their relationship. Juliet’s question “Wherefore art thou Romeo?” asks why he is Romeo, a member of the opposing family, not where he is standing. Analysing the name alongside the public conflict connects intimate speech with social pressure. Avoid reducing the play to a choice between love and hate as if the two were unrelated strands.',
   'Explain Juliet’s concern about Romeo’s name.', ['Clarify wherefore as why.', 'Connect Romeo’s family identity with the feud.', 'Argue that inherited public labels constrain private attachment.'], 'A private question carries a public conflict.', 'Reading wherefore as a request for Romeo’s location.', 'Use historical meaning and dramatic context together.', 'What does wherefore mean here?', 'Why.',
   'Why is “Juliet dislikes Romeo” an inadequate inference from the question?', 'Her concern is the family identity that makes their love dangerous, not a simple rejection of him. The surrounding relationship and feud distinguish the person from the social meaning of his name.',
   d(true, 'What is a theme?', 'A recurring concern or idea developed through a work.', 'Familiar-looking older words can be assigned modern meanings that reverse the passage’s implications.')]
 ]],
 ['Power and voice in poetry', [
  ['Analyse the fragmented monument in Ozymandias', 'Connect the physical image with the ruler’s claim to lasting power.',
   'In Shelley’s Ozymandias, the broken statue and surrounding emptiness undermine the ruler’s boast. The command “Look on my Works, ye Mighty, and despair!” survives, but the works no longer visibly support its intended authority. Irony emerges from the relationship between inscription and setting, not from naming irony alone. The surviving representation also raises questions about art, memory and the limits of political power.',
   'Explain the contrast between the boast and the ruined setting.', ['The inscription commands other rulers to recognise greatness.', 'The broken remains and emptiness suggest that this power has not endured as intended.', 'The reader can therefore understand the command differently from its original boastful purpose.'], 'Read the inscription against what remains.', 'Treating the ruler’s words as the poem’s endorsed judgement.', 'Distinguish a quoted voice from the wider framing of that voice.', 'Who speaks the boast in the inscription?', 'The represented ruler, not simply the poet speaking directly.',
   'Write an analytical sentence linking the imperative with irony.', '“The imperative ‘Look’ attempts to control the viewer’s response, yet the ruined setting defeats that command by making the absence of lasting power more visible than the achievements it advertises.”',
   d(false, 'What is irony in this context?', 'A contrast between an intended or stated meaning and the situation that undermines it.', 'Quoted speech within a poem may be confused with the poem’s overall viewpoint.')],
  ['Challenge: interpret nested voices and uncertain transmission', 'Explain how reported storytelling mediates the reader’s access to the monument.',
   'Ozymandias reaches the reader through a speaker reporting a traveller’s account, which includes an inscription and an interpretation of the sculptor’s work. This layered transmission distances the ruler’s command from direct authority. It also makes representation central: the ruler, sculptor, traveller and speaker do not perform the same role. Avoid assuming that layered narration makes every detail false; its structure shapes how meaning is received.',
   'Trace how the boast reaches the reader.', ['A ruler’s claim is represented as an inscription.', 'A traveller reports the monument and its setting.', 'The poem’s speaker relays that account, placing the command inside further frames.'], 'Ask whose words, through whose account.', 'Collapsing the traveller, ruler, sculptor and speaker into one voice.', 'Map the reporting layers before interpreting a claim.', 'Does reported narration necessarily mean deliberate deception?', 'No.',
   'How could the layers support a reading about the limits of authority?', 'The ruler cannot control the later contexts in which his words are retold. His command survives within other people’s descriptions, which can expose its failure rather than reproduce its intended authority.',
   d(true, 'What is reported speech?', 'An account of another person’s words rather than necessarily a direct present utterance.', 'A quotation’s vividness can obscure the narrative frames controlling its presentation.')]
 ]],
 ['Evidence and whole-text interpretation', [
  ['Build a claim with a quotation and a warranted inference', 'Explain the reasoning between textual detail and interpretation.',
   'A quotation is evidence, not an analysis by itself. In the original model sentence “She folded the untouched letter and placed it beneath the clock”, untouched may suggest avoidance, but the reason remains uncertain without context. A warranted inference explains what the wording supports and what it does not. Do not turn one possible motivation into a factual account of the character’s entire past.',
   'Analyse untouched without inventing an unseen backstory.', ['Identify that the letter has not been opened or used in the model’s implied context.', 'Propose reluctance or delay as a possible interpretation.', 'Acknowledge that fear, grief or another specific cause would need further textual support.'], 'Evidence permits an inference; context limits its reach.', 'Inventing a detailed cause and presenting it as established by one adjective.', 'Qualify the inference and look for corroborating details.', 'Is a quotation alone a complete analytical explanation?', 'No.',
   'Write a defensible interpretation of the placement beneath the clock.', '“Placing the letter beneath the clock may connect the delayed reading with passing time. This is a possible symbolic relationship, but further context is needed before claiming the writer presents a specific deadline or regret.”',
   d(false, 'What is an inference?', 'A conclusion drawn from evidence rather than directly stated.', 'Imaginative engagement can be confused with evidence-based interpretation.')],
  ['Challenge: revise an interpretation using counter-evidence', 'Develop a whole-text argument that accounts for a character’s change or inconsistency.',
   'A strong literary argument addresses details that complicate its initial claim. A character who speaks bravely in one scene but avoids action later may be changing, performing courage or responding to different stakes. Do not discard the second scene simply because it weakens a planned paragraph. Revise the claim so it explains the pattern, while distinguishing genuine development from an unsupported psychological diagnosis.',
   'Test “The character is always fearless” against a later refusal to enter a room.', ['Recognise that always creates a universal claim.', 'Use the refusal as counter-evidence requiring explanation.', 'Revise to a contextual argument about public confidence and private hesitation if other details support it.'], 'Let difficult evidence improve the claim.', 'Ignoring a conflicting scene or calling it an authorial mistake without evidence.', 'Consider context, development and alternative interpretations.', 'Does one fearful moment prove a character is always cowardly?', 'No.',
   'Write a revised claim that avoids both extremes.', '“The character presents confidence publicly, but the later hesitation complicates that self-presentation. The contrast suggests courage is conditional or performed rather than an unchanging quality, a reading that should be tested against further scenes.”',
   d(true, 'What is counter-evidence?', 'Evidence that challenges or limits a proposed interpretation.', 'Essay plans can encourage selective quotation rather than revision of an over-broad claim.')]
 ]]
]]
];
