import type { Subject, ActivityDetail } from '../authoredActivities';
const core: ActivityDetail = { isPremium: false, difficulty: 'Core', estimatedMinutes: 15,
  revision: 'Tomorrow, solve a new example without the worked steps. In a week, explain why the method works and check one deliberately incorrect solution.' };
const challenge: ActivityDetail = { ...core, isPremium: true, difficulty: 'Higher', estimatedMinutes: 20 };
export const year8Maths: Subject = ['maths', [
 ['Linear relationships and proportional reasoning', [
  ['Solve equations with unknowns on both sides', 'Preserve equality while collecting variable terms and constants.',
   'An equation remains true when the same operation is applied to both sides. In 5x + 2 = 3x + 14, subtracting 3x from each side collects the variable terms without guessing x. Subtract the constant next, then divide by the remaining coefficient. Moving a term is shorthand for an operation on both sides, not a mysterious sign-changing rule. Substitution checks the original equation.',
   'Solve 5x + 2 = 3x + 14.', ['Subtract 3x: 2x + 2 = 14.', 'Subtract 2: 2x = 12.', 'Divide by 2: x = 6; both original sides equal 32.'],
   'Balance first, simplify second.', 'Changing a sign without applying a consistent operation.', 'Write the same subtraction on both sides before simplifying.',
   'What inverse operation removes an added constant?', 'Subtracting that constant from both sides.',
   'Solve 4y + 7 = 2y + 19. Then explain why 2z + 3 = 2z + 8 has no solution.',
   'y = 6: subtract 2y and then 7 to get 2y = 12. In the second equation subtracting 2z gives 3 = 8, an impossible statement, so no value of z works.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'Solve 3x = 12.', answer: 'x = 4, dividing both sides by three.' }], memoryExplanation: 'Treat equality like a balance: each permitted change acts on both sides.', misconceptionCause: 'The shortcut of moving terms can conceal the operation maintaining equality.' }],
  ['Find and use a unitary rate', 'Scale quantities through a price or amount for one unit.',
   'For direct proportion, the ratio of corresponding quantities stays constant. If five identical notebooks cost £7.50 with no fixed fee or discount, one costs £1.50 and eight cost £12. A straight graph through the origin represents this relationship. A fixed delivery charge breaks direct proportionality between number ordered and total cost, even if each additional notebook has the same price.',
   'Eight metres of fabric cost £28. Find the cost of eleven metres at the same rate.', ['Find one metre: £28 ÷ 8 = £3.50.', 'Multiply £3.50 by 11.', 'The cost is £38.50, assuming no extra fixed charge.'],
   'Down to one, up to the target.', 'Assuming every steady increase is direct proportion.', 'Check that zero quantity gives zero corresponding amount and that the ratio is constant.',
   'What stays constant in direct proportion?', 'The multiplicative ratio or rate.',
   'Six tickets cost £27. Find ten tickets at that rate. Would adding a £2 booking fee preserve direct proportion?',
   'One ticket costs £4.50, so ten cost £45 before the fee. A fixed £2 fee makes total cost non-proportional: doubling tickets does not double the fixed fee.',
   { ...core, memoryExplanation: 'One unit exposes the constant multiplier.', misconceptionCause: 'An additive pattern can look regular without having a constant ratio.' }],
  ['Challenge: interpret a linear tariff and its graph', 'Combine a fixed charge and a variable rate, and interpret their intersection.',
   'A tariff C = 3d + 5 charges £5 before travel and £3 for each distance unit d. Its graph has intercept five and gradient three; it is linear but not directly proportional. To compare another tariff C = 5d + 1, equate their costs and solve. The crossing point identifies equal cost, while values on either side establish which is cheaper. Restrict conclusions to meaningful distances.',
   'Compare C = 3d + 5 with C = 5d + 1.', ['Set 3d + 5 = 5d + 1, giving 4 = 2d.', 'd = 2 and both cost £11.', 'At d = 1 the second costs less; at d = 3 the first costs less.'],
   'Intercept is the start; gradient is the rate.', 'Choosing the lower intercept as cheapest for every distance.', 'Compare the full expressions and locate any crossing in the allowed domain.',
   'What does the intercept represent in this tariff?', 'The fixed charge at zero distance.',
   'Plans A and B cost 2n + 12 and 4n + 2 pounds. Find the break-even usage and choose the cheaper plan at n = 8.',
   '2n + 12 = 4n + 2 gives n = 5 and cost £22. At eight units A costs £28 and B £34, so A is cheaper by £6.',
   { ...challenge, memoryExplanation: 'A graph separates the starting charge from the amount added per unit.', misconceptionCause: 'Comparing only one feature ignores the trade-off between fixed and variable costs.' }]
 ]],
 ['Geometry and measurement', [
  ['Calculate trapezium area from a rearrangement', 'Connect the area formula with parallel-side lengths and perpendicular height.',
   'Two identical trapezia can be arranged into a parallelogram whose base is the sum of the parallel sides and whose height is their perpendicular separation. One trapezium therefore has half that area: A = (a + b)h/2. A sloping side is not normally the height. Draw or identify the perpendicular distance before inserting measurements, and report square units.',
   'Find the area with parallel sides 7 cm and 11 cm and perpendicular height 4 cm.', ['Add the parallel lengths: 7 + 11 = 18 cm.', 'Multiply by height: 18 × 4 = 72 cm².', 'Halve to obtain 36 cm².'],
   'Average the parallel sides, multiply by height.', 'Using the longest sloping edge as h.', 'Height is measured at right angles between the parallel lines.',
   'Why does the formula include a half?', 'The paired rearrangement has the area of two identical trapezia.',
   'A trapezium has area 45 cm² and parallel sides 6 cm and 12 cm. Find its height.',
   'The average parallel length is 9 cm. Since 9h = 45, h = 5 cm. This is the perpendicular separation, not a sloping edge.',
   { ...core, memoryExplanation: 'The average parallel width represents the equivalent rectangle width.', misconceptionCause: 'Diagrams often label a sloping edge more prominently than the perpendicular separation.' }],
  ['Relate circumference and area of a circle', 'Use radius and diameter correctly in two different measurements.',
   'Circumference is a boundary length, C = πd = 2πr. Area measures the region inside, A = πr². Doubling radius doubles circumference but quadruples area because the radius is squared. Estimate with π approximately 3.14 when a decimal is needed, but retain π for an exact answer. Keep length and area units distinct.',
   'A circle has diameter 10 cm. Find exact circumference and area.', ['The radius is half the diameter: 5 cm.', 'Circumference is π × 10 = 10π cm.', 'Area is π × 5² = 25π cm².'],
   'Round the edge uses diameter; fill the region squares radius.', 'Squaring the diameter in πr².', 'Label radius explicitly before substituting.',
   'What is the radius when diameter is 14 cm?', '7 cm.',
   'For radius 3 m, find C and A. If radius becomes 6 m, how do both change?',
   'Initially C = 6π m and A = 9π m². The new values are 12π m and 36π m²: circumference doubles and area quadruples.',
   { ...core, memoryExplanation: 'Boundary and covering are different quantities and scale differently.', misconceptionCause: 'The same circle measurements appear in both formulas, inviting a radius/diameter substitution error.' }],
  ['Challenge: reason with polygon angles', 'Connect triangulation, angle sums and equal exterior turns.',
   'A convex polygon with n sides can be divided from one vertex into n − 2 triangles, giving interior sum (n − 2) × 180°. A regular polygon shares the interior sum equally. Walking around any convex polygon makes a full turn of 360° through its exterior angles. For a regular polygon, each exterior angle is 360°/n and is supplementary to its interior angle.',
   'A regular polygon has exterior angle 24°. Find its sides and interior angle.', ['The full turn gives n = 360 ÷ 24 = 15.', 'Interior and exterior at a vertex sum to 180°.', 'The interior angle is 156°.'],
   'A journey around the boundary turns once.', 'Using 360° as every polygon’s interior sum.', '360° is the exterior-turn total; the interior sum depends on n.',
   'How many triangles arise from one vertex of a convex hexagon?', 'Four.',
   'Could a regular polygon have exterior angle 22°? Find the interior angle of a regular nonagon.',
   'No: 360 ÷ 22 is not a whole number of sides. A nonagon has nine sides, so exterior angle is 40° and interior angle is 140°.',
   { ...challenge, memoryExplanation: 'The turn argument explains both the total and the whole-number restriction on sides.', misconceptionCause: 'Interior angles and turning angles are easily confused because they share a vertex.' }]
 ]],
 ['Probability and statistical comparison', [
  ['Build a complete sample space', 'List equally likely combined outcomes without omitting or duplicating cases.',
   'For two fair independent coin tosses, the ordered outcomes are HH, HT, TH and TT. Two heads is one of four equally likely outcomes, not one of three categories named zero, one or two heads. Categories can contain different numbers of outcomes. A table systematically represents two-stage experiments and separates outcome counting from labels.',
   'Find the probability of exactly one head in two tosses.', ['List HH, HT, TH, TT.', 'Exactly one head occurs in HT and TH.', 'Probability is 2/4 = 1/2.'],
   'Count equally likely outcomes, not unequal categories.', 'Assigning probability one third to each number of heads.', 'Notice that the one-head category has two underlying outcomes.',
   'Are HT and TH distinct ordered outcomes?', 'Yes.',
   'Roll two fair six-sided dice. How many ordered outcomes total four, and what is the probability?',
   'The favourable outcomes are (1,3), (2,2) and (3,1). There are 36 ordered outcomes in all, so probability is 3/36 = 1/12.',
   { ...core, memoryExplanation: 'A row-column table makes each ordered pair visible exactly once.', misconceptionCause: 'Everyday outcome names can hide unequal numbers of equally likely elementary cases.' }],
  ['Compare centre and spread', 'Use averages and range together when comparing small data sets.',
   'A mean describes the total shared equally, while a median identifies the central value after ordering. Range is maximum minus minimum and describes one aspect of spread. Two groups can have the same mean but very different consistency. An extreme value may pull the mean substantially, so choose summaries appropriate to the question and inspect the actual data.',
   'Compare A = 4, 5, 6 and B = 1, 5, 9.', ['Both totals are 15, so both means are 5.', 'A has range 2 and B range 8.', 'B varies more by this measure despite the identical mean.'],
   'Centre tells typical location; spread tells variation.', 'Concluding equal means imply identical performance.', 'Compare an appropriate spread measure and the distribution too.',
   'What is the first step before finding a median?', 'Put the observations in order.',
   'For 3, 4, 4, 5, 24, calculate mean and median. Which better represents most observations here?',
   'Mean is 40/5 = 8 and median is 4. The median is closer to the cluster of four observations; the large 24 raises the mean.',
   { ...core, memoryExplanation: 'A single summary compresses information; a second measure reveals what was hidden.', misconceptionCause: 'Treating an average as a complete description erases distribution shape and outliers.' }],
  ['Challenge: distinguish expected frequency from a guarantee', 'Combine probability and repeated trials while reasoning about uncertainty.',
   'Expected frequency is probability multiplied by the number of trials. A fair die should produce about fifty sixes in three hundred rolls on average across repeated experiments, but exactly fifty is not guaranteed in one experiment. Relative frequency often stabilises with many trials; it does not force future outcomes to compensate for a recent run. Independence means previous rolls do not alter the next fair roll.',
   'Estimate sixes in 240 fair die rolls.', ['Probability of a six is 1/6.', 'Expected frequency is 240 × 1/6 = 40.', 'An observed total may differ from forty without proving the die is biased.'],
   'Expectation describes repetition, not a promise.', 'Saying a six is due after several non-sixes.', 'For independent fair rolls, the next probability remains one sixth.',
   'What is the expected number of heads in 80 fair tosses?', '40.',
   'A spinner has probability 0.3 of blue. Estimate blues in 500 spins. Does 140 prove unfairness?',
   'The expected frequency is 150. An observed 140 alone does not prove unfairness; random variation, method and further evidence must be considered.',
   { ...challenge, memoryExplanation: 'The long-run prediction is compatible with short-run variation.', misconceptionCause: 'The everyday word expected can be mistaken for a required exact result.' }]
 ]]
]];
