import type { Subject, ActivityDetail } from '../authoredActivities';
const free: ActivityDetail = { isPremium: false, difficulty: 'Core', estimatedMinutes: 15, revision: 'Tomorrow, redraw the physical model and label units. In a week, solve the application before looking at its explanation.' };
const extension: ActivityDetail = { ...free, isPremium: true, difficulty: 'Higher', estimatedMinutes: 20 };
export const year8Physics: Subject = ['physics', [
 ['Current and potential difference', [
  ['Distinguish current from potential difference', 'Explain charge flow and energy transfer as different circuit quantities.',
   'Current is the rate of charge flow, measured in amperes. Potential difference describes energy transferred per unit charge, measured in volts. A lamp does not use up current; charge continues around a complete series circuit while energy is transferred to the surroundings. Use low-voltage classroom apparatus only, with correctly connected meters and supervision.',
   'Explain measurements before and after one lamp in a series circuit.', ['The same rate of charge flow passes each point in steady operation.', 'The lamp transfers energy from the electrical supply.', 'Current remains the same around that single loop; potential difference is measured across components.'], 'Charge circulates; energy transfers.', 'Saying current falls after each component because it is consumed.', 'Separate charge conservation from transfer of energy.', 'What is the unit of current?', 'The ampere.',
   'Why is an ammeter placed in series rather than connected straight across a cell?', 'It measures charge passing through the path. Directly bridging a supply with a low-resistance ammeter can create an unsafe large current.',
   { ...free, memoryExplanation: 'The distinction prevents treating charge as a fuel that disappears.', misconceptionCause: 'Everyday language about using electricity can merge current and energy.' }],
  ['Challenge: reason about parallel branches', 'Apply current splitting and shared potential difference in a simple parallel circuit.',
   'In a parallel circuit, current divides between branches and recombines. The current entering a junction equals the total leaving it. Components connected across the same two junctions have the same potential difference, not necessarily the same current. Branch currents depend on the components. An open branch need not interrupt another complete branch.',
   'A supply current of 0.8 A splits; one branch carries 0.3 A.', ['Apply charge conservation at the junction.', 'Subtract 0.3 from 0.8.', 'The other branch carries 0.5 A and the recombined current is 0.8 A.'], 'Add currents at junctions; compare voltage across common points.', 'Assuming current must divide equally regardless of branch components.', 'Equal division requires equivalent branch behaviour, not merely two paths.', 'What happens to total charge flow at a junction?', 'The incoming rate equals the outgoing total in steady operation.',
   'Two parallel lamps share a supply. One branch opens. Must the other lamp go out?', 'No. The other branch can retain a complete path across the supply, although real supply behaviour and component ratings still matter.',
   { ...extension, memoryExplanation: 'Junction accounting tracks charge without requiring identical branches.', misconceptionCause: 'A symmetric diagram can misleadingly suggest electrically identical components.' }]
 ]],
 ['Thermal energy transfer', [
  ['Explain conduction and convection', 'Connect microscopic transfer with bulk movement in different materials.',
   'Conduction transfers energy through interactions between neighbouring particles; metals also have mobile electrons that contribute. Convection transfers energy through bulk movement of a fluid, often driven by density differences during heating. A solid metal spoon can conduct energy but does not form a convection current within its solid body. Temperature is not itself a material flowing from place to place.',
   'Explain circulating water heated from below.', ['Warmer water expands and becomes less dense under ordinary conditions.', 'Buoyancy can move it upwards while cooler water replaces it.', 'The moving fluid transports energy through a convection pattern.'], 'Conduction passes; convection carries fluid.', 'Describing heat rising as a rule for every transfer process.', 'Identify the substance moving and the mechanism; conduction can occur in any direction.', 'Which process involves bulk fluid movement?', 'Convection.',
   'Why does a metal handle warm even if the solid handle does not circulate?', 'Energy is transferred through the solid by conduction rather than by a bulk convection current.',
   { ...free, memoryExplanation: 'The words distinguish particle interactions from motion of the material as a whole.', misconceptionCause: 'A familiar upward warm-air example is overgeneralised to all thermal transfer.' }],
  ['Challenge: compare insulation evidence', 'Explain an insulation test through several transfer pathways and controlled conditions.',
   'An insulator reduces particular transfer rates rather than creating heat. Trapped air limits conduction and suppresses large convection currents when the pockets are small. A fair cooling test controls initial temperature, liquid volume, container and timing. Temperature change can involve radiation and evaporation too, so identify which pathways the design alters before claiming a universal best material.',
   'Compare covered cups with equal water volumes and starting temperatures.', ['Keep cup type and measurement times consistent.', 'Change the intended insulation layer and record cooling.', 'Interpret a smaller drop as reduced net energy transfer under these conditions, not energy production.'], 'Slower loss is not added energy.', 'Using a warmer starting cup as proof of superior insulation.', 'Compare like-for-like starting conditions or a justified cooling-rate analysis.', 'Does insulation generate energy?', 'No.',
   'Why can adding a lid change the result even when the wall insulation stays the same?', 'A lid can reduce evaporation and air movement at the surface, altering energy loss through a different pathway.',
   { ...extension, memoryExplanation: 'The comparison must track both the starting store and the routes of transfer.', misconceptionCause: 'Final temperature alone hides differences present before the test began.' }]
 ]],
 ['Pressure and turning effects', [
  ['Calculate pressure from force and contact area', 'Explain how spreading a force changes pressure.',
   'Pressure is force divided by area, measured in pascals when force is in newtons and area in square metres. The same force produces a smaller pressure over a larger area. Snowshoes spread a person’s weight; a narrow heel concentrates it. Keep the contact area, not the object’s total surface area, in the calculation.',
   'A 600 N force acts on 0.03 m².', ['Use P = F/A.', 'Calculate 600 ÷ 0.03.', 'Pressure is 20,000 Pa.'], 'Same force, more area, less pressure.', 'Multiplying force by area for pressure.', 'Check that spreading the force should reduce, not increase, the result.', 'What area is relevant to contact pressure?', 'The area over which the force acts.',
   'The same force acts on 0.06 m². Find pressure and compare.', '10,000 Pa. Doubling the contact area halves pressure for the same force.',
   { ...free, memoryExplanation: 'A force shared across more square metres gives fewer newtons to each.', misconceptionCause: 'Using a formula without a physical check can reverse the relationship.' }],
  ['Challenge: balance moments about a pivot', 'Use perpendicular distance to compare turning effects.',
   'A force’s moment equals its magnitude multiplied by the perpendicular distance from pivot to line of action. A system can balance when clockwise and anticlockwise moments are equal. Greater distance can compensate for smaller force. Measuring along a sloping handle instead of perpendicular to the force can overestimate the turning effect.',
   'A 12 N force acts 0.5 m from a pivot. Find an opposing force at 0.3 m for balance.', ['The first moment is 12 × 0.5 = 6 N m.', 'Set the opposing moment F × 0.3 equal to 6.', 'F = 20 N, acting in the opposite turning direction.'], 'Force times perpendicular lever arm.', 'Balancing forces alone when their distances differ.', 'Compare moments around the same pivot, not just force magnitudes.', 'What unit is used for moment?', 'Newton metre, N m.',
   'Two equal 10 N forces act in opposite turning directions at 0.2 m and 0.5 m. Is the system balanced?', 'No. The moments are 2 N m and 5 N m. The larger moment determines the resultant turning tendency, despite equal forces.',
   { ...extension, memoryExplanation: 'The lever arm explains why a modest force can produce a large turn.', misconceptionCause: 'Equal-force reasoning from linear motion misses the role of position.' }]
 ]]
]];
