import type { Subject } from '../authoredActivities';
export const year5Core: Subject[] = [
['maths', [
 ['Factors and equivalent fractions', [
  ['Find all factor pairs', 'Use paired products to identify every positive factor of a number.',
   'A factor divides a whole number exactly. Factors come in pairs: for twenty-four, one pairs with twenty-four, two with twelve, three with eight and four with six. Once a tested smaller factor passes its partner, pairs would repeat. A systematic search avoids missing a factor just because it is not in a recently practised times table.',
   'Find all positive factors of 36.', ['Pair 1 with 36, 2 with 18, 3 with 12 and 4 with 9.', 'Five does not divide exactly; six pairs with six.', 'List each distinct factor: 1, 2, 3, 4, 6, 9, 12, 18, 36.'], 'Pairs prevent missing partners.', 'Counting the square-root factor twice in a factor list.', 'Record six once even though the pair is six times six.',
   'Is 5 a factor of 24?', 'No, because 24 divided by 5 is not a whole number.', 'Find the factors of 18, then explain why 18 is not prime.', '1, 2, 3, 6, 9, 18. A prime has exactly two positive factors; eighteen has six.'],
  ['Generate equivalent fractions', 'Scale numerator and denominator together to preserve a fraction.',
   'Splitting every third of a whole into two equal parts makes sixths. Two shaded thirds become four shaded sixths, so 2/3 = 4/6. Multiplying both numerator and denominator by the same non-zero number preserves the quantity. Multiplying only one changes the proportion. Diagrams must refer to the same-sized whole for this comparison.',
   'Write 3/4 with denominator 20.', ['Four equal parts must each split into five, since 4 × 5 = 20.', 'Scale the shaded count too: 3 × 5 = 15.', 'Therefore 3/4 = 15/20.'], 'Same scale on top and bottom.', 'Adding the same number to both parts and assuming equivalence.', 'Use multiplication or division by a common factor, not equal addition.',
   'Why does 1/2 equal 5/10?', 'Each half has been divided into five tenths, so the same share is represented.', 'Complete 2/5 = ?/30, then simplify 12/18.', '12/30, multiplying both parts by six. 12/18 simplifies to 2/3 by dividing both parts by six.']
 ]],
 ['Fraction calculation and scaling', [
  ['Add related denominators', 'Add fractions after expressing them in equal-sized parts.',
   'Thirds and sixths are different units, so first rename thirds as sixths. One third becomes two sixths; adding one sixth gives three sixths, or one half. The denominator names the part size and does not increase when equal-sized parts are counted together. Check that the result is plausible compared with the original fractions.',
   'Calculate 3/4 + 1/8.', ['Rename 3/4 as 6/8.', 'Add six eighths and one eighth.', 'The result is 7/8, less than one whole.'], 'Equal units before adding counts.', 'Adding denominators as well as numerators.', 'Keep the common part size and add only the number of those parts.',
   'What is 1/5 expressed in tenths?', '2/10.', 'Calculate 2/3 + 1/6, then 3/5 + 7/10.', '5/6. For the second, 6/10 + 7/10 = 13/10 = 1 3/10. A total can exceed one whole.'],
  ['Scale decimal quantities by ten and one hundred', 'Explain multiplication and division through place-value shifts.',
   'Multiplying by ten makes every digit worth ten times as much; dividing by ten makes it worth one tenth as much. The digits occupy different places relative to the fixed decimal boundary. A place-value chart is safer than a rule about adding zeros, which fails for many decimal calculations. Use zeros only where an empty place needs recording.',
   'Calculate 3.47 × 100.', ['Three ones become three hundreds.', 'Four tenths become four tens and seven hundredths become seven ones.', 'The result is 347.'], 'Scale the value of every digit.', 'Adding two zeros to make 3.4700.', 'Trailing decimal zeros preserve value; they do not multiply it by one hundred.',
   'What is 6 divided by 10?', '0.6.', 'Find 4.08 × 10 and 53 ÷ 100.', '40.8 and 0.53. Track each digit into a place ten times larger or one hundred times smaller.']
 ]]
]],
['english-lang', [
 ['Complex sentences', [
  ['Add a relative clause', 'Attach useful detail to a noun using a relative clause.',
   'A relative clause gives information about a noun: “The explorer, who carried a torn map, paused.” Who links the clause to a person. Which commonly refers to things, while that can introduce defining information. A removable parenthetical clause is separated with commas; a clause identifying exactly which person or thing is meant may not be.',
   'Add removable information about a bridge being built in 1902.', ['Start with “The bridge is closed.”', 'Insert “which was built in 1902” after bridge.', 'Write “The bridge, which was built in 1902, is closed.”'], 'Attach the detail beside its noun.', 'Putting the clause so far away that it seems to describe another noun.', 'Place the relative clause immediately after the noun it explains.',
   'Which relative pronoun can refer to a person?', 'Who.', 'Explain the difference between “The pupils who finished left” and “The pupils, who finished, left”.', 'The first identifies the pupils who finished, rather than all pupils. The comma version presents finishing as extra information about the whole named group.'],
  ['Express degrees of possibility', 'Choose modal verbs that match the intended certainty or obligation.',
   'Modal verbs such as might, could, should and must modify the meaning of another verb. “It might rain” expresses possibility; “You must wear eye protection” expresses an obligation in that context. A modal does not always have one fixed meaning: “She must be home” can express a strong inference, not an order. Read the complete sentence.',
   'Make a cautious prediction about a match being delayed.', ['A delay is possible but not certain.', 'Choose might rather than will definitely.', 'Write “The match might be delayed if the rain continues.”'], 'Choose the strength your evidence supports.', 'Using must for a weak guess and making it sound certain.', 'Match the modal to the evidence and the sentence’s purpose.',
   'Does might normally guarantee an event?', 'No.', 'Compare “You should check the map” with “You must check the map before entering”.', 'Should offers advice; must states a stronger requirement in this context. The second sentence can present checking as compulsory.']
 ]],
 ['Cohesion and editorial choices', [
  ['Connect paragraphs without repetition', 'Use a linking phrase to signal a relationship between ideas.',
   'Paragraph links tell a reader whether an idea continues, contrasts or follows from an earlier one. “However” signals contrast; “As a result” signals consequence. These phrases should reflect a real logical relationship. Adding however to an unrelated paragraph does not create a contrast. Read the main idea of each paragraph before choosing the link.',
   'Link a paragraph on benefits of cycling with one on route-safety concerns.', ['Identify the first focus as benefits.', 'Identify the second as a qualification or concern.', 'Use a suitable contrast opening, such as “However, some routes still require safety improvements.”'], 'Meaning chooses the link.', 'Using a consequence phrase when the new idea is merely another example.', 'Name the relationship first: addition, contrast, sequence or consequence.',
   'What relationship does “as a result” signal?', 'Consequence.', 'Choose a link for a paragraph explaining another advantage, not a contrast.', '“In addition” or “Another advantage is...” signals an added supporting point.'],
  ['Use commas to prevent misreading', 'Explain how punctuation can clarify sentence structure.',
   'Commas help readers identify boundaries and relationships. “After eating, the children washed up” separates an introductory phrase from its main clause. Without the comma, a reader may briefly interpret children as the object of eating. Punctuation should clarify grammar and meaning, not simply mark every place a reader happens to breathe.',
   'Clarify “Before leaving Mum checked the windows”.', ['Identify Before leaving as the introductory phrase.', 'Identify Mum as the subject of the main clause.', 'Write “Before leaving, Mum checked the windows.”'], 'Mark the boundary that prevents confusion.', 'Placing a comma between an ordinary subject and its verb.', 'Keep “Mum checked” together unless a genuine inserted phrase intervenes.',
   'Should “The tall tree fell” have a comma after tree?', 'No; that would separate the subject from its verb without a reason.', 'Explain the effect of commas in “Our guide, a skilled climber, checked the rope”.', 'They mark a removable noun phrase supplying extra information about the guide while keeping the main clause readable.']
 ]]
]],
['english-lit', [
 ['Narrative craft', [
  ['Analyse delayed information', 'Explain how withholding a detail can build suspense.',
   'A writer can describe footsteps, a moving shadow and a character’s reaction before naming who approaches. The reader temporarily shares uncertainty, which may build suspense. The effect depends on pacing and context, not on using the word suddenly. Track what information is available at each point and when the uncertainty is resolved.',
   'Explain the suspense in “Three taps. A pause. Then the handle moved.”', ['The cause of the taps is unnamed.', 'Short units delay the revelation while focusing attention.', 'The moving handle suggests an approaching encounter, increasing anticipation.'], 'What is known, and what is withheld?', 'Calling any short sentence suspenseful without explaining its information.', 'Connect the sentence choices to what the reader is waiting to learn.',
   'What is withheld in the example?', 'Who or what is outside and why it is entering.', 'How would “Dad tapped, then opened the door” change the effect?', 'Naming Dad immediately removes one uncertainty, so suspense may decrease unless other context makes his arrival worrying.'],
  ['Evaluate a narrator’s limited perspective', 'Distinguish an account from independently established events.',
   'A first-person narrator reports events through their own knowledge, memory and feelings. “Everyone laughed at me” could be an accurate observation or a frightened interpretation of a few people’s laughter. Look for details that support or complicate the claim. Limited perspective does not automatically mean deliberate lying.',
   'A narrator says nobody helped, then describes a classmate offering a chair.', ['Notice the broad claim nobody helped.', 'Compare the specific offer with that claim.', 'The narrator may overlook help because of distress or judge that help as insufficient.'], 'Claim versus described evidence.', 'Calling every imperfect narrator dishonest.', 'Consider limited knowledge, emotion or memory before alleging deliberate deception.',
   'Does first-person narration give access to every character’s thoughts?', 'No.', 'Why might a second account change the reader’s understanding?', 'It can supply observations or motives unavailable to the first narrator, allowing their interpretation to be reassessed.']
 ]],
 ['Comparison and poetic imagery', [
  ['Compare treatments of a shared theme', 'Build a comparison around a common idea and supporting details.',
   'Two texts can explore courage differently: one character acts despite fear while another learns to ask for help. A comparison should use the same question for both texts, not summarise them separately. State a similarity or difference, select evidence from each and explain what it shows about the shared theme.',
   'Compare a lone rescue story with one about seeking adult help.', ['Identify courage as the common focus.', 'The first may emphasise direct action; the second may emphasise acknowledging limits.', 'Explain how both can challenge the idea that courage means feeling no fear.'], 'One question, two sets of evidence.', 'Comparing plot details without connecting them to the theme.', 'Explain what each chosen action suggests about courage.',
   'What makes a comparison balanced?', 'Relevant evidence and analysis from both texts.', 'Can two stories share a theme but give different messages?', 'Yes. They can explore the same concern while valuing different responses or highlighting different consequences.'],
  ['Trace an extended image', 'Explain how several related images build a coherent impression.',
   'An extended image develops a comparison across more than one phrase. A city described as waking, stretching its roads and yawning open its stations is imagined as a living body. The linked details work together to animate the setting. Identify the shared comparison rather than treating each phrase as an unrelated decorative technique.',
   'Analyse “The harbour woke; cranes stretched and engines cleared their throats”.', ['Notice human waking actions applied to machinery and place.', 'Connect stretching and throat-clearing with a waking body.', 'Explain that the harbour seems to come alive as work begins.'], 'Several details, one developing picture.', 'Listing techniques without explaining their combined effect.', 'Name the underlying comparison and show how each detail extends it.',
   'What connects the harbour’s cranes and engines in the example?', 'They receive actions associated with a person waking.', 'Suggest a detail that would extend the same image rather than introduce an unrelated one.', 'For example, “The docks took their first deep breath” continues the human-body waking comparison.']
 ]]
]],
['science-combined', [
 ['Earth and space', [
  ['Explain day and night through rotation', 'Use Earth’s rotation to explain changing illumination.',
   'Earth rotates on its axis approximately once every twenty-four hours. The side facing the Sun receives daylight, while the opposite side is in darkness. A place moves into and out of sunlight as Earth turns. The Sun’s apparent daily movement across the sky is not evidence that it circles Earth once each day. Never look directly at the Sun.',
   'Model a town using a sticker on a globe and a lamp as the Sun.', ['Keep the lamp in one position.', 'Rotate the globe so the sticker moves into and out of the lit half.', 'The changing light at the sticker models day and night.'], 'Rotation brings the day around.', 'Confusing a daily rotation with Earth’s yearly orbit.', 'Model spinning on an axis separately from travelling around the Sun.',
   'Approximately how long is one Earth rotation?', 'Twenty-four hours.', 'Why can it be daytime in one place and night elsewhere at the same moment?', 'Different parts of the rotating Earth face towards or away from the Sun at that time.'],
  ['Distinguish orbit from visible Moon shape', 'Explain that lunar phases result from viewing the illuminated half from changing positions.',
   'The Moon reflects sunlight rather than producing its own visible light. About half of its spherical surface is illuminated by the Sun, but from Earth we see different fractions of that lit half as the Moon orbits. The familiar phases are not normally caused by Earth’s shadow; that is involved in a lunar eclipse.',
   'Why does a crescent Moon appear partly lit?', ['Sunlight illuminates roughly half the Moon.', 'The Moon’s position changes our viewing angle.', 'We see only a small curved part of the illuminated half from Earth.'], 'A changing view of a lit half.', 'Explaining every phase as Earth blocking sunlight.', 'Reserve Earth’s shadow explanation for a lunar eclipse, not ordinary phases.',
   'Does the Moon make its own visible light like a lamp?', 'No; it reflects sunlight.', 'At full Moon, what fraction of the Moon’s whole surface is approximately sunlit?', 'About half. We see nearly all of that sunlit half, not a Moon illuminated on every side.']
 ]],
 ['Forces and material changes', [
  ['Separate mass from gravitational force', 'Explain weight as a force rather than a synonym for mass.',
   'Gravity attracts objects with mass. Near Earth, this attraction gives an object its weight, measured as a force in newtons. Mass is measured in kilograms and does not depend on the local gravitational field in ordinary classroom comparisons. An object moved to the Moon keeps its mass but experiences less gravitational force.',
   'Compare a sealed equipment box on Earth and on the Moon.', ['The amount of matter in the box stays the same.', 'The Moon’s gravitational field is weaker.', 'Its mass stays the same but its weight is smaller on the Moon.'], 'Mass stays; weight depends on gravity.', 'Writing kilograms as the scientific unit of force.', 'Use kilograms for mass and newtons for force.',
   'Which unit measures force?', 'The newton.', 'Why does dropping a heavier object not prove it must always land first?', 'Fall time also depends on conditions such as air resistance; a fair comparison must control shape and release conditions.'],
  ['Recover a dissolved solid', 'Explain separation by evaporation without claiming the solute vanished.',
   'When salt dissolves in water, it remains present even though individual grains are no longer visible. Evaporation removes water as vapour and can leave salt behind. A filter does not remove dissolved salt because the dissolved particles pass through with the water. Use teacher-led safe methods; never taste experimental solutions or heat them unsupervised.',
   'Choose a method to recover salt from salt water.', ['Recognise that ordinary filtration will not retain dissolved salt.', 'Allow water to evaporate under appropriate supervision.', 'Salt remains as the solvent is removed.'], 'Dissolved is dispersed, not destroyed.', 'Expecting filter paper to catch dissolved salt like sand.', 'Distinguish insoluble particles from substances dissolved in the liquid.',
   'What is the solvent in ordinary salt water?', 'Water.', 'How could you separate a mixture of sand, salt and water?', 'Filter to remove insoluble sand, then evaporate water from the filtrate to recover salt. Each step targets a different property.']
 ]]
]],
['history', [
 ['Anglo-Saxon settlement', [
  ['Explain change after Roman rule', 'Describe changes in authority without imagining an immediate empty country.',
   'Roman imperial administration in Britain ended in the early fifth century, but people and settlements did not simply disappear. Authority changed, and groups from continental Europe settled in different places over time. Later Anglo-Saxon kingdoms developed through complex local processes. Archaeology, texts and place-names provide different kinds of evidence, each with limits.',
   'Evaluate “Britain became empty when the Romans left”.', ['Ending imperial rule is not the same as removing all inhabitants.', 'Existing communities continued and changed.', 'Migration and new kingdoms developed alongside these populations.'], 'Political endings are not population erasers.', 'Treating a change in government as proof that everyone left.', 'Separate administration, population and cultural practice.',
   'Did the end of Roman rule mean all settlements instantly vanished?', 'No.', 'Why use archaeological evidence alongside later chronicles?', 'Material remains can reveal everyday continuity or change that later written narratives omit or simplify.'],
  ['Interpret a rich burial carefully', 'Distinguish what grave goods show from uncertain claims about identity.',
   'The Sutton Hoo ship burial contains rich objects suggesting high status and wide connections in early medieval society. Objects can indicate wealth, craftsmanship and exchange, but identifying the buried person requires further argument. A prestigious burial is not a typical household. Interpretations should distinguish secure observations from plausible but debated conclusions.',
   'What can an imported object in a burial suggest?', ['Identify the material or style connecting it with another region.', 'Consider exchange, gifts or travel as possible routes.', 'Infer wider connections without claiming its owner personally visited that region.'], 'An object travelled; its owner may not have.', 'Assuming every foreign-made object proves direct travel by the buried person.', 'Consider several ways goods could move between communities.',
   'Does a wealthy burial represent every person’s living conditions?', 'No.', 'What further evidence could strengthen an identification of the buried individual?', 'Dated records, inscriptions, the burial date and regional political context could support a claim, though certainty may remain limited.']
 ]],
 ['Viking contact and historical perspectives', [
  ['Distinguish raiding, trading and settling', 'Explain why one label cannot describe all Scandinavian activity.',
   'Scandinavian people came to Britain as raiders, traders and settlers at different times and places. A raid seeks goods or advantage through attack; trade involves exchange; settlement involves establishing communities. One group could engage in more than one activity. Sources describing a violent raid do not by themselves describe every person who later settled.',
   'Compare evidence of a monastery raid with a settlement market.', ['The raid account records violent contact.', 'Market evidence may show exchange and everyday activity.', 'Use both to avoid reducing all contact to one activity.'], 'Ask what happened here, not what everyone was.', 'Treating all Scandinavian arrivals as identical raiders.', 'Distinguish activities and contexts using specific evidence.',
   'What distinguishes settlement from a short raid?', 'Settlement involves establishing or maintaining a community in the place.', 'Why might a monastic account emphasise violence?', 'Its author and community may have experienced attack directly; that viewpoint is valuable but does not describe every kind of contact.'],
  ['Compare an agreement with its consequences', 'Explain that political boundaries and settlements can change over time.',
   'Agreements between Anglo-Saxon and Scandinavian leaders helped define areas of influence, but boundaries and authority changed over time. The term Danelaw relates to areas associated with Scandinavian settlement and legal influence, not a timeless line dividing two uniform populations. A map should be read with its date and purpose rather than treated as permanent.',
   'Two maps show different political divisions decades apart.', ['Read the date and key of each map.', 'Identify changes in areas of control.', 'Explain change through later conflict, agreements or consolidation rather than assuming one map must be wrong.'], 'A political map needs a date.', 'Treating a boundary as permanent for the whole period.', 'Connect each map with the events and time it represents.',
   'Why does a historical map need a date?', 'Control and boundaries can change.', 'Can a political boundary prove everyone on either side shared one identity?', 'No. Population, language, customs and political control can overlap in more complicated ways.']
 ]]
]]
];
