import type { Subject } from '../authoredActivities';
export const year7Humanities: Subject[] = [
['english-lang', [
 ['Analytical sentences', [
  ['Analyse a word in context', 'Connect a precise language choice with a supported inference.',
   'A word’s connotations depend on context. In “the office devoured her evenings”, devoured suggests consumption and loss of control, not literal eating. An analytical sentence should identify the wording, explain relevant associations and connect them with the situation. Naming a metaphor alone does not establish its effect.',
   'Analyse the verb in “Mist swallowed the lane”.', ['Identify swallowed as the selected verb.', 'Explain its association with engulfing or consuming.', 'Connect that association to the lane becoming obscured and potentially threatening.'], 'Choice, association, contextual meaning.', 'Listing every possible dictionary meaning instead of the relevant one.', 'Select associations supported by the sentence and surrounding passage.',
   'Is technique naming by itself a complete analysis?', 'No.', 'Write a short analysis of “The queue crawled towards the door”.', 'Crawled suggests very slow progress and may convey impatience; the queue is described through an action associated with slow physical movement.'],
  ['Embed evidence grammatically', 'Integrate a short quotation into an analytical sentence.',
   'A quotation should fit the grammar of your own sentence while preserving the source’s wording. “The verb ‘crawled’ makes progress seem painfully slow” integrates evidence more smoothly than an unexplained quotation dropped between claims. Select only the relevant words and explain them. Any omission or alteration must not distort the original meaning.',
   'Embed “splintered silence” in a comment on sudden noise.', ['Identify the phrase relevant to the contrast.', 'Write a sentence that introduces its function.', 'For example: The phrase “splintered silence” presents the sound as violently breaking the previous stillness.'], 'Evidence belongs inside reasoning.', 'Using a quotation as a replacement for explaining the point.', 'Add an explicit link between the quoted words and the interpretation.',
   'Should evidence preserve the source’s meaning?', 'Yes.', 'Improve “It is scary. ‘The lock clicked.’” as an analytical sentence.', 'The abrupt statement “The lock clicked” can heighten tension by drawing attention to a small sound before the reader knows who is entering; the wider context must support this effect.']
 ]],
 ['Purposeful writing', [
  ['Control viewpoint in description', 'Select details consistently through a chosen observer’s perspective.',
   'A description is shaped by what its observer notices. A tired traveller may focus on harsh lights and distance to the exit, while an excited visitor notices music and colour. Establish viewpoint through selection rather than repeatedly naming an emotion. Maintain access limits: a first-person observer cannot directly know a stranger’s private thoughts.',
   'Describe a station through an anxious traveller’s viewpoint.', ['Select details relevant to uncertainty, such as changing displays.', 'Use sensory details the traveller could perceive.', 'Suggest anxiety through repeated checking or difficulty choosing a platform.'], 'Viewpoint filters the scene.', 'Switching into another character’s thoughts without a deliberate narrative change.', 'Check whose perceptions the description follows.',
   'Can viewpoint affect detail selection without changing the setting itself?', 'Yes.', 'Why might a confident commuter notice different details in the same station?', 'Their familiarity and purpose guide attention, perhaps towards a routine shortcut rather than confusing signs.'],
  ['Build an evidence-based persuasive paragraph', 'Link a claim, supporting evidence and explanation of relevance.',
   'A persuasive paragraph needs more than forceful wording. State a focused claim, provide relevant evidence and explain how it supports the proposal. If evidence is hypothetical or supplied only for an exercise, label it accordingly rather than presenting invented statistics as fact. Address the audience’s likely concern and avoid certainty beyond the evidence.',
   'Argue for clearer library signs using an observed navigation problem.', ['State that signs should help pupils find sections independently.', 'Describe a genuine or explicitly hypothetical observation of confusion.', 'Explain how clear labels could address that specific barrier and how success could be checked.'], 'Evidence needs an explained connection.', 'Inventing a percentage to make a claim look researched.', 'Use verified information or openly labelled illustrative examples.',
   'Does a statistic automatically support a proposal?', 'No; its relevance and reliability need explaining.', 'What makes “Everyone wants it” weak evidence?', 'It is an unsupported universal claim; a suitable survey or qualified observation would provide a clearer basis.']
 ]]
]],
['english-lit', [
 ['Narrative methods', [
  ['Distinguish narrator from author', 'Explain why a fictional voice should not automatically be treated as the writer’s own beliefs.',
   'The author creates the text; a narrator is the voice presenting its story. A narrator can misunderstand, exaggerate or express views that the wider narrative questions. Analyse how the text positions readers towards that voice rather than assuming every statement represents the author’s opinion. Contradictions between narration and events can be particularly revealing.',
   'A narrator calls himself generous while refusing small requests for help.', ['Identify the narrator’s self-description.', 'Compare it with his actions.', 'The discrepancy may invite readers to question his judgement rather than endorse it.'], 'Created voice is not automatic author endorsement.', 'Attributing every fictional claim directly to the writer.', 'Examine narrative framing, action and contrasting voices.',
   'Can an author create a narrator with objectionable views?', 'Yes.', 'What evidence might show that the text challenges a narrator’s confidence?', 'Events, other perspectives or internal contradictions may expose limits in the narrator’s account.'],
  ['Analyse foreshadowing', 'Explain how an earlier detail gains significance through later events.',
   'Foreshadowing introduces a detail that prepares readers for a later development. A repeatedly mentioned damaged bridge may anticipate a future crossing problem. Not every minor object is foreshadowing: show the later connection and its effect. On rereading, the detail can feel more significant because the reader now understands what it anticipates.',
   'A rope is described as fraying before a later rescue scene.', ['Locate the earlier description.', 'Connect it with the later strain placed on the rope.', 'Explain how it can create apprehension and make the later danger feel prepared.'], 'Earlier detail, later consequence.', 'Calling a detail foreshadowing without identifying what it anticipates.', 'Show a supported link across the narrative.',
   'Does foreshadowing have to reveal the exact ending?', 'No.', 'How might the same frayed-rope detail affect a first reading and a rereading differently?', 'Initially it may create uncertain concern; later it may appear as deliberate preparation for a known event.']
 ]],
 ['Poetry and drama', [
  ['Analyse enjambment and end-stopping', 'Connect line endings with pace and emphasis.',
   'Enjambment carries grammatical meaning beyond a line ending without a full syntactic stop. An end-stopped line closes a phrase or sentence at its boundary. These choices can guide pace, expectation and emphasis, but their effects depend on the actual words. Do not assume every enjambed line must be read breathlessly or every line ending needs a long pause.',
   'Consider “I reached for the light / that nobody had left on.”', ['The first line creates an expectation about a light.', 'The sentence continues across the break.', 'The second line qualifies that expectation, potentially producing disappointment or irony.'], 'Line boundary and sentence boundary may differ.', 'Pausing heavily after every printed line regardless of grammar.', 'Read for both syntax and the expressive possibility of the break.',
   'What does enjambment describe?', 'A grammatical unit continuing across a line break.', 'Why should analysis quote the words around the break?', 'Those words establish the expectation and continuation that make the structural effect specific rather than generic.'],
  ['Read stage directions as dramatic evidence', 'Explain how performance instructions shape an audience’s understanding.',
   'Stage directions can specify movement, pause, setting or delivery. They are not spoken dialogue unless a production deliberately transforms them. A pause before an answer may suggest hesitation, calculation or shock depending on context. Connect the direction with the surrounding speech and action rather than assigning it one permanent emotional meaning.',
   'A character says “Of course” after a direction marking a long pause.', ['Notice the apparent certainty of the words.', 'Compare it with the delayed response.', 'The contrast may suggest reluctance or concealed doubt, depending on the scene.'], 'Speech and action interpret each other.', 'Treating a stage direction as a line another character hears.', 'Distinguish information for performers and readers from spoken dialogue.',
   'Can two productions interpret a pause differently?', 'Yes.', 'What would support interpreting the pause as shock rather than deception?', 'A preceding unexpected revelation and later reactions could support shock, whereas contradictory behaviour might support deception.']
 ]]
]],
['history', [
 ['The Norman Conquest', [
  ['Explain competing claims in 1066', 'Distinguish claims to authority from uncontested succession rules.',
   'After Edward the Confessor died in 1066, different claimants advanced reasons for ruling England. Harold Godwinson’s position and coronation, William of Normandy’s claims about promises, and Harald Hardrada’s dynastic argument reflected different bases of legitimacy. These were contested claims preserved through sources with interests, not a modern election with one agreed procedure.',
   'Why should a claim about a promised succession be examined critically?', ['Identify who reports the promise and when.', 'Consider the claimant’s interest in presenting it as binding.', 'Compare other evidence rather than treating the claim itself as proof.'], 'A claim explains ambition; evidence tests it.', 'Presenting every claimant’s argument as simultaneously established fact.', 'Attribute contested claims and distinguish them from securely dated events.',
   'Which English king died at the start of 1066?', 'Edward the Confessor.', 'Why might later accounts disagree about a succession promise?', 'Authors’ loyalties, information and purposes could affect how they represented a contested claim.'],
  ['Build a multi-causal explanation of Hastings', 'Connect circumstances, decisions and tactics without relying on one slogan.',
   'William’s victory at Hastings in October 1066 followed a sequence involving Harold’s northern campaign, movement south and a contested battle. Explanations can consider preparation, leadership, forces and battlefield developments. A factor matters when its mechanism is explained; saying “luck” or “better tactics” without showing how it affected events is incomplete.',
   'Explain how an earlier campaign could affect a later battle.', ['An earlier campaign uses time and resources.', 'Movement and regrouping can affect readiness and available forces.', 'Connect those conditions to the later battle cautiously rather than claiming they alone determined victory.'], 'Factor plus mechanism, not just a label.', 'Listing several causes without showing how they operated.', 'Explain a causal link and compare its importance with other factors.',
   'Does one contributing cause have to be sufficient on its own?', 'No.', 'Why should an explanation of victory consider the opposing side’s decisions too?', 'Battle outcomes emerge from interacting actions and circumstances, not only one leader’s plan.']
 ]],
 ['Control and source enquiry', [
  ['Explain castles as instruments of power', 'Connect physical features with military and political functions.',
   'Norman castles could provide fortified bases, control routes and display authority over surrounding communities. Their locations and forms varied. A castle’s function was not limited to defence against foreign invasion; it could support local domination and administration. Connect a feature or location with a mechanism rather than assuming any large building automatically creates control.',
   'Explain a castle overlooking a river crossing.', ['A crossing concentrates movement of people and goods.', 'A fortified position can monitor or influence that movement.', 'Its visible presence can also communicate the ruler’s authority.'], 'Place and design support power.', 'Assuming every castle served exactly the same local purpose.', 'Use location, date and surrounding evidence to specify the argument.',
   'Why might a route junction be strategically valuable?', 'It concentrates access and movement.', 'How could a castle affect people without an actual battle taking place?', 'Its garrison, visibility and control of routes could shape behaviour, obligations and local perceptions of authority.'],
  ['Evaluate a source for a specific question', 'Separate usefulness from the simplistic label biased or unbiased.',
   'A source’s usefulness depends on the question. A conquest narrative supporting a ruler may be limited as a balanced battle account but valuable for studying how authority was justified. Examine content, origin, purpose and context together. Bias does not make a source worthless, and being contemporary does not make every statement accurate.',
   'Use a victory celebration to investigate the conqueror’s public image.', ['Identify how the ruler is praised.', 'Connect those choices with the celebratory purpose.', 'Use it as evidence of representation while testing factual battle claims against other sources.'], 'Useful for what?', 'Discarding a partisan source before considering the enquiry.', 'Match its strengths and limits to the particular historical question.',
   'Can propaganda be useful evidence?', 'Yes, especially for how people sought to persuade or justify power.', 'Why compare a source’s claims with independent evidence?', 'Corroboration can strengthen or challenge factual claims beyond the source’s own self-presentation.']
 ]]
]],
['geography', [
 ['Mapping and spatial enquiry', [
  ['Read a four-figure grid reference', 'Identify a map square using eastings before northings.',
   'On an Ordnance Survey-style grid, eastings increase eastwards and northings increase northwards. A four-figure reference names the square using the lower-left grid intersection: two digits for the easting, then two for the northing. It identifies an area, not an exact point. Read the map’s actual numbers rather than counting squares from the page edge.',
   'Name the square east of easting 23 and north of northing 47.', ['Read the left boundary as 23.', 'Read the bottom boundary as 47.', 'The four-figure reference is 2347.'], 'Along the corridor, then up the stairs.', 'Using the top-right corner’s numbers.', 'Identify the square’s lower-left intersection first.',
   'Does a four-figure reference identify one exact building within a square?', 'No.', 'Which square lies immediately east of 2347?', '2447. The easting increases by one while the northing remains unchanged.'],
  ['Use map scale to estimate distance', 'Convert a measured map length into ground distance.',
   'A scale of 1:50,000 means one unit on the map represents fifty thousand of the same unit on the ground. One centimetre therefore represents 50,000 centimetres, or 500 metres. Convert units explicitly and distinguish straight-line distance from route distance, which may be longer. A scale bar can remain useful when a map is resized correctly with it.',
   'At 1:50,000, a straight map line measures 6 cm.', ['Multiply 6 by 50,000 to obtain 300,000 cm.', 'Convert to 3,000 m.', 'The straight ground distance is 3 km.'], 'Same-unit ratio, then convert.', 'Multiplying centimetres directly into kilometres without conversion.', 'Show the intermediate unit or use the known 1 cm to 0.5 km relationship.',
   'At this scale, what does 2 cm represent?', '1 km.', 'Why can a 3 km straight-line measurement underestimate walking distance?', 'Paths follow routes around obstacles and bends rather than necessarily taking the direct line.']
 ]],
 ['Weather processes and fieldwork', [
  ['Explain relief rainfall', 'Link rising air, cooling and condensation near high land.',
   'Moist air forced upwards over high ground cools as it rises. If it cools sufficiently, water vapour condenses into droplets and clouds form; precipitation may follow. On the leeward side, descending air can become warmer and relatively drier, contributing to a rain-shadow effect. The model describes a process, not a guarantee of rain at every hill.',
   'Explain why a windward slope may receive more rain.', ['Air is pushed upwards by the terrain.', 'Rising air cools and may reach conditions for condensation.', 'Cloud droplets can grow and fall, increasing precipitation on that side.'], 'Rise, cool, condense, possibly rain.', 'Saying cold air itself is a liquid that falls.', 'Distinguish air from the water droplets forming within it.',
   'Which side faces the approaching moist wind?', 'The windward side.', 'Why might the leeward side be drier?', 'Air may have lost moisture on ascent and warms during descent, reducing relative humidity and the likelihood of condensation.'],
  ['Evaluate a microclimate comparison', 'Control sampling when investigating small-scale environmental differences.',
   'A microclimate is a local variation in conditions caused by factors such as shade, surfaces, buildings and vegetation. Compare sites at similar times with consistent instruments and methods. A thermometer in direct sunlight may record effects of heating that differ from a shaded air-temperature measurement. State exactly what was measured before explaining why sites differ.',
   'Compare a shaded garden with a paved courtyard.', ['Use a consistent measurement height and suitable instrument exposure.', 'Record at comparable times and repeat observations.', 'Discuss shade and surfaces while acknowledging other differences between sites.'], 'Same method before site explanation.', 'Attributing the difference to paving when one reading was taken hours later.', 'Control timing and recognise remaining site differences.',
   'Can buildings affect local wind and shade?', 'Yes.', 'Why should a conclusion mention the day’s weather?', 'Cloud, wind and recent rain can influence the observed difference and limit how widely it can be generalised.']
 ]]
]],
['religious-studies', [
 ['Knowledge, belief and enquiry', [
  ['Distinguish a belief claim from evidence for it', 'Identify what a statement asserts and what reasons support it.',
   'A belief claim expresses what someone holds to be true. Reasons may include experience, testimony, tradition, philosophical argument or observation, depending on the claim. Describing those reasons accurately does not require agreeing with them. Enquiry asks whether the support is relevant and how alternatives or objections are addressed rather than judging a person’s worth.',
   'A person says a practice matters because it connects them with ancestors.', ['Identify the claim about significance.', 'Identify personal and communal experience as the stated support.', 'Evaluate what that reason explains without turning it into a universal claim about everyone.'], 'Claim and support are separate parts.', 'Treating a sincerely held belief as proof that every associated factual claim is established.', 'Distinguish sincerity, meaning and the evidence needed for particular claims.',
   'Can a belief be described accurately without being endorsed?', 'Yes.', 'Why clarify the exact claim before discussing evidence?', 'Different claims, such as personal significance and historical dates, require different kinds of support.'],
  ['Use counterexamples carefully', 'Test a universal claim with a relevant exception.',
   'A universal statement such as “All moral actions are motivated only by reward” can be challenged by an action that appears to have another motive. A proposed counterexample must actually fit the terms, and motives may be difficult to know. Careful reasoning defines the claim and recognises uncertainty rather than presenting a speculative case as decisive proof.',
   'Test “Everyone who belongs to one religion follows identical practices”.', ['Clarify that the claim says every member and identical practice.', 'Identify well-supported variation within a tradition.', 'Such variation challenges the universal claim without denying shared features.'], 'One genuine exception challenges all.', 'Using an irrelevant example that does not meet the claim’s conditions.', 'Check definitions and the quality of evidence for the exception.',
   'Does challenging a universal claim prove the opposite universal claim?', 'No.', 'Why does showing two members differ not prove a tradition has no shared practices?', 'It refutes complete uniformity, but common patterns can coexist with individual variation.']
 ]],
 ['Ethical arguments', [
  ['Compare consequences and duties', 'Explain a disagreement in terms of the reasons each approach prioritises.',
   'A consequence-focused argument evaluates likely outcomes, while a duty-focused argument emphasises obligations or principles. A decision about telling an uncomfortable truth may involve both honesty and possible harm. These approaches are not exclusively religious or non-religious, and a person may combine them. Analyse a clearly defined case rather than assuming a slogan resolves every conflict.',
   'Discuss whether to reveal a surprise that is causing serious distress.', ['Identify the duty associated with keeping a promise.', 'Consider the harm caused by continuing secrecy.', 'Explain how the specific severity and context affect the balance of reasons.'], 'Name the principle and the consequence.', 'Assuming one ethical label automatically supplies an answer for every case.', 'Examine the facts, competing duties and likely effects.',
   'Can two duties conflict?', 'Yes.', 'Why is accurate factual information important in ethical reasoning?', 'A judgement about consequences or obligations can change if the situation has been misunderstood.'],
  ['Write a qualified ethical judgement', 'Reach a reasoned conclusion while acknowledging its conditions and objections.',
   'A judgement should state a conclusion, its main reason and the strongest relevant objection. It may depend on conditions: a rule may normally be valuable but admit exceptions when serious harm is involved. Qualification is not indecision if the conditions are clear. Avoid replacing argument with a count of how many people agree.',
   'Evaluate a proposed school rule restricting phone use during lessons.', ['Identify a relevant aim such as attention or safety.', 'Consider exceptions such as approved accessibility or medical needs.', 'State a conclusion with clear conditions rather than an absolute claim ignoring those needs.'], 'Conclusion, reason, condition, objection.', 'Treating popularity as sufficient proof of moral correctness.', 'Explain the principle and practical effects supporting the conclusion.',
   'Can a clear conclusion include exceptions?', 'Yes.', 'What would make “It depends” an inadequate final answer?', 'Without specifying what it depends on and why, it avoids rather than completes the reasoning.']
 ]]
]]
];
