import type { Subject, ActivityDetail } from '../authoredActivities';
const detail = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({
 isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 20 : 15,
 priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause,
 revision: 'Tomorrow, explain the design or visual decision without notes. In a week, apply it to a different brief and compare the outcome against the intended effect.'
});
export const year8Creative: Subject[] = [
['art', [
 ['Depth and pictorial space', [
  ['Construct a one-point interior', 'Use a vanishing point for a deliberately simplified room drawing.',
   'In a one-point perspective drawing of a box-like room viewed squarely, edges receding away from the viewer converge on one vanishing point on the horizon. Front-facing verticals remain vertical and front-facing horizontals remain horizontal. The horizon represents eye level, not necessarily the boundary between land and sky. Start with a front-facing rectangle, then establish consistent depth directions rather than making every line converge.',
   'Plan a simple room with a back wall and floor.', ['Draw the back-wall rectangle and mark an eye-level vanishing point.', 'Extend depth guides through the rectangle’s corners.', 'Keep the front-facing edges upright or horizontal while checking the receding edges against the guides.'], 'Receding edges converge; front-facing edges do not.', 'Sending every vertical and horizontal line to the vanishing point.', 'Identify each edge’s spatial direction before using a perspective guide.', 'What does the horizon represent in this construction?', 'The viewer’s eye level.',
   'Why would a tilted back-wall vertical usually be inconsistent with this simplified upright room?', 'The model assumes an upright, front-facing rectangular wall. Its vertical edges remain vertical; a tilt would suggest a different geometry or viewpoint that the rest of the construction does not support.',
   detail(false, 'What is a rectangle?', 'A four-sided shape with four right angles.', 'Perspective guides can be treated as a rule for every line rather than for particular spatial directions.')],
  ['Challenge: reconcile overlapping depth cues', 'Diagnose a drawing where perspective, overlap and scale suggest incompatible spaces.',
   'Artists can suggest depth through overlap, diminishing size, linear perspective and atmospheric changes. These cues need not always agree, especially in deliberately ambiguous work. For an intended convincing room, however, a far object drawn larger without explanation or an impossible overlap may undermine the construction. Diagnose the conflicting cue and propose a focused revision rather than calling the entire drawing wrong.',
   'A chair intended to be behind a desk covers the desk’s front edge.', ['Overlap normally makes the covering shape appear nearer.', 'The chair’s intended placement conflicts with that cue.', 'Revise the contour interruption so the desk appropriately obscures the chair, unless ambiguity is intentional.'], 'Check cues against the intended space.', 'Assuming a correct vanishing point guarantees all depth relationships work.', 'Inspect overlap, relative size and placement as well as guide lines.', 'Can an artist intentionally create contradictory space?', 'Yes.',
   'Explain one reason not to “correct” every inconsistent cue in an artwork.', 'The inconsistency may be a deliberate expressive or compositional choice. Evaluation should establish the artist’s intention before assuming realistic space is the only valid goal.',
   detail(true, 'What does overlap often suggest?', 'The covering shape appears in front of the covered one.', 'Technical accuracy may be evaluated without first identifying the intended visual effect.')]
 ]],
 ['Colour interaction and composition', [
  ['Investigate simultaneous colour contrast', 'Explain why the same colour patch can appear different on different grounds.',
   'A colour is perceived in relation to its surroundings. Identical grey patches can appear lighter against a dark ground and darker against a light one. This does not mean the pigment itself changed. Compare patches cut from the same sheet under consistent lighting to isolate the surrounding field as the variable. Record the observed effect rather than assuming everyone experiences it identically.',
   'Test one grey patch on black and white backgrounds.', ['Use matched patches from the same material.', 'Keep lighting and patch size consistent.', 'Compare apparent brightness and distinguish perception from a physical pigment change.'], 'Same patch, different surroundings.', 'Mixing different greys and attributing every difference to the background.', 'Hold the patch material constant while changing the ground.', 'Does a perceived shift necessarily mean the pigment changed?', 'No.',
   'Name two controls needed for a useful comparison.', 'Use identical patch material and consistent illumination. Keeping patch size and viewing conditions similar also reduces alternative explanations.',
   detail(false, 'What is tonal value?', 'How light or dark a colour appears.', 'Perceived appearance can be confused with a change in the material itself.')],
  ['Challenge: direct attention without adding detail everywhere', 'Use selective contrast to support a focal point.',
   'A focal point can be strengthened by local tonal, colour, scale or edge contrast. Increasing detail and contrast everywhere may create competing centres rather than stronger emphasis. Work with thumbnail studies to compare a quiet background against a high-contrast subject, then test whether the intended reading order emerges. Evaluation should describe visible relationships rather than declare that bright colours always attract attention most.',
   'A poster’s background lettering competes with its main image.', ['Locate the strongest contrasts in both areas.', 'Reduce selected background contrast or edge sharpness.', 'Compare whether the main image now becomes the first clear focus without losing necessary information.'], 'Emphasis depends on difference from its surroundings.', 'Adding equal sharpness and saturation throughout to make one area stand out.', 'Create a hierarchy instead of maximising every feature.', 'Can reducing contrast strengthen another area’s emphasis?', 'Yes.',
   'Suggest a test for whether a revision improves reading order.', 'Show original and revised thumbnails briefly to several viewers without explaining the intended focus, then ask what they noticed first. Compare the responses while recognising the sample and viewing conditions are limited.',
   detail(true, 'What is a focal point?', 'An area intended to draw particular attention.', 'More visual intensity is often mistaken for clearer hierarchy.')]
 ]],
 ['Print planning and visual development', [
  ['Plan reversal in a relief-print design', 'Predict the printed orientation from a reversed design.',
   'A relief print transfers ink from raised areas of a printing surface. The resulting image is laterally reversed relative to that surface, so lettering must be planned carefully. Use a mirror or a safe paper simulation before making a block. This planning exercise does not require cutting tools; any practical carving must follow a teacher’s risk assessment and supervision.',
   'Plan a print containing a capital R.', ['Draw the intended final R on paper.', 'Use a mirror or tracing to view its reversed form.', 'Place that reversed form in the block plan so the transfer reads as intended.'], 'Plan the surface by checking the final impression.', 'Designing readable lettering on the surface and expecting it to stay unchanged in the print.', 'Test reversal with paper before committing to a surface.', 'Which areas transfer ink in a simple relief print?', 'The raised, inked areas.',
   'Why is a symmetrical shape alone a poor test of whether reversal was considered?', 'A laterally symmetrical shape may look unchanged after reversal, hiding an error that would become obvious in asymmetric lettering or imagery.',
   detail(false, 'What does lateral reversal mean?', 'A left-right reversal.', 'Symmetrical motifs can conceal the transfer’s reversal until lettering is added.')],
  ['Challenge: revise a print after a proof', 'Separate design choices from printing variables when diagnosing a weak impression.',
   'A proof is a trial impression used to inspect both the design and the printing process. A faint area may result from uneven inking or contact, not necessarily a poor drawing. Repeatedly filled gaps may indicate an over-dense design or excessive ink. Change one variable at a time, record the result and distinguish intentional texture from a defect that prevents the image’s purpose.',
   'One side of a paper trial print appears faint.', ['Check whether the design contains printable areas there.', 'Compare ink coverage and contact across the surface.', 'Repeat with a controlled change before permanently altering the design.'], 'Diagnose the process before redesigning the image.', 'Removing a useful design area because one impression printed badly.', 'Use further proofs to distinguish repeatable design issues from process variation.', 'What is a proof in printmaking?', 'A trial impression used to inspect and refine the result.',
   'Why does changing ink amount and pressure simultaneously make evaluation harder?', 'If the next result improves, it is unclear which change caused it or whether both were necessary. Controlled trials provide more useful evidence for the next decision.',
   detail(true, 'What is a controlled comparison?', 'A comparison that changes a chosen factor while keeping relevant others similar.', 'A visible printing fault may be attributed to the design before process conditions are examined.')]
 ]]
]],
['design-tech', [
 ['Mechanisms and motion', [
  ['Explain a simple gear ratio', 'Relate tooth counts to relative rotation in two meshing gears.',
   'When two external gears mesh, they rotate in opposite directions. A driver with 12 teeth must turn three times to move all 36 teeth of a 36-tooth driven gear past the contact point, so the driven gear turns at one third of the driver’s speed. An ideal reduction can increase torque, but real mechanisms lose some energy through friction; gearing does not create extra energy.',
   'A 12-tooth driver turns at 90 revolutions per minute and drives 36 teeth.', ['Calculate the ratio 12 divided by 36.', 'Multiply 90 by one third to obtain 30 revolutions per minute.', 'State that the driven gear rotates in the opposite direction.'], 'Speed follows driver teeth divided by driven teeth.', 'Multiplying output speed by three because the output gear is larger.', 'Track how many driver revolutions are needed for one driven revolution.', 'Do two external meshing gears turn in the same direction?', 'No.',
   'Find the output speed for a 10-tooth driver at 120 rpm driving 40 teeth.', '120 × 10/40 = 30 rpm, in the opposite direction. The larger driven gear trades speed for greater ideal torque rather than multiplying energy.',
   detail(false, 'What does rpm measure?', 'Revolutions per minute: rotational speed.', 'Larger physical size may be confused with greater rotational speed.')],
  ['Challenge: choose gearing for a constrained product', 'Balance desired output speed against torque and practical losses.',
   'A mechanism’s ratio must serve its load and speed requirements. A fast motor driving a slow lifting mechanism may need reduction, but a single ratio calculation does not prove the design is safe or powerful enough. Load, motor torque, friction, strength and guarding all matter. Evaluate a low-energy model concept without attempting to build a lifting device for people or heavy loads.',
   'A classroom model motor runs at 120 rpm and needs approximately 30 rpm at its output.', ['Calculate the desired speed ratio as 30/120 = one quarter.', 'A 12-tooth driver with a 48-tooth driven gear supplies that ideal speed ratio.', 'Check torque demand, losses and safe construction before treating the ratio as a finished design.'], 'Ratio solves speed, not every design requirement.', 'Claiming a correct ratio guarantees the motor can lift any load.', 'Compare available torque and component limits with the actual required load.', 'Does gearing eliminate friction losses?', 'No.',
   'Why might the measured output be slower than the ideal calculation under load?', 'The motor may slow under load and the mechanism has losses. The ratio relates shaft speeds when the gears mesh correctly, but the loaded motor may no longer maintain the assumed input speed.',
   detail(true, 'What does torque describe?', 'The turning effect of a force.', 'An ideal calculation may be mistaken for a complete performance and safety assessment.')]
 ]],
 ['Tolerances and quality control', [
  ['Interpret a dimensional tolerance', 'Calculate an acceptable range from a nominal measurement and tolerance.',
   'A nominal dimension is a target size; its tolerance states the permitted variation. A part specified as 50 mm ± 0.5 mm may measure from 49.5 to 50.5 mm inclusive. Tolerance is not permission to ignore accuracy, and a measuring tool must resolve differences relevant to the limit. Decide whether a result meets the specification without rounding away a known failure.',
   'Check a measured length of 50.6 mm against 50 mm ± 0.5 mm.', ['Calculate the upper limit as 50.5 mm.', 'Compare 50.6 with that limit.', 'The part is outside the stated tolerance by 0.1 mm.'], 'Nominal plus or minus defines two limits.', 'Rounding a failed measurement into the acceptable interval.', 'Compare using the measured precision and consider measurement uncertainty explicitly.', 'What is the lower limit of 20 mm ± 0.2 mm?', '19.8 mm.',
   'Which values meet 20 mm ± 0.2 mm: 19.7, 20.0 and 20.2 mm?', '20.0 and 20.2 mm meet the stated inclusive limits of 19.8 to 20.2 mm; 19.7 mm does not.',
   detail(false, 'How many millimetres are in a centimetre?', 'Ten.', 'A target dimension can be mistaken for the only acceptable value, or tolerances can be treated as arbitrary rounding.')],
  ['Challenge: check worst-case clearance', 'Combine two tolerance ranges to test whether parts can always fit.',
   'A hole and a peg can each meet their own specification yet fail to provide enough clearance together. For a guaranteed loose fit, compare the smallest permitted hole with the largest permitted peg. Maximum clearance uses the largest hole and smallest peg. This worst-case approach exposes combinations that checking nominal sizes alone would miss; real fits also depend on shape, surface and material behaviour.',
   'A hole is 10.5 ± 0.1 mm and a peg is 10.0 ± 0.1 mm.', ['The smallest hole is 10.4 mm and largest peg is 10.1 mm.', 'Minimum diametral clearance is 10.4 − 10.1 = 0.3 mm.', 'Maximum clearance is 10.6 − 9.9 = 0.7 mm.'], 'Smallest hole against largest peg tests minimum clearance.', 'Subtracting only nominal dimensions and calling that guaranteed clearance.', 'Combine the relevant extremes of both ranges.', 'Which peg size produces the smallest clearance?', 'The largest permitted peg.',
   'Does this specification guarantee at least 0.4 mm diametral clearance?', 'No. Its worst-case clearance is 0.3 mm. A guaranteed 0.4 mm requirement would need a revised size or tighter tolerance, then a fresh worst-case check.',
   detail(true, 'What is clearance?', 'A deliberate gap between mating parts.', 'Independent acceptable measurements can conceal an unacceptable combined assembly.')]
 ]],
 ['Sustainable decisions and iteration', [
  ['Map a product’s life cycle', 'Identify impacts before use, during use and after disposal.',
   'A product’s environmental effects can arise from raw-material extraction, processing, manufacture, transport, use and end-of-life treatment. Focusing only on whether the material is recyclable misses energy use, durability and whether collection facilities actually exist. A life-cycle map identifies where evidence is needed; it is not a numerical environmental assessment unless reliable quantities and assumptions are supplied.',
   'Map the life cycle of a reusable bottle.', ['Include material production and manufacturing.', 'Include transport, repeated use and washing.', 'Include realistic collection, reuse or disposal at the end of service.'], 'Follow the product before, during and after use.', 'Calling a product impact-free because it is reusable.', 'Consider how many uses occur and the resources needed across the whole life cycle.', 'Does technically recyclable mean always recycled?', 'No.',
   'Why is the number of actual reuses important in a comparison with single-use alternatives?', 'Manufacturing impacts are spread across the uses achieved. A bottle discarded after very few uses may not deliver the benefit assumed by a comparison based on long service.',
   detail(false, 'What does reusable mean?', 'Designed or able to be used more than once.', 'A favourable label may substitute for examining the conditions under which a benefit occurs.')],
  ['Challenge: defend a repairability redesign', 'Evaluate trade-offs between opening a product, durability and manufacturing constraints.',
   'Repairability can be improved with accessible fasteners, replaceable components and clear information, but design choices have trade-offs. A removable joint may cost more or need a seal to resist water; a permanent adhesive joint may obstruct repair. Compare options against the brief and likely failure modes rather than assume every removable joint is automatically best. Plan safe maintenance boundaries, especially around electrical or pressurised components.',
   'Compare a glued cover with a screw-fastened cover on a low-voltage classroom enclosure.', ['Screws may allow repeated opening and component replacement.', 'They require space, tooling and attention to fastening and any sealing requirements.', 'Judge the options against expected servicing, strength and safety, not access alone.'], 'Design for likely repairs within safe limits.', 'Treating repairability as permission for users to dismantle hazardous parts.', 'Separate accessible serviceable components from work requiring qualified supervision.', 'What is a trade-off?', 'A decision where improving one requirement may compromise another.',
   'Suggest evidence for choosing between the two cover designs.', 'Use supervised tests of repeated opening, secure closure and required protection, together with manufacturing cost and repair needs. Record failures and limits rather than selecting the design solely because it looks easier to open.',
   detail(true, 'What is a design specification?', 'A set of requirements against which a proposal can be tested.', 'A desirable sustainability feature can be assessed without considering conflicting functional and safety requirements.')]
 ]]
]]
];
