import type { Subject } from '../authoredActivities';
export const year7Practical: Subject[] = [
['art', [
 ['Formal elements in observation', [
  ['Use contour and proportion together', 'Build an observed drawing from relationships rather than memorised symbols.',
   'A contour follows the visible edge or change of a form. Before committing to details, compare overall height, width and the angles between key points. Light construction marks allow correction. Observation is not defeated by revision: checking proportions often produces a stronger drawing than preserving an inaccurate first outline.',
   'Draw a bottle with a narrow neck.', ['Compare total height with maximum width.', 'Mark the neck and shoulder positions lightly.', 'Refine contours using those relationships before adding surface detail.'], 'Large relationships before small decoration.', 'Drawing a familiar bottle symbol without checking this particular object.', 'Return to the observed proportions and revise the construction.',
   'Does contour describe only shading?', 'No; it concerns the boundaries or surface-defining lines of form.', 'Why might detailing an inaccurate outline early make revision harder?', 'Time and visual commitment accumulate around the wrong structure, making proportional correction more disruptive.'],
  ['Separate local colour from observed tone', 'Explain why an object’s inherent colour does not determine all its light-dark values.',
   'Local colour is the colour associated with an object under ordinary conditions; tone concerns lightness and darkness as observed. A pale object in shadow can appear darker than a dark object in bright light. Compare areas directly and identify the light source rather than shading solely according to the object’s named colour.',
   'Compare the shadowed side of a white cup with a lit dark cloth.', ['Observe the actual light-dark relationship.', 'Do not assume white must be the lightest area everywhere.', 'Use tonal values matching the observation, distinguishing object colour from illumination.'], 'Observed light can override expected colour.', 'Leaving every part of a white object unshaded.', 'Study its shadows, reflections and changes in illumination.',
   'Can a white object contain dark observed tones?', 'Yes.', 'Why test a scene with a quick monochrome study?', 'Removing colour helps isolate tonal relationships and the distribution of light and shadow.']
 ]],
 ['Visual research and development', [
  ['Analyse an artist’s method before borrowing it', 'Translate researched features into a purposeful experiment.',
   'Studying an artist can reveal decisions about mark, material, composition or process. Identify a specific method and test what it does rather than copying a finished image without understanding. Credit the source and explain which choices are yours. Research supports experimentation; it does not automatically make every inspired work an exact stylistic match.',
   'Explore an artist’s use of repeated angular marks.', ['Describe the marks and their arrangement in a chosen work.', 'Test them on a different observed subject.', 'Evaluate which effects transfer and which need adaptation.'], 'Borrow a question or method, not an uncredited identity.', 'Claiming all work by an artist uses one feature after viewing one example.', 'Specify the researched work and avoid unsupported generalisation.',
   'Why identify the particular artwork studied?', 'An artist’s methods can vary across works and periods.', 'What should an annotation say beyond the artist’s name?', 'It should identify the observed technique, the experiment it prompted and what was learned from testing it.'],
  ['Evaluate experimentation against an intention', 'Choose between studies using visual evidence and practical constraints.',
   'An experiment can succeed technically yet fail to support the intended meaning. Compare studies using relevant criteria: texture, clarity, mood, durability or scale. Keep unsuccessful results as evidence of development. Explain a decision with observed effects rather than treating the chosen version as objectively best for every purpose.',
   'Choose a medium for an image intended to suggest fragile movement.', ['Compare a rigid thick line study with a lighter broken-line study.', 'Identify which effects support the intended fragility.', 'Select or combine methods and explain the reason.'], 'Intentions give experiments a question.', 'Selecting only the neatest study regardless of purpose.', 'Judge the relevant effect as well as technical control.',
   'Can an unexpected result be useful?', 'Yes, if it suggests a justified new direction or clarifies a limitation.', 'Why record practical problems such as smudging?', 'They affect how the work can be developed, handled or displayed, not just its initial appearance.']
 ]]
]],
['design-tech', [
 ['Design specification and measurement', [
  ['Turn user research into a specification', 'Translate an observed need into testable requirements.',
   'A design specification states what a product should achieve and the constraints it must respect. “Easy to carry” becomes more useful when linked to a user, expected load and grip needs. Separate essential safety and function from preferences. User research should inform requirements rather than merely confirm a solution already chosen.',
   'Specify a portable holder for shared classroom tools.', ['Identify the intended users and actual tool dimensions.', 'State capacity, stability and safe handling requirements.', 'Define how each requirement will be tested using appropriate loads and supervision.'], 'Need, measurable requirement, test.', 'Writing only appearance adjectives in the specification.', 'Include function, user access, safety and relevant constraints.',
   'Why measure the actual contents before designing the holder?', 'The internal dimensions and arrangement must accommodate them.', 'What makes “hold six pencils upright on a level desk” stronger than “be good”?', 'It states a specific observable function that can be tested.'],
  ['Allow clearance in a fit', 'Explain why matching nominal dimensions exactly may prevent assembly.',
   'A part intended to slide into an opening needs suitable clearance, while a fixed joint may need a different fit. Material thickness, cutting accuracy and finishing can alter actual dimensions. Measure and test a small sample before making all parts. More clearance is not always better: excessive gaps can reduce stability or function.',
   'A lid must slide into a cardboard sleeve.', ['Measure actual material and opening dimensions.', 'Allow a small suitable gap for movement and test a sample.', 'Adjust based on whether the lid slides without becoming too loose.'], 'Fit is a relationship, not one isolated size.', 'Assuming identical nominal widths guarantee a sliding fit.', 'Account for thickness, manufacturing variation and intended movement.',
   'Can too much clearance cause a problem?', 'Yes; parts can become loose or unstable.', 'Why test a joint sample before cutting an entire product?', 'It reveals fit problems with less wasted material and allows dimensions to be adjusted early.']
 ]],
 ['Materials and responsible manufacture', [
  ['Choose a material from its properties', 'Connect strength, stiffness and toughness with a product requirement.',
   'Strength concerns resisting failure under load, stiffness concerns resisting deformation and toughness concerns absorbing energy before breaking. These are related but not interchangeable. A stiff material may be brittle, and a flexible material can be tough. Choose against the product’s loading and use conditions rather than calling one material simply strongest or best.',
   'Choose properties for a reusable protective case.', ['Identify likely impacts and handling loads.', 'Consider toughness for knocks and suitable stiffness for shape retention.', 'Compare candidates with evidence and safe practical tests.'], 'Name the property that solves the problem.', 'Using hard, strong and tough as exact synonyms.', 'Explain which behaviour each term describes.',
   'What does stiffness describe?', 'Resistance to deformation under load.', 'Why might a very brittle rigid material be unsuitable for a case likely to be dropped?', 'It may keep its shape under small loads but fracture under impact, so stiffness alone does not meet the need.'],
  ['Plan a safe making sequence', 'Order operations to reduce avoidable risk and error.',
   'Manufacture needs a planned sequence: measure, mark, check, secure and use the approved process under appropriate supervision. Some operations should occur before assembly because access later is limited. Risk assessment must reflect the actual tools and materials, and pupils should not improvise unfamiliar cutting, heating or electrical procedures.',
   'Plan a model panel that needs holes before joining.', ['Mark and check hole positions while the panel is accessible.', 'Have the approved hole-making process carried out with required supervision.', 'Inspect the result before final assembly.'], 'Check while correction is still easy.', 'Assembling first and then using an unsafe improvised method to reach the holes.', 'Plan tool access and supervised operations before joining parts.',
   'Why secure a workpiece appropriately?', 'Movement can make a process inaccurate or unsafe.', 'What should happen when the available tool differs from the planned tool?', 'Stop and seek guidance; reassess the method rather than assuming the same procedure remains safe.']
 ]]
]],
['music', [
 ['Rhythm and metre', [
  ['Interpret simple time signatures', 'Connect the written metre with beat grouping in a taught example.',
   'In 4/4, the upper number indicates four crotchet beats per bar and the lower number identifies the crotchet as the reference note value. In 3/4, there are three such beats. A time signature is not itself a tempo instruction: either metre can be performed at different speeds. Keep bar grouping separate from how quickly the pulse moves.',
   'Fill one bar of 3/4 with a minim and a crotchet.', ['A minim lasts two crotchet beats.', 'A crotchet supplies one more beat.', 'The total is three beats, completing the bar.'], 'Metre groups duration; tempo sets speed.', 'Calling 3/4 automatically faster than 4/4.', 'Count beats per bar separately from beats per minute.',
   'How many crotchet beats fill a bar of 4/4?', 'Four.', 'Can two minims fill one 4/4 bar?', 'Yes. Each lasts two crotchet beats, so their combined duration is four.'],
  ['Recognise syncopation', 'Explain emphasis placed away from the expected strong beat.',
   'Syncopation shifts emphasis towards a normally weaker part of the beat or bar, often through accents or notes carried across a stronger beat. The underlying pulse still matters; without it the displacement is hard to perceive. Not every quick rhythm is syncopated, and volume alone does not identify the relationship to the metre.',
   'Accent the offbeats while keeping a steady count of one-and-two-and.', ['Maintain even numbered beats.', 'Place the accented sounds on the and positions.', 'Hear the tension between the regular pulse and the displaced emphasis.'], 'Feel the expected beat to hear its displacement.', 'Defining syncopation as simply playing fast.', 'Identify where accents or sustained notes fall relative to the pulse.',
   'Does syncopation require abandoning the steady pulse?', 'No.', 'Why practise the underlying pulse separately first?', 'It establishes the reference against which the offbeat emphasis becomes audible and controlled.']
 ]],
 ['Pitch and texture', [
  ['Construct a major-scale pattern', 'Use tones and semitones to explain a familiar scale.',
   'A major scale follows the interval pattern tone, tone, semitone, tone, tone, tone, semitone. On a keyboard, adjacent keys including black keys are a semitone apart. C major uses white keys, but moving the same interval pattern to another starting note may require black keys. The shape of the pattern matters more than copying white-key positions.',
   'Find the semitone steps in C major.', ['List C-D-E-F-G-A-B-C.', 'E to F has no intervening key.', 'B to C also forms a semitone; the other adjacent scale steps are tones.'], 'T-T-S-T-T-T-S.', 'Assuming any sequence of white keys from any starting note makes a major scale.', 'Check the interval pattern from the chosen tonic.',
   'How many semitones make one tone?', 'Two.', 'Why does G major need F sharp rather than F natural?', 'The raised seventh creates the required tone from E to F sharp and semitone from F sharp to G, preserving the major pattern.'],
  ['Distinguish melody, accompaniment and texture', 'Explain musical roles without equating them with specific instruments.',
   'A melody is a recognisable sequence of pitches and rhythm; accompaniment supports it through harmony, rhythm or other patterns. Texture describes how parts combine. One instrument can provide several roles, and a role can move between instruments. Identify what a part does rather than assuming the loudest or highest instrument is always the melody.',
   'A keyboard plays a tune in the right hand and chords in the left.', ['Identify the tune’s melodic role.', 'Identify chordal support as accompaniment.', 'Describe the combined texture rather than counting the keyboard as only one musical layer.'], 'Count musical roles, not just players.', 'Assuming one performer always means one-part texture.', 'Listen for simultaneous lines and functions.',
   'Can a melody move from one instrument to another?', 'Yes.', 'Why might reducing accompaniment improve a performance without altering the melody?', 'It can clarify balance and let the intended melodic line be heard more distinctly.']
 ]]
]],
['drama', [
 ['Character and intention', [
  ['Distinguish an objective from an emotion', 'Give a character a playable aim within a scene.',
   'An objective is what a character wants to achieve, such as persuading someone to stay. An emotion such as sadness may influence the performance but is not itself a specific action towards another person. A clear objective helps choices about pace, gesture and tactics remain purposeful. It can change when the scene’s circumstances change.',
   'A character asks a friend not to leave.', ['Define the objective as keeping the friend present.', 'Choose a tactic, such as reassurance or bargaining.', 'Test how voice and movement pursue that objective without simply acting generally sad.'], 'Want something; do something towards it.', 'Treating an emotional label as the whole character plan.', 'Identify the concrete aim and how the character tries to achieve it.',
   'Is “convince my friend to listen” an objective?', 'Yes.', 'How might two actors pursue the same objective differently?', 'They can choose contrasting tactics, such as humour or urgent appeal, while still seeking the same result.'],
  ['Use subtext to shape delivery', 'Explore a difference between spoken words and underlying intention.',
   'Subtext is meaning or intention implied beneath the literal words. “That is fine” can express genuine agreement, reluctant acceptance or an attempt to conceal anger. Performance choices need support from the situation and relationships. Subtext is not permission to contradict the scene arbitrarily; it is an interpretation tested through context and action.',
   'Perform “You are early” as welcome and as suspicion.', ['For welcome, use an open response suited to pleasure.', 'For suspicion, choose a pause or guarded attention supported by the imagined circumstances.', 'Compare how intention changes the audience’s reading of the same words.'], 'Words stay; intention changes their action.', 'Assuming every line has one universal emotional delivery.', 'Use the scene’s evidence to justify the chosen subtext.',
   'Does subtext have to be spoken aloud?', 'No.', 'What would make a suspicious reading more convincing?', 'A relevant context, such as an unexpected arrival or concealed plan, and consistent performance choices.']
 ]],
 ['Space and ensemble technique', [
  ['Use proxemics deliberately', 'Explain how distance and position can communicate relationships.',
   'Proxemics concerns the use of space and distance between performers. Standing close can suggest intimacy, pressure or threat depending on context, posture and consent. A stage picture should remain visible and safe for the audience and performers. Agree physical boundaries; no performer should be pressured into uncomfortable contact for an exercise.',
   'Show a character excluded from a group without dialogue.', ['Arrange the group with a shared focus.', 'Place the excluded character at a deliberate distance or outside the shape.', 'Check that posture and sightlines support the intended relationship.'], 'Distance means something only in context.', 'Assuming closeness always means friendship.', 'Combine position with action, focus and the scene’s circumstances.',
   'What are sightlines?', 'The audience’s lines of view to the action.', 'Why test a stage picture from the audience position?', 'A relationship clear to performers may be hidden or visually ambiguous from where viewers sit.'],
  ['Build and evaluate a freeze-frame sequence', 'Use still images and transitions to communicate a change.',
   'A freeze-frame holds a deliberate stage picture. A sequence can show before, turning point and after, using posture, focus and levels to make change legible. Transitions are part of the meaning and must be rehearsed safely. Evaluate what a viewer can infer from the images rather than explaining away unclear choices afterwards.',
   'Show trust breaking down across three images.', ['Create an opening image with shared focus and appropriate closeness.', 'Introduce a turning-point image showing a revealed conflict.', 'End with a changed spatial relationship and test whether viewers recognise the shift.'], 'A still image needs a readable relationship.', 'Relying on a spoken explanation to supply everything missing from the frame.', 'Refine visible focus, posture and composition to carry the meaning.',
   'Can a transition change how an audience interprets a freeze-frame?', 'Yes.', 'What useful feedback goes beyond “I liked it”?', 'A viewer can identify the relationship they inferred, cite a visible choice and describe where the intended change became unclear.']
 ]]
]],
['pe', [
 ['Skill and tactical transfer', [
  ['Separate a technique from a tactical decision', 'Explain how execution and choice contribute differently to performance.',
   'Technique concerns how an action is executed; tactics concern why and when an action is chosen to achieve a game aim. A accurately delivered pass can still be a poor decision if it goes to an unavailable teammate. Evaluate both dimensions and adapt movement methods for the learner rather than treating one body-specific form as the only route to tactical understanding.',
   'A technically controlled pass goes into a crowded area.', ['Recognise the controlled execution.', 'Identify the poor availability of the receiving space.', 'Set a decision-making target such as scanning before release.'], 'Good execution cannot replace a good choice.', 'Calling the whole action successful solely because the throw was accurate.', 'Assess the outcome in relation to the game situation and intended goal.',
   'Is choosing when to pass mainly a technique or tactical issue?', 'A tactical issue.', 'Can a learner demonstrate tactical understanding using adapted equipment?', 'Yes. The decision about space, timing and options can remain meaningful with an accessible movement method.'],
  ['Create an overload in a small-sided game', 'Explain how an extra available player can create options.',
   'An overload occurs when one side has more players in a relevant area, such as two attackers facing one defender. The numerical advantage only helps if positioning and timing create usable options. Crowding together can waste it. Use agreed non-contact rules and adaptations so the task develops decisions rather than unsafe speed or pressure.',
   'Two attackers approach one defender.', ['Separate into positions offering distinct passing or movement options.', 'Observe which option the defender covers.', 'Choose the remaining safe achievable route at an appropriate moment.'], 'Extra player, distinct option.', 'Standing together and assuming the extra number guarantees success.', 'Create separation and coordinate timing.',
   'Does an overload guarantee a score?', 'No.', 'Why can a defender delay rather than immediately win the ball?', 'Delaying may allow support to recover or reduce the attackers’ advantage without an unsafe challenge.']
 ]],
 ['Fitness concepts and evaluation', [
  ['Distinguish fitness components', 'Match a component such as strength or endurance to a task’s demands.',
   'Strength is the ability to exert force; muscular endurance concerns repeated or sustained muscular effort; cardiovascular endurance concerns sustained activity supported by the circulatory and respiratory systems. Tasks often require several components. These concepts describe demands, not a ranking of personal worth, and practical work must match age, health and individual access needs.',
   'Compare a brief controlled force task with a sustained movement activity.', ['The brief task may emphasise strength.', 'The sustained activity may place greater endurance demands.', 'Acknowledge overlap and the specific task conditions.'], 'Name the demand, not a label for the person.', 'Using one performance to declare someone fit or unfit in every respect.', 'Fitness is multidimensional and context-specific.',
   'Can one activity require more than one fitness component?', 'Yes.', 'Why should a teacher adapt a fitness task rather than require identical performance from everyone?', 'Learners differ in needs and starting points; safe meaningful learning does not require one uniform physical outcome.'],
  ['Evaluate measurement limitations in performance', 'Interpret a test result with attention to method and context.',
   'Performance measures depend on the task, equipment, conditions and measurement method. A timed activity can be affected by start signals, surface or reaction time. Repeated results under comparable conditions are more informative than one isolated number, but do not justify medical conclusions. Use results to guide appropriate learning with adult supervision.',
   'Two shuttle times differ slightly on different surfaces.', ['Record that the surface changed.', 'Consider grip and turning conditions as possible influences.', 'Avoid attributing the whole difference to a change in fitness.'], 'A number carries its test conditions.', 'Treating a tiny improvement as certain evidence of training effect.', 'Consider variation, method and context before drawing a conclusion.',
   'Does a stopwatch’s decimal display remove human timing error?', 'No.', 'What would improve a comparison of two attempts?', 'Consistent surface, distance, instructions and timing procedure, with suitable repetition and attention to participant wellbeing.']
 ]]
]],
['pshe', [
 ['Belonging and pressure', [
  ['Recognise manipulation within friendship', 'Distinguish a respectful request from pressure that undermines choice.',
   'A friend can ask for something while respecting a refusal. Manipulation may involve threats of exclusion, guilt or demands to prove loyalty through an uncomfortable action. The label friend does not make every request safe. Seek trusted adult support when pressure persists or involves harm; the responsibility for coercion lies with the person applying it.',
   'Someone says “If you were really my friend, you would share your password”.', ['Identify the loyalty pressure.', 'Keep the password private and decline.', 'Seek adult support if threats or repeated pressure follow.'], 'Friendship leaves room for no.', 'Treating access to private accounts as proof of trust.', 'Healthy trust respects boundaries rather than demanding their removal.',
   'Can a close friend still make an inappropriate request?', 'Yes.', 'Why is a calm refusal enough even without a lengthy explanation?', 'A person does not need to win an argument before keeping a legitimate privacy or safety boundary.'],
  ['Respond to discriminatory behaviour', 'Use safe reporting and support without escalating risk.',
   'Discriminatory comments or exclusion target people through characteristics such as race, religion, disability or sex. A bystander can help by not joining in, offering support and reporting through trusted channels. Direct confrontation is not always safe, and the affected person should not be required to educate or forgive others. Follow school safeguarding and reporting guidance.',
   'A group repeatedly mocks a classmate’s religion.', ['Do not amplify or reward the behaviour.', 'Support the affected person in a way they welcome.', 'Report the repeated concern to a trusted adult with clear details.'], 'Support safely; report clearly.', 'Dismissing repeated discriminatory comments as harmless because the speaker calls them a joke.', 'Consider the behaviour, pattern and impact rather than only the claimed intention.',
   'Must someone confront a group alone to be a helpful bystander?', 'No.', 'What details can make a report useful?', 'What was said or done, when and where it happened, who was involved and whether it has occurred before.']
 ]],
 ['Online identity and practical judgement', [
  ['Explain a digital footprint', 'Recognise that online traces can persist beyond the intended audience.',
   'A digital footprint includes information created through posts, messages, account activity and data recorded by services. Deleting a post may not remove copies or screenshots already shared. Privacy settings can reduce exposure but are not a guarantee. Before posting, consider audience, consent, personal details and possible future context without blaming people who experience misuse.',
   'A private group shares a class photo outside the group.', ['The original privacy setting did not prevent recipients from copying it.', 'Consider the consent and safety of everyone pictured.', 'Seek adult support and use reporting options rather than spreading the image further.'], 'Private audience is not impossible copying.', 'Assuming deletion from your account erases every existing copy.', 'Recognise limits and respond promptly with appropriate support.',
   'Can other people contribute to someone’s digital footprint?', 'Yes, for example by posting about or tagging them.', 'Why ask permission before sharing an identifiable photo of a friend?', 'The image affects their privacy and audience too, not only the person pressing share.'],
  ['Identify a scam’s pressure mechanism', 'Explain how urgency, reward or impersonation can bypass careful judgement.',
   'Scams often create a reason to act before checking: a threatened account closure, a prize or a familiar-looking sender. The mechanism is to narrow attention and obtain information, money or access. Pause and verify through a separately known official route with adult support. Reporting an error quickly is more protective than hiding it through embarrassment.',
   'A message claims a delivery requires an immediate small payment.', ['Do not use its link merely because the amount is small.', 'Check whether a delivery is expected and seek adult guidance.', 'Verify through an independently known official service if necessary.'], 'Small payment can open a bigger risk.', 'Assuming a tiny requested amount makes a request harmless.', 'The page may seek card details or account access as well as the immediate payment.',
   'Does a familiar logo prove the sender’s identity?', 'No.', 'Why should a person who clicked a suspicious link tell a trusted adult promptly?', 'Timely support can help protect accounts or payment details; blame and delay can worsen the situation.']
 ]]
]]
];
