import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 24 : 17, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, draw the physical model and repeat the calculation with units. In a week, solve a changed case and state whether the original assumptions still apply.' });
export const year10Physics: Subject = ['physics', [
 ['Energy stores, work and efficiency', [
  ['Connect mechanical work with energy transfer', 'Apply W = Fs for a force parallel to displacement.',
   'Work done is energy transferred by a force acting through a displacement. When the force is constant and parallel to the displacement, W = Fs. A force in newtons multiplied by displacement in metres gives joules. Holding a stationary object does not perform mechanical work on it through displacement, even though a person’s muscles still use metabolic energy. Name the system and transfer rather than treating everyday effort as the definition of work.',
   'A constant 30 N force moves a box 4 m in the force direction.', ['Identify parallel force and displacement.', 'Calculate W = 30 × 4.', 'The force transfers 120 J mechanically over that displacement.'], 'Force through displacement transfers energy.', 'Counting any tiring task as work on the object under W = Fs.', 'Check the object’s displacement and the force direction.', 'What is one newton metre equivalent to as work?', 'One joule.',
   'A 15 N resistive force acts opposite motion over 6 m. How much energy is transferred against resistance?', '90 J. The resistive force does negative work on the moving object under a signed convention, while 90 J is transferred to other energy stores, often through heating.',
   d(false, 'What is displacement?', 'A change in position with direction.', 'Everyday effort and the technical definition of mechanical work are not identical.')],
  ['Challenge: combine useful output, power and efficiency', 'Calculate an energy budget without losing dissipated transfers.',
   'Efficiency is useful output energy divided by total input energy, or useful output power divided by input power when measured consistently. A 60 percent efficient device receiving 500 J supplies 300 J usefully and transfers 200 J in other ways. Energy is not destroyed; usefulness depends on the task. Power measures the rate of transfer, so time is required when converting between joules and watts.',
   'A motor receives 800 J in 4 s and lifts a load, increasing its gravitational store by 500 J.', ['Input power is 800/4 = 200 W.', 'Useful output power is 500/4 = 125 W.', 'Efficiency is 500/800 = 0.625, or 62.5 percent; 300 J follows other transfer routes.'], 'Efficiency compares usefulness; conservation accounts for everything.', 'Calling dissipated energy destroyed.', 'Include the surroundings in the energy account.', 'What is a watt?', 'One joule per second.',
   'A device supplies 90 W usefully at 75 percent efficiency. Find its input power.', 'Input power = 90/0.75 = 120 W. The remaining 30 W is transferred through non-useful routes in the stated task.',
   d(true, 'How is power calculated from energy and time?', 'Energy transferred divided by elapsed time.', 'A missing useful output can be mistaken for a violation of energy conservation.')]
 ]],
 ['Particles, heating and state changes', [
  ['Explain latent heating without a temperature rise', 'Separate internal-energy change from a change in average particle kinetic energy.',
   'During a pure substance’s state change at constant pressure, energy can transfer without a temperature rise. It changes particle separation and interactions rather than simply increasing average kinetic energy. Specific latent heat is energy per kilogram for the specified change, with E = mL. Melting and vaporisation have different values; reaching the melting point is distinct from completing the melting of the sample.',
   'A 0.20 kg sample melts with L = 50,000 J/kg at its melting temperature.', ['Use E = mL.', 'Calculate 0.20 × 50,000 = 10,000.', 'Melting requires 10,000 J without a necessary temperature rise during the idealised change.'], 'A flat temperature can hide an energy transfer.', 'Assuming zero temperature change means zero energy transfer.', 'Check whether the material is changing state.', 'What are the units of specific latent heat?', 'J/kg.',
   'Why might only part of a sample melt after receiving some latent energy?', 'Each kilogram requires the stated energy for complete conversion. Insufficient transferred energy can change only part of the mass, leaving a mixture of phases at the transition temperature.',
   d(false, 'What does temperature relate to in a simple particle model?', 'Average particle kinetic energy.', 'Temperature is sometimes treated as a direct measure of all internal energy.')],
  ['Challenge: add sensible and latent energy stages', 'Partition a heating calculation according to the physical process in each interval.',
   'Heating a solid to its melting point and then melting it requires two distinct terms: mcΔT for the temperature rise and mL for the state change. Applying mcΔT to the whole process misses latent energy. Real apparatus also heats and loses energy to surroundings, so electrical input may exceed the ideal sample requirement. Draw the stages first and attach the correct relationship to each.',
   'A 0.10 kg sample warms by 20 °C with c = 500 J/(kg °C), then melts with L = 40,000 J/kg.', ['Warming needs 0.10 × 500 × 20 = 1,000 J.', 'Melting needs 0.10 × 40,000 = 4,000 J.', 'The ideal total is 5,000 J, excluding apparatus and environmental transfers.'], 'Split the process before selecting equations.', 'Using only the final-minus-initial temperature and ignoring a phase change.', 'Account separately for each physical stage.', 'Which term accounts for melting?', 'mL.',
   'If a 100 W heater transferred all its output to this sample, find the ideal heating time.', 't = E/P = 5,000/100 = 50 s. Real time may be longer because the assumption of complete transfer to the sample is idealised.',
   d(true, 'What does specific heat capacity describe?', 'Energy required per kilogram per degree of temperature rise.', 'A multi-stage process may be forced into a single familiar formula.')]
 ]],
 ['Elastic forces and turning effects', [
  ['Interpret Hooke’s law within its range', 'Use extension rather than total length and convert units consistently.',
   'For a spring within its proportional range, F = ke, where e is extension from the unloaded length and k is stiffness in N/m. A spring growing from 10 cm to 14 cm extends by 4 cm, not 14 cm. Beyond the limit of proportionality the straight-line relationship no longer applies; this need not be identical to the point where permanent deformation begins.',
   'A spring with k = 200 N/m extends by 3 cm.', ['Convert 3 cm to 0.03 m.', 'Calculate F = 200 × 0.03.', 'The force is 6 N within the stated proportional range.'], 'Subtract original length, then convert extension.', 'Putting total spring length into F = ke.', 'Define extension relative to the unloaded spring.', 'What is the unit of spring stiffness?', 'N/m.',
   'An unloaded spring is 8 cm long and becomes 11 cm under 9 N. Find k.', 'Extension is 0.03 m, so k = F/e = 9/0.03 = 300 N/m, assuming proportional behaviour at this load.',
   d(false, 'How many metres is one centimetre?', '0.01 m.', 'The most visible measurement may be total length even though the model uses a change in length.')],
  ['Challenge: satisfy force and moment balance together', 'Find support forces using a specified pivot and total-force equilibrium.',
   'A stationary beam requires both zero resultant force and zero resultant moment. Taking moments about one support can eliminate that support’s unknown turning effect because its perpendicular distance is zero. The remaining force then follows from total vertical balance. Support reactions are not automatically equal: the position of loads matters even when the beam has equal end supports.',
   'A light 4 m beam has end supports and a 120 N load 1 m from the left end.', ['Take moments about the left end: right reaction × 4 = 120 × 1.', 'The right reaction is 30 N.', 'Vertical balance gives left reaction = 120 − 30 = 90 N.'], 'Choose a pivot, then check total force.', 'Dividing the load equally without considering its position.', 'Use turning balance as well as vertical balance.', 'What is the moment arm of a force acting through the pivot?', 'Zero.',
   'Move the same load to the centre. What are the reactions for the light beam?', 'Each is 60 N: taking moments gives right reaction × 4 = 120 × 2, and force balance gives the same left reaction. Symmetry now justifies equality.',
   d(true, 'How is the moment of a perpendicular force calculated?', 'Force multiplied by perpendicular distance from the pivot.', 'Zero net force may be treated as sufficient even when a remaining turning effect would rotate the object.')]
 ]],
 ['Momentum and stopping', [
  ['Use momentum conservation for a defined system', 'Apply p = mv and retain direction in a collision model.',
   'Momentum is mass multiplied by velocity and has direction. Total momentum is conserved in a system with no significant resultant external impulse over the interval. Two objects sticking together can share a final velocity even though kinetic energy decreases. Conservation of momentum does not mean each object keeps its own momentum or that kinetic energy is always conserved.',
   'A 2 kg trolley moving at 3 m/s sticks to a stationary 1 kg trolley.', ['Initial momentum is 2 × 3 + 1 × 0 = 6 kg m/s.', 'Combined mass is 3 kg.', 'Final velocity is 6/3 = 2 m/s in the original direction under the isolated-system model.'], 'Conserve the system total, not each object separately.', 'Assuming sticking collisions conserve kinetic energy automatically.', 'Check momentum and energy with their different formulas.', 'What is the momentum of a stationary object?', 'Zero in the stated reference frame.',
   'Compare kinetic energies before and after the worked collision.', 'Initially E = ½ × 2 × 3² = 9 J. Finally E = ½ × 3 × 2² = 6 J. The 3 J difference transfers to other stores; momentum remains conserved in the model.',
   d(false, 'How is kinetic energy calculated for ordinary non-relativistic motion?', 'One half × mass × speed squared.', 'Different conservation statements can be assumed to apply to the same named quantity in every collision.')],
  ['Challenge: separate thinking distance from braking-distance scaling', 'Combine reaction time and a constant-force stopping model.',
   'Thinking distance equals speed multiplied by reaction time in a constant-speed reaction interval. Braking distance can be related to kinetic energy and work by the braking force. With the same mass and constant braking-force magnitude, doubling speed quadruples braking distance because kinetic energy depends on speed squared. The total stopping distance combines two parts that therefore need not scale equally.',
   'At one speed, thinking distance is 6 m and braking distance 10 m. Double speed with unchanged reaction time and braking force.', ['Thinking distance doubles to 12 m.', 'Braking distance quadruples to 40 m.', 'Total stopping distance becomes 52 m, not simply twice the original 16 m.'], 'Reaction scales with speed; ideal braking scales with speed squared.', 'Doubling every stopping-distance component when speed doubles.', 'State and apply the model for each part separately.', 'What can increase thinking distance at the same speed?', 'A longer reaction time.',
   'Why is the quadrupling rule not a guarantee on an actual wet road?', 'Available braking force, tyre grip, braking control and other conditions can change. The scaling assumes a constant comparable force; different conditions require a revised model.',
   d(true, 'What does work against braking transfer?', 'Energy from the vehicle’s kinetic store to other stores.', 'A useful ideal relationship can be applied without its force and condition assumptions.')]
 ]],
 ['Electrical energy and circuit relationships', [
  ['Link charge, potential difference and transferred energy', 'Use Q = It and E = QV with explicit units.',
   'Current is charge flow per second, so Q = It. Potential difference is energy transferred per unit charge, so E = QV. Charge circulates through a circuit; it is not consumed by a resistor. Energy is transferred as charge moves through a potential difference. Combining the relationships gives E = VIt for constant voltage and current over the interval.',
   'A component carries 0.5 A for 20 s across 6 V.', ['Charge transferred is Q = 0.5 × 20 = 10 C.', 'Energy transferred is E = 10 × 6 = 60 J.', 'The charge is not used up; the component transfers energy to other stores.'], 'Amps count charge per second; volts count joules per coulomb.', 'Describing a component as consuming current.', 'Distinguish charge conservation from energy transfer.', 'What is the unit of electric charge?', 'Coulombs.',
   'How much charge passes in 2 minutes at 0.20 A?', 'Convert time to 120 s, then Q = 0.20 × 120 = 24 C. Keeping minutes in the formula would give an incorrect unit conversion.',
   d(false, 'What is one ampere equivalent to?', 'One coulomb per second.', 'Energy-use language can be incorrectly applied to the charge that carries energy through a circuit.')],
  ['Challenge: compare series and parallel power under a fixed supply', 'Use circuit structure before applying P = VI or V²/R.',
   'Two identical resistors in series share a fixed supply voltage; in parallel each has the full supply voltage. Their equivalent resistances and total power therefore differ. For an ideal resistor P = V²/R, but V must be the voltage across that resistor or the corresponding whole network. Real components may change resistance with temperature, so the fixed-resistance model must be stated.',
   'Two 6-ohm resistors are connected to an ideal 12 V supply.', ['In series, equivalent resistance is 12 ohms, so total power is 12²/12 = 12 W.', 'In parallel, equivalent resistance is 3 ohms, so total power is 12²/3 = 48 W.', 'The comparison assumes fixed resistance and a supply able to maintain 12 V.'], 'The topology determines which voltage each resistor receives.', 'Using the full supply voltage across every series component.', 'Label voltage drops and branch voltages before calculating power.', 'What voltage is across each resistor in the parallel case?', '12 V.',
   'Find each resistor’s power in the series case.', 'The equal resistors each have 6 V, so P = 6²/6 = 6 W each, totaling 12 W. Their powers add consistently with the network calculation.',
   d(true, 'What happens to resistance when two identical resistors are connected in series?', 'Their resistances add.', 'A valid component formula can be supplied with the voltage of a different part of the circuit.')]
 ]],
 ['Electromagnetic waves and practical observations', [
  ['Connect frequency with photon energy across the spectrum', 'Distinguish wave speed in vacuum from differences in wavelength and interaction.',
   'Radio, microwave, infrared, visible, ultraviolet, X-ray and gamma radiation are electromagnetic waves. They have the same speed in vacuum but different frequencies and wavelengths. Higher-frequency photons carry more energy; sufficiently energetic radiation can ionise atoms. Risk depends on radiation type, dose, exposure and tissue, not merely whether a wave is invisible. Common visible-light models and protective measures should not be generalised to every part of the spectrum.',
   'Compare radio waves and X-rays in vacuum.', ['They share the same vacuum wave speed.', 'X-rays have much higher frequency and shorter wavelength.', 'Their higher photon energies lead to different interactions, including ionisation in suitable circumstances.'], 'Same vacuum speed does not mean the same interaction.', 'Assuming high frequency means a higher vacuum propagation speed.', 'Use v = fλ with fixed vacuum speed.', 'Which has longer wavelength: infrared or ultraviolet?', 'Infrared.',
   'Why is a statement that all radiation is equally dangerous misleading?', 'Interaction mechanisms and doses differ enormously. A meaningful risk assessment needs the type, intensity or dose, duration and circumstances rather than the word radiation alone.',
   d(false, 'What relationship links wave speed, frequency and wavelength?', 'v = fλ.', 'A broad category name may obscure the physical differences relevant to uses and hazards.')],
  ['Challenge: infer a wavelength from repeated wavefront measurements', 'Reduce percentage uncertainty while preserving a valid measurement model.',
   'Measuring across several wavelength intervals and dividing can reduce the influence of a fixed ruler uncertainty. Count intervals, not crests: six consecutive crests span five wavelengths. The method assumes the pattern is sufficiently regular and the image scale is known. Repeating measurements helps quantify variation but does not correct a consistently wrong scale or a systematic counting error.',
   'Six consecutive crests span 15 cm on a correctly scaled record.', ['Six crests define five intervals.', 'Wavelength is 15/5 = 3 cm.', 'If the total-span uncertainty is ±0.2 cm, the corresponding wavelength uncertainty is ±0.04 cm under this simplified model.'], 'Count gaps between markers, not the markers themselves.', 'Dividing a six-crest span by six.', 'Mark the first and last crest and count intervening intervals.', 'How many wavelength intervals lie between four consecutive crests?', 'Three.',
   'Why does measuring many intervals not fix an image printed at the wrong scale?', 'The scale error affects every interval proportionally. Dividing by the number of intervals reduces neither that systematic factor nor its bias.',
   d(true, 'What is measurement uncertainty?', 'A quantified or stated range of doubt associated with a measurement.', 'Averaging is sometimes assumed to remove every kind of error.')]
 ]],
 ['Magnetic fields and electromagnetic effects', [
  ['Explain the motor effect on a current-carrying conductor', 'Relate field, current and force while stating the orientation dependence.',
   'A current-carrying conductor in a magnetic field can experience a force. The force is greatest when current is perpendicular to the field and zero in the ideal parallel case. Reversing either current or field reverses force; reversing both preserves its direction. Fleming’s left-hand rule is a convention for relating field, conventional current and force, not a cause of the interaction. Motors use controlled forces to create turning effects.',
   'Predict what happens when only the current reverses in a fixed perpendicular field.', ['Keep the magnetic-field direction unchanged.', 'Reverse the conventional current direction.', 'The force reverses while the geometric perpendicular relationship remains.'], 'Reverse one direction, reverse force; reverse both, preserve it.', 'Claiming any wire near a magnet moves regardless of current or orientation.', 'Specify field, current and their angle.', 'What current direction does the standard left-hand rule use?', 'Conventional current.',
   'Why can two sides of a motor coil experience forces producing the same rotational sense?', 'The current travels in opposite directions along opposite sides, so their forces are opposite. Acting on opposite sides of the pivot, those forces can form a turning couple rather than simply canceling the rotation.',
   d(false, 'What does a magnetic field describe?', 'The region and direction of magnetic interaction represented by field vectors or lines.', 'Equal opposite forces may be assumed to prevent rotation without considering their points of action.')],
  ['Challenge: distinguish induction from the motor effect', 'Explain an induced potential difference through changing magnetic linkage.',
   'Electromagnetic induction produces a potential difference when magnetic linkage with a conductor or coil changes. A complete circuit permits induced current; an open circuit may have potential difference without sustained current. Faster change, more turns or a stronger changing field can increase the induced effect under suitable conditions. The induced response opposes the change causing it, consistent with energy conservation rather than free energy creation.',
   'A magnet is moved towards a coil connected to a sensitive meter.', ['Changing magnetic linkage induces a potential difference.', 'A closed measuring circuit allows a transient current.', 'Holding the magnet stationary then removes the continuing change in this simple arrangement, so the induced response ceases.'], 'Change creates induction; a circuit allows current.', 'Claiming a stationary magnet near a stationary coil continuously generates energy.', 'Identify what is changing and what supplies the mechanical energy.', 'Can an induced potential difference exist across an open coil?', 'Yes.',
   'Why does a loaded generator require mechanical input rather than produce energy from magnetism alone?', 'The induced electrical transfer is associated with an opposing mechanical effect. External work maintains the change and supplies the output energy plus losses.',
   d(true, 'What is potential difference?', 'Energy transferred per unit charge between two points.', 'A magnetic field’s presence can be confused with the ongoing energy input needed to generate electrical output.')]
 ]],
 ['Radioactive change and half-life', [
  ['Distinguish irradiation from contamination', 'Explain exposure to radiation separately from radioactive material on or in an object.',
   'Irradiation means exposure to radiation from a source; contamination means radioactive material is present where it is unwanted. Removing an external source can end irradiation, while contamination can continue causing exposure until the material is removed or decays. Irradiation does not ordinarily make an object radioactive in the introductory situations considered here. Risk assessment depends on radiation type, activity, exposure route and time, not one label alone.',
   'Compare standing near a sealed source with radioactive dust on clothing.', ['The sealed source can irradiate a person without transferring material.', 'Dust on clothing is contamination and may continue to irradiate nearby tissue.', 'The appropriate controls differ because the location and persistence of the source differ.'], 'Exposure is not the same as transferred material.', 'Assuming every irradiated object becomes a radioactive source.', 'Ask whether radioactive material was actually transferred.', 'Can contamination also cause irradiation?', 'Yes.',
   'Why can an alpha-emitting contaminant inside the body pose a different risk from an external sealed alpha source?', 'Alpha radiation has a short range but strong ionising effects along that range. An internal source can expose sensitive tissue directly, whereas external penetration is limited; actual risk still depends on dose and circumstances.',
   d(false, 'What does ionising radiation do?', 'It can remove electrons from atoms or molecules.', 'Exposure and source transfer are often described with the same informal word radiation.')],
  ['Challenge: correct background counts before estimating half-life', 'Use net count rates and repeated halving without treating decay as deterministic for each nucleus.',
   'Half-life is the time for the number of undecayed nuclei, or activity of a suitable sample, to fall to half its value. Individual decay is random; the large-sample trend is predictable statistically. A measured detector count includes background, which should be estimated and subtracted before comparing sample rates. Detector geometry and efficiency must remain comparable for count rate to track the source’s activity.',
   'Total count rate falls from 420 to 120 counts/min in 12 min; background is 20 counts/min.', ['Subtract background to obtain net rates 400 and 100.', 'The sample rate has halved twice: 400 to 200 to 100.', 'Two half-lives take 12 min, so the estimated half-life is 6 min.'], 'Subtract background before counting halvings.', 'Using 420 and 120 directly as if all counts came from the sample.', 'Separate sample signal from persistent background.', 'Does each nucleus decay exactly after one half-life?', 'No.',
   'With the same half-life and a net initial rate of 800 counts/min, predict the net rate after 18 min.', 'Eighteen minutes is three half-lives, so 800 → 400 → 200 → 100 counts/min. This is an expected trend, with observed counts subject to random variation.',
   d(true, 'What is background radiation?', 'Radiation detected from environmental and other sources apart from the sample under study.', 'A detector’s total measurement can be mistaken for a pure measurement of the chosen source.')]
 ]]
]];
