import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 24 : 17, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, reconstruct the chronology and explain one causal link. In a week, compare a later period and support a judgement about change, continuity or significance with precise evidence.' });
export const year10History: Subject = ['history', [
 ['Medieval medicine: explanations and practice', [
  ['Explain the influence of humoral medicine', 'Connect an explanation of illness with the treatments it made plausible.',
   'In medieval European learned medicine, the four-humour model associated health with balance between blood, phlegm, yellow bile and black bile. Treatments such as changing diet or bloodletting could seem logical within that model. Religious explanations and practical remedies also coexisted; people did not use one uniform theory for every illness. Explaining why a treatment appeared reasonable historically does not endorse it as medically effective today.',
   'Explain the connection between an imbalance diagnosis and bloodletting.', ['The theory identified an excess or imbalance of humours as a possible cause.', 'Removing blood was intended to restore balance under that framework.', 'The reasoning followed the accepted model even though modern evidence rejects the model’s physiology.'], 'Historical plausibility is different from modern effectiveness.', 'Calling every past treatment random because its theory is now rejected.', 'Reconstruct the explanation before evaluating its evidence or outcomes.', 'Which humour was associated with bloodletting most directly?', 'Blood.',
   'Why should a historian distinguish learned medical texts from every household’s practice?', 'Texts reveal influential formal ideas, but access, local remedies, cost and experience shaped what people actually did. One written tradition cannot establish complete uniformity across society.',
   d(false, 'What is a historical context?', 'The circumstances and ideas within which people acted.', 'Hindsight can replace explanation with a judgement that past people simply lacked intelligence.')],
  ['Challenge: evaluate continuity without denying local variation', 'Use authority, institutions and evidence to explain persistence of a theory.',
   'Humoral ideas persisted partly because respected ancient authorities such as Galen shaped education and interpretation, while institutions reproduced established teaching. Persistence does not mean nobody observed patients or questioned details. A theory can absorb contrary experiences through flexible interpretation. Explain the mechanisms sustaining authority rather than claim that religion or tradition alone prevented all change everywhere.',
   'Assess “Humoral medicine survived only because nobody observed patients”.', ['Identify that observation existed alongside inherited theory.', 'Explain how observations could be interpreted through an established framework.', 'Consider education, authority and available alternatives as interacting reasons for continuity.'], 'Continuity needs mechanisms, not a single blame label.', 'Treating long survival of a theory as proof that no observation occurred.', 'Distinguish collecting evidence from interpreting it through a model.', 'Can a theory influence what observers regard as important?', 'Yes.',
   'What would strengthen an explanation of institutional continuity?', 'Evidence about training texts, teaching practices and professional authority would connect the theory to how practitioners learned and worked. Merely naming Galen does not explain the transmission process.',
   d(true, 'What does continuity mean in historical study?', 'Features that persist across time despite other changes.', 'A persistent outcome can be attributed to one untested cause rather than traced through institutions and practice.')]
 ]],
 ['Renaissance anatomy and circulation', [
  ['Connect anatomical investigation with challenges to authority', 'Explain Vesalius’s significance without claiming immediate transformation of all treatment.',
   'Vesalius’s 1543 anatomical work used detailed human investigation and illustrations to challenge some inherited descriptions associated with Galen. Printing helped images and arguments circulate. More accurate anatomy did not immediately establish germ theory or make every treatment effective. Significance can lie in methods and corrected knowledge as well as immediate clinical results; these effects should not be collapsed into one sudden revolution.',
   'Explain why improved diagrams could matter beyond their artistic quality.', ['They communicated detailed anatomical observations.', 'Readers could compare claims and structures more systematically.', 'Dissemination supported scrutiny of inherited descriptions, although access and acceptance varied.'], 'New observation plus communication can challenge authority.', 'Claiming anatomical correction instantly cured infectious disease.', 'Match the advance to the type of knowledge and practice it affected.', 'In which century was the 1543 work published?', 'The sixteenth century.',
   'Why mention printing when evaluating significance?', 'Printing enabled wider reproduction and comparison of text and images than isolated observation alone. It helps explain transmission, not simply the discovery itself.',
   d(false, 'What is anatomy?', 'The study of bodily structures.', 'Different kinds of medical knowledge can be grouped under one undifferentiated idea of progress.')],
  ['Challenge: explain Harvey’s evidential case for circulation', 'Distinguish a demonstrated mechanism from unresolved parts of the explanation.',
   'In 1628 William Harvey published an account of blood circulation and the heart’s pumping role, drawing on observations, experiments and quantitative reasoning. The volume moved made continual fresh production and consumption of blood implausible. He did not directly observe the capillary connections later seen with microscopy. A powerful explanation can establish a general mechanism while leaving a detail for later investigation.',
   'Explain the role of a quantity argument in challenging an older blood model.', ['Estimate that the heart moves a substantial volume repeatedly.', 'Compare that with the body’s limited amount of blood.', 'Infer reuse through circulation rather than continual replacement at the required rate.'], 'A mechanism can be constrained by quantities as well as images.', 'Assuming an unobserved connection made every part of the circulation argument unsupported.', 'Separate established evidence from remaining explanatory gaps.', 'What major function did Harvey assign to the heart?', 'Pumping blood around a circulation.',
   'Why did Harvey’s work not immediately solve the causes of infection?', 'It concerned circulation, not microorganisms and transmission. Its significance in physiology and method should not be inflated into an immediate solution to unrelated medical problems.',
   d(true, 'What is a quantitative argument?', 'Reasoning using measurements or numerical relationships.', 'Later knowledge can be projected backwards, making a discovery appear more complete than it was.')]
 ]],
 ['Germ theory and medical explanations', [
  ['Distinguish Pasteur’s general challenge from pathogen identification', 'Explain complementary contributions rather than a single-hero story.',
   'Pasteur’s nineteenth-century investigations challenged spontaneous generation and supported the role of microorganisms in processes such as decay. Koch’s work helped establish links between particular microorganisms and particular diseases, including identifying the tuberculosis bacterium in 1882. A general germ explanation and identifying a specific pathogen are related but distinct developments. Laboratory methods, equipment and communication contributed alongside individual researchers.',
   'Compare the questions addressed by germ theory and identification of a specific bacterium.', ['The general theory challenges explanations excluding microorganisms.', 'Specific identification links a particular organism with a particular disease.', 'Together they support more targeted investigation, but neither is identical to discovering an immediate cure.'], 'General cause framework, specific causal agent, then further application.', 'Attributing every nineteenth-century infection advance to one person and one experiment.', 'Specify which claim each contribution supported.', 'Which disease is linked here with Koch’s 1882 identification?', 'Tuberculosis.',
   'Why would a pathogen discovery not automatically produce an effective treatment?', 'Understanding a cause is one step; finding a safe way to prevent or treat the infection requires additional research, testing and implementation.',
   d(false, 'What is a microorganism?', 'An organism too small to see clearly without suitable magnification.', 'A discovered cause can be mistaken for an already available cure.')],
  ['Challenge: evaluate why acceptance and practice changed unevenly', 'Link theory to resources, professional habits and implementation.',
   'A new explanation can spread unevenly because practitioners differ in training, resources, experience and willingness to change. A technique requiring equipment, time or unfamiliar procedures may not be adopted immediately even when its rationale is persuasive. Explain resistance through evidence rather than dismiss all critics as irrational. Some objections may reveal real practical problems, while others protect established authority.',
   'Assess “Once germ theory appeared, old practices disappeared at once”.', ['Separate publication from professional acceptance.', 'Separate acceptance from the ability to implement new methods.', 'Consider institutions, training and resources as reasons for uneven change.'], 'Discovery, acceptance and implementation run on different clocks.', 'Using one publication date as the end date of every older practice.', 'Look for evidence of actual uptake across settings.', 'Can someone accept a theory but lack equipment to apply it fully?', 'Yes.',
   'What evidence would test a claim of rapid adoption?', 'Hospital procedures, training materials, practitioner accounts and outcome records across several locations would help. One enthusiastic report cannot establish universal change.',
   d(true, 'What is implementation?', 'Putting a policy, theory or method into practical operation.', 'A memorable discovery date can overshadow the slower social process of changing practice.')]
 ]],
 ['Surgery: pain, infection and linked advances', [
  ['Explain why anaesthesia solved only one surgical barrier', 'Distinguish relief of pain from control of infection and blood loss.',
   'Anaesthesia made longer and more complex operations possible by reducing pain and awareness. It did not itself prevent infection or major blood loss, so expanded surgery could expose patients to other dangers. The public demonstration of ether in 1846 and Simpson’s use of chloroform in 1847 belong to a wider development, not the instant arrival of modern safe surgery. Evaluate separate barriers and their interaction.',
   'Why could longer operations remain dangerous after anaesthesia?', ['Pain control allowed more time and extensive procedures.', 'Infection risks and bleeding were not automatically removed.', 'Improvement in one constraint could therefore increase exposure to others.'], 'Removing one barrier can reveal another.', 'Claiming anaesthesia made all operations safe immediately.', 'Separate pain, infection, blood loss and practical monitoring.', 'Did anaesthesia itself establish sterile operating conditions?', 'No.',
   'How does this example complicate a simple progress narrative?', 'A genuine advance created new possibilities but also made unresolved risks more consequential. Historical change can involve benefits and new problems rather than uninterrupted improvement.',
   d(false, 'What is anaesthesia intended to address?', 'Pain and awareness during medical procedures under qualified care.', 'A dramatic innovation can be credited with solving every difficulty in the same activity.')],
  ['Challenge: connect antisepsis with a changing causal explanation', 'Explain Lister’s significance and distinguish killing germs from preventing their entry.',
   'Lister applied ideas about microorganisms to surgical infection and developed antiseptic methods using carbolic acid in the 1860s. Antisepsis aims to kill microorganisms; later aseptic approaches increasingly aimed to prevent contamination through controlled clean conditions and sterilised equipment. These categories overlap in practice but represent a useful distinction in emphasis. Adoption depended on evidence, technique and hospital organisation, not terminology alone.',
   'Compare applying an antiseptic with sterilising instruments before use.', ['The antiseptic targets microorganisms where it is applied.', 'Sterilising instruments reduces a potential route of introduction.', 'Both relate to microbial causation while intervening at different points in the infection pathway.'], 'Kill contamination or prevent its introduction: identify the intervention point.', 'Using antiseptic and aseptic as identical historical labels in every context.', 'Explain the method’s mechanism rather than rely only on the word.', 'What chemical is associated with Lister’s early antiseptic work?', 'Carbolic acid.',
   'Why is linking Lister to germ theory stronger than merely listing both developments?', 'The link explains how a causal theory suggested an intervention against surgical infection. It turns chronology into an account of influence and application.',
   d(true, 'What is a causal explanation?', 'An account of how one factor contributes to an outcome.', 'A sequence of names and dates can be mistaken for an explanation of relationships between developments.')]
 ]],
 ['Public health and state intervention', [
  ['Explain the importance and limits of Snow’s cholera investigation', 'Connect spatial evidence with waterborne transmission rather than claim a complete germ theory.',
   'John Snow investigated cholera and linked cases to water supplies, including the Broad Street outbreak in 1854. Mapping and comparison helped challenge explanations focused on bad air. This supported a route of transmission without directly identifying the cholera organism in that investigation. Public-health action can follow strong evidence about a pathway even before every microscopic mechanism is established.',
   'Explain what a concentration of cases around a water source can suggest.', ['It identifies a pattern requiring investigation.', 'Comparisons of water use and affected groups can strengthen a waterborne explanation.', 'The map alone is not sufficient proof without checking population distribution and other evidence.'], 'A spatial pattern is a starting clue, strengthened by comparison.', 'Treating one map as a complete demonstration of every cholera mechanism.', 'Separate association, transmission evidence and microorganism identification.', 'Which year is associated with the Broad Street investigation?', '1854.',
   'Why investigate people near the source who did not become ill?', 'Their water use or other circumstances can test the proposed pathway and alternative explanations. Exceptions can be informative rather than simply discarded.',
   d(false, 'What is a historical source’s utility?', 'Its usefulness for answering a particular historical question.', 'A famous image can overshadow the wider investigation that made its pattern persuasive.')],
  ['Challenge: explain why public-health reform required more than discovery', 'Link infrastructure, finance and political responsibility to practical change.',
   'Clean water and sewage systems require collective decisions, investment, engineering and maintenance. Scientific understanding can strengthen the case for reform, but it does not itself build infrastructure or settle who pays. In nineteenth-century Britain, public-health legislation developed alongside urban pressures, political debate and changing expectations of government. Distinguish a law’s powers and duties from the speed and quality of implementation in different places.',
   'Evaluate “Medical science alone explains improved urban sanitation”.', ['Science helped explain disease risks and possible interventions.', 'Infrastructure also required finance, engineering and administrative authority.', 'A multi-causal account connects knowledge with the institutions able to act on it.'], 'Knowing what helps is not the same as delivering it.', 'Treating legislation as proof that every locality changed immediately.', 'Check implementation and local conditions as well as national policy.', 'Can a public-health improvement occur before a fully correct disease theory?', 'Yes.',
   'Why is that final possibility important when studying change?', 'Effective measures can arise from empirical evidence or partly mistaken explanations. Judging their actual effects requires separating the rationale used from the consequences achieved.',
   d(true, 'What is infrastructure?', 'The physical and organisational systems supporting services such as water and sanitation.', 'Scientific explanation can be treated as sufficient without accounting for the resources and authority needed for action.')]
 ]],
 ['Twentieth-century treatment and access', [
  ['Trace penicillin from observation to usable medicine', 'Distinguish discovery, development and production at scale.',
   'Fleming’s 1928 observation of antibacterial effects was important, but turning penicillin into a usable medicine required later work, including Florey and Chain’s team, testing, purification and large-scale production. Wartime demand and industrial cooperation helped accelerate supply. A single discovery does not automatically provide an affordable, stable treatment to patients; development and distribution are separate historical problems.',
   'Explain why naming Fleming alone leaves the treatment story incomplete.', ['The observation identified antibacterial potential.', 'Further research made a usable treatment and assessed it.', 'Industrial production and distribution were needed for wider practical access.'], 'Observe, develop, test, manufacture, distribute.', 'Equating discovery with immediate widespread availability.', 'Identify the stages and contributors between laboratory observation and patient treatment.', 'In which year did Fleming make the famous observation?', '1928.',
   'Why could war both accelerate medical development and cause enormous health harm?', 'Urgent demand and resources could support selected innovations while conflict simultaneously caused injury, deprivation and death. A balanced significance judgement must not turn a particular advance into an overall celebration of war.',
   d(false, 'What is mass production?', 'Manufacturing at a scale allowing many units to be supplied consistently.', 'A memorable individual discovery can hide collective development and resource-intensive implementation.')],
  ['Challenge: evaluate the NHS as a change in access rather than a single cure', 'Separate medical technology from organisation and funding of care.',
   'The NHS began in 1948 and changed the organisation and availability of healthcare in Britain, with services intended to meet need rather than depend directly on payment at the point of use. It did not itself discover every medicine or eliminate all unequal outcomes. Evaluate access, funding, workforce and subsequent changes separately from scientific advances, recognising that policy aims and lived experience are not automatically identical.',
   'Compare the significance of an antibiotic and a national health service.', ['The antibiotic changes treatment possibilities for susceptible infections.', 'The service changes how care is organised, financed and accessed.', 'Their benefits can interact, but they operate through different mechanisms.'], 'A treatment changes what can be done; a system changes who can receive it.', 'Measuring health-service significance only by the number of new cures it invented.', 'Use criteria suited to organisation, access and outcomes.', 'When did the NHS begin?', '1948.',
   'What evidence would help evaluate whether access improved equally for all groups?', 'Regional service availability, waiting and utilisation data, staffing and patient accounts could reveal uneven experiences. A national principle alone cannot establish equal practical access in every place or period.',
   d(true, 'What does access to healthcare involve?', 'The practical ability to obtain appropriate services, shaped by cost, location, availability and other barriers.', 'A universal policy principle can be mistaken for immediate uniform experience.')]
 ]]
]];
