import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 24 : 17, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, explain the mechanism and measurement chain without notes. In a week, redesign one control and predict how an identified error would affect the conclusion.' });
export const year10Combined: Subject = ['science-combined', [
 ['Enzyme mechanisms and rate evidence', [
  ['Explain enzyme activity through binding and shape', 'Distinguish reversible rate changes from denaturation.',
   'An enzyme’s active site interacts with particular substrates and supports a reaction without being consumed overall. Temperature changes particle motion and collision frequency, but sufficiently high temperatures can disrupt the enzyme’s structure and active-site shape. Lower activity at low temperature does not necessarily mean denaturation. An optimum is specific to the enzyme and conditions rather than a universal temperature for all biological catalysts.',
   'Explain why a cooled enzyme sample may regain activity when returned to a suitable temperature.', ['Cooling can reduce molecular motion and reaction rate.', 'The enzyme’s functional structure may remain intact.', 'Restoring suitable temperature can therefore restore activity, unlike some irreversible structural damage.'], 'Slow is not automatically denatured.', 'Calling every reduction in enzyme rate destruction of the active site.', 'Distinguish kinetic conditions from structural change.', 'Is an enzyme used up as a reactant overall?', 'No.',
   'Why can pH alter enzyme activity?', 'Changes in pH can affect charges and interactions maintaining protein shape and substrate binding. The effect depends on the enzyme; one optimum cannot be assumed for all enzymes.',
   d(false, 'What is a catalyst?', 'A substance that changes reaction rate and is regenerated overall.', 'An observed loss of activity can be assigned one cause despite several possible mechanisms.')],
  ['Challenge: use completion time as an inverse-rate proxy', 'State the conditions under which 1/time supports comparison.',
   'If each enzyme trial reaches the same defined extent of reaction from comparable starting amounts, a shorter completion time suggests a higher average rate. The reciprocal 1/t can serve as a relative rate indicator, but it is not directly a concentration-per-second measurement without further information. Endpoint judgement, mixing and timing intervals affect uncertainty. Use teacher-provided observations or supervised procedures rather than assume a colour test supplies continuous exact data.',
   'Comparable trials reach the same endpoint in 40 s and 20 s.', ['Compute reciprocal times 0.025 s⁻¹ and 0.050 s⁻¹.', 'The second reciprocal rate indicator is twice the first.', 'That comparison relies on equivalent endpoints and starting reaction amounts.'], 'Same amount to the same endpoint makes time comparable.', 'Comparing completion times when one trial contains twice as much substrate.', 'Standardise what completion represents before using reciprocals.', 'Does 1/t alone have units of grams per second?', 'No.',
   'Why can testing every ten seconds limit the precision of a 20-second endpoint?', 'The actual change occurs between observations, so the recorded time may overstate precision. Shorter consistent intervals or an appropriate continuous method can improve temporal resolution.',
   d(true, 'What is an endpoint?', 'An operationally defined observation used to mark a chosen reaction stage.', 'A convenient proxy can be treated as a direct rate measurement without checking what it represents.')]
 ]],
 ['Plant transport and measurement proxies', [
  ['Explain transpiration as a linked water pathway', 'Connect evaporation from leaves with water movement through xylem.',
   'Water evaporates from moist internal leaf surfaces and diffuses out mainly through stomata. This loss contributes to a pull through the continuous water pathway in xylem from roots towards leaves. Wind, humidity, temperature and stomatal opening affect the process. Water transport is not simply water being pumped upwards by photosynthesis, although leaf function and water supply are connected.',
   'Predict the effect of moving air near a leaf when other conditions remain suitable.', ['Water vapour can accumulate near the leaf in still air.', 'Moving air removes some of this humid boundary layer.', 'A steeper vapour gradient can increase water loss, subject to stomatal responses and other constraints.'], 'Evaporation, vapour diffusion, linked water supply.', 'Saying wind directly pushes liquid water up the stem.', 'Identify the effect on the leaf’s surrounding humidity and gradient.', 'Which tissue carries most upward water transport in a plant?', 'Xylem.',
   'Why can high surrounding humidity reduce transpiration?', 'The water-vapour difference between leaf air spaces and outside air becomes smaller, reducing the driving gradient for net diffusion under otherwise similar conditions.',
   d(false, 'What are stomata?', 'Pores in the leaf surface whose opening is regulated by guard cells.', 'A visible environmental factor may be connected to the wrong step of the transport pathway.')],
  ['Challenge: evaluate a potometer as a water-loss estimate', 'Distinguish measured uptake from the transpiration process inferred.',
   'A potometer measures water uptake by a shoot, often from movement of an air bubble in a capillary. Uptake is commonly used as a proxy for transpiration, but some water supports growth and other processes. Leaks, changing temperature and different leaf areas affect interpretation. The apparatus requires supervised preparation; these exercises analyse supplied measurements, not instructions to cut plant material with sharp equipment.',
   'A bubble moves 30 mm in 5 min, then 45 mm in 5 min under another condition.', ['Compare displacement rates: 6 and 9 mm/min.', 'With the same capillary, the second uptake indicator is 1.5 times the first.', 'This is not automatically an exact transpiration volume without capillary area and the proxy assumptions.'], 'Measure uptake; justify the inference to loss.', 'Calling bubble distance alone a volume of water.', 'Use geometry for volume and distinguish measured and inferred processes.', 'What extra geometric information converts capillary distance into volume?', 'The internal cross-sectional area.',
   'Why normalise uptake by leaf area when comparing different shoots?', 'A larger leaf area can provide more evaporating surface. Without accounting for it, a difference may reflect shoot size rather than the environmental treatment.',
   d(true, 'What is a proxy measurement?', 'A measurable quantity used to estimate another through a justified relationship.', 'An instrument’s convenient output can be mistaken for the target process itself.')]
 ]],
 ['Reaction quantities and gas collection', [
  ['Explain apparent mass loss in an open reaction vessel', 'Account for gas leaving the measured system rather than losing atoms.',
   'When an acid-carbonate reaction produces carbon dioxide in an open vessel, the balance reading can fall because gas leaves the apparatus being weighed. Total mass remains conserved when all products and surroundings are included. A recorded mass-loss curve can track gas escape under suitable assumptions, but splashes or evaporation can contribute too. Define the measured system before explaining a change.',
   'A supplied experiment record falls from 150.00 g to 148.90 g.', ['The measured apparatus loses 1.10 g.', 'If carbon dioxide escape is the only loss, it estimates 1.10 g of gas released.', 'Other losses would make that interpretation unreliable without controls.'], 'Mass can leave the balance’s system without being destroyed.', 'Saying a falling balance reading disproves mass conservation.', 'Track products beyond the vessel boundary.', 'What gas forms in a typical acid-carbonate reaction?', 'Carbon dioxide.',
   'Why would adding a tight stopper be an unsafe simplistic improvement?', 'Gas production can build pressure in a sealed rigid vessel. Any closed-system measurement needs appropriately designed, supervised apparatus rather than improvised sealing.',
   d(false, 'What does conservation of mass state for a closed chemical system?', 'Total mass of reactants and products is unchanged.', 'The object on the balance can be confused with the complete material system.')],
  ['Challenge: distinguish initial rate from final gas yield', 'Use gradient and plateau for different reaction questions.',
   'An initial gradient on a gas-volume-time graph estimates early reaction rate. A final plateau records collected gas amount when the process ends or measurement stops changing. Smaller particles may increase initial rate through greater exposed surface without changing the final yield if the same limiting-reactant amount fully reacts. A plateau can also reflect leaks or an apparatus limit, so interpretation needs the experimental context.',
   'Two curves reach the same 80 cm³ plateau, but one rises more steeply initially.', ['The steeper initial curve indicates a higher early collection rate.', 'Equal plateaus suggest the same final collected amount under the method.', 'Rate and total product are different comparisons rather than contradictory results.'], 'Gradient for speed; endpoint for amount.', 'Assuming a faster reaction must always produce more final gas.', 'Check reactant quantities and the meaning of the endpoint.', 'What units suit a gas-volume gradient measured against seconds?', 'cm³/s.',
   'How could a leaking collection system imitate a lower yield?', 'Some gas would escape without being recorded, so the measured plateau would underestimate production. A lower graph endpoint alone cannot distinguish a chemical yield difference from collection failure.',
   d(true, 'What does a graph’s gradient represent?', 'Change in the vertical quantity per change in the horizontal quantity.', 'The height and steepness of a curve may be used interchangeably despite representing different quantities.')]
 ]],
 ['Thermal radiation and fair comparisons', [
  ['Explain emission and absorption without a material medium', 'Distinguish infrared transfer from conduction and convection.',
   'Thermal radiation transfers energy by electromagnetic waves and can occur through a vacuum. At the same temperature and comparable conditions, a good absorber at relevant wavelengths is also a good emitter. Surface finish affects radiative exchange, but conduction, convection, area and temperature difference may also control cooling. An object’s visible colour alone is not a complete measurement of its infrared properties.',
   'Explain why insulation against conduction does not remove all heat transfer.', ['Conduction requires suitable material contact pathways.', 'Radiation can carry energy across a gap, even without air.', 'A complete energy-transfer account must consider the remaining pathways.'], 'A vacuum stops convection, not radiation.', 'Claiming heat cannot transfer through empty space.', 'Separate particle-mediated pathways from electromagnetic transfer.', 'Which transfer mode can occur through a vacuum?', 'Radiation.',
   'Why can a shiny surface reduce radiative transfer in some designs?', 'A low-emissivity surface emits and absorbs less thermal radiation at relevant wavelengths under the stated conditions. Its effect must still be considered alongside other transfer routes.',
   d(false, 'What is convection?', 'Energy transfer associated with bulk movement of a fluid.', 'All heating may be pictured as particles physically travelling between objects.')],
  ['Challenge: isolate surface finish in a cooling investigation', 'Control competing pathways and compare like parts of cooling curves.',
   'To investigate radiative surface effects, containers should have comparable material, size, water mass, initial temperature and surroundings. Different starting temperatures create different transfer rates, while lids and air movement affect evaporation and convection. Compare rates over similar temperature ranges rather than only at the same clock time after unequal starts. A school experiment usually estimates combined cooling, so claims about radiation alone need caution.',
   'A black container starts at 80 °C and a shiny one at 60 °C.', ['Their initial temperature differences from the room are unequal.', 'A greater initial cooling rate cannot be assigned solely to surface finish.', 'Repeat with matched starting conditions or analyse comparable temperature intervals with justified controls.'], 'Match the driving difference before comparing the material.', 'Calling the fastest-cooling container the best radiator without accounting for temperature.', 'Control temperature difference and other transfer pathways.', 'Why keep water masses equal?', 'Different masses change the energy needed for each degree of temperature change.',
   'Would three repeats remove the bias of consistently different starting temperatures?', 'No. Repeats can reveal scatter but preserve the confounding condition. The design itself must be corrected before averaging can support the intended comparison.',
   d(true, 'What is a confounding variable?', 'A factor changing with the intended variable that can also affect the outcome.', 'Repeated observations may look rigorous while repeating the same unfair comparison.')]
 ]],
 ['Resistance, geometry and practical graphs', [
  ['Relate wire length to resistance in a controlled model', 'Explain why a longer uniform wire presents a longer conduction path.',
   'For the same material, cross-sectional area and temperature, a uniform wire’s resistance is proportional to length. Changing thickness or heating the wire changes the comparison. Measuring several lengths and calculating R = V/I can reveal the relationship. Use only teacher-approved low-voltage circuits; limiting current and switching off between readings can help reduce heating and risk.',
   'A uniform wire has resistance 2 ohms at 0.5 m under fixed conditions.', ['The resistance per metre is 2/0.5 = 4 ohms/m.', 'At 0.8 m the proportional model predicts 4 × 0.8.', 'The predicted resistance is 3.2 ohms, provided area, material and temperature remain comparable.'], 'Same wire conditions make length the isolated change.', 'Attributing a resistance change to length when a different thickness was used.', 'Control cross-sectional area, material and temperature.', 'Does a thicker wire of the same material necessarily have the same resistance per metre?', 'No.',
   'Why might leaving current flowing distort later readings?', 'Heating can change resistivity, so the wire no longer has the same temperature as in earlier measurements. The apparent length effect would then include a temperature effect.',
   d(false, 'How is resistance calculated from potential difference and current?', 'R = V/I.', 'A variable labelled length may be treated as isolated even while the wire’s temperature changes.')],
  ['Challenge: interpret a non-zero intercept from contact resistance', 'Separate a physical proportional relationship from added measurement contributions.',
   'A measured resistance may include leads and contacts as well as the selected wire. If those contributions are roughly constant, a graph can follow R_measured = aL + b with a positive intercept b. The wire’s own resistance can still be proportional to length. Fitting a line through the origin automatically can distort the estimated gradient and hide evidence of the extra contribution.',
   'A measured model is R = 4L + 0.6 with R in ohms and L in metres.', ['The gradient is 4 ohms per metre for the changing wire contribution.', 'The 0.6-ohm intercept models a constant added contribution.', 'At 0.5 m the measured resistance is 2.6 ohms, not 2.0.'], 'Gradient captures change; intercept can reveal an offset.', 'Discarding every non-zero intercept as proof the whole relationship is invalid.', 'Investigate plausible systematic contributions and their stability.', 'What resistance does the model predict at zero selected length?', '0.6 ohms.',
   'Why is the intercept not necessarily a literal measurement of one particular contact?', 'It aggregates whatever constant effects and modelling errors contribute. Additional measurements are needed to assign it to a specific component rather than merely name a plausible cause.',
   d(true, 'What is the intercept of a graph?', 'Its vertical value where the horizontal variable is zero.', 'A convenient model parameter may be assigned a unique physical cause without independent evidence.')]
 ]],
 ['Population change and scientific inference', [
  ['Explain selection of antibiotic resistance in a population', 'Distinguish selection of variants from an individual bacterium choosing to adapt.',
   'Bacterial populations can contain genetic variants affecting susceptibility to an antibiotic. Exposure changes survival and reproduction, so resistant variants can become more common. The antibiotic does not teach each bacterium to develop the needed mutation. Resistance can also spread through gene transfer. Treatment decisions must follow qualified clinical guidance; the evolutionary explanation is not a reason to alter a prescription independently.',
   'Explain a population becoming more resistant over several generations after exposure.', ['Some variants survive better under the antibiotic conditions.', 'Survivors reproduce and pass on relevant genetic information.', 'The proportion of resistant descendants can increase through selection.'], 'Variation first; unequal survival and reproduction change proportions.', 'Saying bacteria become resistant because they try harder to survive.', 'Use population-level variation and inheritance rather than intention.', 'Is resistance necessarily a change in every individual bacterium?', 'No.',
   'Why can resistance remain uncommon without antibiotic exposure in some cases?', 'Some resistance traits carry costs under particular conditions, and selection depends on the environment. This is not universal: costs and persistence vary, so absence of treatment does not guarantee resistance disappears.',
   d(false, 'What is natural selection?', 'Differential survival and reproduction associated with heritable variation under particular conditions.', 'An outcome useful to survivors may be incorrectly explained as a purposeful individual response.')],
  ['Challenge: estimate population size with a capture-recapture model', 'State assumptions behind a numerical estimate from supplied ecological data.',
   'A simplified capture-recapture estimate is population ≈ first marked sample × second sample size / marked individuals recaptured. It assumes marks are retained and recognised, mixing occurs, capture probabilities are suitable and the population does not change substantially between samples. These exercises use supplied data; animal handling requires ethical approval and appropriate expertise. A calculated value is an estimate conditional on the model, not a census.',
   'Twenty animals are marked; a later sample of 30 contains six marked animals.', ['The marked proportion in the second sample is 6/30 = 0.2.', 'Treat 20 as approximately 20 percent of the whole population.', 'Estimate N = 20 × 30/6 = 100.'], 'Sample marked fraction estimates population marked fraction.', 'Treating the estimate as exact despite migration or unequal capture chances.', 'List and assess the sampling assumptions before interpreting the number.', 'What happens to the calculation if no marked animals are recaptured?', 'The simple formula cannot produce a finite estimate because its denominator is zero.',
   'If some marks are lost, what direction of bias may result under otherwise comparable conditions?', 'Fewer recaptured animals are recognised as marked, lowering the denominator and potentially inflating the estimated population. The model’s mark-retention assumption is therefore important.',
   d(true, 'What is a population in ecology?', 'Individuals of a species in a defined area at a specified time.', 'A precise arithmetic result can conceal uncertain sampling assumptions.')]
 ]]
]];
