import type { Subject, ActivityDetail } from '../authoredActivities';
const d = (premium: boolean, prompt: string, answer: string, cause: string): ActivityDetail => ({ isPremium: premium, difficulty: premium ? 'Higher' : 'Core', estimatedMinutes: premium ? 22 : 16, priorKnowledgeCheck: [{ prompt, answer }], misconceptionCause: cause, revision: 'Tomorrow, reconstruct the mechanism without notes. In a week, explain a new case, distinguishing the evidence from assumptions and checking every causal link.' });
export const year9Biology: Subject = ['biology', [
 ['Inheritance and variation', [
  ['Connect chromosomes, genes and alleles', 'Explain how alternative versions of a gene can contribute to inherited differences.',
   'Chromosomes contain long DNA molecules. A gene is a region of DNA with a biological function, often instructions for making a protein; alleles are alternative versions at a gene location. In a simple diploid model, an organism has two alleles for an autosomal gene, one inherited from each parent. Genotype describes the allele combination, while phenotype describes an observable characteristic influenced by genotype and sometimes environment. Not every characteristic follows a single dominant-recessive pattern.',
   'Interpret Bb in a stated model where B is dominant over b.', ['Bb contains two different alleles, so the genotype is heterozygous.', 'One B allele is sufficient for the model’s dominant phenotype.', 'This does not establish that B is more common, healthier or better.'], 'Dominance describes expression in a heterozygote, not superiority.', 'Assuming dominant means common or advantageous.', 'Keep inheritance terminology separate from frequency and fitness.', 'What does homozygous mean?', 'Having two identical alleles at the gene location being considered.',
   'Compare BB and Bb under this simple complete-dominance model.', 'They have different genotypes but the same dominant phenotype in the stated model. BB is homozygous and Bb heterozygous; their possible transmitted alleles differ.',
   d(false, 'Where is most DNA located in a typical animal cell?', 'In the nucleus.', 'Everyday meanings of dominant can be imported into genetics.')],
  ['Challenge: interpret a genetic cross probabilistically', 'Distinguish predicted proportions from guarantees for a small family.',
   'A Punnett square combines possible gamete alleles, not actual children arranged in birth order. For two heterozygous parents in a complete-dominance model, each produces A or a gametes with equal probability. The combinations AA, Aa, aA and aa yield an expected genotype ratio of 1:2:1. Each fertilisation is a new event in this simplified model; four offspring are not guaranteed to match the ratio.',
   'Cross Aa with Aa and find the chance of the recessive phenotype.', ['Each parent supplies A or a with probability one half.', 'Only aa expresses the recessive phenotype under the model.', 'Its probability is one quarter, not a guarantee of exactly one in every four offspring.'], 'A square lists possibilities, not a birth schedule.', 'Predicting the fourth child must be recessive after three dominant phenotypes.', 'Treat each event using the parental gamete probabilities, not a balancing rule.', 'What genotype gives the recessive phenotype in this model?', 'aa.',
   'Find the probability that two independent offspring both have genotype aa.', 'One quarter multiplied by one quarter is one sixteenth. The calculation assumes the stated inheritance model and independent fertilisations; it is not a prediction about a particular real family.',
   d(true, 'What does a probability of one quarter mean?', 'An event has a 25 percent chance under the model.', 'Expected long-run proportions can be mistaken for fixed outcomes in small samples.')]
 ]],
 ['Photosynthesis and limiting conditions', [
  ['Explain photosynthesis as energy transfer and material conversion', 'Identify the sources of carbon and energy in plant growth.',
   'Photosynthesis uses light energy to make glucose from carbon dioxide and water, releasing oxygen. Chlorophyll absorbs light; it does not supply the carbon atoms. Carbon dioxide provides carbon that can become plant biomass through glucose and other molecules. Plants also respire continuously, transferring energy from organic molecules. Saying plants photosynthesise by day and respire only at night incorrectly separates processes that can occur together.',
   'Explain why soil minerals alone cannot account for a growing tree’s carbon.', ['Mineral uptake supplies important elements but not the main carbon input described here.', 'Carbon dioxide enters leaves and supplies carbon for photosynthesis.', 'Products can be converted into cellulose and other biomass while respiration also continues.'], 'Light supplies energy; carbon dioxide supplies carbon.', 'Treating light or soil as the material source of all plant mass.', 'Distinguish an energy input from sources of atoms.', 'Do plants respire in daylight?', 'Yes.',
   'A plant receives water and light but no carbon dioxide. Why cannot it sustain normal photosynthetic glucose production?', 'The carbon reactant is missing. Light supplies energy but cannot replace the carbon atoms needed to construct glucose; stored materials may still support processes temporarily.',
   d(false, 'What does conservation of atoms mean in a chemical reaction?', 'Atoms are rearranged rather than created or destroyed.', 'Visible soil and sunlight can overshadow the invisible gaseous carbon input.')],
  ['Challenge: explain a plateau in a photosynthesis graph', 'Use limiting factors without claiming a graph identifies an unmeasured cause.',
   'At low light intensity, increasing light may raise photosynthesis rate because energy supply limits the process. A plateau suggests that more light alone no longer increases the measured rate under those conditions. Carbon dioxide availability, temperature or another constraint may now matter, but the graph alone does not identify which. Test a proposed limiting factor while controlling others and consider whether the measurement itself has reached a limit.',
   'A graph levels off as lamp brightness increases.', ['Identify the plateau rather than claim photosynthesis stops.', 'Propose carbon dioxide availability as one possible constraint.', 'Vary carbon dioxide at the plateau while controlling temperature and light to test that proposal.'], 'A plateau reveals a constraint, not its name.', 'Calling the plateau proof that carbon dioxide must be limiting.', 'Compare controlled follow-up evidence and alternative explanations.', 'Does a horizontal rate plateau mean the rate is zero?', 'No.',
   'Why might moving a lamp closer confound a light experiment?', 'It may also warm the apparatus, changing temperature along with light. A heat shield or monitored temperature and suitable controls help distinguish the effects.',
   d(true, 'What is the independent variable?', 'The factor deliberately changed in an investigation.', 'A plausible explanation can be treated as a demonstrated cause without a discriminating test.')]
 ]],
 ['Infection, immunity and population evidence', [
  ['Distinguish pathogens from immune responses', 'Explain why antibiotics and vaccines perform different roles.',
   'Pathogens include disease-causing bacteria, viruses and other organisms or agents. Antibiotics act against susceptible bacteria, not viruses. Vaccination exposes the immune system to an antigen or instructions for producing one in a controlled way, promoting specific immune memory without requiring the person to experience the full disease. Later responses can be faster and more effective, but protection varies by vaccine, person and time. Treatment decisions belong with qualified health professionals.',
   'Explain why an antibiotic is not a replacement for a viral vaccine.', ['The antibiotic targets bacterial processes and does not directly treat the virus.', 'The vaccine prepares a specific immune response before or against future exposure.', 'The tools have different targets and purposes rather than being interchangeable medicines.'], 'Antibiotics target susceptible bacteria; vaccination prepares immune memory.', 'Assuming every infection needs an antibiotic.', 'Identify the cause and obtain appropriate professional advice.', 'What is immune memory useful for?', 'A more rapid or effective response to a recognised antigen on later exposure.',
   'Why does feeling better after taking an antibiotic not prove a viral infection was cured by it?', 'The illness may improve naturally, the original diagnosis may differ, or another factor may contribute. Timing alone does not establish that an antibiotic acted against a virus.',
   d(false, 'What is a pathogen?', 'An agent that can cause disease.', 'Different causes of infection are often grouped under an undifferentiated idea of germs.')],
  ['Challenge: compare infection risks using denominators', 'Evaluate vaccine data without confusing case counts with group risks.',
   'Comparing raw case counts ignores how many people are in each group. In an explicitly fictional study, 20 cases among 1,000 vaccinated people is a 2 percent observed risk, while 10 among 100 unvaccinated people is 10 percent. The vaccinated group has more cases but a lower proportion. This comparison alone does not control exposure, age or other differences and is not a claim about a particular vaccine.',
   'Calculate relative risk reduction in the fictional data.', ['Compute risks as 20/1,000 = 0.02 and 10/100 = 0.10.', 'The absolute difference is 0.08, or 8 percentage points.', 'Relative reduction is (0.10 − 0.02)/0.10 = 80 percent, subject to the study’s limitations.'], 'Cases need denominators; causal claims need a design.', 'Concluding vaccination increases risk because more vaccinated people appear among cases.', 'Compare rates and examine confounding before interpreting the difference.', 'Is an 8-percentage-point difference the same as an 8 percent relative reduction?', 'No.',
   'Why would unequal exposure weaken a causal conclusion?', 'If one group has much greater contact with the pathogen, the observed difference may partly reflect exposure rather than vaccination alone. Comparable groups or suitable adjustment are needed for stronger inference.',
   d(true, 'How is a proportion calculated?', 'Divide the number with the outcome by the number at risk in that group.', 'Raw counts attract attention while unequal group sizes and exposure are easily overlooked.')]
 ]]
]];
