import type { Subject, ActivityDetail } from '../authoredActivities';
const core: ActivityDetail = { isPremium: false, difficulty: 'Core', estimatedMinutes: 15, revision: 'Tomorrow, rebuild the sentence and mark each verb’s position. In a week, change the opening phrase or subject and check case and word order again.' };
const challenge: ActivityDetail = { ...core, isPremium: true, difficulty: 'Higher', estimatedMinutes: 20 };
export const year8German: Subject = ['german', [
 ['Modals and clause structure', [
  ['Place an infinitive after a modal verb', 'Use können in a main clause with the action infinitive at the end.',
   'Ich kann schwimmen means I can swim. The finite modal kann occupies second constituent position in a standard main clause, while the infinitive schwimmen goes at the end. Wir können heute schwimmen uses the plural können. If Heute begins the clause, the finite verb still stays second: Heute können wir schwimmen. Second position refers to constituents rather than a fixed written word count.',
   'Say “Today I can play football”.', ['Begin with Heute.', 'Put finite kann next, then ich.', 'Finish with Fußball spielen: Heute kann ich Fußball spielen.'], 'Finite modal second; action infinitive last.', 'Writing Heute ich kann spiele Fußball.', 'Check inversion after the opening phrase and keep spielen infinitive at the end.', 'What is the ich form of können?', 'Kann.',
   'Translate “We can read today” with heute first.', 'Heute können wir lesen. Heute fills the first constituent position, können remains second and lesen ends the clause.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'Where is the finite verb in a normal German declarative main clause?', answer: 'In second constituent position.' }], memoryExplanation: 'The two verbs form a sentence bracket around the other information.', misconceptionCause: 'English word order can be carried into German without accounting for the final infinitive.' }],
  ['Challenge: add a reason with weil', 'Distinguish main-clause verb position from subordinate-clause word order.',
   'In standard written German, a clause introduced by weil places its finite verb at the end: Ich lese, weil das Buch interessant ist. The main clause still follows its own word-order rule. With a modal, the infinitive precedes the final finite modal: weil ich schwimmen kann. Do not transfer the main-clause second-position rule unchanged across the comma.',
   'Complete “I play because I can play” using spielen.', ['The main clause is Ich spiele.', 'Weil introduces the subordinate reason.', 'Place kann last: Ich spiele, weil ich spielen kann.'], 'Weil sends the finite verb to the end.', 'Writing weil ich kann spielen in a standard written exercise.', 'Identify the subordinate clause and place its finite modal last.', 'Which is finite in weil ich spielen kann?', 'Kann.',
   'Translate “I read because the book is interesting”.', 'Ich lese, weil das Buch interessant ist. Lese is second in the main clause; ist is final in the weil clause.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What is the infinitive in ich kann lesen?', answer: 'Lesen.' }], memoryExplanation: 'Clause boundaries determine which word-order pattern applies.', misconceptionCause: 'A correct main-clause pattern may be overextended to a subordinate clause.' }]
 ]],
 ['The conversational past', [
  ['Build a regular perfect tense with haben', 'Combine a conjugated auxiliary and a final past participle.',
   'German often uses the perfect tense when talking about past events. Ich habe gespielt means I played or have played, depending on context. For a simple regular verb such as spielen, the participle is gespielt, formed with ge- and -t. The auxiliary haben is conjugated and the participle normally ends the main clause. Not every verb forms its participle regularly or takes haben.',
   'Say “Yesterday we played football”.', ['Start with Gestern and keep haben second.', 'Place wir after the finite auxiliary.', 'Finish with Fußball gespielt: Gestern haben wir Fußball gespielt.'], 'Auxiliary carries person; participle completes the bracket.', 'Putting a regular infinitive after haben to express this past event.', 'Use the participle gespielt, not spielen, in this construction.', 'What is the participle of spielen?', 'Gespielt.',
   'Translate “I bought a book” using kaufen.', 'Ich habe ein Buch gekauft. Habe is the finite auxiliary; gekauft is the regular participle at the end. Ein Buch is the neuter accusative object.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What does ich habe mean?', answer: 'I have.' }], memoryExplanation: 'The two parts work together to express past time; neither alone supplies the full construction.', misconceptionCause: 'A familiar have expression may be read as possession rather than as an auxiliary.' }],
  ['Challenge: select sein with gehen', 'Contrast two taught perfect constructions without inventing an all-purpose movement rule.',
   'Gehen forms its perfect with sein: ich bin gegangen, wir sind gegangen. Spielen uses haben: ich habe gespielt. Auxiliary choice must be learned with verbs and constructions; “anything involving movement uses sein” is too broad, since playing can involve movement but still takes haben. Both constructions keep the participle at the end of a simple main clause.',
   'Compare “We went to the park” and “We played in the park”.', ['Use Wir sind in den Park gegangen for going to the park.', 'Use Wir haben im Park gespielt for playing there.', 'The verbs select different auxiliaries in these constructions despite movement being possible in both activities.'], 'Learn auxiliary and participle as a pair.', 'Using sein for every physically active verb.', 'Learn spielen with haben and gehen with sein rather than relying on physical activity alone.', 'What is the ich perfect form of gehen?', 'Ich bin gegangen.',
   'Write “Yesterday I went to the park and played football”.', 'Gestern bin ich in den Park gegangen und habe Fußball gespielt. Bin belongs with gegangen, while habe belongs with gespielt; each participle completes its own coordinated clause.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What do ich bin and wir sind mean?', answer: 'I am and we are.' }], memoryExplanation: 'Paired vocabulary records prevent auxiliary choice from being inferred from an unreliable slogan.', misconceptionCause: 'A useful tendency involving changes of location is often simplified into any movement.' }]
 ]],
 ['Dative and two-way prepositions', [
  ['Use the dative after mit', 'Choose dem or der according to gender after a taught dative preposition.',
   'Mit means with or, in transport expressions, by, and takes the dative. With definite singular articles, masculine der becomes dem, feminine die becomes der and neuter das becomes dem. Mit dem Bus means by bus; mit der Freundin means with the female friend. These changes mark grammatical case, not a change in the noun’s gender.',
   'Say “I travel by bus” using fahren.', ['Bus is masculine: der Bus in the nominative.', 'Mit requires the dative, so choose dem Bus.', 'Write Ich fahre mit dem Bus.'], 'Mit requires dative; gender chooses its form.', 'Assuming every der is masculine regardless of case.', 'Read the article together with its case and noun.', 'What is the dative definite article for feminine singular nouns?', 'Der.',
   'Complete mit ... Buch and mit ... Tasche, using das Buch and die Tasche.', 'Mit dem Buch and mit der Tasche. The neuter noun uses dem in the dative and the feminine noun uses der.',
   { ...core, priorKnowledgeCheck: [{ prompt: 'What are the nominative articles for masculine, feminine and neuter singular nouns?', answer: 'Der, die and das.' }], memoryExplanation: 'Article forms depend on two coordinates: gender and case.', misconceptionCause: 'A nominative vocabulary list can lead to the false belief that an article has only one grammatical function.' }],
  ['Challenge: distinguish destination from location with in', 'Use accusative or dative according to the spatial relationship, not merely the presence of movement.',
   'In is a two-way preposition. A destination into a place normally takes the accusative: Ich gehe in den Park. A location within it takes the dative: Ich spiele im Park, where im contracts in dem. Movement can occur within a location, so “movement equals accusative” is unreliable. Ask whether the phrase names where something happens or the destination into which it moves.',
   'Explain Ich laufe im Park versus Ich laufe in den Park.', ['Im Park locates the running inside the park.', 'In den Park presents the park as the destination entered.', 'Both involve running, but the spatial relationship selects the case.'], 'Where within, or where into?', 'Selecting accusative simply because the verb describes motion.', 'Decide whether the phrase expresses location or a destination.', 'What does im contract?', 'In dem.',
   'Choose the phrase for “We play in the park”, not entering it: im Park or in den Park.', 'Wir spielen im Park. The phrase locates the activity within the park, so the dative is used even if the players move around.',
   { ...challenge, priorKnowledgeCheck: [{ prompt: 'What are the masculine singular definite articles in the accusative and dative?', answer: 'Den and dem respectively.' }], memoryExplanation: 'The contrast depends on the relation expressed by the phrase rather than on whether bodies physically move.', misconceptionCause: 'Movement-versus-no-movement shortcuts obscure the actual destination/location distinction.' }]
 ]]
]];
